In [1]:
!git config --global user.email "clement.dilasser@croix-rouge.fr"
!git clone https://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@github.com/clementsouk-aloun-dot/Code-PAT.git

Cloning into 'Code-PAT'...
remote: Enumerating objects: 1291, done.
remote: Counting objects: 100% (204/204), done.
remote: Compressing objects: 100% (160/160), done.
remote: Total 1291 (delta 93), reused 66 (delta 44), pack-reused 1087 (from 1)
Receiving objects: 100% (1291/1291), 2.86 MiB | 9.29 MiB/s, done.
Resolving deltas: 100% (863/863), done.

In [123]:
%cd Code-PAT
!git checkout main

[Errno 2] No such file or directory: 'Code-PAT'
/content/Code-PAT
M	scripts_data/base_contact.py
M	scripts_data/mobilite.py
Already on 'main'
Your branch is up to date with 'origin/main'.

In [124]:
!git add .

In [125]:
!git commit -m "Corrections pour all_data"

[main 2d04930] Corrections pour all_data
 2 files changed, 2 insertions(+), 4 deletions(-)

In [98]:
!git fetch origin

remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 5.64 KiB | 641.00 KiB/s, done.
From https://github.com/clementsouk-aloun-dot/Code-PAT
   1440d85..8507247  main       -> origin/main

In [99]:
!git config pull.rebase true

In [100]:
!git pull

Successfully rebased and updated refs/heads/main.

In [126]:
!git push

Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 490 bytes | 490.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/clementsouk-aloun-dot/Code-PAT.git
   1939cd3..2d04930  main -> main

#INSTALL PACKAGE

In [3]:
!gcloud auth application-default login

Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=Gm1DI3XTXMPK1ylR3z0EsONH4Ict5D&prompt=consent&token_usage=remote&access_type=offline&code_challenge=ba69a2A6aXEKq3r73mpnCWxwbuj90-t7HmhZ1TPuQWE&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0ASc3gC1FotJeRMEMQ4dc7woCLnzPcZ2KI7CH2cJqTxjEJw4joKUzuK52G68IWz9toS3mlA

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.


To take a quick anonymous survey, run:
  $ gcloud survey

In [4]:
!pip install PyPDF2
!pip install reportlab
!pip install PyMuPDF tools
!pip install xlsxwriter

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 3.0 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1
Collecting reportlab
  Downloading reportlab-4.4.9-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.4)
Downloading reportlab-4.4.9-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 12.4 MB/s eta 0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-4.4.9
Collecting PyMuPDF
  Downloading pymupdf-1.27.1-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Collecting tools
  Downloading tools-1.0.23-py3-none-any.whl.metadata (1.3 kB)
Downloading pymupdf-1.27.1-cp310-abi3-manylinux_2_28_x86_64.whl (24.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 MB 49.4 MB/s eta 0:00:00
Downloading tools-1.0.23-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 2.8 MB/s eta 0:00:00
Installing collected packages: tools, PyMuPDF
Successfully installed PyMuPDF-1.27.1 tools-1.0.23
Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 2.5 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9

In [5]:
import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import sys
import io
import re
import shutil
import zipfile
from google.colab import drive, files

from google.colab import auth
from google.auth import default
import unicodedata
import re
import torch
from sentence_transformers import SentenceTransformer, util
from google.cloud import bigquery
from pyspark.sql import SparkSession
import gc
from functools import reduce

Imports des fichiers .py

In [6]:
sys.path.append(os.path.abspath("/content/Code-PAT/scripts_data"))
sys.path.append(os.path.abspath("/content/Code-PAT"))

from adherent import *
from alim import *
from domifa import *
from financier import *
from gaia import *
from impact import *
from manuelles import *
from maraude import *
from base_contact import*
from mobilite import *
from nomination import *
from pegass import *

from utils import *

#AUTHENTIFICATION

In [7]:
PROJECT_ID = "crf-pat"
client = bigquery.Client(project=PROJECT_ID)

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [8]:
# Etape 0 : Préparation de l'environnement

CREDENTIALS_JSON = """
{
  "type": "service_account",
  "project_id": "alexandrevalent",
  "private_key_id": "dba39c84ba4135ce5ede6479a186ad8cde499dee",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvGU4ZJFrBwCBb\nu8s4aPA5bQTOKDkPZEVdNyY//RneR6RC9JPrcbfVfIUaQU7A036sfdhDGFKJbw20\nTZ55fafcH9yCMiUO+Nzek0eogON4TXrXsh8UFtdw8BOuaVkFitU5yg8kFhTnEZtd\ntPfZHW3Aqhd/aDoTOBNgRuF/hVTKQ2ytbCbE77fL2/pz9kvpZ2Zrz3u1lmksSJls\nHIolNwX9R05YqmrkpZ/TMAULFk4bT0VRQng5pmN9AeB61eJLWhlLaEdeu79NWV4B\n7tZd6RzzTFors804aJkmXHM63VRtvGD0UlR0O7w1QlI3ymUxpy5hrjbz6n9bmpMI\nfebvydLnAgMBAAECggEADipn7RTJ2t7mP0WkHT4wIRU2zE7ovtwH2JC7oXWigB8f\npOMQjH24t6bJReR+sI7rspzDwDnZg5DedPXKml2WFPLm7gmMgfeUNtWHeJRk0rjB\n9W1NolxutY5WqUeQkig3M+Oq8epvano8LYqUepYs6OdZ207dU+y3dJSHbb+lqm9D\ntQZR2oBj7W1iZ8fJ+SQLSjU5BztS1CvWuayRd/tLd9Spp0NUn5uQFTKwel9Gazmz\n28IsPPm6SudplFhaGd4kCPvhcg0jGEKe61VYdgHoBzp+EXRWXUvQ+SbMafXtMvoB\nLoUH4X3creKzJQKXnjlDpAzRHMYhJTvHinHXaggdcQKBgQDcJszFOECfSovXFZNq\nMyQOWbesyDb2OQhJLFZCD2QraZm3jPaIPeMfFkmFAumcVal6EzpR5IE8g9jBuLo+\ng6j3NTo5jbGO9WEn4361yEotb+S8t3/DTHvWqXBK7HdUB/KHlyGtctm8yErdMZQB\nvzo03aTwwStNTeFG8GzT1Nd7JQKBgQDLnHIMbx9iAG3K21XCq0Dot2Q63hklJC26\nsJlrTkdXMOIlhpwJ6LTOJe2paHbR56IrKOHQCuLxQFhRd8Eidz1ahjO7D8fKr/TG\nS8/V32FrpONyxhKinLsccSb86S3vvpKCI265z5EEjk/1qnx3TOo6oqA/2DQLv0Q4\nYinmNSOeGwKBgHGjYY3n9IuE6lwy2e42ycTSkNoSWzSLyfgjd78PvNAf6WXy0IsR\nDvzL/1U2ZKn7GclWxYLiJce78xZEKXb9dSluA0kUF/RIO0dgydZBtfBwUq0LN1rz\nTvVGbx1tpEbu90UAQTUMFNK6vNIitliUghIp2usfex+jNMbuce6Cblw1AoGBAKDH\n1gtZiFeT7R7d2jfRkXzyrBQMI6D/k5izMULZ2l3QfROS2w68EmIi8yvuEL2qApXA\nP6hPoGtPGy6huQHlVK5yANF7IZI9JbWcUe8Z6MzetLiCDl8YEmzgMSBPZXXGb9yR\n7DKP5HzLf/qG+KggNWm913ry2A5ap506bsmZNpn3AoGBAM6vvI9tb+AcNfd4ewmY\nAWSb4GLliRTaBIGHYmotfyBEBWpXZq2/0JG32RRf3rYUJWWn/r7K+zrRUqeMwlD+\nz7GuSU+OaSDzYj7fwDyuxOwTJMLrh+AkKbUYBsMF7YH1qIRjBjKNdj1LOznASQMe\nu1E4sNa9RRRujbQw4AEP3Xjl\n-----END PRIVATE KEY-----\n",
  "client_email": "crf-slidemanager@alexandrevalent.iam.gserviceaccount.com",
  "client_id": "101959630014487618959",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/crf-slidemanager%40alexandrevalent.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly']


# Authentification
credentials = service_account.Credentials.from_service_account_info(json.loads(CREDENTIALS_JSON, strict=False), scopes=SCOPES)

# Initialisation des services
slides_service = build('slides', 'v1', credentials=credentials)
drive_service = build('drive', 'v3', credentials=credentials)
gspread_client  = gspread.authorize(credentials)

# Variables globales

In [9]:
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

# CHARGEMENT DE TOUTES LES DONNEES PAR TABLE

# 0. Ref_structure

In [10]:
df_ref_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw/').worksheet('Feuille 1'))

In [11]:
df_ref_structure = renommer_par_nom_table(df_ref_structure, "AS_Informations_structures", mapping_df)
df_ref_structure['n_structure'] = df_ref_structure['n_structure'].astype(int)
df_ref_structure = df_ref_structure[df_ref_structure["type_structure"].isin(["UNITE LOCALE - UL", "DELEGATION TERRITORIALE - DT", 'IMPLANTATION LOCALE HORS AL - IL', 'ANTENNE LOCALE - AL'])]
df_ref_structure = df_ref_structure[df_ref_structure['n_structure'] != 1]

df_ref_structure.head()

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,Structure_de_rattachement,Rattachements_successifs,DT_de_rattachement,lon,lat
0,2615,ANTENNE LOCALE - AL,AL DE DELLE,90100.0,90033,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",90,2010-02-08 00:00:00,NaT,95 - DT DU TERRITOIRE DE BELFORT,AL 2615,95 - DT DU TERRITOIRE DE BELFORT,7.000705,47.506725
1,2669,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43220.0,43087,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2669,48 - DT DE LA HAUTE LOIRE,4.346423,45.214392
2,2670,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43600.0,43224,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2670,48 - DT DE LA HAUTE LOIRE,4.235474,45.242445
3,2671,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43300.0,43112,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2671,48 - DT DE LA HAUTE LOIRE,3.495645,45.098285
4,2672,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43000.0,43157,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2672,48 - DT DE LA HAUTE LOIRE,3.879748,45.044677

In [78]:
df_ref_structure_DT = df_ref_structure[df_ref_structure['nom_structure'].str.contains('DT')].astype(str)
df_ref_structure_DT['n_structure'] = df_ref_structure['n_structure'].astype(int)

## 0.1 rattachement_court

In [13]:
rattachement_court = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU/edit?usp=sharing').worksheet('Feuille 1'))

# 1. PEGASS

In [14]:
df_ref_activite_benevole, df_pegass_activite,df_pegass_activite_seance, df_pegass_activite_seance_inscription,ref_structure1,df_rattachement_court,df_ref_action_groupe_action = import_tables_PEGASS(client)

# 2. GAIA

In [15]:
df_gaia_rattachement_benevole = clean_gaia(client)

# 3. NOMINATION

In [16]:
df_ref_nomination, df_nomination = clean_nomination(client)

# 4. IMPACT

In [17]:
df_ref_impact, df_impact = clean_impact(client)

# 5. Données financières

In [18]:
financier = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c')

In [19]:
dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute, dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute = import_clean_donnees_financieres(financier,df_ref_structure,mapping_df)

Financier DPS & FGP

In [20]:
financier_DPS = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/145xeh1LkmYzTSW2zeAwHqmLyjmw_tobICHf-oXZmUFI/').worksheet('Base Smtw 03.03.25'))

In [21]:
financier_FGP = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13J2zfbmLTILtGYtE_sM-ME8B0pNEwBeGJ1Gg5vKLeOc/').worksheet('DT_Prod'))

# 6. Mobilité

In [22]:
mobilite = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1dvxT58WR-FqdT-4r-A9ca4vaA9FG7IXHJJaTbnjio8A/')

In [23]:
df_mobilite = filtres_mobilite(mobilite,mapping_df)

# 7. Données manuelles

## 7.1 OCR

In [24]:
df_OCR = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ccRoyPycFDwvQvacvmHjfE87LtnlzUgtoRbITkC0pVQ/').worksheet('Feuille 1'))

## 7.2 PST

In [25]:
df_PST = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1yifNna4Hsn5RihkRg50g9h1yKjuRjfolrjsWonEHnrQ').worksheet('Données'))

## 7.3 Déclenchements

In [26]:
df_declenchement = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1y9jehT5fStcEWCF0pxAP7BdiI62VY3JM_hQzFftbcZA').worksheet('Feuille 1'))

## 7.4 Redcall

In [27]:
df_redcall = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1EQzq0K8RY2Liyq-jtggX0bTlnOk9cwUTmf4t6c5_CiI').worksheet('structure-stats_2025-01-01_2025-12-31_min-1 (1)'))

## 7.5 CHAI CHU CMCC

In [28]:
df_CAICHUCMCC = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/12nZY2leRCMn71NGAEUUtA0Pes598gOfeufDStxSCcnY').worksheet('Toutes données'))

## 7.6 Conventions

In [29]:
df_conventions = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1OYSSkUhWwVpWne9EygH1EEz8EJnFjSeAOEpQQe9utiM').worksheet('Feuille 1'))

## 7.7 DOMIFA

In [30]:
df_domiciliation, df_rattachement_court = clean_domifa(client,df_ref_structure)

/content/Code-PAT/utils.py:197: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ref['nom_structure'] = df_ref['nom_structure'].fillna('').astype(str)
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

## 7.8 Alim

In [31]:
df_alim = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1bk_ktsT9hBPJS5EY70teq80NzOs_cm3JfrRkX4AYTF4/edit?gid=0#gid=0")

✅ Chargement des données réalisées
    Sheet : Liste U2A a jour - 21/01/2026
    Feuille 1 : Feuille 1 (628 lignes et 10 colonnes)

## 7.9 Adherent

In [32]:
df_adherent = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1hsk3Xp2IrwnUs59sgWjhT9E9vEsw4TN2WT3nKejlBOE/edit?usp=drive_link")

✅ Chargement des données réalisées
    Sheet : exportAdherents (1) (1)
    Feuille 1 : exportAdherents (1) (1).csv (48300 lignes et 25 colonnes)

## 7.10 Préparation

In [33]:
df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions = clean_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement, df_redcall, df_CAICHUCMCC, df_conventions)
df_alim = clean_alim(df_alim)
df_adherent = clean_adherent(df_adherent)

Unique values in 'Année de l'adhésion du contact': [2025]
Data type of 'Année de l'adhésion du contact': int64
Taille du DataFrame après suppression des doublons : (47424, 4)

/content/Code-PAT/scripts_data/manuelles.py:119: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['Grand Total', 'Exercice']] = df[['Grand Total', 'Exercice']].fillna(0)
/content/Code-PAT/scripts_data/manuelles.py:185: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Département"] = df["Département"].str.replace(
/content/Code-PAT/scripts_data/manuelles.py:228: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Departement"] = df["Departement"].str.replace(
/content/Code-PAT/scripts_data/manuelles.py:253: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[colonnes_oui_non] = df[colonnes_oui_non].applymap(
/content/Code-PAT/scripts_data/manuelles.py:253: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[colonnes_oui_non] = df[colonnes_oui_non].applymap(
/content/Code-PAT/scripts_data/manuelles.py:258: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Dispositifs_d_urgence Nb_conventions_operateurs'] = (
/content/Code-PAT/scripts_data/adherent.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_adherent["Année de l'adhésion du contact"] = pd.to_numeric(df_adherent["Année de l'adhésion du contact"], errors='coerce')

# 8. Maraudes

In [34]:
df_nb_personnes_rencontrees_sigma, df_Nb_maraudes_SIGMA, df_maraude, df_rattachement_court = clean_maraudes(client)

# 9. Base Contact

In [35]:
df_formation_session_resultat = clean_base_contact(client)

# FUSION DES TABLES

## 1. Fusion NOMINATION

In [36]:
df_NOMINATION = fusion_nomination(df_nomination, df_ref_nomination)

## 2. Fusion IMPACT

In [37]:
df_IMPACT = fusion_impact(df_impact, df_ref_impact)

## 3. Fusion Données financières

### 3.1 Fusion des tables

In [38]:
df_financier_DT, df_financier_DT_UL = fusion_donnees_financieres(dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute,dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute, df_ref_structure)

### 3.2 Vérifications

In [39]:
verifier_n_dept(df_financier_DT,df_ref_structure)

 ❌ Il y a des doublons :

,DT_de_rattachement,n_dept,Financier Prod_2024,libelle_structure,Financier ResNet_2024,Financier ResCorrProd_2024,Financier TresoBrute_2024,Financier Mois_AvanceTreso_2024
62,4303 - DT DE WALLIS,986,3196.08,DT - WALLIS ET FUTUNA,2776.14,0.868608,2776.14,4.488718

 ❌ Il manque des départements :
set()

In [40]:
verifier_colonne_structure(df_financier_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## 4. Fusion DOMIFA

In [41]:
df_domiciliation = pd.merge(df_domiciliation, df_rattachement_court, on='n_structure', how="left") #a conserver dans le code principal

# Calcul des indicateurs

## PEGASS

In [42]:
pegass_output = calcul_PEGASS_indicateurs(df_ref_structure,
    ref_structure1,
    df_ref_action_groupe_action,
    df_ref_activite_benevole,
    df_pegass_activite,
    df_pegass_activite_seance,
    df_pegass_activite_seance_inscription,
    df_rattachement_court
)

## GAIA

In [43]:
nb_benevoles = indicateurs_gaia(df_gaia_rattachement_benevole)
nb_nvx_benevoles = indicateurs_gaia_nvx(df_gaia_rattachement_benevole)
nb_benevoles_DT = indicateurs_gaia_DT(nb_benevoles,rattachement_court)
nb_nvx_benevoles_DT = indicateurs_gaia_nvx_DT(nb_nvx_benevoles, rattachement_court)

## NOMINATION

- RTAEO & RLAEO
- RTOCR & RLOCR

In [44]:
referents_AEO = indicateurs_nomination_AEO(df_NOMINATION, annee=2025)
referents_OCR = indicateurs_nomination_OCR(df_NOMINATION, annee=2025)
referents_AEO_DT = indicateurs_nominationAEO_DT(referents_AEO, rattachement_court)
referents_OCR_DT = indicateurs_nominationOCR_DT(referents_OCR, rattachement_court)

## IMPACT

- Nombre d'agréments territoriaux (Dispos d'urgence)
- Nombre de personnes prises en charge (Dispos d'urgence)

In [45]:
IMPACT_ppc = indicateurs_impact_ppc(df_IMPACT)
IMPACT_agrementAB = indicateurs_impact_agrementAB(df_IMPACT)
IMPACT_agrementDPS = indicateurs_impact_agrementDPS(df_IMPACT)
IMPACT_ppc_DT = indicateurs_IMPACTppc_DT(IMPACT_ppc, rattachement_court)
IMPACT_agrementAB_DT = indicateurs_IMPACTagrementAB_DT(IMPACT_agrementAB, rattachement_court)
IMPACT_agrementDPS_DT = indicateurs_IMPACTagrementDPS_DT(IMPACT_agrementDPS, rattachement_court)

/content/Code-PAT/scripts_data/impact.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (
/content/Code-PAT/scripts_data/impact.py:137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (
/content/Code-PAT/scripts_data/impact.py:173: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (

## Financier DPS & FGP

In [46]:
df_Secours_ProduitsDPS = indicateur_financier_DPS(financier_DPS, df_ref_structure)
df_financier_DPS_DT = financier_DPS_DT(df_Secours_ProduitsDPS, rattachement_court)
df_financier_FGP = indicateur_financier_FGP(financier_FGP, df_ref_structure)
df_inancier_FGP_DT = financier_FGP_DT(df_financier_FGP, rattachement_court)

🔎 Vérification de la colonne 'libelle' et mapping associé 'n_structure'
   ✅ Mapping réalisé avec succès.

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

🔎 Vérification de la colonne 'Nom Structure' et mapping associé 'n_structure'
   ✅ Mapping réalisé avec succès.

## Mobilité


Indicateurs qui nécessitent seulement les données mobilité :

- Nb de structures menant une activité AEO/AAD mobile
- Nombre de personnes accompagnées par des dispositifs AEO/AAD mobiles
<br>
Indicateurs qui nécessitent une fusion avec données AEO/AAD :

- Nombre de bénévoles impliqués dans les activités AEO ou AAD
- Nombre de bénévoles impliqués dans les activités AEO ou AAD

In [47]:
df_mobilite_DT = indicateurs_mobilite(df_mobilite, df_ref_structure, 'DT_de_rattachement')
df_mobilite_DT_UL = indicateurs_mobilite(df_mobilite, df_ref_structure, 'n_structure')

In [48]:
verifier_colonne_structure(df_mobilite_DT, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [49]:
verifier_colonne_structure(df_mobilite_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## Données manuelles

In [50]:
df_OCR_Nb_deployees, df_Dispositifs_d_urgence_PST, df_declenchement3, df_redcall2, df_CAICHUCMCC_VF, df_conventions2 = indicateurs_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions, df_ref_structure)

Nb_OCR_DT,RedCall_DT = OCR_RedCall_DT(df_OCR_Nb_deployees, df_redcall2, rattachement_court)

# ALIM
df_alim_U2A_sans_doublons, df_alim_epicerie_sociale, df_alim_accueil_alimentaire, df_alim_crsr = indicateurs_alim(df_alim, df_ref_structure)
df_alim_U2A_DT, df_alim_epicerie_sociale_DT, df_alim_accueil_alimentaire_DT, df_alim_crsr_DT = indicateurs_alim_DT(df_alim_U2A_sans_doublons, df_alim_epicerie_sociale, df_alim_accueil_alimentaire, df_alim_crsr, rattachement_court)

# ADHERENT
df_adherent = indicateurs_adherent(df_adherent, df_ref_structure)
df_adherent_DT = indicateurs_adherent_DT(df_adherent, rattachement_court)

# DOMIFA
df_personnes_domiciliees_struct, df_personnes_domiciliees_DT = indicateurs_domifa(df_domiciliation)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [51]:
verifier_colonne_structure(df_OCR_Nb_deployees, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Dispositifs_d_urgence_PST, "n_structure", df_ref_structure)
verifier_colonne_structure(df_declenchement3, "n_structure", df_ref_structure)
verifier_colonne_structure(df_redcall2, "n_structure", df_ref_structure)
verifier_colonne_structure(df_CAICHUCMCC_VF, "n_structure", df_ref_structure)
verifier_colonne_structure(df_conventions2, "n_structure", df_ref_structure)

# DOMIFA

verificiation_domifa(df_domiciliation, df_personnes_domiciliees_struct,df_personnes_domiciliees_DT,df_ref_structure,df_rattachement_court)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'Structure' et mapping associé 'n_structure'
   ✅ Mapping réalisé avec succès.
OK ✅ : sommes égales (30833) entre table struct[AEO Nb_personnes_domiciliees_crf] et table source[AEO Nb_personnes_domiciliees_crf]
OK ✅ : sommes égales (30833) entre table struct[AEO Nb_personnes_domiciliees_crf] et table source[AEO Nb_personnes_domiciliees_crf]

## Maraudes

In [52]:
df_Nb_maraudes_SIGMA,df_Nb_maraudes_SIGMA_DT, df_nb_personnes_rencontrees_SIGMA, df_nb_personnes_rencontrees_SIGMA_DT, df_max_nb_personnes, df_max_nb_personnes_struct = indicateurs_maraude(df_nb_personnes_rencontrees_sigma, df_Nb_maraudes_SIGMA,df_rattachement_court)
#verification_maraude(df_ref_structure,df_Nb_maraudes_SIGMA,df_Nb_maraudes_SIGMA_DT, df_nb_personnes_rencontrees_sigma, df_nb_personnes_rencontrees_SIGMA,df_nb_personnes_rencontrees_SIGMA_DT,df_maraude)

## Base contact

In [53]:
# Indicateurs
indicateurs_base_contact, indicateurs_base_contact_DT = indicateurs_base_contact(df_formation_session_resultat,df_ref_structure)

# Création du DataFrame final

In [122]:
df_financier_DT_UL

Empty DataFrame
Columns: [n_structure, Financier Prod_2024, libelle_structure, Financier ResNet_2024, Financier ResCorrProd_2024, Financier TresoBrute_2024, Financier Mois_AvanceTreso_2024]
Index: []

La liste de tous les dataframes à fusionner sur df_ref_structure

In [105]:
liste_df_a_fusionner_toutes_structures = [nb_benevoles,nb_nvx_benevoles,referents_AEO,referents_OCR, IMPACT_ppc, IMPACT_agrementAB, IMPACT_agrementDPS,
                                          df_mobilite_DT_UL,df_OCR_Nb_deployees, df_Dispositifs_d_urgence_PST, df_declenchement3, df_redcall2,
                                          df_CAICHUCMCC_VF, df_conventions2, df_alim_U2A_sans_doublons, df_alim_epicerie_sociale,
                                          df_alim_accueil_alimentaire, df_alim_crsr, df_adherent, df_personnes_domiciliees_struct, df_Nb_maraudes_SIGMA,
                                          df_nb_personnes_rencontrees_SIGMA, df_max_nb_personnes_struct, indicateurs_base_contact, df_financier_DT_UL, pegass_output['Indics_pegass_struct']]

liste_df_a_fusionner_DT = [nb_benevoles_DT,nb_nvx_benevoles_DT,referents_AEO_DT,referents_OCR_DT,
                           IMPACT_ppc_DT, IMPACT_agrementAB_DT, IMPACT_agrementDPS_DT,df_mobilite_DT,Nb_OCR_DT,RedCall_DT,
                           df_alim_U2A_DT, df_alim_epicerie_sociale_DT, df_alim_accueil_alimentaire_DT, df_alim_crsr_DT, df_adherent_DT,
                           df_personnes_domiciliees_DT, df_nb_personnes_rencontrees_SIGMA_DT,df_Nb_maraudes_SIGMA_DT, indicateurs_base_contact_DT,df_financier_DT,pegass_output['Indics_pegass_DT']]

In [106]:
for i,df in enumerate(liste_df_a_fusionner_toutes_structures):
  if type(df) != type(df_ref_structure):
    display(df)
    liste_df_a_fusionner_toutes_structures[i] = liste_df_a_fusionner_toutes_structures[i].to_frame()
  if len(liste_df_a_fusionner_toutes_structures[i].columns) < 2:
    liste_df_a_fusionner_toutes_structures[i] = liste_df_a_fusionner_toutes_structures[i].reset_index()

n_structure
1       1255
5        373
6          2
7          5
9          2
        ...
4951      12
4953       2
4956      22
4967      11
4968       3
Name: Structure Nb_Benevoles, Length: 943, dtype: int64

n_structure
1       149
5        82
10       29
12       16
13        1
       ...
4951     12
4953      2
4956     23
4967     11
4968      3
Name: Structure Nb_nvx_Benevoles_2025, Length: 828, dtype: int64

In [107]:
for i,df in enumerate(liste_df_a_fusionner_DT):
  if type(df) != type(df_ref_structure):
    display(df)
    liste_df_a_fusionner_DT[i] = liste_df_a_fusionner_DT[i].to_frame()
  if len(liste_df_a_fusionner_DT[i].columns) < 2:
    liste_df_a_fusionner_DT[i] = liste_df_a_fusionner_DT[i].reset_index()

DT_de_rattachement
10 - DT DES ALPES MARITIMES         1717
100 - DT DU VAL D'OISE              1036
102 - DT DE LA GUADELOUPE            690
103 - DT DE LA MARTINIQUE            465
104 - DT DE NOUVELLE CALEDONIE       428
                                    ...
94 - DT DE L'YONNE                   517
95 - DT DU TERRITOIRE DE BELFORT     126
96 - DT DE L'ESSONNE                1472
97 - DT DES HAUTS DE SEINE          3899
99 - DT DU VAL DE MARNE             1817
Name: Structure Nb_Benevoles, Length: 108, dtype: int64

DT_de_rattachement
10 - DT DES ALPES MARITIMES         209
100 - DT DU VAL D'OISE              193
102 - DT DE LA GUADELOUPE            60
103 - DT DE LA MARTINIQUE            88
104 - DT DE NOUVELLE CALEDONIE      104
                                   ...
94 - DT DE L'YONNE                  109
95 - DT DU TERRITOIRE DE BELFORT     13
96 - DT DE L'ESSONNE                427
97 - DT DES HAUTS DE SEINE          646
99 - DT DU VAL DE MARNE             336
Name: Structure Nb_nvx_Benevoles_2025, Length: 106, dtype: int64

DT_de_rattachement
34 - DT DU FINISTERE    1
64 - DT DU NORD         1
80 - DT DE PARIS        1
83 - DT DES YVELINES    3
Name: AEO Nb_responsables, dtype: int64

DT_de_rattachement
103 - DT DE LA MARTINIQUE       1
18 - DT DU CALVADOS             1
34 - DT DU FINISTERE            1
3959 - DT DE LA REUNION         2
3986 - DT DE LA SAVOIE          1
42 - DT D'INDRE ET LOIRE        1
4394 - DT DE HAUTE SAONE        1
44 - DT DU JURA                 2
74 - DT DU RHONE                1
76 - DT DE SAONE ET LOIRE       2
79 - DT DE LA HAUTE SAVOIE      1
80 - DT DE PARIS                2
81 - DT DE LA SEINE MARITIME    1
83 - DT DES YVELINES            3
96 - DT DE L'ESSONNE            1
Name: OCR Nb_referents, dtype: int64

DT_de_rattachement
10 - DT DES ALPES MARITIMES                40
100 - DT DU VAL D'OISE                    126
12 - DT DES ARDENNES                       38
15 - DT DE L'AUDE                           0
17 - DT DES BOUCHES DU RHONE                0
18 - DT DU CALVADOS                       222
20 - DT DE LA CHARENTE                     23
23 - DT DE LA CORREZE                       0
26 - DT DE LA COTE D'OR                     0
31 - DT DE LA DROME                         0
33 - DT D'EURE ET LOIR                   1000
35 - DT DU GARD                            32
37 - DT DU GERS                          1573
38 - DT DE LA GIRONDE                       0
39 - DT DE L'HERAULT                      345
3959 - DT DE LA REUNION                    54
3968 - DT DE LA DORDOGNE                   49
3969 - DT DES HAUTES PYRENEES              37
3971 - DT DES COTES D'ARMOR                72
3986 - DT DE LA SAVOIE                   1507
3997 - DT DES ALPES DE HAUTE PROVENCE       0
4017 - DT DU VAR                           31
42 - DT D'INDRE ET LOIRE                 1312
43 - DT DE L'ISERE                         67
4394 - DT DE HAUTE SAONE                    0
44 - DT DU JURA                             0
4631 - DT DE SEINE SAINT DENIS             51
4649 - DT DE LA MEUSE                       0
47 - DT DE LA LOIRE                         0
49 - DT DE LA LOIRE ATLANTIQUE             57
50 - DT DU LOIRET                        1466
52 - DT DU LOT ET GARONNE                 427
54 - DT DU MAINE ET LOIRE                  28
55 - DT DE LA MANCHE                      133
57 - DT DE LA HAUTE MARNE                 391
59 - DT DE MEURTHE ET MOSELLE              17
61 - DT DU MORBIHAN                         0
62 - DT DE LA MOSELLE                      42
63 - DT DE LA NIEVRE                        0
64 - DT DU NORD                           220
67 - DT DU PAS DE CALAIS                  143
72 - DT DU BAS RHIN                       418
73 - DT DU HAUT RHIN                       15
76 - DT DE SAONE ET LOIRE                  10
77 - DT DE LA SARTHE                        1
80 - DT DE PARIS                          642
81 - DT DE LA SEINE MARITIME             2141
82 - DT DE LA SEINE ET MARNE               34
83 - DT DES YVELINES                      248
85 - DT DE LA SOMME                       818
86 - DT DU TARN                             1
87 - DT DU TARN ET GARONNE                  3
89 - DT DU VAUCLUSE                        78
90 - DT DE VENDEE                           0
92 - DT DE LA HAUTE VIENNE                  0
94 - DT DE L'YONNE                         65
95 - DT DU TERRITOIRE DE BELFORT          429
96 - DT DE L'ESSONNE                      144
97 - DT DES HAUTS DE SEINE                203
99 - DT DU VAL DE MARNE                   665
Name: Dispositifs_d_urgence Nb_personnes_prises_charge, dtype: int64

DT_de_rattachement
10 - DT DES ALPES MARITIMES              0
100 - DT DU VAL D'OISE                   0
102 - DT DE LA GUADELOUPE                0
12 - DT DES ARDENNES                     0
15 - DT DE L'AUDE                        0
17 - DT DES BOUCHES DU RHONE             0
18 - DT DU CALVADOS                      0
20 - DT DE LA CHARENTE                   0
23 - DT DE LA CORREZE                    0
2570 - DT DE LA GUYANE                   0
26 - DT DE LA COTE D'OR                  0
31 - DT DE LA DROME                      0
33 - DT D'EURE ET LOIR                   0
37 - DT DU GERS                          0
38 - DT DE LA GIRONDE                    0
39 - DT DE L'HERAULT                     0
3959 - DT DE LA REUNION                  0
3968 - DT DE LA DORDOGNE                 0
3969 - DT DES HAUTES PYRENEES            0
3971 - DT DES COTES D'ARMOR              0
3986 - DT DE LA SAVOIE                   0
3997 - DT DES ALPES DE HAUTE PROVENCE    0
4017 - DT DU VAR                         0
42 - DT D'INDRE ET LOIRE                 0
4394 - DT DE HAUTE SAONE                 0
4395 - DT DE L'AVEYRON                   0
44 - DT DU JURA                          0
4631 - DT DE SEINE SAINT DENIS           0
4649 - DT DE LA MEUSE                    0
47 - DT DE LA LOIRE                      0
49 - DT DE LA LOIRE ATLANTIQUE           0
50 - DT DU LOIRET                        0
54 - DT DU MAINE ET LOIRE                0
55 - DT DE LA MANCHE                     0
57 - DT DE LA HAUTE MARNE                0
59 - DT DE MEURTHE ET MOSELLE            0
61 - DT DU MORBIHAN                      0
62 - DT DE LA MOSELLE                    0
63 - DT DE LA NIEVRE                     0
64 - DT DU NORD                          0
72 - DT DU BAS RHIN                      0
73 - DT DU HAUT RHIN                     0
76 - DT DE SAONE ET LOIRE                0
77 - DT DE LA SARTHE                     0
80 - DT DE PARIS                         0
81 - DT DE LA SEINE MARITIME             0
83 - DT DES YVELINES                     0
85 - DT DE LA SOMME                      0
86 - DT DU TARN                          0
87 - DT DU TARN ET GARONNE               0
89 - DT DU VAUCLUSE                      0
90 - DT DE VENDEE                        0
92 - DT DE LA HAUTE VIENNE               0
94 - DT DE L'YONNE                       0
95 - DT DU TERRITOIRE DE BELFORT         0
97 - DT DES HAUTS DE SEINE               0
99 - DT DU VAL DE MARNE                  0
Name: Dispositifs_d_urgence Nb_agrements, dtype: object

DT_de_rattachement
102 - DT DE LA GUADELOUPE                0
12 - DT DES ARDENNES                     0
17 - DT DES BOUCHES DU RHONE             0
2570 - DT DE LA GUYANE                   0
26 - DT DE LA COTE D'OR                  0
33 - DT D'EURE ET LOIR                   0
39 - DT DE L'HERAULT                     0
3959 - DT DE LA REUNION                  0
3968 - DT DE LA DORDOGNE                 0
3986 - DT DE LA SAVOIE                   0
3997 - DT DES ALPES DE HAUTE PROVENCE    0
4017 - DT DU VAR                         0
42 - DT D'INDRE ET LOIRE                 0
4394 - DT DE HAUTE SAONE                 0
4395 - DT DE L'AVEYRON                   0
4631 - DT DE SEINE SAINT DENIS           0
47 - DT DE LA LOIRE                      0
50 - DT DU LOIRET                        0
54 - DT DU MAINE ET LOIRE                0
55 - DT DE LA MANCHE                     0
59 - DT DE MEURTHE ET MOSELLE            0
62 - DT DE LA MOSELLE                    0
72 - DT DU BAS RHIN                      0
73 - DT DU HAUT RHIN                     0
76 - DT DE SAONE ET LOIRE                0
77 - DT DE LA SARTHE                     0
80 - DT DE PARIS                         0
81 - DT DE LA SEINE MARITIME             0
83 - DT DES YVELINES                     0
85 - DT DE LA SOMME                      0
86 - DT DU TARN                          0
87 - DT DU TARN ET GARONNE               0
89 - DT DU VAUCLUSE                      0
94 - DT DE L'YONNE                       0
95 - DT DU TERRITOIRE DE BELFORT         0
97 - DT DES HAUTS DE SEINE               0
99 - DT DU VAL DE MARNE                  0
Name: Secours Nb_agrements_DPS_2025, dtype: object

DT_de_rattachement
17 - DT DES BOUCHES DU RHONE         1
26 - DT DE LA COTE D'OR              2
33 - DT D'EURE ET LOIR               4
34 - DT DU FINISTERE                 1
35 - DT DU GARD                      2
3667 - DT DE ST BARTHELEMY           1
38 - DT DE LA GIRONDE                2
3966 - DT DES VOSGES                12
3971 - DT DES COTES D'ARMOR          2
42 - DT D'INDRE ET LOIRE             1
4394 - DT DE HAUTE SAONE             1
48 - DT DE LA HAUTE LOIRE            1
52 - DT DU LOT ET GARONNE            1
54 - DT DU MAINE ET LOIRE            2
59 - DT DE MEURTHE ET MOSELLE        1
61 - DT DU MORBIHAN                  1
69 - DT DES PYRENEES ATLANTIQUES     1
74 - DT DU RHONE                     3
79 - DT DE LA HAUTE SAVOIE          10
82 - DT DE LA SEINE ET MARNE         1
83 - DT DES YVELINES                 3
86 - DT DU TARN                      3
Name: OCR Nb_deployees, dtype: int64

DT_de_rattachement
10 - DT DES ALPES MARITIMES         Oui
100 - DT DU VAL D'OISE              Oui
104 - DT DE NOUVELLE CALEDONIE      Oui
11 - DT DE L'ARDECHE                Oui
12 - DT DES ARDENNES                Oui
                                   ...
94 - DT DE L'YONNE                  Oui
95 - DT DU TERRITOIRE DE BELFORT    Oui
96 - DT DE L'ESSONNE                Oui
97 - DT DES HAUTS DE SEINE          Oui
99 - DT DU VAL DE MARNE             Oui
Name: Dispositifs_d_urgence_Utilisation_RedCall, Length: 98, dtype: object

In [108]:
for i,df in enumerate(liste_df_a_fusionner_toutes_structures):
  if 'n_structure' not in df.columns:
    print(i)
    display(df)

In [109]:
for i,df in enumerate(liste_df_a_fusionner_DT):
  if 'n_structure' not in df.columns:
    print(i)
    display(df)
    if 'DT_de_rattachement' in df.columns:
      liste_df_a_fusionner_DT[i] = liste_df_a_fusionner_DT[i].rename(columns={'DT_de_rattachement': 'n_structure'})

  if liste_df_a_fusionner_DT[i]['n_structure'].dtype == 'object':
    # 2️⃣ Vérifier s’il y a au moins une valeur contenant des lettres
    contient_lettres = liste_df_a_fusionner_DT[i]['n_structure'].astype(str).str.contains(r'[A-Za-z]', na=False).any()
    if contient_lettres:
      print(i)
      display(liste_df_a_fusionner_DT[i]['n_structure'])
      liste_df_a_fusionner_DT[i]['n_structure'] = liste_df_a_fusionner_DT[i]['n_structure'].apply(keep_integer).astype(int)

0

                   DT_de_rattachement  Structure Nb_Benevoles
0         10 - DT DES ALPES MARITIMES                    1717
1              100 - DT DU VAL D'OISE                    1036
2           102 - DT DE LA GUADELOUPE                     690
3           103 - DT DE LA MARTINIQUE                     465
4      104 - DT DE NOUVELLE CALEDONIE                     428
..                                ...                     ...
103                94 - DT DE L'YONNE                     517
104  95 - DT DU TERRITOIRE DE BELFORT                     126
105              96 - DT DE L'ESSONNE                    1472
106        97 - DT DES HAUTS DE SEINE                    3899
107           99 - DT DU VAL DE MARNE                    1817

[108 rows x 2 columns]

0

0           10 - DT DES ALPES MARITIMES
1                100 - DT DU VAL D'OISE
2             102 - DT DE LA GUADELOUPE
3             103 - DT DE LA MARTINIQUE
4        104 - DT DE NOUVELLE CALEDONIE
                     ...
103                  94 - DT DE L'YONNE
104    95 - DT DU TERRITOIRE DE BELFORT
105                96 - DT DE L'ESSONNE
106          97 - DT DES HAUTS DE SEINE
107             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 108, dtype: object

1

                   DT_de_rattachement  Structure Nb_nvx_Benevoles_2025
0         10 - DT DES ALPES MARITIMES                              209
1              100 - DT DU VAL D'OISE                              193
2           102 - DT DE LA GUADELOUPE                               60
3           103 - DT DE LA MARTINIQUE                               88
4      104 - DT DE NOUVELLE CALEDONIE                              104
..                                ...                              ...
101                94 - DT DE L'YONNE                              109
102  95 - DT DU TERRITOIRE DE BELFORT                               13
103              96 - DT DE L'ESSONNE                              427
104        97 - DT DES HAUTS DE SEINE                              646
105           99 - DT DU VAL DE MARNE                              336

[106 rows x 2 columns]

1

0           10 - DT DES ALPES MARITIMES
1                100 - DT DU VAL D'OISE
2             102 - DT DE LA GUADELOUPE
3             103 - DT DE LA MARTINIQUE
4        104 - DT DE NOUVELLE CALEDONIE
                     ...
101                  94 - DT DE L'YONNE
102    95 - DT DU TERRITOIRE DE BELFORT
103                96 - DT DE L'ESSONNE
104          97 - DT DES HAUTS DE SEINE
105             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 106, dtype: object

2

     DT_de_rattachement  AEO Nb_responsables
0  34 - DT DU FINISTERE                    1
1       64 - DT DU NORD                    1
2      80 - DT DE PARIS                    1
3  83 - DT DES YVELINES                    3

2

0    34 - DT DU FINISTERE
1         64 - DT DU NORD
2        80 - DT DE PARIS
3    83 - DT DES YVELINES
Name: n_structure, dtype: object

3

              DT_de_rattachement  OCR Nb_referents
0      103 - DT DE LA MARTINIQUE                 1
1            18 - DT DU CALVADOS                 1
2           34 - DT DU FINISTERE                 1
3        3959 - DT DE LA REUNION                 2
4         3986 - DT DE LA SAVOIE                 1
5       42 - DT D'INDRE ET LOIRE                 1
6       4394 - DT DE HAUTE SAONE                 1
7                44 - DT DU JURA                 2
8               74 - DT DU RHONE                 1
9      76 - DT DE SAONE ET LOIRE                 2
10    79 - DT DE LA HAUTE SAVOIE                 1
11              80 - DT DE PARIS                 2
12  81 - DT DE LA SEINE MARITIME                 1
13          83 - DT DES YVELINES                 3
14          96 - DT DE L'ESSONNE                 1

3

0        103 - DT DE LA MARTINIQUE
1              18 - DT DU CALVADOS
2             34 - DT DU FINISTERE
3          3959 - DT DE LA REUNION
4           3986 - DT DE LA SAVOIE
5         42 - DT D'INDRE ET LOIRE
6         4394 - DT DE HAUTE SAONE
7                  44 - DT DU JURA
8                 74 - DT DU RHONE
9        76 - DT DE SAONE ET LOIRE
10      79 - DT DE LA HAUTE SAVOIE
11                80 - DT DE PARIS
12    81 - DT DE LA SEINE MARITIME
13            83 - DT DES YVELINES
14            96 - DT DE L'ESSONNE
Name: n_structure, dtype: object

4

,DT_de_rattachement,Dispositifs_d_urgence Nb_personnes_prises_charge
0,10 - DT DES ALPES MARITIMES,40
1,100 - DT DU VAL D'OISE,126
2,12 - DT DES ARDENNES,38
3,15 - DT DE L'AUDE,0
4,17 - DT DES BOUCHES DU RHONE,0
5,18 - DT DU CALVADOS,222
6,20 - DT DE LA CHARENTE,23
7,23 - DT DE LA CORREZE,0
8,26 - DT DE LA COTE D'OR,0
9,31 - DT DE LA DROME,0
10,33 - DT D'EURE ET LOIR,1000
11,35 - DT DU GARD,32
12,37 - DT DU GERS,1573
13,38 - DT DE LA GIRONDE,0
14,39 - DT DE L'HERAULT,345
15,3959 - DT DE LA REUNION,54
16,3968 - DT DE LA DORDOGNE,49
17,3969 - DT DES HAUTES PYRENEES,37
18,3971 - DT DES COTES D'ARMOR,72
19,3986 - DT DE LA SAVOIE,1507
20,3997 - DT DES ALPES DE HAUTE PROVENCE,0
21,4017 - DT DU VAR,31
22,42 - DT D'INDRE ET LOIRE,1312
23,43 - DT DE L'ISERE,67
24,4394 - DT DE HAUTE SAONE,0
25,44 - DT DU JURA,0
26,4631 - DT DE SEINE SAINT DENIS,51
27,4649 - DT DE LA MEUSE,0
28,47 - DT DE LA LOIRE,0
29,49 - DT DE LA LOIRE ATLANTIQUE,57
30,50 - DT DU LOIRET,1466
31,52 - DT DU LOT ET GARONNE,427
32,54 - DT DU MAINE ET LOIRE,28
33,55 - DT DE LA MANCHE,133
34,57 - DT DE LA HAUTE MARNE,391
35,59 - DT DE MEURTHE ET MOSELLE,17
36,61 - DT DU MORBIHAN,0
37,62 - DT DE LA MOSELLE,42
38,63 - DT DE LA NIEVRE,0
39,64 - DT DU NORD,220
40,67 - DT DU PAS DE CALAIS,143
41,72 - DT DU BAS RHIN,418
42,73 - DT DU HAUT RHIN,15
43,76 - DT DE SAONE ET LOIRE,10
44,77 - DT DE LA SARTHE,1
45,80 - DT DE PARIS,642
46,81 - DT DE LA SEINE MARITIME,2141
47,82 - DT DE LA SEINE ET MARNE,34
48,83 - DT DES YVELINES,248
49,85 - DT DE LA SOMME,818
50,86 - DT DU TARN,1
51,87 - DT DU TARN ET GARONNE,3
52,89 - DT DU VAUCLUSE,78
53,90 - DT DE VENDEE,0
54,92 - DT DE LA HAUTE VIENNE,0
55,94 - DT DE L'YONNE,65
56,95 - DT DU TERRITOIRE DE BELFORT,429
57,96 - DT DE L'ESSONNE,144
58,97 - DT DES HAUTS DE SEINE,203
59,99 - DT DU VAL DE MARNE,665

4

0               10 - DT DES ALPES MARITIMES
1                    100 - DT DU VAL D'OISE
2                      12 - DT DES ARDENNES
3                         15 - DT DE L'AUDE
4              17 - DT DES BOUCHES DU RHONE
5                       18 - DT DU CALVADOS
6                    20 - DT DE LA CHARENTE
7                     23 - DT DE LA CORREZE
8                   26 - DT DE LA COTE D'OR
9                       31 - DT DE LA DROME
10                   33 - DT D'EURE ET LOIR
11                          35 - DT DU GARD
12                          37 - DT DU GERS
13                    38 - DT DE LA GIRONDE
14                     39 - DT DE L'HERAULT
15                  3959 - DT DE LA REUNION
16                 3968 - DT DE LA DORDOGNE
17            3969 - DT DES HAUTES PYRENEES
18              3971 - DT DES COTES D'ARMOR
19                   3986 - DT DE LA SAVOIE
20    3997 - DT DES ALPES DE HAUTE PROVENCE
21                         4017 - DT DU VAR
22                 42 - DT D'INDRE ET LOIRE
23                       43 - DT DE L'ISERE
24                 4394 - DT DE HAUTE SAONE
25                          44 - DT DU JURA
26           4631 - DT DE SEINE SAINT DENIS
27                    4649 - DT DE LA MEUSE
28                      47 - DT DE LA LOIRE
29           49 - DT DE LA LOIRE ATLANTIQUE
30                        50 - DT DU LOIRET
31                52 - DT DU LOT ET GARONNE
32                54 - DT DU MAINE ET LOIRE
33                     55 - DT DE LA MANCHE
34                57 - DT DE LA HAUTE MARNE
35            59 - DT DE MEURTHE ET MOSELLE
36                      61 - DT DU MORBIHAN
37                    62 - DT DE LA MOSELLE
38                     63 - DT DE LA NIEVRE
39                          64 - DT DU NORD
40                 67 - DT DU PAS DE CALAIS
41                      72 - DT DU BAS RHIN
42                     73 - DT DU HAUT RHIN
43                76 - DT DE SAONE ET LOIRE
44                     77 - DT DE LA SARTHE
45                         80 - DT DE PARIS
46             81 - DT DE LA SEINE MARITIME
47             82 - DT DE LA SEINE ET MARNE
48                     83 - DT DES YVELINES
49                      85 - DT DE LA SOMME
50                          86 - DT DU TARN
51               87 - DT DU TARN ET GARONNE
52                      89 - DT DU VAUCLUSE
53                        90 - DT DE VENDEE
54               92 - DT DE LA HAUTE VIENNE
55                       94 - DT DE L'YONNE
56         95 - DT DU TERRITOIRE DE BELFORT
57                     96 - DT DE L'ESSONNE
58               97 - DT DES HAUTS DE SEINE
59                  99 - DT DU VAL DE MARNE
Name: n_structure, dtype: object

5

                       DT_de_rattachement Dispositifs_d_urgence Nb_agrements
0             10 - DT DES ALPES MARITIMES                                  0
1                  100 - DT DU VAL D'OISE                                  0
2               102 - DT DE LA GUADELOUPE                                  0
3                    12 - DT DES ARDENNES                                  0
4                       15 - DT DE L'AUDE                                  0
5            17 - DT DES BOUCHES DU RHONE                                  0
6                     18 - DT DU CALVADOS                                  0
7                  20 - DT DE LA CHARENTE                                  0
8                   23 - DT DE LA CORREZE                                  0
9                  2570 - DT DE LA GUYANE                                  0
10                26 - DT DE LA COTE D'OR                                  0
11                    31 - DT DE LA DROME                                  0
12                 33 - DT D'EURE ET LOIR                                  0
13                        37 - DT DU GERS                                  0
14                  38 - DT DE LA GIRONDE                                  0
15                   39 - DT DE L'HERAULT                                  0
16                3959 - DT DE LA REUNION                                  0
17               3968 - DT DE LA DORDOGNE                                  0
18          3969 - DT DES HAUTES PYRENEES                                  0
19            3971 - DT DES COTES D'ARMOR                                  0
20                 3986 - DT DE LA SAVOIE                                  0
21  3997 - DT DES ALPES DE HAUTE PROVENCE                                  0
22                       4017 - DT DU VAR                                  0
23               42 - DT D'INDRE ET LOIRE                                  0
24               4394 - DT DE HAUTE SAONE                                  0
25                 4395 - DT DE L'AVEYRON                                  0
26                        44 - DT DU JURA                                  0
27         4631 - DT DE SEINE SAINT DENIS                                  0
28                  4649 - DT DE LA MEUSE                                  0
29                    47 - DT DE LA LOIRE                                  0
30         49 - DT DE LA LOIRE ATLANTIQUE                                  0
31                      50 - DT DU LOIRET                                  0
32              54 - DT DU MAINE ET LOIRE                                  0
33                   55 - DT DE LA MANCHE                                  0
34              57 - DT DE LA HAUTE MARNE                                  0
35          59 - DT DE MEURTHE ET MOSELLE                                  0
36                    61 - DT DU MORBIHAN                                  0
37                  62 - DT DE LA MOSELLE                                  0
38                   63 - DT DE LA NIEVRE                                  0
39                        64 - DT DU NORD                                  0
40                    72 - DT DU BAS RHIN                                  0
41                   73 - DT DU HAUT RHIN                                  0
42              76 - DT DE SAONE ET LOIRE                                  0
43                   77 - DT DE LA SARTHE                                  0
44                       80 - DT DE PARIS                                  0
45           81 - DT DE LA SEINE MARITIME                                  0
46                   83 - DT DES YVELINES                                  0
47                    85 - DT DE LA SOMME                                  0
48                        86 - DT DU TARN                                  0
49             87 - DT DU TARN ET GARONNE                                  0
50                    89 - DT DU VAUCLUSE                                  0
51                      90 - DT DE VENDEE                                  0
52             92 - DT DE LA HAUTE VIENNE                                  0
53                     94 - DT DE L'YONNE                                  0
54       95 - DT DU TERRITOIRE DE BELFORT                                  0
55             97 - DT DES HAUTS DE SEINE                                  0
56                99 - DT DU VAL DE MARNE                                  0

5

0               10 - DT DES ALPES MARITIMES
1                    100 - DT DU VAL D'OISE
2                 102 - DT DE LA GUADELOUPE
3                      12 - DT DES ARDENNES
4                         15 - DT DE L'AUDE
5              17 - DT DES BOUCHES DU RHONE
6                       18 - DT DU CALVADOS
7                    20 - DT DE LA CHARENTE
8                     23 - DT DE LA CORREZE
9                    2570 - DT DE LA GUYANE
10                  26 - DT DE LA COTE D'OR
11                      31 - DT DE LA DROME
12                   33 - DT D'EURE ET LOIR
13                          37 - DT DU GERS
14                    38 - DT DE LA GIRONDE
15                     39 - DT DE L'HERAULT
16                  3959 - DT DE LA REUNION
17                 3968 - DT DE LA DORDOGNE
18            3969 - DT DES HAUTES PYRENEES
19              3971 - DT DES COTES D'ARMOR
20                   3986 - DT DE LA SAVOIE
21    3997 - DT DES ALPES DE HAUTE PROVENCE
22                         4017 - DT DU VAR
23                 42 - DT D'INDRE ET LOIRE
24                 4394 - DT DE HAUTE SAONE
25                   4395 - DT DE L'AVEYRON
26                          44 - DT DU JURA
27           4631 - DT DE SEINE SAINT DENIS
28                    4649 - DT DE LA MEUSE
29                      47 - DT DE LA LOIRE
30           49 - DT DE LA LOIRE ATLANTIQUE
31                        50 - DT DU LOIRET
32                54 - DT DU MAINE ET LOIRE
33                     55 - DT DE LA MANCHE
34                57 - DT DE LA HAUTE MARNE
35            59 - DT DE MEURTHE ET MOSELLE
36                      61 - DT DU MORBIHAN
37                    62 - DT DE LA MOSELLE
38                     63 - DT DE LA NIEVRE
39                          64 - DT DU NORD
40                      72 - DT DU BAS RHIN
41                     73 - DT DU HAUT RHIN
42                76 - DT DE SAONE ET LOIRE
43                     77 - DT DE LA SARTHE
44                         80 - DT DE PARIS
45             81 - DT DE LA SEINE MARITIME
46                     83 - DT DES YVELINES
47                      85 - DT DE LA SOMME
48                          86 - DT DU TARN
49               87 - DT DU TARN ET GARONNE
50                      89 - DT DU VAUCLUSE
51                        90 - DT DE VENDEE
52               92 - DT DE LA HAUTE VIENNE
53                       94 - DT DE L'YONNE
54         95 - DT DU TERRITOIRE DE BELFORT
55               97 - DT DES HAUTS DE SEINE
56                  99 - DT DU VAL DE MARNE
Name: n_structure, dtype: object

6

                       DT_de_rattachement Secours Nb_agrements_DPS_2025
0               102 - DT DE LA GUADELOUPE                             0
1                    12 - DT DES ARDENNES                             0
2            17 - DT DES BOUCHES DU RHONE                             0
3                  2570 - DT DE LA GUYANE                             0
4                 26 - DT DE LA COTE D'OR                             0
5                  33 - DT D'EURE ET LOIR                             0
6                    39 - DT DE L'HERAULT                             0
7                 3959 - DT DE LA REUNION                             0
8                3968 - DT DE LA DORDOGNE                             0
9                  3986 - DT DE LA SAVOIE                             0
10  3997 - DT DES ALPES DE HAUTE PROVENCE                             0
11                       4017 - DT DU VAR                             0
12               42 - DT D'INDRE ET LOIRE                             0
13               4394 - DT DE HAUTE SAONE                             0
14                 4395 - DT DE L'AVEYRON                             0
15         4631 - DT DE SEINE SAINT DENIS                             0
16                    47 - DT DE LA LOIRE                             0
17                      50 - DT DU LOIRET                             0
18              54 - DT DU MAINE ET LOIRE                             0
19                   55 - DT DE LA MANCHE                             0
20          59 - DT DE MEURTHE ET MOSELLE                             0
21                  62 - DT DE LA MOSELLE                             0
22                    72 - DT DU BAS RHIN                             0
23                   73 - DT DU HAUT RHIN                             0
24              76 - DT DE SAONE ET LOIRE                             0
25                   77 - DT DE LA SARTHE                             0
26                       80 - DT DE PARIS                             0
27           81 - DT DE LA SEINE MARITIME                             0
28                   83 - DT DES YVELINES                             0
29                    85 - DT DE LA SOMME                             0
30                        86 - DT DU TARN                             0
31             87 - DT DU TARN ET GARONNE                             0
32                    89 - DT DU VAUCLUSE                             0
33                     94 - DT DE L'YONNE                             0
34       95 - DT DU TERRITOIRE DE BELFORT                             0
35             97 - DT DES HAUTS DE SEINE                             0
36                99 - DT DU VAL DE MARNE                             0

6

0                 102 - DT DE LA GUADELOUPE
1                      12 - DT DES ARDENNES
2              17 - DT DES BOUCHES DU RHONE
3                    2570 - DT DE LA GUYANE
4                   26 - DT DE LA COTE D'OR
5                    33 - DT D'EURE ET LOIR
6                      39 - DT DE L'HERAULT
7                   3959 - DT DE LA REUNION
8                  3968 - DT DE LA DORDOGNE
9                    3986 - DT DE LA SAVOIE
10    3997 - DT DES ALPES DE HAUTE PROVENCE
11                         4017 - DT DU VAR
12                 42 - DT D'INDRE ET LOIRE
13                 4394 - DT DE HAUTE SAONE
14                   4395 - DT DE L'AVEYRON
15           4631 - DT DE SEINE SAINT DENIS
16                      47 - DT DE LA LOIRE
17                        50 - DT DU LOIRET
18                54 - DT DU MAINE ET LOIRE
19                     55 - DT DE LA MANCHE
20            59 - DT DE MEURTHE ET MOSELLE
21                    62 - DT DE LA MOSELLE
22                      72 - DT DU BAS RHIN
23                     73 - DT DU HAUT RHIN
24                76 - DT DE SAONE ET LOIRE
25                     77 - DT DE LA SARTHE
26                         80 - DT DE PARIS
27             81 - DT DE LA SEINE MARITIME
28                     83 - DT DES YVELINES
29                      85 - DT DE LA SOMME
30                          86 - DT DU TARN
31               87 - DT DU TARN ET GARONNE
32                      89 - DT DU VAUCLUSE
33                       94 - DT DE L'YONNE
34         95 - DT DU TERRITOIRE DE BELFORT
35               97 - DT DES HAUTS DE SEINE
36                  99 - DT DU VAL DE MARNE
Name: n_structure, dtype: object

8

                  DT_de_rattachement  OCR Nb_deployees
0       17 - DT DES BOUCHES DU RHONE                 1
1            26 - DT DE LA COTE D'OR                 2
2             33 - DT D'EURE ET LOIR                 4
3               34 - DT DU FINISTERE                 1
4                    35 - DT DU GARD                 2
5         3667 - DT DE ST BARTHELEMY                 1
6              38 - DT DE LA GIRONDE                 2
7               3966 - DT DES VOSGES                12
8        3971 - DT DES COTES D'ARMOR                 2
9           42 - DT D'INDRE ET LOIRE                 1
10          4394 - DT DE HAUTE SAONE                 1
11         48 - DT DE LA HAUTE LOIRE                 1
12         52 - DT DU LOT ET GARONNE                 1
13         54 - DT DU MAINE ET LOIRE                 2
14     59 - DT DE MEURTHE ET MOSELLE                 1
15               61 - DT DU MORBIHAN                 1
16  69 - DT DES PYRENEES ATLANTIQUES                 1
17                  74 - DT DU RHONE                 3
18        79 - DT DE LA HAUTE SAVOIE                10
19      82 - DT DE LA SEINE ET MARNE                 1
20              83 - DT DES YVELINES                 3
21                   86 - DT DU TARN                 3

8

0         17 - DT DES BOUCHES DU RHONE
1              26 - DT DE LA COTE D'OR
2               33 - DT D'EURE ET LOIR
3                 34 - DT DU FINISTERE
4                      35 - DT DU GARD
5           3667 - DT DE ST BARTHELEMY
6                38 - DT DE LA GIRONDE
7                 3966 - DT DES VOSGES
8          3971 - DT DES COTES D'ARMOR
9             42 - DT D'INDRE ET LOIRE
10            4394 - DT DE HAUTE SAONE
11           48 - DT DE LA HAUTE LOIRE
12           52 - DT DU LOT ET GARONNE
13           54 - DT DU MAINE ET LOIRE
14       59 - DT DE MEURTHE ET MOSELLE
15                 61 - DT DU MORBIHAN
16    69 - DT DES PYRENEES ATLANTIQUES
17                    74 - DT DU RHONE
18          79 - DT DE LA HAUTE SAVOIE
19        82 - DT DE LA SEINE ET MARNE
20                83 - DT DES YVELINES
21                     86 - DT DU TARN
Name: n_structure, dtype: object

9

                  DT_de_rattachement Dispositifs_d_urgence_Utilisation_RedCall
0        10 - DT DES ALPES MARITIMES                                       Oui
1             100 - DT DU VAL D'OISE                                       Oui
2     104 - DT DE NOUVELLE CALEDONIE                                       Oui
3               11 - DT DE L'ARDECHE                                       Oui
4               12 - DT DES ARDENNES                                       Oui
..                               ...                                       ...
93                94 - DT DE L'YONNE                                       Oui
94  95 - DT DU TERRITOIRE DE BELFORT                                       Oui
95              96 - DT DE L'ESSONNE                                       Oui
96        97 - DT DES HAUTS DE SEINE                                       Oui
97           99 - DT DU VAL DE MARNE                                       Oui

[98 rows x 2 columns]

9

0          10 - DT DES ALPES MARITIMES
1               100 - DT DU VAL D'OISE
2       104 - DT DE NOUVELLE CALEDONIE
3                 11 - DT DE L'ARDECHE
4                 12 - DT DES ARDENNES
                    ...
93                  94 - DT DE L'YONNE
94    95 - DT DU TERRITOIRE DE BELFORT
95                96 - DT DE L'ESSONNE
96          97 - DT DES HAUTS DE SEINE
97             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 98, dtype: object

10

                  DT_de_rattachement  Aide_alimentaire Nb_U2A
0        10 - DT DES ALPES MARITIMES                       14
1             100 - DT DU VAL D'OISE                        9
2          102 - DT DE LA GUADELOUPE                        1
3          103 - DT DE LA MARTINIQUE                        1
4               11 - DT DE L'ARDECHE                        3
..                               ...                      ...
94                94 - DT DE L'YONNE                        8
95  95 - DT DU TERRITOIRE DE BELFORT                        3
96              96 - DT DE L'ESSONNE                       10
97        97 - DT DES HAUTS DE SEINE                        5
98           99 - DT DU VAL DE MARNE                       10

[99 rows x 2 columns]

10

0          10 - DT DES ALPES MARITIMES
1               100 - DT DU VAL D'OISE
2            102 - DT DE LA GUADELOUPE
3            103 - DT DE LA MARTINIQUE
4                 11 - DT DE L'ARDECHE
                    ...
94                  94 - DT DE L'YONNE
95    95 - DT DU TERRITOIRE DE BELFORT
96                96 - DT DE L'ESSONNE
97          97 - DT DES HAUTS DE SEINE
98             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 99, dtype: object

11

                  DT_de_rattachement  Aide_alimentaire Nb_epiceries_sociales
0        10 - DT DES ALPES MARITIMES                                       1
1               1286 - DT DE MAYOTTE                                       1
2       17 - DT DES BOUCHES DU RHONE                                       3
3            26 - DT DE LA COTE D'OR                                       1
4                31 - DT DE LA DROME                                       3
5           36 - DT DE HAUTE GARONNE                                       2
6              38 - DT DE LA GIRONDE                                       1
7               39 - DT DE L'HERAULT                                       1
8        3971 - DT DES COTES D'ARMOR                                       2
9             3986 - DT DE LA SAVOIE                                       3
10          42 - DT D'INDRE ET LOIRE                                       8
11                43 - DT DE L'ISERE                                       1
12         4381 - DT DES DEUX SEVRES                                       6
13                   44 - DT DU JURA                                       2
14    4631 - DT DE SEINE SAINT DENIS                                       3
15                   5 - DT DE L'AIN                                       1
16         52 - DT DU LOT ET GARONNE                                       1
17         57 - DT DE LA HAUTE MARNE                                       1
18     59 - DT DE MEURTHE ET MOSELLE                                       1
19                 6 - DT DE L'AISNE                                       1
20             62 - DT DE LA MOSELLE                                       1
21          67 - DT DU PAS DE CALAIS                                       1
22  69 - DT DES PYRENEES ATLANTIQUES                                       3
23   71 - DT DES PYRENEES ORIENTALES                                       1
24              73 - DT DU HAUT RHIN                                       1
25                  74 - DT DU RHONE                                       1
26         76 - DT DE SAONE ET LOIRE                                       3
27        79 - DT DE LA HAUTE SAVOIE                                       2
28                  80 - DT DE PARIS                                       4
29      81 - DT DE LA SEINE MARITIME                                       1
30      82 - DT DE LA SEINE ET MARNE                                       1
31              83 - DT DES YVELINES                                       4
32        87 - DT DU TARN ET GARONNE                                       1
33               89 - DT DU VAUCLUSE                                       3
34              96 - DT DE L'ESSONNE                                       3
35        97 - DT DES HAUTS DE SEINE                                       3
36           99 - DT DU VAL DE MARNE                                       1

11

0          10 - DT DES ALPES MARITIMES
1                 1286 - DT DE MAYOTTE
2         17 - DT DES BOUCHES DU RHONE
3              26 - DT DE LA COTE D'OR
4                  31 - DT DE LA DROME
5             36 - DT DE HAUTE GARONNE
6                38 - DT DE LA GIRONDE
7                 39 - DT DE L'HERAULT
8          3971 - DT DES COTES D'ARMOR
9               3986 - DT DE LA SAVOIE
10            42 - DT D'INDRE ET LOIRE
11                  43 - DT DE L'ISERE
12           4381 - DT DES DEUX SEVRES
13                     44 - DT DU JURA
14      4631 - DT DE SEINE SAINT DENIS
15                     5 - DT DE L'AIN
16           52 - DT DU LOT ET GARONNE
17           57 - DT DE LA HAUTE MARNE
18       59 - DT DE MEURTHE ET MOSELLE
19                   6 - DT DE L'AISNE
20               62 - DT DE LA MOSELLE
21            67 - DT DU PAS DE CALAIS
22    69 - DT DES PYRENEES ATLANTIQUES
23     71 - DT DES PYRENEES ORIENTALES
24                73 - DT DU HAUT RHIN
25                    74 - DT DU RHONE
26           76 - DT DE SAONE ET LOIRE
27          79 - DT DE LA HAUTE SAVOIE
28                    80 - DT DE PARIS
29        81 - DT DE LA SEINE MARITIME
30        82 - DT DE LA SEINE ET MARNE
31                83 - DT DES YVELINES
32          87 - DT DU TARN ET GARONNE
33                 89 - DT DU VAUCLUSE
34                96 - DT DE L'ESSONNE
35          97 - DT DES HAUTS DE SEINE
36             99 - DT DU VAL DE MARNE
Name: n_structure, dtype: object

12

,DT_de_rattachement,Aide_alimentaire Nb_Centre_distribution_alimentaire
0,10 - DT DES ALPES MARITIMES,13
1,100 - DT DU VAL D'OISE,9
2,102 - DT DE LA GUADELOUPE,1
3,11 - DT DE L'ARDECHE,3
4,12 - DT DES ARDENNES,3
...,...,...
89,94 - DT DE L'YONNE,7
90,95 - DT DU TERRITOIRE DE BELFORT,3
91,96 - DT DE L'ESSONNE,6
92,97 - DT DES HAUTS DE SEINE,2
93,99 - DT DU VAL DE MARNE,9

12

0          10 - DT DES ALPES MARITIMES
1               100 - DT DU VAL D'OISE
2            102 - DT DE LA GUADELOUPE
3                 11 - DT DE L'ARDECHE
4                 12 - DT DES ARDENNES
                    ...
89                  94 - DT DE L'YONNE
90    95 - DT DU TERRITOIRE DE BELFORT
91                96 - DT DE L'ESSONNE
92          97 - DT DES HAUTS DE SEINE
93             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 94, dtype: object

13

                  DT_de_rattachement  Aide_alimentaire Nb_crsr
0          103 - DT DE LA MARTINIQUE                         1
1               1286 - DT DE MAYOTTE                         1
2                18 - DT DU CALVADOS                         1
3              23 - DT DE LA CORREZE                         1
4                   30 - DT DU DOUBS                         2
5                    37 - DT DU GERS                         1
6            3959 - DT DE LA REUNION                         2
7               3966 - DT DES VOSGES                         1
8           42 - DT D'INDRE ET LOIRE                         1
9                 43 - DT DE L'ISERE                         3
10          4394 - DT DE HAUTE SAONE                         1
11                   44 - DT DU JURA                         1
12                45 - DT DES LANDES                         1
13           46 - DT DU LOIR ET CHER                         1
14               47 - DT DE LA LOIRE                         5
15    49 - DT DE LA LOIRE ATLANTIQUE                         1
16                   5 - DT DE L'AIN                         2
17                 50 - DT DU LOIRET                         1
18                 6 - DT DE L'AISNE                         1
19               61 - DT DU MORBIHAN                         2
20                   64 - DT DU NORD                         1
21  69 - DT DES PYRENEES ATLANTIQUES                         1
22         76 - DT DE SAONE ET LOIRE                         1
23              83 - DT DES YVELINES                         1
24                   86 - DT DU TARN                         2
25               89 - DT DU VAUCLUSE                         1
26           9 - DT DES HAUTES ALPES                         1
27                94 - DT DE L'YONNE                         1
28              96 - DT DE L'ESSONNE                         1

13

0            103 - DT DE LA MARTINIQUE
1                 1286 - DT DE MAYOTTE
2                  18 - DT DU CALVADOS
3                23 - DT DE LA CORREZE
4                     30 - DT DU DOUBS
5                      37 - DT DU GERS
6              3959 - DT DE LA REUNION
7                 3966 - DT DES VOSGES
8             42 - DT D'INDRE ET LOIRE
9                   43 - DT DE L'ISERE
10            4394 - DT DE HAUTE SAONE
11                     44 - DT DU JURA
12                  45 - DT DES LANDES
13             46 - DT DU LOIR ET CHER
14                 47 - DT DE LA LOIRE
15      49 - DT DE LA LOIRE ATLANTIQUE
16                     5 - DT DE L'AIN
17                   50 - DT DU LOIRET
18                   6 - DT DE L'AISNE
19                 61 - DT DU MORBIHAN
20                     64 - DT DU NORD
21    69 - DT DES PYRENEES ATLANTIQUES
22           76 - DT DE SAONE ET LOIRE
23                83 - DT DES YVELINES
24                     86 - DT DU TARN
25                 89 - DT DU VAUCLUSE
26             9 - DT DES HAUTES ALPES
27                  94 - DT DE L'YONNE
28                96 - DT DE L'ESSONNE
Name: n_structure, dtype: object

14

                   DT_de_rattachement  Structure Nb_Adherents
0         10 - DT DES ALPES MARITIMES                     708
1              100 - DT DU VAL D'OISE                     646
2           102 - DT DE LA GUADELOUPE                     183
3           103 - DT DE LA MARTINIQUE                     279
4      104 - DT DE NOUVELLE CALEDONIE                     107
..                                ...                     ...
103                94 - DT DE L'YONNE                     300
104  95 - DT DU TERRITOIRE DE BELFORT                      79
105              96 - DT DE L'ESSONNE                     655
106        97 - DT DES HAUTS DE SEINE                    1915
107           99 - DT DU VAL DE MARNE                     894

[108 rows x 2 columns]

14

0           10 - DT DES ALPES MARITIMES
1                100 - DT DU VAL D'OISE
2             102 - DT DE LA GUADELOUPE
3             103 - DT DE LA MARTINIQUE
4        104 - DT DE NOUVELLE CALEDONIE
                     ...
103                  94 - DT DE L'YONNE
104    95 - DT DU TERRITOIRE DE BELFORT
105                96 - DT DE L'ESSONNE
106          97 - DT DES HAUTS DE SEINE
107             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 108, dtype: object

15

                  DT_de_rattachement  AEO Nb_personnes_domiciliees_crf
0             100 - DT DU VAL D'OISE                              1067
1                   30 - DT DU DOUBS                               133
2             33 - DT D'EURE ET LOIR                               864
3           36 - DT DE HAUTE GARONNE                             10116
4              38 - DT DE LA GIRONDE                                72
5       40 - DT DE L'ILLE ET VILAINE                              3342
6                    64 - DT DU NORD                              2404
7   69 - DT DES PYRENEES ATLANTIQUES                               224
8                72 - DT DU BAS RHIN                              3872
9               77 - DT DE LA SARTHE                              1350
10                  80 - DT DE PARIS                              1115
11              83 - DT DES YVELINES                              3328
12               89 - DT DU VAUCLUSE                               205
13              91 - DT DE LA VIENNE                              1356
14        97 - DT DES HAUTS DE SEINE                              1385

15

0               100 - DT DU VAL D'OISE
1                     30 - DT DU DOUBS
2               33 - DT D'EURE ET LOIR
3             36 - DT DE HAUTE GARONNE
4                38 - DT DE LA GIRONDE
5         40 - DT DE L'ILLE ET VILAINE
6                      64 - DT DU NORD
7     69 - DT DES PYRENEES ATLANTIQUES
8                  72 - DT DU BAS RHIN
9                 77 - DT DE LA SARTHE
10                    80 - DT DE PARIS
11                83 - DT DES YVELINES
12                 89 - DT DU VAUCLUSE
13                91 - DT DE LA VIENNE
14          97 - DT DES HAUTS DE SEINE
Name: n_structure, dtype: object

16

                  DT_de_rattachement  Maraude Nb_personnes_rencontrees
0        10 - DT DES ALPES MARITIMES                               137
1             100 - DT DU VAL D'OISE                               385
2               11 - DT DE L'ARDECHE                                90
3               12 - DT DES ARDENNES                               978
4                13 - DT DE L'ARIEGE                              3293
5       17 - DT DES BOUCHES DU RHONE                              2972
6            26 - DT DE LA COTE D'OR                              5458
7                31 - DT DE LA DROME                                38
8             33 - DT D'EURE ET LOIR                                86
9               34 - DT DU FINISTERE                             16402
10          36 - DT DE HAUTE GARONNE                               641
11                   37 - DT DU GERS                              1359
12             38 - DT DE LA GIRONDE                                 5
13              39 - DT DE L'HERAULT                                73
14           3959 - DT DE LA REUNION                              4257
15                 3970 - DT DU CHER                                 2
16       3971 - DT DES COTES D'ARMOR                              7760
17                41 - DT DE L'INDRE                              1556
18               4284 - DT DE L'ORNE                               145
19                43 - DT DE L'ISERE                               687
20         4381 - DT DES DEUX SEVRES                                69
21                   44 - DT DU JURA                               138
22                45 - DT DES LANDES                              1576
23           46 - DT DU LOIR ET CHER                               113
24    4631 - DT DE SEINE SAINT DENIS                               339
25                  4674 - DT DU LOT                              1824
26               47 - DT DE LA LOIRE                              1907
27    49 - DT DE LA LOIRE ATLANTIQUE                               100
28                   5 - DT DE L'AIN                              7988
29         52 - DT DU LOT ET GARONNE                                 8
30              55 - DT DE LA MANCHE                               447
31               56 - DT DE LA MARNE                              2341
32               61 - DT DU MORBIHAN                              3684
33                   64 - DT DU NORD                               667
34  69 - DT DES PYRENEES ATLANTIQUES                              1820
35              73 - DT DU HAUT RHIN                               926
36                  74 - DT DU RHONE                              1940
37         76 - DT DE SAONE ET LOIRE                              3834
38              77 - DT DE LA SARTHE                                 7
39        79 - DT DE LA HAUTE SAVOIE                               426
40                  80 - DT DE PARIS                              4624
41      81 - DT DE LA SEINE MARITIME                               148
42      82 - DT DE LA SEINE ET MARNE                              4518
43              83 - DT DES YVELINES                              6246
44           9 - DT DES HAUTES ALPES                               377
45                 90 - DT DE VENDEE                                 1
46              91 - DT DE LA VIENNE                              6517
47                94 - DT DE L'YONNE                               308
48  95 - DT DU TERRITOIRE DE BELFORT                               320
49              96 - DT DE L'ESSONNE                               994
50           99 - DT DU VAL DE MARNE                              1482

16

0          10 - DT DES ALPES MARITIMES
1               100 - DT DU VAL D'OISE
2                 11 - DT DE L'ARDECHE
3                 12 - DT DES ARDENNES
4                  13 - DT DE L'ARIEGE
5         17 - DT DES BOUCHES DU RHONE
6              26 - DT DE LA COTE D'OR
7                  31 - DT DE LA DROME
8               33 - DT D'EURE ET LOIR
9                 34 - DT DU FINISTERE
10            36 - DT DE HAUTE GARONNE
11                     37 - DT DU GERS
12               38 - DT DE LA GIRONDE
13                39 - DT DE L'HERAULT
14             3959 - DT DE LA REUNION
15                   3970 - DT DU CHER
16         3971 - DT DES COTES D'ARMOR
17                  41 - DT DE L'INDRE
18                 4284 - DT DE L'ORNE
19                  43 - DT DE L'ISERE
20           4381 - DT DES DEUX SEVRES
21                     44 - DT DU JURA
22                  45 - DT DES LANDES
23             46 - DT DU LOIR ET CHER
24      4631 - DT DE SEINE SAINT DENIS
25                    4674 - DT DU LOT
26                 47 - DT DE LA LOIRE
27      49 - DT DE LA LOIRE ATLANTIQUE
28                     5 - DT DE L'AIN
29           52 - DT DU LOT ET GARONNE
30                55 - DT DE LA MANCHE
31                 56 - DT DE LA MARNE
32                 61 - DT DU MORBIHAN
33                     64 - DT DU NORD
34    69 - DT DES PYRENEES ATLANTIQUES
35                73 - DT DU HAUT RHIN
36                    74 - DT DU RHONE
37           76 - DT DE SAONE ET LOIRE
38                77 - DT DE LA SARTHE
39          79 - DT DE LA HAUTE SAVOIE
40                    80 - DT DE PARIS
41        81 - DT DE LA SEINE MARITIME
42        82 - DT DE LA SEINE ET MARNE
43                83 - DT DES YVELINES
44             9 - DT DES HAUTES ALPES
45                   90 - DT DE VENDEE
46                91 - DT DE LA VIENNE
47                  94 - DT DE L'YONNE
48    95 - DT DU TERRITOIRE DE BELFORT
49                96 - DT DE L'ESSONNE
50             99 - DT DU VAL DE MARNE
Name: n_structure, dtype: object

17

                  DT_de_rattachement  Maraude Nb_maraudes_SIGMA
0        10 - DT DES ALPES MARITIMES                          5
1             100 - DT DU VAL D'OISE                         24
2               11 - DT DE L'ARDECHE                         37
3               12 - DT DES ARDENNES                        125
4                13 - DT DE L'ARIEGE                        233
5       17 - DT DES BOUCHES DU RHONE                        291
6            26 - DT DE LA COTE D'OR                        223
7                31 - DT DE LA DROME                          3
8             33 - DT D'EURE ET LOIR                         10
9               34 - DT DU FINISTERE                        415
10          36 - DT DE HAUTE GARONNE                        200
11                   37 - DT DU GERS                         38
12             38 - DT DE LA GIRONDE                          2
13              39 - DT DE L'HERAULT                         17
14           3959 - DT DE LA REUNION                        466
15              3966 - DT DES VOSGES                          1
16                 3970 - DT DU CHER                          3
17       3971 - DT DES COTES D'ARMOR                        314
18                41 - DT DE L'INDRE                         61
19               4284 - DT DE L'ORNE                         90
20                43 - DT DE L'ISERE                        103
21         4381 - DT DES DEUX SEVRES                          5
22                   44 - DT DU JURA                         50
23                45 - DT DES LANDES                         90
24           46 - DT DU LOIR ET CHER                         15
25    4631 - DT DE SEINE SAINT DENIS                         38
26                  4674 - DT DU LOT                        114
27               47 - DT DE LA LOIRE                         95
28    49 - DT DE LA LOIRE ATLANTIQUE                         84
29                   5 - DT DE L'AIN                        457
30         52 - DT DU LOT ET GARONNE                          6
31              55 - DT DE LA MANCHE                        114
32               56 - DT DE LA MARNE                        254
33               61 - DT DU MORBIHAN                        135
34                   64 - DT DU NORD                        174
35          67 - DT DU PAS DE CALAIS                         27
36  69 - DT DES PYRENEES ATLANTIQUES                        106
37              73 - DT DU HAUT RHIN                        120
38                  74 - DT DU RHONE                        255
39         76 - DT DE SAONE ET LOIRE                        188
40              77 - DT DE LA SARTHE                          1
41        79 - DT DE LA HAUTE SAVOIE                         36
42                  80 - DT DE PARIS                        723
43      81 - DT DE LA SEINE MARITIME                         44
44      82 - DT DE LA SEINE ET MARNE                        336
45              83 - DT DES YVELINES                        726
46           9 - DT DES HAUTES ALPES                         38
47                 90 - DT DE VENDEE                          3
48              91 - DT DE LA VIENNE                        345
49                94 - DT DE L'YONNE                         49
50  95 - DT DU TERRITOIRE DE BELFORT                         39
51              96 - DT DE L'ESSONNE                        216
52           99 - DT DU VAL DE MARNE                        335

17

0          10 - DT DES ALPES MARITIMES
1               100 - DT DU VAL D'OISE
2                 11 - DT DE L'ARDECHE
3                 12 - DT DES ARDENNES
4                  13 - DT DE L'ARIEGE
5         17 - DT DES BOUCHES DU RHONE
6              26 - DT DE LA COTE D'OR
7                  31 - DT DE LA DROME
8               33 - DT D'EURE ET LOIR
9                 34 - DT DU FINISTERE
10            36 - DT DE HAUTE GARONNE
11                     37 - DT DU GERS
12               38 - DT DE LA GIRONDE
13                39 - DT DE L'HERAULT
14             3959 - DT DE LA REUNION
15                3966 - DT DES VOSGES
16                   3970 - DT DU CHER
17         3971 - DT DES COTES D'ARMOR
18                  41 - DT DE L'INDRE
19                 4284 - DT DE L'ORNE
20                  43 - DT DE L'ISERE
21           4381 - DT DES DEUX SEVRES
22                     44 - DT DU JURA
23                  45 - DT DES LANDES
24             46 - DT DU LOIR ET CHER
25      4631 - DT DE SEINE SAINT DENIS
26                    4674 - DT DU LOT
27                 47 - DT DE LA LOIRE
28      49 - DT DE LA LOIRE ATLANTIQUE
29                     5 - DT DE L'AIN
30           52 - DT DU LOT ET GARONNE
31                55 - DT DE LA MANCHE
32                 56 - DT DE LA MARNE
33                 61 - DT DU MORBIHAN
34                     64 - DT DU NORD
35            67 - DT DU PAS DE CALAIS
36    69 - DT DES PYRENEES ATLANTIQUES
37                73 - DT DU HAUT RHIN
38                    74 - DT DU RHONE
39           76 - DT DE SAONE ET LOIRE
40                77 - DT DE LA SARTHE
41          79 - DT DE LA HAUTE SAVOIE
42                    80 - DT DE PARIS
43        81 - DT DE LA SEINE MARITIME
44        82 - DT DE LA SEINE ET MARNE
45                83 - DT DES YVELINES
46             9 - DT DES HAUTES ALPES
47                   90 - DT DE VENDEE
48                91 - DT DE LA VIENNE
49                  94 - DT DE L'YONNE
50    95 - DT DU TERRITOIRE DE BELFORT
51                96 - DT DE L'ESSONNE
52             99 - DT DU VAL DE MARNE
Name: n_structure, dtype: object

19

,DT_de_rattachement,n_dept,Financier Prod_2024,libelle_structure,Financier ResNet_2024,Financier ResCorrProd_2024,Financier TresoBrute_2024,Financier Mois_AvanceTreso_2024
0,95 - DT DU TERRITOIRE DE BELFORT,90,371153.13,DT - TERRITOIRE-DE-BELFORT,5174.82,0.013943,439146.13,13.890856
1,48 - DT DE LA HAUTE LOIRE,43,319290.45,DT - HAUTE-LOIRE,24919.92,0.078048,655591.68,26.174435
2,3970 - DT DU CHER,18,238379.24,DT - CHER,2797.52,0.011736,55989.64,3.640181
3,3965 - DT DE LA CORSE DU SUD,2A,146007.64,DT - CORSE-DU-SUD,10322.60,0.070699,125813.48,11.670411
4,3967 - DT DE LA HAUTE CORSE,2B,207120.51,DT - HAUTE-CORSE,4395.64,0.021223,372021.23,22.959576
...,...,...,...,...,...,...,...,...
103,92 - DT DE LA HAUTE VIENNE,87,360290.22,DT - HAUTE-VIENNE,-39555.42,-0.109788,727311.68,21.531738
104,94 - DT DE L'YONNE,89,489487.34,DT - YONNE,53515.15,0.109329,675805.08,19.342680
105,96 - DT DE L'ESSONNE,91,1636929.31,DT - ESSONNE,-10866.67,-0.006638,1547551.36,11.772285
106,97 - DT DES HAUTS DE SEINE,92,3568821.35,DT - HAUTS-DE-SEINE,460756.15,0.129106,7158583.91,26.185043
107,99 - DT DU VAL DE MARNE,94,1235949.97,DT - VAL-DE-MARNE,-152720.48,-0.123565,2653772.29,21.799823

19

0      95 - DT DU TERRITOIRE DE BELFORT
1             48 - DT DE LA HAUTE LOIRE
2                     3970 - DT DU CHER
3          3965 - DT DE LA CORSE DU SUD
4           3967 - DT DE LA HAUTE CORSE
                     ...
103          92 - DT DE LA HAUTE VIENNE
104                  94 - DT DE L'YONNE
105                96 - DT DE L'ESSONNE
106          97 - DT DES HAUTS DE SEINE
107             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 108, dtype: object

In [110]:
liste_df_a_fusionner_DT[18] = liste_df_a_fusionner_DT[18][liste_df_a_fusionner_DT[18]['n_structure'] !='']

In [111]:
for i,df in enumerate(liste_df_a_fusionner_toutes_structures):
  if liste_df_a_fusionner_toutes_structures[i]['n_structure'].dtype != df_ref_structure['n_structure'].dtype:
    liste_df_a_fusionner_toutes_structures[i]['n_structure'] = liste_df_a_fusionner_toutes_structures[i]['n_structure'].astype(int)

for i,df in enumerate(liste_df_a_fusionner_DT):
  if liste_df_a_fusionner_DT[i]['n_structure'].dtype != df_ref_structure['n_structure'].dtype:
    liste_df_a_fusionner_DT[i]['n_structure'] = liste_df_a_fusionner_DT[i]['n_structure'].astype(int)

/tmp/ipython-input-2569522971.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  liste_df_a_fusionner_DT[i]['n_structure'] = liste_df_a_fusionner_DT[i]['n_structure'].astype(int)

In [112]:
def merge_left_on_df1(df1, l, on):

    def safe_merge(left, right):
        # Supprime les colonnes déjà présentes (sauf la clé)
        cols_to_drop = [col for col in right.columns if col in left.columns and col != on]
        right_clean = right.drop(columns=cols_to_drop)

        return left.merge(right_clean, how='left', on=on)

    return reduce(safe_merge, l, df1)

In [113]:
def find_duplicates_in_list_of_dfs(dfs, column):
    """
    Pour chaque DataFrame dans une liste, trouve les doublons dans la colonne spécifiée.

    Args:
        dfs (list of pd.DataFrame): Liste de DataFrames à analyser
        column (str): Nom de la colonne sur laquelle chercher les doublons

    Returns:
        dict: Clé = index du DataFrame, Valeur = DataFrame des doublons
    """
    duplicates_dict = {}

    for i, df in enumerate(dfs):
        if column not in df.columns:
            print(f"⚠️ DataFrame {i} : la colonne '{column}' n'existe pas.")
            continue

        # Trouve les doublons
        df_duplicates = df[df.duplicated(subset=[column], keep=False)]

        if not df_duplicates.empty:
            duplicates_dict[i] = df_duplicates
            print(f"🔹 DataFrame {i} : {len(df_duplicates)} doublons trouvés dans '{column}'")
        else:
            print(f"✅ DataFrame {i} : aucun doublon dans '{column}'")

    return duplicates_dict

duplicates = find_duplicates_in_list_of_dfs(liste_df_a_fusionner_toutes_structures, column='n_structure')

✅ DataFrame 0 : aucun doublon dans 'n_structure'
✅ DataFrame 1 : aucun doublon dans 'n_structure'
✅ DataFrame 2 : aucun doublon dans 'n_structure'
✅ DataFrame 3 : aucun doublon dans 'n_structure'
✅ DataFrame 4 : aucun doublon dans 'n_structure'
✅ DataFrame 5 : aucun doublon dans 'n_structure'
✅ DataFrame 6 : aucun doublon dans 'n_structure'
✅ DataFrame 7 : aucun doublon dans 'n_structure'
✅ DataFrame 8 : aucun doublon dans 'n_structure'
✅ DataFrame 9 : aucun doublon dans 'n_structure'
✅ DataFrame 10 : aucun doublon dans 'n_structure'
✅ DataFrame 11 : aucun doublon dans 'n_structure'
✅ DataFrame 12 : aucun doublon dans 'n_structure'
✅ DataFrame 13 : aucun doublon dans 'n_structure'
✅ DataFrame 14 : aucun doublon dans 'n_structure'
✅ DataFrame 15 : aucun doublon dans 'n_structure'
✅ DataFrame 16 : aucun doublon dans 'n_structure'
✅ DataFrame 17 : aucun doublon dans 'n_structure'
✅ DataFrame 18 : aucun doublon dans 'n_structure'
✅ DataFrame 19 : aucun doublon dans 'n_structure'
✅ DataFrame 20 : aucun doublon dans 'n_structure'
✅ DataFrame 21 : aucun doublon dans 'n_structure'
✅ DataFrame 22 : aucun doublon dans 'n_structure'
✅ DataFrame 23 : aucun doublon dans 'n_structure'
✅ DataFrame 24 : aucun doublon dans 'n_structure'
✅ DataFrame 25 : aucun doublon dans 'n_structure'

In [114]:
liste_df_a_fusionner_toutes_structures[22]

,n_structure,Maraude Nb_personnes_rencontrees,DT_de_rattachement
0,5,6559,5 - DT DE L'AIN
1,12,978,12 - DT DES ARDENNES
2,39,1,39 - DT DE L'HERAULT
3,41,960,41 - DT DE L'INDRE
4,44,138,44 - DT DU JURA
...,...,...,...
108,4633,170,4631 - DT DE SEINE SAINT DENIS
109,4635,5,4631 - DT DE SEINE SAINT DENIS
110,4640,75,4631 - DT DE SEINE SAINT DENIS
111,4674,64,4674 - DT DU LOT
112,4676,1760,4674 - DT DU LOT

In [115]:
all_data  = merge_left_on_df1(df_ref_structure, liste_df_a_fusionner_toutes_structures, on = 'n_structure')
all_data_DT  = merge_left_on_df1(df_ref_structure_DT, liste_df_a_fusionner_DT, on = 'n_structure')

In [119]:
all_data

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,...,Financier Prod_2024,libelle_structure,Financier ResNet_2024,Financier ResCorrProd_2024,Financier TresoBrute_2024,Financier Mois_AvanceTreso_2024,nb_Maraude_Pegass,Dispositifs_d_urgence Nb_operations,Dispositifs_d_urgence Nb_exercices,AEO Structure_activite_fixe
0,2615,ANTENNE LOCALE - AL,AL DE DELLE,90100.0,90033,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",90,2010-02-08 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2669,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43220.0,43087,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",43,2011-01-01 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2670,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43600.0,43224,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",43,2011-01-01 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2671,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43300.0,43112,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",43,2011-01-01 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2672,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43000.0,43157,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",43,2011-01-01 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1180,993,UNITE LOCALE - UL,UL DE HAUTE PICARDIE,80320.0,80186,CHAULNES,"36 Avenue Roger Salengro, 80320 CHAULNES",80,1919-12-10 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1181,995,UNITE LOCALE - UL,UL DE DOULLENNAIS,80600.0,80253,DOULLENS,"1 Avenue du Général de Gaulle, 80600 DOULLENS",80,1916-12-10 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN
1182,996,UNITE LOCALE - UL,UL DU PAYS HAMOIS,80400.0,80410,HAM,"25 Boulevard du Général de Gaulle, 80400 HAM",80,1894-12-10 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1183,998,UNITE LOCALE - UL,UL DU VAL D'AVRE,80500.0,80561,MONTDIDIER,"6 Rue AMAND DE VIENNE, 80500 MONTDIDIER",80,1914-12-10 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1184,999,UNITE LOCALE - UL,UL DU PAYS NESLOIS,80190.0,80585,NESLE,"2 bis Avenue Clémenceau, 80190 NESLE",80,1917-12-10 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [120]:
all_data_DT

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,...,Financier Prod_2024,libelle_structure,Financier ResNet_2024,Financier ResCorrProd_2024,Financier TresoBrute_2024,Financier Mois_AvanceTreso_2024,nb_Maraude_Pegass,Dispositifs_d_urgence Nb_operations,Dispositifs_d_urgence Nb_exercices,AEO Structure_activite_fixe
0,10,DELEGATION TERRITORIALE - DT,DT DES ALPES MARITIMES,6700.0,06123,ST LAURENT DU VAR,"658 Boulevard JEAN OSSOLA, 06700 ST LAURENT DU...",6,1986-12-10 00:00:00,NaT,...,1679851.25,DT - ALPES-MARITIMES,221064.56,0.131598,3207611.24,28.730802,NaN,NaN,NaN,NaN
1,100,DELEGATION TERRITORIALE - DT,DT DU VAL D'OISE,95460.0,95229,EZANVILLE,"1 bis Rue Henri Dunant, 95460 EZANVILLE",95,1986-12-10 00:00:00,NaT,...,1493196.98,DT - VAL-D'OISE,-124741.48,-0.083540,1930418.47,17.038343,NaN,NaN,NaN,NaN
2,102,DELEGATION TERRITORIALE - DT,DT DE LA GUADELOUPE,97139.0,97101,LES ABYMES,"Rue des écoles, 97139 LES ABYMES",971,1986-12-10 00:00:00,NaT,...,190848.28,DT - GUADELOUPE,-81957.84,-0.429440,-138952.44,2.164438,0.0,1.0,0.0,0.0
3,103,DELEGATION TERRITORIALE - DT,DT DE LA MARTINIQUE,97200.0,97209,FORT DE FRANCE,"195 Avenue Leona Gabriel, 97200 FORT DE FRANCE",972,1986-12-10 00:00:00,NaT,...,190189.97,DT - MARTINIQUE,-30058.08,-0.158042,165405.65,5.575564,NaN,NaN,NaN,NaN
4,104,DELEGATION TERRITORIALE - DT,DT DE NOUVELLE CALEDONIE,98800.0,98818,NOUMEA,"26 Rue DU DOCTEUR GEORGES COLLARD, 98800 NOUMEA",988,1956-12-10 00:00:00,NaT,...,1136238.00,DT - NOUVELLE-CALEDONIE,-764.10,-0.000672,272333.05,3.835414,0.0,3.0,7.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,94,DELEGATION TERRITORIALE - DT,DT DE L'YONNE,89300.0,89206,JOIGNY,"Rue JEAN FRANÇOIS DE LA PÉROUSE, 89300 JOIGNY",89,1986-12-10 00:00:00,NaT,...,489487.34,DT - YONNE,53515.15,0.109329,675805.08,19.342680,NaN,NaN,NaN,NaN
104,95,DELEGATION TERRITORIALE - DT,DT DU TERRITOIRE DE BELFORT,90000.0,90010,BELFORT,"15 Avenue du Général Sarrail, 90000 BELFORT",90,1986-12-10 00:00:00,NaT,...,371153.13,DT - TERRITOIRE-DE-BELFORT,5174.82,0.013943,439146.13,13.890856,44.0,72.0,4.0,0.0
105,96,DELEGATION TERRITORIALE - DT,DT DE L'ESSONNE,91080.0,91228,EVRY COURCOURONNES,"12 Rue Jean Mermoz, 91080 EVRY COURCOURONNES",91,1986-12-10 00:00:00,NaT,...,1636929.31,DT - ESSONNE,-10866.67,-0.006638,1547551.36,11.772285,NaN,NaN,NaN,NaN
106,97,DELEGATION TERRITORIALE - DT,DT DES HAUTS DE SEINE,92100.0,92012,BOULOGNE BILLANCOURT,"14 Rue de l'Est, 92100 BOULOGNE BILLANCOURT",92,1986-12-10 00:00:00,NaT,...,3568821.35,DT - HAUTS-DE-SEINE,460756.15,0.129106,7158583.91,26.185043,NaN,NaN,NaN,NaN
107,99,DELEGATION TERRITORIALE - DT,DT DU VAL DE MARNE,94450.0,94044,LIMEIL BREVANNES,"2 Rue ALBERT GARRY, 94450 LIMEIL BREVANNES",94,1986-12-10 00:00:00,NaT,...,1235949.97,DT - VAL-DE-MARNE,-152720.48,-0.123565,2653772.29,21.799823,NaN,NaN,NaN,NaN

# Enregistrement des données

In [121]:
# Entregistrement du DataFrame
save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", gspread_client, all_data, sheet_name = 'UL')
save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", gspread_client, all_data_DT, sheet_name = 'DT')

# save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", client, df_rattachement_court)

➕ La feuille 'UL' n'existe pas. Création en cours...
✅ Feuille 'UL' créée.
🗑️ Les anciennes données ont été supprimées de la feuille 'UL'
💾 Données sauvegardées dans 'all_data' → feuille 'UL'
    Nombre de lignes : 1185
    Nombre de colonnes : 102
📄 Feuille existante 'DT' sélectionnée.
🗑️ Les anciennes données ont été supprimées de la feuille 'DT'
💾 Données sauvegardées dans 'all_data' → feuille 'DT'
    Nombre de lignes : 108
    Nombre de colonnes : 78