In [6]:
!git config --global user.email "clement.souk-aloun@croix-rouge.fr"
!git clone https://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@github.com/clementsouk-aloun-dot/Code-PAT.git

Cloning into 'Code-PAT'...
remote: Enumerating objects: 525, done.
remote: Counting objects: 100% (185/185), done.
remote: Compressing objects: 100% (139/139), done.
remote: Total 525 (delta 110), reused 72 (delta 46), pack-reused 340 (from 1)
Receiving objects: 100% (525/525), 2.14 MiB | 13.85 MiB/s, done.
Resolving deltas: 100% (286/286), done.

In [7]:
%cd Code-PAT
!git checkout donnees_maraude

/content/Code-PAT/Code-PAT
Branch 'donnees_maraude' set up to track remote branch 'donnees_maraude' from 'origin'.
Switched to a new branch 'donnees_maraude'

In [4]:
!git add .

In [8]:
!git commit -m "donnees_maraude"

On branch donnees_maraude
Your branch is up to date with 'origin/donnees_maraude'.

nothing to commit, working tree clean

In [19]:
!git fetch origin

In [20]:
!git config pull.rebase true

In [21]:
!git pull

Already up to date.

In [22]:
!git push

Everything up-to-date

#INSTALL PACKAGE

In [9]:
!pip install PyPDF2
!pip install reportlab
!pip install PyMuPDF tools
!pip install xlsxwriter

Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.12/dist-packages (3.0.1)
Requirement already satisfied: reportlab in /usr/local/lib/python3.12/dist-packages (4.4.9)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.4)
Requirement already satisfied: PyMuPDF in /usr/local/lib/python3.12/dist-packages (1.26.7)
Requirement already satisfied: tools in /usr/local/lib/python3.12/dist-packages (1.0.23)
Requirement already satisfied: xlsxwriter in /usr/local/lib/python3.12/dist-packages (3.2.9)

In [10]:
import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import sys
import io
import re
import shutil
import zipfile
from google.colab import drive, files

from google.colab import auth
from google.auth import default
import unicodedata
import re
import torch
from sentence_transformers import SentenceTransformer, util

Imports des fichiers .py

In [11]:
sys.path.append(os.path.abspath("/content/Code-PAT/scripts_data"))
sys.path.append(os.path.abspath("/content/Code-PAT"))

from financier import *
from mobilite import *
from utils import *

#AUTHENTIFICATION

In [12]:
from google.colab import auth
!gcloud auth application-default login

from google.cloud import bigquery
import pandas as pd

PROJECT_ID = "crf-pat"
client = bigquery.Client(project=PROJECT_ID)

# Import
query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.crf_pat_2025_maraude`
"""
df = client.query(query).to_dataframe()
df.head()

query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.Ref_structure`
"""

df_ref_structure = client.query(query).to_dataframe()
df_ref_structure.head()

query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.rattachement_court`
"""

df_rattachement_court = client.query(query).to_dataframe()

Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=dSHmt4YtEeTHnKMPPNJfWegM9gUCaL&prompt=consent&token_usage=remote&access_type=offline&code_challenge=Gf6j-pldOLjo2l6hR5imSlfvaRg4_6IPOdNQXnJoNSk&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0ASc3gC3FHzAib0H9LjXT3-jvXCchKCHX-d7cNmY8_GNNF5kmxj3bQDhsaSjBDhckciW1Tw

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.


To take a quick anonymous survey, run:
  $ gcloud survey

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

# Variables globales

In [75]:
df.columns

Index(['maraude_id_fk', 'point_rencontre_id_fk', 'rencontre_id_fk',
       'distribution_id_fk', 'maraude_structure_id_fk', 'maraude_date_debut',
       'maraude_date_fin', 'maraude_point_rencontre_heure_depart',
       'maraude_point_rencontre_heure_fin', 'maraude_statut',
       'maraude_rencontre_beneficiaire_id_fk',
       'maraude_rencontre_contact_realise', 'maraude_rencontre_typologie',
       'maraude_rencontre_nb_hommes', 'maraude_rencontre_nb_femmes',
       'maraude_rencontre_nb_transgenres', 'maraude_rencontre_nb_mineurs',
       'maraude_rencontre_nb_inconnus', 'maraude_distribution_nb_collations',
       'maraude_distribution_nb_croquettes',
       'maraude_distribution_nb_vetements',
       'maraude_distribution_nb_couvertures',
       'maraude_distribution_nb_bons_vestimentaires',
       'maraude_distribution_nb_kits_hygiene',
       'maraude_distribution_nb_produits_hygiene'],
      dtype='object')

In [76]:
df

,maraude_id_fk,point_rencontre_id_fk,rencontre_id_fk,distribution_id_fk,maraude_structure_id_fk,maraude_date_debut,maraude_date_fin,maraude_point_rencontre_heure_depart,maraude_point_rencontre_heure_fin,maraude_statut,...,maraude_rencontre_nb_transgenres,maraude_rencontre_nb_mineurs,maraude_rencontre_nb_inconnus,maraude_distribution_nb_collations,maraude_distribution_nb_croquettes,maraude_distribution_nb_vetements,maraude_distribution_nb_couvertures,maraude_distribution_nb_bons_vestimentaires,maraude_distribution_nb_kits_hygiene,maraude_distribution_nb_produits_hygiene
0,2705541,223239,399947,399947,1060,2025-01-01,2025-01-01,14:00:00,13:30:00,FINISHED,...,<NA>,<NA>,<NA>,0,0,0,0,0,0,0
1,2705541,223239,399948,399948,1060,2025-01-01,2025-01-01,14:00:00,13:30:00,FINISHED,...,<NA>,<NA>,<NA>,1,0,0,1,0,0,0
2,2705541,223239,399949,399949,1060,2025-01-01,2025-01-01,14:00:00,13:30:00,FINISHED,...,<NA>,<NA>,<NA>,0,0,0,0,0,0,0
3,2705541,223240,399950,399950,1060,2025-01-01,2025-01-01,15:30:00,14:00:00,FINISHED,...,<NA>,<NA>,<NA>,0,0,0,0,0,0,0
4,2705541,223240,399951,399951,1060,2025-01-01,2025-01-01,15:30:00,14:00:00,FINISHED,...,<NA>,<NA>,<NA>,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116435,3022193,279474,521860,521860,83,2025-08-26,2025-08-26,23:36:00,23:15:00,FINISHED,...,<NA>,<NA>,<NA>,0,0,0,0,0,0,0
116436,2132747,279475,521861,521861,893,2025-10-07,2025-10-07,19:11:00,19:11:00,FINISHED,...,<NA>,<NA>,<NA>,2,0,0,0,2,0,0
116437,2132747,279475,521864,521864,893,2025-10-07,2025-10-07,19:11:00,19:11:00,FINISHED,...,<NA>,<NA>,<NA>,2,0,0,0,0,0,2
116438,2132747,279477,521868,521868,893,2025-10-07,2025-10-07,13:35:00,13:35:00,FINISHED,...,<NA>,<NA>,<NA>,2,0,0,0,0,0,2
116439,2132747,279481,521870,521870,893,2025-10-07,2025-10-07,13:49:00,13:49:00,FINISHED,...,0,0,0,0,0,0,0,0,0,0

Import des bonnes colonnes

In [77]:
# Clean

def prep_nb_personnes_rencontrees_sigma(df, filtre_annee_fn=None):
    cols_keep = ["maraude_id_fk","maraude_structure_id_fk","maraude_statut","maraude_date_debut","maraude_date_fin", 'maraude_rencontre_beneficiaire_id_fk',
       'maraude_rencontre_contact_realise', 'maraude_rencontre_typologie',
       'maraude_rencontre_nb_hommes', 'maraude_rencontre_nb_femmes',
       'maraude_rencontre_nb_transgenres', 'maraude_rencontre_nb_mineurs',
       'maraude_rencontre_nb_inconnus']

    missing = [c for c in cols_keep if c not in df.columns]
    if missing:
        print("Colonnes manquantes:", missing)

    d = df.loc[:, [c for c in cols_keep if c in df.columns]].copy()

    d = d.drop_duplicates()

    d = d.loc[d["maraude_statut"] == "FINISHED"].copy()

    d = d.loc[d["maraude_rencontre_contact_realise"] == "Oui"].copy()

    if filtre_annee_fn is not None:
        filtre_annee_fn(d, "maraude_date_debut")  # si ta fonction modifie d "in place"
        # ou: d = filtre_annee_fn(d, "maraude_date_debut") si elle retourne un df

    return d

In [78]:
df_nb_personnes_rencontrees_sigma = prep_nb_personnes_rencontrees_sigma(df)

In [79]:
df_nb_personnes_rencontrees_sigma

,maraude_id_fk,maraude_structure_id_fk,maraude_statut,maraude_date_debut,maraude_date_fin,maraude_rencontre_beneficiaire_id_fk,maraude_rencontre_contact_realise,maraude_rencontre_typologie,maraude_rencontre_nb_hommes,maraude_rencontre_nb_femmes,maraude_rencontre_nb_transgenres,maraude_rencontre_nb_mineurs,maraude_rencontre_nb_inconnus
0,2705541,1060,FINISHED,2025-01-01,2025-01-01,396621,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
1,2705541,1060,FINISHED,2025-01-01,2025-01-01,396622,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
2,2705541,1060,FINISHED,2025-01-01,2025-01-01,396623,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
3,2705541,1060,FINISHED,2025-01-01,2025-01-01,396624,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
4,2705541,1060,FINISHED,2025-01-01,2025-01-01,396625,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...
116435,3022193,83,FINISHED,2025-08-26,2025-08-26,518108,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
116436,2132747,893,FINISHED,2025-10-07,2025-10-07,518109,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
116437,2132747,893,FINISHED,2025-10-07,2025-10-07,518112,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
116438,2132747,893,FINISHED,2025-10-07,2025-10-07,518116,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
116439,2132747,893,FINISHED,2025-10-07,2025-10-07,<NA>,Oui,groupe,2,0,0,0,0

In [80]:
# calcul

def add_nb_personnes(df,
                     out_col="nb personnes",
                     cols=None,
                     col_typologie="maraude_rencontre_typologie"):
    if cols is None:
        cols = [
            "maraude_rencontre_nb_hommes",
            "maraude_rencontre_nb_femmes",
            "maraude_rencontre_nb_transgenres",
            "maraude_rencontre_nb_mineurs",
            "maraude_rencontre_nb_inconnus",
        ]

    d = df.copy()
    missing = [c for c in cols + [col_typologie] if c not in d.columns]
    if missing:
        raise ValueError(f"Colonnes manquantes pour calculer '{out_col}': {missing}")

    d[cols] = d[cols].apply(pd.to_numeric, errors="coerce").fillna(0)
    d[out_col] = d[cols].sum(axis=1)

    # +1 si typologie == "individu"
    d[out_col] += (d[col_typologie].astype(str).str.strip().str.lower() == "individu").astype(int)

    return d

In [81]:
df_nb_personnes_rencontrees_sigma = add_nb_personnes(df_nb_personnes_rencontrees_sigma)

In [84]:
df_nb_personnes_rencontrees_sigma

,maraude_id_fk,maraude_structure_id_fk,maraude_statut,maraude_date_debut,maraude_date_fin,maraude_rencontre_beneficiaire_id_fk,maraude_rencontre_contact_realise,maraude_rencontre_typologie,maraude_rencontre_nb_hommes,maraude_rencontre_nb_femmes,maraude_rencontre_nb_transgenres,maraude_rencontre_nb_mineurs,maraude_rencontre_nb_inconnus,nb personnes
0,2705541,1060,FINISHED,2025-01-01,2025-01-01,396621,Oui,individu,0,0,0,0,0,1
1,2705541,1060,FINISHED,2025-01-01,2025-01-01,396622,Oui,individu,0,0,0,0,0,1
2,2705541,1060,FINISHED,2025-01-01,2025-01-01,396623,Oui,individu,0,0,0,0,0,1
3,2705541,1060,FINISHED,2025-01-01,2025-01-01,396624,Oui,individu,0,0,0,0,0,1
4,2705541,1060,FINISHED,2025-01-01,2025-01-01,396625,Oui,individu,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116435,3022193,83,FINISHED,2025-08-26,2025-08-26,518108,Oui,individu,0,0,0,0,0,1
116436,2132747,893,FINISHED,2025-10-07,2025-10-07,518109,Oui,individu,0,0,0,0,0,1
116437,2132747,893,FINISHED,2025-10-07,2025-10-07,518112,Oui,individu,0,0,0,0,0,1
116438,2132747,893,FINISHED,2025-10-07,2025-10-07,518116,Oui,individu,0,0,0,0,0,1
116439,2132747,893,FINISHED,2025-10-07,2025-10-07,<NA>,Oui,groupe,2,0,0,0,0,2

In [83]:
df_nb_personnes_rencontrees_SIGMA = (
    df_nb_personnes_rencontrees_sigma
    .groupby("maraude_structure_id_fk", as_index=False)["nb personnes"]
    .sum()
)

In [85]:
df_nb_personnes_rencontrees_SIGMA.columns = ["n_structure", "Maraude Nb_contacts"]

In [92]:
df_nb_personnes_rencontrees_SIGMA

     n_structure  Maraude Nb_contacts              DT_de_rattachement
0              5                 6610                 5 - DT DE L'AIN
1             12                 1333            12 - DT DES ARDENNES
2             39                    1            39 - DT DE L'HERAULT
3             41                  992              41 - DT DE L'INDRE
4             44                  234                 44 - DT DU JURA
..           ...                  ...                             ...
110         4633                  176  4631 - DT DE SEINE SAINT DENIS
111         4635                    9  4631 - DT DE SEINE SAINT DENIS
112         4640                   75  4631 - DT DE SEINE SAINT DENIS
113         4674                   64                4674 - DT DU LOT
114         4676                 1760                4674 - DT DU LOT

[115 rows x 3 columns]

❌ 3 valeur(s) manquante(s) ou vide(s) détectée(s) dans 'DT_de_rattachement'.

In [87]:
# Vérifications

#1. vérification du personnes_rencontrees dans Sigma
if df_nb_personnes_rencontrees_SIGMA["Maraude Nb_contacts"].sum() != df_nb_personnes_rencontrees_sigma["nb personnes"].sum():
    raise ValueError(
        f"Incohérence: Maraude Nb_contacts ={df_nb_personnes_rencontrees_SIGMA["Maraude Nb_contacts"].sum()} vs nb_lignes df_Nb_maraudes_sigma={df_nb_personnes_rencontrees_sigma["nb personnes"].sum()}"
    )
else:
    print("OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_Nb_maraudes_SIGMA")

OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_Nb_maraudes_SIGMA

In [89]:
df_nb_personnes_rencontrees_SIGMA  = pd.merge(df_nb_personnes_rencontrees_SIGMA , df_rattachement_court, on='n_structure', how="left") #a conserver dans le code principal

In [91]:
#Calcul DT

def nb_personnes_rencontrees_SIGMA_DT(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="Maraude Nb_contacts",
                              out_col="Maraude Nb_contacts"):
    d = df.query(filtre) if filtre else df
    return (d.groupby(col_structure)[col_user]
              .sum()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

In [93]:
nb_personnes_rencontrees_SIGMA_DT = nb_personnes_rencontrees_SIGMA_DT(df_nb_personnes_rencontrees_SIGMA)

In [94]:
nb_personnes_rencontrees_SIGMA_DT

                  DT_de_rattachement  Maraude Nb_contacts
0        10 - DT DES ALPES MARITIMES                  151
1             100 - DT DU VAL D'OISE                  385
2               11 - DT DE L'ARDECHE                  109
3               12 - DT DES ARDENNES                 1333
4                13 - DT DE L'ARIEGE                 3687
5       17 - DT DES BOUCHES DU RHONE                 4678
6            26 - DT DE LA COTE D'OR                 5605
7                31 - DT DE LA DROME                   41
8             33 - DT D'EURE ET LOIR                   86
9               34 - DT DU FINISTERE                16784
10          36 - DT DE HAUTE GARONNE                 5225
11                   37 - DT DU GERS                 1359
12             38 - DT DE LA GIRONDE                   80
13              39 - DT DE L'HERAULT                   88
14           3959 - DT DE LA REUNION                 7960
15                 3970 - DT DU CHER                   30
16       3971 - DT DES COTES D'ARMOR                 7859
17                41 - DT DE L'INDRE                 1588
18               4284 - DT DE L'ORNE                  234
19                43 - DT DE L'ISERE                  877
20         4381 - DT DES DEUX SEVRES                   69
21                   44 - DT DU JURA                  234
22                45 - DT DES LANDES                 1576
23           46 - DT DU LOIR ET CHER                  161
24    4631 - DT DE SEINE SAINT DENIS                  351
25                  4674 - DT DU LOT                 1824
26               47 - DT DE LA LOIRE                 2363
27    49 - DT DE LA LOIRE ATLANTIQUE                 1740
28                   5 - DT DE L'AIN                 8051
29         52 - DT DU LOT ET GARONNE                   14
30              55 - DT DE LA MANCHE                  687
31               56 - DT DE LA MARNE                 2543
32               61 - DT DU MORBIHAN                 3684
33                   64 - DT DU NORD                 4169
34          67 - DT DU PAS DE CALAIS                  838
35  69 - DT DES PYRENEES ATLANTIQUES                 2483
36              73 - DT DU HAUT RHIN                 1010
37                  74 - DT DU RHONE                 3341
38         76 - DT DE SAONE ET LOIRE                 3837
39              77 - DT DE LA SARTHE                    9
40        79 - DT DE LA HAUTE SAVOIE                  426
41                  80 - DT DE PARIS                 6867
42      81 - DT DE LA SEINE MARITIME                  609
43      82 - DT DE LA SEINE ET MARNE                 4810
44              83 - DT DES YVELINES                 6725
45           9 - DT DES HAUTES ALPES                  380
46                 90 - DT DE VENDEE                   28
47              91 - DT DE LA VIENNE                 6517
48                94 - DT DE L'YONNE                  308
49  95 - DT DU TERRITOIRE DE BELFORT                  642
50              96 - DT DE L'ESSONNE                 1125
51           99 - DT DU VAL DE MARNE                 1529

In [95]:
lignes_vides(nb_personnes_rencontrees_SIGMA, "DT_de_rattachement")

✅ Aucun NaN ou valeur vide détecté dans 'DT_de_rattachement'.

(True,
 Empty DataFrame
 Columns: [DT_de_rattachement, Maraude Nb_contacts]
 Index: [])

In [96]:
lignes_vides(nb_personnes_rencontrees_SIGMA_DT, "DT_de_rattachement")

✅ Aucun NaN ou valeur vide détecté dans 'DT_de_rattachement'.

(True,
 Empty DataFrame
 Columns: [DT_de_rattachement, Maraude Nb_contacts]
 Index: [])

In [97]:
lignes_vides(nb_personnes_rencontrees_SIGMA_DT, "DT_de_rattachement")

✅ Aucun NaN ou valeur vide détecté dans 'DT_de_rattachement'.

(True,
 Empty DataFrame
 Columns: [DT_de_rattachement, Maraude Nb_contacts]
 Index: [])

In [103]:
# Vérifications

Personnes_rencontrees = lignes_vides(df_nb_personnes_rencontrees_SIGMA, "DT_de_rattachement")[1]['Maraude Nb_contacts'].sum()

#1. vérification du nombre de personnes rencontrées par maraude dans Sigma
if nb_personnes_rencontrees_SIGMA_DT["Maraude Nb_contacts"].sum() + Personnes_rencontrees!= df_nb_personnes_rencontrees_SIGMA["Maraude Nb_contacts"].sum():
    raise ValueError(
        f"Incohérence: somme des maraudes par DT={nb_personnes_rencontrees_SIGMA_DT["Maraude Nb_contacts"].sum()} vs total des maraudes finies={df_nb_personnes_rencontrees_SIGMA["Maraude Nb_contacts"].sum()}"
    )
else:
    print("OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_PREP_Nb_maraudes_SIGMA")

❌ 3 valeur(s) manquante(s) ou vide(s) détectée(s) dans 'DT_de_rattachement'.
OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_PREP_Nb_maraudes_SIGMA

In [33]:
# Clean
cols_keep = ['maraude_id_fk',"maraude_structure_id_fk","maraude_statut", "maraude_date_debut", "maraude_date_fin"]

missing = [c for c in cols_keep if c not in df.columns]
if missing:
    print("Colonnes manquantes:", missing)

df_PREP_Nb_maraudes_SIGMA  = df.loc[:, [c for c in cols_keep if c in df.columns]].copy()

df_PREP_Nb_maraudes_SIGMA = df_PREP_Nb_maraudes_SIGMA.drop_duplicates()

df_PREP_Nb_maraudes_SIGMA =df_PREP_Nb_maraudes_SIGMA[df_PREP_Nb_maraudes_SIGMA["maraude_statut"] == "FINISHED"].copy()

filtre_2025(df_PREP_Nb_maraudes_SIGMA,"maraude_date_debut")

,maraude_id_fk,maraude_structure_id_fk,maraude_statut,maraude_date_debut,maraude_date_fin
0,2705541,1060,FINISHED,2025-01-01,2025-01-01
8,2632965,609,FINISHED,2025-01-01,2025-01-01
9,2673723,619,FINISHED,2025-01-01,2025-01-01
15,2663007,829,FINISHED,2025-01-01,2025-01-01
19,2615558,623,FINISHED,2025-01-01,2025-01-01
...,...,...,...,...,...
116130,2887306,4065,FINISHED,2025-04-30,2025-04-30
116279,2887251,4065,FINISHED,2025-03-17,2025-03-17
116309,3287327,4065,FINISHED,2025-01-06,2025-01-06
116391,3292636,83,FINISHED,2025-12-28,2025-12-28
116421,3287244,930,FINISHED,2025-12-27,2025-12-27

In [48]:
#calcul

df_Nb_maraudes_SIGMA = df_PREP_Nb_maraudes_SIGMA.groupby("maraude_structure_id_fk", as_index=False)["maraude_id_fk"].count()
df_Nb_maraudes_SIGMA.columns = ["n_structure", "Maraude Nb_maraudes_SIGMA"]

In [49]:
df_Nb_maraudes_SIGMA

     n_structure  Maraude Nb_maraudes_SIGMA
0              5                        291
1             12                        125
2             39                          1
3             41                         37
4             44                         50
..           ...                        ...
111         4633                         14
112         4635                          2
113         4640                          5
114         4674                          7
115         4676                        107

[116 rows x 2 columns]

In [50]:
# Vérifications

#1. vérification du nombre de maraude dans Sigma
if df_Nb_maraudes_SIGMA["Maraude Nb_maraudes_SIGMA"].sum() != len(df_PREP_Nb_maraudes_SIGMA):
    raise ValueError(
        f"Incohérence: somme df_counts={df_counts['Maraude Nb_maraudes_SIGMA'].sum()} vs nb_lignes df_Nb_maraudes_SIGMA={len(df_Nb_maraudes_SIGMA)}"
    )
else:
    print("OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_Nb_maraudes_SIGMA")

OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_Nb_maraudes_SIGMA

In [51]:
# Vérifications

#1. vérification du nombre de maraude dans Sigma
if df_Nb_maraudes_SIGMA["Maraude Nb_maraudes_SIGMA"].sum() != len(df_PREP_Nb_maraudes_SIGMA):
    raise ValueError(
        f"Incohérence: somme df_counts={df_counts['Maraude Nb_maraudes_SIGMA'].sum()} vs nb_lignes df_Nb_maraudes_SIGMA={len(df_Nb_maraudes_SIGMA)}"
    )
else:
    print("OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_Nb_maraudes_SIGMA")

OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_Nb_maraudes_SIGMA

In [52]:
df_Nb_maraudes_SIGMA

     n_structure  Maraude Nb_maraudes_SIGMA
0              5                        291
1             12                        125
2             39                          1
3             41                         37
4             44                         50
..           ...                        ...
111         4633                         14
112         4635                          2
113         4640                          5
114         4674                          7
115         4676                        107

[116 rows x 2 columns]

#Merge

In [80]:
Nb_maraudes_SIGMA = pd.merge(df_Nb_maraudes_SIGMA, df_rattachement_court, on='n_structure', how="left") #a conserver dans le code principal

In [58]:
Nb_maraudes_SIGMA

     n_structure  Maraude Nb_maraudes_SIGMA              DT_de_rattachement
0              5                        291                 5 - DT DE L'AIN
1             12                        125            12 - DT DES ARDENNES
2             39                          1            39 - DT DE L'HERAULT
3             41                         37              41 - DT DE L'INDRE
4             44                         50                 44 - DT DU JURA
..           ...                        ...                             ...
108         4633                         14  4631 - DT DE SEINE SAINT DENIS
109         4635                          2  4631 - DT DE SEINE SAINT DENIS
110         4640                          5  4631 - DT DE SEINE SAINT DENIS
111         4674                          7                4674 - DT DU LOT
112         4676                        107                4674 - DT DU LOT

[113 rows x 3 columns]

In [63]:
#Calcul indicateur par DT

def Nb_maraudes_SIGMA_DT(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="Maraude Nb_maraudes_SIGMA",
                              out_col="Maraude Nb_maraudes_SIGMA"):
    d = df.query(filtre) if filtre else df
    return (d.groupby(col_structure)[col_user]
              .sum()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

In [69]:
Nb_maraudes_SIGMA_DT = Nb_maraudes_SIGMA_DT(Nb_maraudes_SIGMA)

In [72]:
Nb_maraudes_SIGMA_DT

                  DT_de_rattachement  Maraude Nb_maraudes_SIGMA
0        10 - DT DES ALPES MARITIMES                          5
1             100 - DT DU VAL D'OISE                         24
2               11 - DT DE L'ARDECHE                         37
3               12 - DT DES ARDENNES                        125
4                13 - DT DE L'ARIEGE                        233
5       17 - DT DES BOUCHES DU RHONE                        291
6            26 - DT DE LA COTE D'OR                        223
7                31 - DT DE LA DROME                          3
8             33 - DT D'EURE ET LOIR                         10
9               34 - DT DU FINISTERE                        415
10          36 - DT DE HAUTE GARONNE                        200
11                   37 - DT DU GERS                         38
12             38 - DT DE LA GIRONDE                          2
13              39 - DT DE L'HERAULT                         17
14           3959 - DT DE LA REUNION                        466
15              3966 - DT DES VOSGES                          1
16                 3970 - DT DU CHER                          3
17       3971 - DT DES COTES D'ARMOR                        314
18                41 - DT DE L'INDRE                         61
19               4284 - DT DE L'ORNE                         90
20                43 - DT DE L'ISERE                        103
21         4381 - DT DES DEUX SEVRES                          5
22                   44 - DT DU JURA                         50
23                45 - DT DES LANDES                         90
24           46 - DT DU LOIR ET CHER                         15
25    4631 - DT DE SEINE SAINT DENIS                         38
26                  4674 - DT DU LOT                        114
27               47 - DT DE LA LOIRE                         95
28    49 - DT DE LA LOIRE ATLANTIQUE                         84
29                   5 - DT DE L'AIN                        457
30         52 - DT DU LOT ET GARONNE                          6
31              55 - DT DE LA MANCHE                        114
32               56 - DT DE LA MARNE                        254
33               61 - DT DU MORBIHAN                        135
34                   64 - DT DU NORD                        174
35          67 - DT DU PAS DE CALAIS                         27
36  69 - DT DES PYRENEES ATLANTIQUES                        106
37              73 - DT DU HAUT RHIN                        120
38                  74 - DT DU RHONE                        255
39         76 - DT DE SAONE ET LOIRE                        188
40              77 - DT DE LA SARTHE                          1
41        79 - DT DE LA HAUTE SAVOIE                         36
42                  80 - DT DE PARIS                        723
43      81 - DT DE LA SEINE MARITIME                         44
44      82 - DT DE LA SEINE ET MARNE                        336
45              83 - DT DES YVELINES                        726
46           9 - DT DES HAUTES ALPES                         38
47                 90 - DT DE VENDEE                          3
48              91 - DT DE LA VIENNE                        345
49                94 - DT DE L'YONNE                         49
50  95 - DT DU TERRITOIRE DE BELFORT                         39
51              96 - DT DE L'ESSONNE                        216
52           99 - DT DU VAL DE MARNE                        335

In [54]:
# 1. Vérification des NaN ou valeurs vides
def lignes_vides(df, col_code_structure, label=None, raise_error=False):

    #Vérifie si une colonne contient des NaN ou des valeurs vides ("").
    #Affiche un message OK/KO. Optionnellement lève une erreur.

    s = df[col_code_structure]
    lignes_vides = df[s.isna() | (s.astype(str).str.strip() == "")]

    col_name = label or col_code_structure
    if not lignes_vides.empty:
        msg = f"❌ {len(lignes_vides)} valeur(s) manquante(s) ou vide(s) détectée(s) dans '{col_name}'."
        print(msg)
        if raise_error:
            raise ValueError(msg)
        return False, lignes_vides
    else:
        print(f"✅ Aucun NaN ou valeur vide détecté dans '{col_name}'.")
        return True, lignes_vides

In [100]:
Sigma_vide = lignes_vides(Nb_maraudes_SIGMA, "DT_de_rattachement")

❌ 3 valeur(s) manquante(s) ou vide(s) détectée(s) dans 'DT_de_rattachement'.

In [103]:
verifier_colonne_structure(Nb_maraudes_SIGMA, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 3 code(s) non trouvés dans le référentiel : [np.int64(3910), np.int64(4228), np.int64(4549)]

In [102]:
# Vérifications

Maraude_etab = sum(Sigma_vide[1]['Maraude Nb_maraudes_SIGMA'])

#1. vérification du nombre de maraude dans Sigma
if Nb_maraudes_SIGMA_DT["Maraude Nb_maraudes_SIGMA"].sum() + Maraude_etab != len(df_PREP_Nb_maraudes_SIGMA):
    raise ValueError(
        f"Incohérence: somme des maraudes par DT={Nb_maraudes_SIGMA_DT['Maraude Nb_maraudes_SIGMA'].sum()} vs total des maraudes finies={len(df_PREP_Nb_maraudes_SIGMA)}"
    )
else:
    print("OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_PREP_Nb_maraudes_SIGMA")

OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_PREP_Nb_maraudes_SIGMA

In [54]:
Nb_maraudes_SIGMA

     n_structure  Maraude Nb_maraudes_SIGMA              DT_de_rattachement
0              5                        291                 5 - DT DE L'AIN
1             12                        125            12 - DT DES ARDENNES
2             39                          1            39 - DT DE L'HERAULT
3             41                         37              41 - DT DE L'INDRE
4             44                         50                 44 - DT DU JURA
..           ...                        ...                             ...
108         4633                         14  4631 - DT DE SEINE SAINT DENIS
109         4635                          2  4631 - DT DE SEINE SAINT DENIS
110         4640                          5  4631 - DT DE SEINE SAINT DENIS
111         4674                          7                4674 - DT DU LOT
112         4676                        107                4674 - DT DU LOT

[113 rows x 3 columns]

In [ ]:
df_Nb_maraudes_SIGMA

,maraude_id_fk,maraude_structure_id_fk,maraude_statut,maraude_date_debut,maraude_date_fin
0,2705541,1060,FINISHED,2025-01-01,2025-01-01
8,2632965,609,FINISHED,2025-01-01,2025-01-01
9,2673723,619,FINISHED,2025-01-01,2025-01-01
15,2663007,829,FINISHED,2025-01-01,2025-01-01
19,2615558,623,FINISHED,2025-01-01,2025-01-01
...,...,...,...,...,...
116130,2887306,4065,FINISHED,2025-04-30,2025-04-30
116279,2887251,4065,FINISHED,2025-03-17,2025-03-17
116309,3287327,4065,FINISHED,2025-01-06,2025-01-06
116391,3292636,83,FINISHED,2025-12-28,2025-12-28
116421,3287244,930,FINISHED,2025-12-27,2025-12-27

In [ ]:
df_Nb_maraudes_SIGMA['maraude_statut'].unique()

array(['FINISHED'], dtype=object)

In [ ]:
df_Nb_maraudes_SIGMA.dtypes

maraude_id_fk               Int64
maraude_structure_id_fk     Int64
maraude_statut             object
maraude_date_debut         dbdate
maraude_date_fin           dbdate
dtype: object

revue de utis.py

In [ ]:
def import_clean_donnees_financieres(financier,df_ref_structure, mapping_df):

  # Clean
  dt_prod = get_as_dataframe(financier.worksheet('DT_Prod'), skiprows=3,evaluate_formulas=True)
  dt_resnet = get_as_dataframe(financier.worksheet('DT_Res Net'), skiprows=3,evaluate_formulas=True)
  dt_resnet_corr_prod = get_as_dataframe(financier.worksheet('DT_Res corrélé Prod'), skiprows=3, evaluate_formulas=True)
  dt_treso_brute = get_as_dataframe(financier.worksheet('DT_Trés brute'), skiprows=3,evaluate_formulas=True)
  dt_ul_ant_prod = get_as_dataframe(financier.worksheet('DT-UL-Ant_Prod'), skiprows=3, evaluate_formulas=True)
  dt_ul_ant_res_net = get_as_dataframe(financier.worksheet('DT-UL-Ant_Res Net'), skiprows=3, evaluate_formulas=True)
  dt_ul_res_net_corr_prod = get_as_dataframe(financier.worksheet('DT-UL-Res corrélé Prod'), skiprows=3, evaluate_formulas=True)
  dt_ul_treso_brute = get_as_dataframe(financier.worksheet('DT-UL_Tréso brute'), skiprows=3, evaluate_formulas=True)

  # Renommer colonnes
  dt_prod = renommer_par_nom_table(dt_prod, "financier_DT", mapping_df)
  dt_resnet = renommer_par_nom_table(dt_resnet, "financier_DT", mapping_df)
  dt_resnet_corr_prod = renommer_par_nom_table(dt_resnet_corr_prod, "financier_DT", mapping_df)
  dt_treso_brute = renommer_par_nom_table(dt_treso_brute, "financier_DT", mapping_df)
  dt_ul_ant_prod = renommer_par_nom_table(dt_ul_ant_prod, "financier_DT_UL", mapping_df)
  dt_ul_ant_res_net = renommer_par_nom_table(dt_ul_ant_res_net, "financier_DT_UL", mapping_df)
  dt_ul_res_net_corr_prod = renommer_par_nom_table(dt_ul_res_net_corr_prod, "financier_DT_UL", mapping_df)
  dt_ul_treso_brute = renommer_par_nom_table(dt_ul_treso_brute, "financier_DT_UL", mapping_df)

  dt_prod = dt_prod[['n_dept','Réalisé 2024 Total Année','libelle_structure']].rename(columns = {'Réalisé 2024 Total Année' : 'Financier Prod_2024'}).iloc[:dt_prod.shape[0]-2]
  dt_prod['libelle_structure'] = 'DT - ' + dt_prod['libelle_structure']
  dt_resnet = dt_resnet[['n_dept','Réalisé 2024 Total Année']].rename(columns = {'Réalisé 2024 Total Année' : 'Financier ResNet_2024'}).iloc[:dt_resnet.shape[0]-2]
  dt_resnet_corr_prod = dt_resnet_corr_prod[['n_dept','Réalisé 2024 Total Année']].rename(columns = {'Réalisé 2024 Total Année' : 'Financier ResCorrProd_2024'}).iloc[:dt_resnet_corr_prod.shape[0]-2]
  dt_treso_brute = dt_treso_brute[['n_dept','Tréso nette au 31/12/2024','Financier Mois_AvanceTreso_2024']].rename(columns = {'Tréso nette au 31/12/2024' : "Financier TresoBrute_2024"}).iloc[:dt_treso_brute.shape[0]-2]

  dt_ul_ant_prod = dt_ul_ant_prod[['n_structure','Réalisé 2024 Total Année','libelle_structure']].rename(columns = {'Réalisé 2024 Total Année' : 'Financier Prod_2024'}).iloc[:dt_ul_ant_prod.shape[0]-1]
  dt_ul_ant_res_net = dt_ul_ant_res_net[['n_structure','Réalisé 2024 Total Année']].rename(columns = {'Réalisé 2024 Total Année' : 'Financier ResNet_2024'}).iloc[:dt_ul_ant_res_net.shape[0]-1]
  dt_ul_res_net_corr_prod = dt_ul_res_net_corr_prod[['n_structure','Réalisé 2024 Total Année']].rename(columns = {'Réalisé 2024 Total Année' : 'Financier ResCorrProd_2024'}).iloc[:dt_ul_res_net_corr_prod.shape[0]-1]
  dt_ul_treso_brute = dt_ul_treso_brute[['n_structure','Tréso nette au 31/12/2024','Financier Mois_AvanceTreso_2024']].rename(columns = {'Tréso nette au 31/12/2024' : "Financier TresoBrute_2024"}).iloc[:dt_ul_treso_brute.shape[0]-1]

  # Clean
  def dept_clean(x):
    if x == '2A' or x == '2B':
      return str(x)
    else : return str(int(x))
  dt_prod['n_dept'] = dt_prod['n_dept'].apply(dept_clean)
  dt_resnet['n_dept'] = dt_resnet['n_dept'].apply(dept_clean)
  dt_resnet_corr_prod['n_dept'] = dt_resnet_corr_prod['n_dept'].apply(dept_clean)
  dt_treso_brute['n_dept'] = dt_treso_brute['n_dept'].apply(dept_clean)

  dt_ul_ant_prod['n_structure'] = dt_ul_ant_prod['n_structure'].astype(int).astype(str)
  dt_ul_ant_res_net['n_structure'] = dt_ul_ant_res_net['n_structure'].astype(int).astype(str)
  dt_ul_res_net_corr_prod['n_structure'] = dt_ul_res_net_corr_prod['n_structure'].astype(int).astype(str)
  dt_ul_treso_brute['n_structure'] = dt_ul_treso_brute['n_structure'].astype(int).astype(str)

  # Normalement le seul doublon est DT de la dordogne Code structure : 3968, on garde la première occurence

  dt_ul_ant_prod = dt_ul_ant_prod.drop_duplicates(subset="n_structure", keep="first")
  dt_ul_ant_res_net = dt_ul_ant_res_net.drop_duplicates(subset="n_structure", keep="first")
  dt_ul_res_net_corr_prod = dt_ul_res_net_corr_prod.drop_duplicates(subset="n_structure", keep="first")
  dt_ul_treso_brute = dt_ul_treso_brute.drop_duplicates(subset="n_structure", keep="first")

  # On garde seulement unités locales et DT
  mask = dt_ul_ant_prod['libelle_structure'].isin(set(df_ref_structure['n_structure'].drop_duplicates()))
  dt_ul_ant_prod = dt_ul_ant_prod[mask]

  return dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute, dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute


def fusion_donnees_financieres(dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute,dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute):
  # Données par DT
  df_financier_DT = pd.merge(dt_prod, dt_resnet, on="n_dept", how="left")
  df_financier_DT = pd.merge(df_financier_DT, dt_resnet_corr_prod, on="n_dept", how="left")
  df_financier_DT = pd.merge(df_financier_DT, dt_treso_brute, on="n_dept", how="left")

  # Données par structures
  df_financier_DT_UL = pd.merge(dt_ul_ant_prod,dt_ul_ant_res_net, on="n_structure", how="left")
  df_financier_DT_UL = pd.merge(df_financier_DT_UL, dt_ul_res_net_corr_prod, on="n_structure", how="left")
  df_financier_DT_UL = pd.merge(df_financier_DT_UL, dt_ul_treso_brute, on="n_structure", how="left")

  # Pas de numéro de structure pour le dataframe contenant les DT, on fera le merge sur le numéro de département
  return df_financier_DT, df_financier_DT_UL

def verifier_n_dept(df_financier_DT,df_ref_structure):

  # Doublons
  doublons = df_financier_DT[df_financier_DT.duplicated(subset=['n_dept'])]
  if doublons.shape[0] > 0 :
    print(' ❌ Il y a des doublons :')
    display(df_financier_DT[df_financier_DT.duplicated(subset=['n_dept'])])
  else :
    print(' ✅ Aucun doublon')

  # Taille des données
  if df_financier_DT['n_dept'].shape[0] == 107 :
    print(' ✅ Pas de département manquant')
  else :
    print(' ❌ Il manque des départements : ')
    manquants_financier = set(df_financier_DT['n_dept'])
    manquants_struct = set(df_ref_structure['n_dept'])
    manquants = manquants_financier.union(manquants_struct) - manquants_struct.intersection(manquants_financier)
    print(manquants)

def clean_financier_DPS(financier_DPS):
    # Renommer les colonnes
    financier_DPS.columns.values[0] = 'code_comptable'
    financier_DPS.columns.values[1] = 'libelle'
    financier_DPS.columns.values[3] = 'année'
    financier_DPS.columns.values[4] = 'imputation_comptable'

    # Filtrer sur la bonne année
    df = financier_DPS[financier_DPS['année'] == "2024"]

    # Filtrer sur l'activité DPS
    df = df[df['imputation_comptable'] == "ACTA204"]

    # Extraire le département
    def extraire_et_nettoyer_code_departement(texte):
        code = texte[-3:] # Extraire les 3 derniers caractères
        code = code.lstrip('0') # Supprimer les zéros initiaux
        return code
    df['Code Département'] = df['code_comptable'].apply(extraire_et_nettoyer_code_departement)

    # Suppression de la ligne nationnale
    df = df[df["libelle"] != "TOTAL DELEGATION"]

    # Suppression des doublons (corse)
    df = df.drop_duplicates(subset=['Code Département'], keep='first')

    # Conserver les colonnes utiles
    df = df[["code_comptable","libelle","Code Département","année","imputation_comptable","PRODUITS DES POSTES SECOURS"]]
    return df


def clean_financier_FGP(financier_FGP):
    # Fusionner les 5 premières lignes pour créer les noms de colonnes
    header_row = 5
    header = financier_FGP.iloc[:header_row].apply(lambda x: ' '.join(x.dropna()).strip(), axis=0)
    financier_FGP = pd.DataFrame(financier_FGP.iloc[header_row:].values, columns=header)

    # Conservation des lignes utiles
    df = financier_FGP.head(13)

    # Conservation des colonnes utiles
    df = df[["Nom Structure","PRODUITS DE FORMATIONS SCOLARITE ET DROITS D INSCRIPTION Réalisé 2024"]]
    return df


def clean_financier_FGP_DPS(
    financier_FGP,
    financier_DPS
):
    df_financier_FGP_clean = clean_financier_FGP(financier_FGP)
    df_financier_DPS_clean = clean_financier_DPS(financier_DPS)

    return (
        df_financier_FGP_clean,
        df_financier_DPS_clean,
    )


def indicateur_financier_DPS(financier_DPS, df_ref_structure):
    # Mapping sur le département
    mapping_dict = df_ref_structure[df_ref_structure["Type_structure"] == "DELEGATION TERRITORIALE - DT"].set_index('N_dept')['N_structure'].to_dict()
    financier_DPS['N_structure'] = financier_DPS['Code Département'].map(mapping_dict)
    verifier_mapping(financier_DPS, "N_structure", "libelle" ,df_ref_structure)

    # Transformation des str en int
    financier_DPS['PRODUITS DES POSTES SECOURS'] = financier_DPS['PRODUITS DES POSTES SECOURS'].str.replace("€", "").str.replace("\u202f", "").str.replace(" ", "").replace("",0).astype(int)

    # Conserver les colonnes utiles
    financier_DPS = financier_DPS[["N_structure","PRODUITS DES POSTES SECOURS"]]

    # Modification du nom de colonne
    financier_DPS = financier_DPS.rename(columns={"PRODUITS DES POSTES SECOURS":"Secours Produits_DPS_2024"})

    return financier_DPS


def indicateur_financier_FGP(financier_FGP, df_ref_structure):
    # Recherche des correspondances vis à vis du référentiel structure
    df = rapprochement_libelles(df_ref_structure, financier_FGP, "Nom Structure")

    # Correction des écarts
    index_to_correct = df[df['Nom Structure'] == "PACA CORSE"].index[0]
    df.at[index_to_correct, 'N_structure'] = "3732"

    index_to_correct = df[df['Nom Structure'] == "GRAND EST"].index[0]
    df.at[index_to_correct, 'N_structure'] = "4455"

    # Conservation des colonnes utiles
    df = df[["PRODUITS DE FORMATIONS SCOLARITE ET DROITS D INSCRIPTION Réalisé 2024","N_structure"]]

    # Modification du nom des colonnes
    df = df.rename(columns={'PRODUITS DE FORMATIONS SCOLARITE ET DROITS D INSCRIPTION Réalisé 2024': 'Formation_grand_public CA_2024'})

    # Modification des données pour obtenir des int
    df['Formation_grand_public CA_2024'] = df['Formation_grand_public CA_2024'].str.replace(',', '').str.replace(' €', '').str.replace(' ', '').astype(int)

def indicateur_financier_FGP_DPS(
    financier_FGP,
    financier_DPS
):
    df_financier_FGP_indicateur = indicateur_financier_FGP(financier_FGP)
    df_financier_DPS_indicateur = indicateur_financier_DPS(financier_DPS)

    return (
        df_financier_FGP_indicateur,
        df_financier_DPS_indicateur,
    )

# CHARGEMENT DE TOUTES LES DONNEES PAR TABLE

# 0. Ref_structure

In [ ]:
df_ref_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw/').worksheet('Feuille 1'))

NameError: name 'gspread_client' is not defined

In [ ]:
df_ref_structure = renommer_par_nom_table(df_ref_structure, "AS_Informations_structures", mapping_df)
df_ref_structure['n_structure'] = df_ref_structure['n_structure'].astype(int).astype(str)
df_ref_structure.head()

NameError: name 'df_ref_structure' is not defined

In [ ]:
df_ref_structure_DT = df_ref_structure[df_ref_structure['nom_structure'].str.contains('DT')].astype(str)

# 1. PEGASS

In [ ]:
# EXEMPLE :  Charger le DataFrame
# spreadsheet = gspread_client.open_by_url("https://docs.google.com/spreadsheets/d/1WEoWR3dnhy7NL5ISoD6o-58krsttfHkiqaJz30Vvg74/")
# worksheet = spreadsheet.worksheet("Feuille 1")
# df_raw = get_as_dataframe(worksheet)

##3.0. rattachement_court

In [ ]:
rattachement_court = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU/edit?usp=sharing').worksheet('Feuille 1'))

In [ ]:
rattachement_court.head()

In [ ]:
rattachement_court.columns

## 3.1. Activité_benevole ref activité

In [ ]:
Ref_activité_benevole = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1rf1gXTylNEHEt72UfwZO62gIfgzf9eY8lPqhXLJ5hs8/edit').worksheet('Feuille 1'))

In [ ]:
Ref_activité_benevole.head()

In [ ]:
Ref_activité_benevole.columns

## 3.2.Pegass_activite / Activite

In [ ]:
Pegass_activite = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13Ygh1goryIgp2UCh19tKaTv3AWkfsSMInuS8-VMbmeU/edit').worksheet('Feuille 1'))

In [ ]:
Pegass_activite.head()

In [ ]:
Pegass_activite.dtypes

In [ ]:
Pegass_activite.columns

## 3.3. PegassInscription / Inscription

In [ ]:
Pegass_inscription = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1wCYPGwDVKZC6BBuMnOc7kB98agof5IMkdn9W7xn5UUg/edit').worksheet('Feuille 1'))

In [ ]:
Pegass_inscription.dtypes

In [ ]:
Pegass_inscription.columns

In [ ]:
Pegass_inscription.head()

## 1.5. PREPARATION DE LA BASE DE DONNEES

##4.1. Renommer les variables

In [ ]:
Pegass_inscription = renommer_par_nom_table(Pegass_inscription, "Pegass_inscription", mapping_df)

In [ ]:
Pegass_inscription.head()

In [ ]:
Pegass_inscription.columns

In [ ]:
Pegass_inscription.dtypes

Verifier que les données soient au bon format

In [ ]:
#mettre les dates en format date
Pegass_inscription["debut_inscription"] = pd.to_datetime( Pegass_inscription["debut_inscription"])
Pegass_inscription["fin_inscription"] = pd.to_datetime( Pegass_inscription["fin_inscription"])

In [ ]:
Pegass_activite = renommer_par_nom_table(Pegass_activite, "Pegass_activite", mapping_df)
Pegass_activite.head()

In [ ]:
Pegass_activite.columns

In [ ]:
Ref_activité_benevole = renommer_par_nom_table(Ref_activité_benevole, "Ref_activité_benevole", mapping_df)
Ref_activité_benevole.head()

In [ ]:
Ref_activité_benevole.columns

##4.2. Selection des colonnes qui nous serons utiles

## 2.1. GAIA_contact

In [ ]:
GAIA_contact = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1k4-nMZqUulcZBPMplZLWHcvSTvzISqF9uMnlITdikmI/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.2. GAIA_action

In [ ]:
GAIA_action = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1XvfYhne_YxMBVfgkDUzKhhOle9-bmEP3j0gpBYZsKuo/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.3. GAIA_rattachement_action

In [ ]:
GAIA_rattachement_action = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1vtC3hpxh6RIcmhMjifVFoi169uhdi0f9fpKXP9FqEd8/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.4 GAIA_act_str

In [ ]:
GAIA_act_str = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1PrK18aa8dllTjXOEyPHXMEgqP4gm1ZeJdnCmlUG78EA/edit?usp=drive_link').worksheet('Feuille 1'))

In [ ]:
GAIA_act_str.head()

## 2.5. GAIA_structure

In [ ]:
GAIA_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1forcw_rC0WCcwu6K8-AUhm1sur9pp5XZX_YTCKaBA6g/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.6. Preparation de la base

### 2.6.1. Renommer les variables

In [ ]:
GAIA_action = renommer_par_nom_table(GAIA_action, "GAIA_action", mapping_df)
GAIA_rattachement_action = renommer_par_nom_table(GAIA_rattachement_action, "GAIA_rattachement_action", mapping_df)
GAIA_contact = renommer_par_nom_table(GAIA_contact, "GAIA_contact", mapping_df)
GAIA_structure = renommer_par_nom_table(GAIA_structure, "GAIA_structure", mapping_df)
GAIA_act_str = renommer_par_nom_table(GAIA_act_str, "GAIA_act_str", mapping_df)

In [ ]:
GAIA_structure.head()

# 3. NOMINATION

## 3.1. NOMINATION_nomination

In [ ]:
NOMINATION_nomination = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ywCGFgW5eLONMNK64o4NZrQQzasqfEGnnQL6LfDXbbM/edit?gid=614834196').worksheet('NOMINATION_nomination'))

In [ ]:
NOMINATION_nomination.head()

## 3.2 NOMINATION_attribution_nomination

In [ ]:
NOMINATION_attribution_nomination = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1BzCcfO1NLM5oMmBD1cBELIuvBvVjucsK6Wm4zPTaO-Q/').worksheet('NOMINATION_attribution_nomination'))

In [ ]:
NOMINATION_attribution_nomination.head()

## 3.3. Préparation de la base

### 3.3.1. Renommer les variables

In [ ]:
NOMINATION_nomination = renommer_par_nom_table(NOMINATION_nomination, "nomination", mapping_df)
NOMINATION_attribution_nomination = renommer_par_nom_table(NOMINATION_attribution_nomination, "attribution_nomination", mapping_df)

# 4. IMPACT

## 4.1 Impact_indicateurs

In [ ]:
IMPACT_indicateurs = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.2 Impact_indicateur_value

In [ ]:
IMPACT_indicateur_value = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.3 Impact_donnees_activite

In [ ]:
IMPACT_donnees_activite = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.4 Impact_abstract_donnees_activite

In [ ]:
IMPACT_abstract_donnees_activite = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.5. Preparation de la base

### 4.5.1. Renommer les variables

In [ ]:
IMPACT_indicateurs = renommer_par_nom_table(IMPACT_indicateurs, "IMPACT_indicateurs", mapping_df)
IMPACT_indicateur_value = renommer_par_nom_table(IMPACT_indicateur_value, "IMPACT_indicateur_value", mapping_df)
IMPACT_donnees_activite = renommer_par_nom_table(IMPACT_donnees_activite, "IMPACT_donnees_activite", mapping_df)
IMPACT_abstract_donnees_activite = renommer_par_nom_table(IMPACT_abstract_donnees_activite, "IMPACT_abstract_donnees_activite", mapping_df)

# 5. Données financières

In [ ]:
financier = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c')

In [ ]:
dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute, dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute = import_clean_donnees_financieres(financier,df_ref_structure,mapping_df)

# 6. Mobilité

In [ ]:
mobilite = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1dvxT58WR-FqdT-4r-A9ca4vaA9FG7IXHJJaTbnjio8A/')

In [ ]:
df_mobilite = filtres_mobilite(mobilite,mapping_df)

# FUSION DES TABLES

## 1. Fusion PEGASS activité, inscription, ref_activité_bénévole, rattachement_court

### 1.1 Filtres généraux à appliquer

In [ ]:
FILTERS = {
    "filtres_activites_ben_test": {"col": "activite_benevole_id", "values": [1, 2, 3, 4]}, #variables numeric
     "statut_inscription" : {"col": "statut_inscription", "values": [1]},
    "vulne_core": {"col": "Indicateur", "values": ["Indice de vulnérabilité global", "Revenu median"]}, #variables textuelles
}

### 1.2. Fusion des tables

In [ ]:
# left join (tous les id de df1, et ce qu'on trouve dans df2)
# left = pd.merge(df1, df2, on="id", how="left")

df1 = pd.merge(Pegass_inscription, Pegass_activite, left_on="activite_id", right_on="activite_id", how="left")

In [ ]:
df1.head()

In [ ]:
df2 = pd.merge(df1, Ref_activité_benevole, left_on="activite_benevole_id", right_on="activite_benevole_id", how="left")

In [ ]:
df2.head()

In [ ]:
df2.to_csv("df2.csv", index=False, encoding="utf-8-sig")

In [ ]:
df2 = df2.rename(columns={"structureMenanActiviteId": "structure_menant_activite_id"}) #renomage temporaire à  supprimer après

In [ ]:
#Merge sur la structure de ratachement
df2 = pd.merge(df2, rattachement_court, left_on="structure_menant_activite_id", right_on="n_structure", how="left").drop(columns=["n_structure"])

In [ ]:
df2.columns

## 2. Fusion GAIA rattachement_action, action, act_str, structure

### 2.1. Filtres généraux à appliquer

In [ ]:
#FTILRE SUR ANNEE NULLE OU FIN EN 2025

# Vérification que la colonne est au format datetime
GAIA_act_str['date_fin_activite_struct'] = pd.to_datetime(GAIA_act_str['date_fin_activite_struct'], errors='coerce')

# Filtrage : date nulle ou année = 2025
GAIA_act_str = GAIA_act_str[
    GAIA_act_str['date_fin_activite_struct'].isna() | (GAIA_act_str['date_fin_activite_struct'].dt.year == 2025)
]

### 2.2. Fusion des tables

In [ ]:
# left = pd.merge(df1, df2, on="id", how="left")

# 1) Join avec action sur act_id
df_GAIA = pd.merge(GAIA_rattachement_action, GAIA_action, on="n_action_ben", how="left")

# 2) Join avec rattachement_action sur act_id + str_id
df_GAIA = pd.merge(df_GAIA, GAIA_act_str, on="n_action_ben", how="left")

# 3) Join avec contact sur cob_idrp
df_GAIA = pd.merge(df_GAIA, GAIA_structure, on="id_structure", how="left")

# df final disponible dans df_GAIA
df_GAIA.head()

## 3. Fusion NOMINATION nomination, attribution_nomination

### 3.1. Filtres généraux à appliquer

In [ ]:
#FTILRE SUR ANNEE NULLE OU FIN EN 2025

# Vérification que la colonne est au format datetime
NOMINATION_attribution_nomination['date_fin_nomination'] = pd.to_datetime(NOMINATION_attribution_nomination['date_fin_nomination'], errors='coerce')
NOMINATION_attribution_nomination['date_debut_nomination'] = pd.to_datetime(NOMINATION_attribution_nomination['date_debut_nomination'], errors='coerce')

# Filtrage : date nulle ou année = 2025
NOMINATION_attribution_nomination = NOMINATION_attribution_nomination[
    NOMINATION_attribution_nomination['date_fin_nomination'].isna() | (NOMINATION_attribution_nomination['date_fin_nomination'].dt.year == 2025)
]

### 3.2. Fusion des tables

In [ ]:
# left join (tous les id de df1, et ce qu'on trouve dans df2)
# left = pd.merge(df1, df2, on="id", how="left")

df_NOMINATION = pd.merge(NOMINATION_nomination, NOMINATION_attribution_nomination,on="nomination_id", how="left") #VERIFIER LA FOREIGN KEY!

## 4. Fusion IMPACT indicateurs, indicateurs_value, donnees_activite, abstract_donnes_activite

### 4.1. Filtres généraux à appliquer

In [ ]:
#FTILRE SUR ANNEE 2025

# Vérification que la colonne est au format datetime
IMPACT_donnees_activite['date_fin_activite'] = pd.to_datetime(IMPACT_donnees_activite['date_fin_activite'], errors='coerce')
IMPACT_donnees_activite['date_debut_activite'] = pd.to_datetime(IMPACT_donnees_activite['date_debut_activite'], errors='coerce')

# Filtrage : date nulle ou année = 2025
IMPACT_donnees_activite = IMPACT_donnees_activite[ (IMPACT_donnees_activite['date_debut_activite'].dt.year == 2025)]

### 4.2. Fusion des tables

In [ ]:
# left = pd.merge(df1, df2, on="id", how="left")

# 1) Join avec action sur act_id
df_IMPACT = pd.merge(IMPACT_indicateur_value, IMPACT_indicateurs, on="n_indicateurs", how="left")

# 2) Join avec rattachement_action sur act_id + str_id
df_IMPACT = pd.merge(df_IMPACT, IMPACT_donnees_activite, on="id_activite", how="left")

# 3) Join avec contact sur cob_idrp
df_IMPACT = pd.merge(df_IMPACT, IMPACT_abstract_donnees_activite, on="id_activite", how="left")

# df final disponible dans df_GAIA
df_IMPACT.head()

## 5. Fusion Données financières

### 5.1 Fusion des tables

In [ ]:
df_financier_DT, df_financier_DT_UL = fusion_donnees_financieres(dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute,dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute)

### 5.2 Vérifications

In [ ]:
verifier_n_dept(df_financier_DT,df_ref_structure)

 ✅ Aucun doublon
 ✅ Pas de département manquant

In [ ]:
verifier_colonne_structure(df_financier_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

# Calcul des indicateurs

## 1. Nombre de bénévoles par activité benevole

### 1.1 Selection des colonnes qui nous serons utiles

#### 1.1.1 Filtres génériques par indicateur

#### 1.1.2 définition des filtres génériques à appliquer

In [ ]:
# NOMBRE DE BENEVOLES PAR ACTIVITE BENEVOLES
# Fonction filtre encore plus sophistiqué

FILTERS_PEGASS = {
    "filtres_activites_ben_test": {"col": "activite_benevole_id", "values": [1, 2, 3, 4]}, #variables numeric
     "statut_inscription" : {"col": "statut_inscription", "values": [1]},
    "vulne_core": {"col": "Indicateur", "values": ["Indice de vulnérabilité global", "Revenu median"]}, #variables textuelles
}

#### 1.1.3 Application des filtres primaires

In [ ]:
df2 = filtre_2025(df2,date_col="debut_inscription" )

df2 = filtre(df2,"statut_inscription")

df2 = filtre(df2,"filtres_activites_ben_test")

#### 1.1.4 Ajout de la variable mensuelle

In [ ]:
df2['debut_inscription'] = pd.to_datetime(df2['debut_inscription'])
df2["mois_debut_inscription"] = df2["debut_inscription"].dt.month

In [ ]:
Pegass_inscription.head()

### 1.2 Definition de l'indicateur générique *annuel*

In [ ]:
# On compte le nb de NivolS unniques par Structure
Nb_benevoles_distincts = (df2.groupby('structure_menant_activite_id')['nivol'].nunique()).rename("nb_benevoles_distincts")
# A voir si on peut pas remplacer reset_index par .rename()

In [ ]:
##Definition pour calcul benevoles distincts
def nb_benevoles_distincts_gen(df, filtre=None,
                              col_structure="structure_menant_activite_id",
                              col_user="nivol",
                              out_col="nb_benevoles_distincts"):
    d = df.query(filtre) if filtre else df
    return (d.groupby(col_structure)[col_user]
              .nunique()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

In [ ]:
Nb_benevoles_distincts.head()

In [ ]:
# A faire sur la base du code de Clément D

#### 1.2.1 Calcul des indicateurs un par un

In [ ]:
activite_ben_cible = "Distribution alimentaire"  # l'intitulé que l'on souhaite

Nb_benevoles_Distribution_alimentaire = (
    df2[df2['libelle_activite_benevole'] == activite_ben_cible]  # filtre sur l’intitulé
      .nunique()
      .reset_index(name='nb_benevoles_distincts')
)

In [ ]:
Nb_benevoles_Distribution_alimentaire.head()

#### 1.2.1 Calcul indicateur avec def

In [ ]:
# 2) Indicateur avec filtre
activite_ben_cible = "Distribution alimentaire"
Nb_benevoles_Distribution_alimentaire1 = nb_benevoles_distincts_gen(
    df2,
    filtre=f"libelle_activite_benevole == @activite_ben_cible"
)

#### 1.2.2 Calcul des indicateurs par type d'activités bénévole ( avec boucle)

In [ ]:
##Automatisation en créant une boucle

#Il faut prendre activite_id pour le numero d'activité mais là je teste direct avec le libellé
liste_activite_ben= [
    "Distribution alimentaire",
    "Épicerie sociale",
    "Colis alimentaire",
    "Aide d'urgence",
    "Autre dispositif"
]

In [ ]:

def make_var_name(libelle_activite_benevole):
    # Supprimer les accents
    s = unicodedata.normalize("NFKD", libelle_activite_benevole)
    s = "".join(c for c in s if not unicodedata.combining(c))
    # Minuscules + remplacer tout ce qui n'est pas lettre/chiffre par "_"
    s = s.lower()
    s = re.sub(r"[^0-9a-zA-Z]+", "_", s).strip("_")
    return f"df_{s}"

In [ ]:
for activite in liste_activite_ben:
    df_tmp = (
        df2[df2['libelle_activite_benevole'] == activite]
          .groupby('structure_menant_activite_id')['nivol']
          .nunique()
          .reset_index(name='nb_benevoles_distincts')
    )

    var_name = make_var_name(activite)
    globals()[var_name] = df_tmp  # crée une variable df_<nom_simplifié>

    print(f"Créé : {var_name} (libelle_activite_benevole = {activite})")

In [ ]:
df_distribution_alimentaire.head()

### 1.3. Calcul de l'indicateur annuel par DT de rattachement

In [ ]:
##Definition pour calcul benevoles distincts
def nb_benevoles_distincts_DT_gen(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="nivol",
                              out_col="nb_benevoles_distincts"):
    d = df.query(filtre) if filtre else df
    return (d.groupby(col_structure)[col_user]
              .nunique()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

In [ ]:
# 2) Indicateur avec filtre
activite_ben_cible = "Distribution alimentaire"
Nb_benevoles_Distribution_alimentaire2 = nb_benevoles_distincts_gen(
    df2,
    filtre=f"libelle_activite_benevole == @activite_ben_cible"
)

In [ ]:
Nb_benevoles_Distribution_alimentaire2

### 1.4 Calcul de l'indicateur générique mensuel

In [ ]:
##Definition pour calcul benevoles distincts
def nb_benevoles_distincts_mois_gen(df, filtre=None,
                              col_structure="structure_menant_activite_id",
                              col_user="nivol",
                              col_mois = "mois_debut_inscription",
                              out_col="nb_benevoles_distincts_mois"):
    d = df.query(filtre) if filtre else df
    return (d.groupby([col_structure, col_mois])[col_user]
              .nunique()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

In [ ]:
# 2) Indicateur avec filtre
activite_ben_cible = "Distribution alimentaire"
Nb_benevoles_Distribution_alimentaire3 = nb_benevoles_distincts_mois_gen(
    df2,
    filtre=f"libelle_activite_benevole == @activite_ben_cible"
)

In [ ]:
Nb_benevoles_Distribution_alimentaire3.head()

### 1.5 Calcul de l'indicateur mensuel par DT de rattachement

In [ ]:
##Definition pour calcul benevoles distincts
def nb_benevoles_distincts_mois_DT_gen(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="nivol",
                              col_mois = "mois_debut_inscription",
                              out_col="nb_benevoles_distincts_mois"):
    d = df.query(filtre) if filtre else df
    return (d.groupby([col_structure, col_mois])[col_user]
              .nunique()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

In [ ]:
# 2) Indicateur avec filtre
activite_ben_cible = "Distribution alimentaire"
Nb_benevoles_Distribution_alimentaire4 = nb_benevoles_distincts_mois_DT_gen(
    df2,
    filtre=f"libelle_activite_benevole == @activite_ben_cible"
)

In [ ]:
Nb_benevoles_Distribution_alimentaire4.head()

## Nombre de bénévoles déclarés sur une activitée

### 10.1. Calcul nb de volontaires de l'urgence

In [ ]:
# Filtre sur le libelle approprié
df_urgence = df_GAIA[df_GAIA["libelle_action_ben"] == "Urgences et autres opérations"]

In [ ]:
# On compte le nb de volontaires de l'urgence
NbBeneDecla_GAIA = (df_urgence.groupby('n_structure_x')['id_gaia'].nunique())

In [ ]:
# NbBeneDecla_GAIA.head()

## 3. RTAEO & RLAEO

In [ ]:
# Filtre sur le libelle approprié
referents_AEO = df_NOMINATION[df_NOMINATION["libelle_nomination"] == "RTAEO"]

# Filtre sur le libelle approprié
referents_OCR = df_NOMINATION[df_NOMINATION["libelle_nomination"] == "RTOCR"]

In [ ]:
# On compte le nb de RTAEO & RLAEO
referents_AEO = (referents_AEO.groupby('structure_id')['libelle_nomination'].nunique())

In [ ]:
# DF par mois
annee = 2025

# Mois de l'année
mois = pd.date_range(
    start=f"{annee}-01-01",
    end=f"{annee}-12-01",
    freq="MS"
)

resultats = []

for m in mois:
    debut_mois = m
    fin_mois = m + pd.offsets.MonthEnd(1)

    actifs = referents_AEO[
        (referents_AEO["date_debut_nomination"] <= fin_mois) &
        (referents_AEO["date_fin_nomination"] >= debut_mois)
    ]

    comptage = (
        actifs
        .groupby("structure")
        .size()
        .reset_index(name="nb")
    )

    comptage["mois"] = m.strftime("%Y-%m")
    resultats.append(comptage)

# Concaténation
referents_AEO_mois = pd.concat(resultats)

# Tableau croisé
referents_AEO_mois = referents_AEO_mois.pivot(
    index="structure_id",
    columns="mois",
    values="nb"
).fillna(0).astype(int)

print(pivot)

## 4. RTOCR & RLOCR

In [ ]:
# On compte le nb de RTAEO & RLAeo
referents_OCR = (referents_OCR.groupby('structure_id')['nom'].nunique())

In [ ]:
# DF par mois
annee = 2025

# Mois de l'année
mois = pd.date_range(
    start=f"{annee}-01-01",
    end=f"{annee}-12-01",
    freq="MS"
)

resultats = []

for m in mois:
    debut_mois = m
    fin_mois = m + pd.offsets.MonthEnd(1)

    actifs = referents_OCR[
        (referents_OCR["date_debut_nomination"] <= fin_mois) &
        (referents_OCR["date_fin_nomination"] >= debut_mois)
    ]

    comptage = (
        actifs
        .groupby("structure")
        .size()
        .reset_index(name="nb")
    )

    comptage["mois"] = m.strftime("%Y-%m")
    resultats.append(comptage)

# Concaténation
referents_OCR_mois = pd.concat(resultats)

# Tableau croisé
referents_OCR_mois = referents_OCR_mois.pivot(
    index="structure_id",
    columns="mois",
    values="nb"
).fillna(0).astype(int)

print(pivot)

##  Nombre d'agréments territoriaux (Dispos d'urgence)

## Nombre de personnes prises en charge (Dispos d'urgence)

## Indicateurs Mobilité


Indicateurs qui nécessitent seulement les données mobilité :

- Nb de structures menant une activité AEO/AAD mobile
- Nombre de personnes accompagnées par des dispositifs AEO/AAD mobiles
<br>
Indicateurs qui nécessitent une fusion avec données AEO/AAD :

- Nombre de bénévoles impliqués dans les activités AEO ou AAD
- Nombre de bénévoles impliqués dans les activités AEO ou AAD

In [ ]:
df_mobilite_DT = indicateurs_mobilite(df_mobilite, df_ref_structure, 'DT_de_rattachement')
df_mobilite_DT_UL = indicateurs_mobilite(df_mobilite, df_ref_structure, 'n_structure')

In [ ]:
verifier_colonne_structure(df_mobilite_DT, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [ ]:
verifier_colonne_structure(df_mobilite_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

# Enregistrement des données

In [ ]:
# Entregistrement du DataFrame
# save_dataframe_to_sheet("1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw", client, df_structure)
# save_dataframe_to_sheet("1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU", client, df_rattachement_court)