In [1]:
!git config --global user.email "clement.dilasser@croix-rouge.fr"
!git clone https://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@github.com/clementsouk-aloun-dot/Code-PAT.git

Cloning into 'Code-PAT'...
remote: Enumerating objects: 1481, done.
remote: Counting objects: 100% (223/223), done.
remote: Compressing objects: 100% (173/173), done.
remote: Total 1481 (delta 113), reused 79 (delta 50), pack-reused 1258 (from 2)
Receiving objects: 100% (1481/1481), 8.40 MiB | 6.81 MiB/s, done.
Resolving deltas: 100% (992/992), done.

In [1]:
%cd Code-PAT
!git checkout main

/content/Code-PAT
M	__pycache__/utils.cpython-312.pyc
M	scripts_data/__pycache__/adherent.cpython-312.pyc
M	scripts_data/__pycache__/alim.cpython-312.pyc
M	scripts_data/__pycache__/base_contact.cpython-312.pyc
M	scripts_data/__pycache__/domifa.cpython-312.pyc
M	scripts_data/__pycache__/financier.cpython-312.pyc
M	scripts_data/__pycache__/gaia.cpython-312.pyc
M	scripts_data/__pycache__/impact.cpython-312.pyc
M	scripts_data/__pycache__/manuelles.cpython-312.pyc
M	scripts_data/__pycache__/maraude.cpython-312.pyc
M	scripts_data/__pycache__/mobilite.cpython-312.pyc
M	scripts_data/__pycache__/nomination.cpython-312.pyc
M	scripts_data/__pycache__/pegass.cpython-312.pyc
M	scripts_data/gaia.py
M	scripts_data/impact.py
M	scripts_data/maraude.py
M	scripts_data/nomination.py
Already on 'main'
Your branch is up to date with 'origin/main'.

In [2]:
!git add .

In [3]:
!git commit -m "corrections"

[main 5945bbf] corrections
 17 files changed, 20 insertions(+), 17 deletions(-)
 rewrite scripts_data/__pycache__/impact.cpython-312.pyc (65%)

In [ ]:
!git fetch origin

remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 12 (delta 7), reused 7 (delta 5), pack-reused 0 (from 0)
Unpacking objects: 100% (12/12), 70.91 KiB | 797.00 KiB/s, done.
From https://github.com/clementsouk-aloun-dot/Code-PAT
   29101f2..a5e968c  main                 -> origin/main
   125a2dc..4943af5  Merged_GAIA-+-NOMINATION-+-impact -> origin/Merged_GAIA-+-NOMINATION-+-impact
 * [new branch]      Verif-Maraude        -> origin/Verif-Maraude
 * [new branch]      Verified_Textile_SBO -> origin/Verified_Textile_SBO

In [ ]:
!git config pull.rebase true

In [ ]:
!git pull

Successfully rebased and updated refs/heads/main.

In [4]:
!git push

Enumerating objects: 31, done.
Counting objects: 100% (31/31), done.
Delta compression using up to 2 threads
Compressing objects: 100% (22/22), done.
Writing objects: 100% (22/22), 58.30 KiB | 4.86 MiB/s, done.
Total 22 (delta 10), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (10/10), completed with 8 local objects.
To https://github.com/clementsouk-aloun-dot/Code-PAT.git
   6aa209a..5945bbf  main -> main

#INSTALL PACKAGE

In [3]:
!gcloud auth application-default login

Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=iS5MtTiKs3plBapRmO0GREU12NWsu4&prompt=consent&token_usage=remote&access_type=offline&code_challenge=LQp5pVjmii3powcRR-mb_CQzo0HLm-ExA04czyWRPYw&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0AfrIepBFbzBrMC-t_FP3P31pkn898PcWVMO0shhjsHyomKeNSfxfDs_KKVxM1xLSXIKFLg

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.


To take a quick anonymous survey, run:
  $ gcloud survey

In [4]:
!pip install PyPDF2
!pip install reportlab
!pip install PyMuPDF tools
!pip install xlsxwriter

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 7.2 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1
Collecting reportlab
  Downloading reportlab-4.4.10-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.4)
Downloading reportlab-4.4.10-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 35.4 MB/s eta 0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-4.4.10
Collecting PyMuPDF
  Downloading pymupdf-1.27.1-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Collecting tools
  Downloading tools-1.0.23-py3-none-any.whl.metadata (1.3 kB)
Downloading pymupdf-1.27.1-cp310-abi3-manylinux_2_28_x86_64.whl (24.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 MB 28.1 MB/s eta 0:00:00
Downloading tools-1.0.23-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 871.2 kB/s eta 0:00:00
Installing collected packages: tools, PyMuPDF
Successfully installed PyMuPDF-1.27.1 tools-1.0.23
Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 7.1 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9

In [5]:
import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import sys
import io
import re
import shutil
import zipfile
from google.colab import drive, files

from google.colab import auth
from google.auth import default
import unicodedata
import re
import torch
from sentence_transformers import SentenceTransformer, util
from google.cloud import bigquery
from pyspark.sql import SparkSession
import gc
from functools import reduce

Imports des fichiers .py

In [6]:
sys.path.append(os.path.abspath("/content/Code-PAT/scripts_data"))
sys.path.append(os.path.abspath("/content/Code-PAT"))

from adherent import *
from alim import *
from domifa import *
from financier import *
from gaia import *
from impact import *
from manuelles import *
from maraude import *
from base_contact import*
from mobilite import *
from nomination import *
from pegass import *

from utils import *

#AUTHENTIFICATION

In [7]:
PROJECT_ID = "crf-pat"
client = bigquery.Client(project=PROJECT_ID)

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [8]:
# Etape 0 : Préparation de l'environnement

CREDENTIALS_JSON = """
{
  "type": "service_account",
  "project_id": "alexandrevalent",
  "private_key_id": "dba39c84ba4135ce5ede6479a186ad8cde499dee",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvGU4ZJFrBwCBb\nu8s4aPA5bQTOKDkPZEVdNyY//RneR6RC9JPrcbfVfIUaQU7A036sfdhDGFKJbw20\nTZ55fafcH9yCMiUO+Nzek0eogON4TXrXsh8UFtdw8BOuaVkFitU5yg8kFhTnEZtd\ntPfZHW3Aqhd/aDoTOBNgRuF/hVTKQ2ytbCbE77fL2/pz9kvpZ2Zrz3u1lmksSJls\nHIolNwX9R05YqmrkpZ/TMAULFk4bT0VRQng5pmN9AeB61eJLWhlLaEdeu79NWV4B\n7tZd6RzzTFors804aJkmXHM63VRtvGD0UlR0O7w1QlI3ymUxpy5hrjbz6n9bmpMI\nfebvydLnAgMBAAECggEADipn7RTJ2t7mP0WkHT4wIRU2zE7ovtwH2JC7oXWigB8f\npOMQjH24t6bJReR+sI7rspzDwDnZg5DedPXKml2WFPLm7gmMgfeUNtWHeJRk0rjB\n9W1NolxutY5WqUeQkig3M+Oq8epvano8LYqUepYs6OdZ207dU+y3dJSHbb+lqm9D\ntQZR2oBj7W1iZ8fJ+SQLSjU5BztS1CvWuayRd/tLd9Spp0NUn5uQFTKwel9Gazmz\n28IsPPm6SudplFhaGd4kCPvhcg0jGEKe61VYdgHoBzp+EXRWXUvQ+SbMafXtMvoB\nLoUH4X3creKzJQKXnjlDpAzRHMYhJTvHinHXaggdcQKBgQDcJszFOECfSovXFZNq\nMyQOWbesyDb2OQhJLFZCD2QraZm3jPaIPeMfFkmFAumcVal6EzpR5IE8g9jBuLo+\ng6j3NTo5jbGO9WEn4361yEotb+S8t3/DTHvWqXBK7HdUB/KHlyGtctm8yErdMZQB\nvzo03aTwwStNTeFG8GzT1Nd7JQKBgQDLnHIMbx9iAG3K21XCq0Dot2Q63hklJC26\nsJlrTkdXMOIlhpwJ6LTOJe2paHbR56IrKOHQCuLxQFhRd8Eidz1ahjO7D8fKr/TG\nS8/V32FrpONyxhKinLsccSb86S3vvpKCI265z5EEjk/1qnx3TOo6oqA/2DQLv0Q4\nYinmNSOeGwKBgHGjYY3n9IuE6lwy2e42ycTSkNoSWzSLyfgjd78PvNAf6WXy0IsR\nDvzL/1U2ZKn7GclWxYLiJce78xZEKXb9dSluA0kUF/RIO0dgydZBtfBwUq0LN1rz\nTvVGbx1tpEbu90UAQTUMFNK6vNIitliUghIp2usfex+jNMbuce6Cblw1AoGBAKDH\n1gtZiFeT7R7d2jfRkXzyrBQMI6D/k5izMULZ2l3QfROS2w68EmIi8yvuEL2qApXA\nP6hPoGtPGy6huQHlVK5yANF7IZI9JbWcUe8Z6MzetLiCDl8YEmzgMSBPZXXGb9yR\n7DKP5HzLf/qG+KggNWm913ry2A5ap506bsmZNpn3AoGBAM6vvI9tb+AcNfd4ewmY\nAWSb4GLliRTaBIGHYmotfyBEBWpXZq2/0JG32RRf3rYUJWWn/r7K+zrRUqeMwlD+\nz7GuSU+OaSDzYj7fwDyuxOwTJMLrh+AkKbUYBsMF7YH1qIRjBjKNdj1LOznASQMe\nu1E4sNa9RRRujbQw4AEP3Xjl\n-----END PRIVATE KEY-----\n",
  "client_email": "crf-slidemanager@alexandrevalent.iam.gserviceaccount.com",
  "client_id": "101959630014487618959",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/crf-slidemanager%40alexandrevalent.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly']


# Authentification
credentials = service_account.Credentials.from_service_account_info(json.loads(CREDENTIALS_JSON, strict=False), scopes=SCOPES)

# Initialisation des services
slides_service = build('slides', 'v1', credentials=credentials)
drive_service = build('drive', 'v3', credentials=credentials)
gspread_client  = gspread.authorize(credentials)

# Variables globales

In [9]:
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

# CHARGEMENT DE TOUTES LES DONNEES PAR TABLE

## 0. Ref_structure

In [10]:
df_ref_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw/').worksheet('Feuille 1'))

In [11]:
df_ref_structure = renommer_par_nom_table(df_ref_structure, "AS_Informations_structures", mapping_df)
df_ref_structure['n_structure'] = df_ref_structure['n_structure'].astype(int)
df_ref_structure = df_ref_structure[df_ref_structure["type_structure"].isin(["UNITE LOCALE - UL", "DELEGATION TERRITORIALE - DT", 'IMPLANTATION LOCALE HORS AL - IL', 'ANTENNE LOCALE - AL'])]
df_ref_structure = df_ref_structure[df_ref_structure['n_structure'] != 1]

df_ref_structure.head()

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,Structure_de_rattachement,Rattachements_successifs,DT_de_rattachement,lon,lat
0,2615,ANTENNE LOCALE - AL,AL DE DELLE,90100.0,90033,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",90,2010-02-08 00:00:00,NaT,95 - DT DU TERRITOIRE DE BELFORT,AL 2615,95 - DT DU TERRITOIRE DE BELFORT,7.000705,47.506725
1,2669,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43220.0,43087,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2669,48 - DT DE LA HAUTE LOIRE,4.346423,45.214392
2,2670,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43600.0,43224,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2670,48 - DT DE LA HAUTE LOIRE,4.235474,45.242445
3,2671,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43300.0,43112,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2671,48 - DT DE LA HAUTE LOIRE,3.495645,45.098285
4,2672,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43000.0,43157,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2672,48 - DT DE LA HAUTE LOIRE,3.879748,45.044677

In [12]:
df_ref_structure_DT = df_ref_structure[df_ref_structure['nom_structure'].str.contains('DT')].astype(str)
df_ref_structure_DT['n_structure'] = df_ref_structure['n_structure'].astype(int)

### 0.1 rattachement_court

In [13]:
rattachement_court = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU/edit?usp=sharing').worksheet('Feuille 1'))

## 1. PEGASS

In [14]:
df_ref_activite_benevole, df_pegass_activite, df_pegass_activite_seance, df_pegass_activite_seance_inscription,ref_structure1,df_rattachement_court,df_ref_action_groupe_action = import_tables_PEGASS(client)

##2. GAIA

In [15]:
df_gaia_rattachement_benevole = clean_gaia(client)

## 3. NOMINATION

In [16]:
df_ref_nomination, df_nomination = clean_nomination(client)

## 4. IMPACT

In [17]:
df_ref_impact, df_impact = clean_impact(client)

## 5. Données financières

In [18]:
financier = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c')

In [19]:
dt_ul_ant_prod = get_as_dataframe(financier.worksheet('DT-UL-Ant_Prod'), skiprows=3, evaluate_formulas=True)

In [20]:
dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute, dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute = import_clean_donnees_financieres(financier,df_ref_structure,mapping_df)

Financier DPS & FGP

In [21]:
financier_DPS = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/145xeh1LkmYzTSW2zeAwHqmLyjmw_tobICHf-oXZmUFI/').worksheet('Base Smtw 03.03.25'))

In [22]:
financier_FGP = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13J2zfbmLTILtGYtE_sM-ME8B0pNEwBeGJ1Gg5vKLeOc/').worksheet('DT_Prod'))

## 6. Mobilité

In [23]:
mobilite = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1dvxT58WR-FqdT-4r-A9ca4vaA9FG7IXHJJaTbnjio8A/')

In [24]:
df_mobilite = filtres_mobilite(mobilite,mapping_df)

## 7. Données manuelles

### 7.1 OCR

In [25]:
df_OCR = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ccRoyPycFDwvQvacvmHjfE87LtnlzUgtoRbITkC0pVQ/').worksheet('Feuille 1'))

### 7.2 PST

In [26]:
df_PST = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1yifNna4Hsn5RihkRg50g9h1yKjuRjfolrjsWonEHnrQ').worksheet('Données'))

### 7.3 Déclenchements

In [27]:
df_declenchement = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1y9jehT5fStcEWCF0pxAP7BdiI62VY3JM_hQzFftbcZA').worksheet('Feuille 1'))

### 7.4 Redcall

In [28]:
df_redcall = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1EQzq0K8RY2Liyq-jtggX0bTlnOk9cwUTmf4t6c5_CiI').worksheet('structure-stats_2025-01-01_2025-12-31_min-1 (1)'))

### 7.5 CHAI CHU CMCC

In [29]:
df_CAICHUCMCC = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/12nZY2leRCMn71NGAEUUtA0Pes598gOfeufDStxSCcnY').worksheet('Toutes données'))

### 7.6 Conventions

In [30]:
df_conventions = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1OYSSkUhWwVpWne9EygH1EEz8EJnFjSeAOEpQQe9utiM').worksheet('Feuille 1'))

### 7.7 Textile

In [31]:
df_raw_Textile = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1QYuKZo5lVI0HN4BWtk0v7bVFY2a2p4c72a0gU0ltWac/').worksheet('Liste des PAV'))

df_raw_ProdResTextile = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1l7KMjiav3usmLVJIbE2uENfNQCeQuxVeU1h13Cep3qk/",sheet_name="Compil Détail",header_row=7)

✅ Chargement des données réalisées
    Sheet : Résultat Textile_2020-2024_V1_13 févr 2025
    Feuille  : Compil Détail (1338 lignes et 29 colonnes)

### 7.8 DOMIFA

In [32]:
df_domiciliation, df_rattachement_court = clean_domifa(client,df_ref_structure)

/content/Code-PAT/utils.py:197: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ref['nom_structure'] = df_ref['nom_structure'].fillna('').astype(str)
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

### 7.9 Alim

In [33]:
df_alim = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1bk_ktsT9hBPJS5EY70teq80NzOs_cm3JfrRkX4AYTF4/edit?gid=0#gid=0")

✅ Chargement des données réalisées
    Sheet : Liste U2A a jour - 21/01/2026
    Feuille 1 : Feuille 1 (628 lignes et 10 colonnes)

### 7.10 Adherent

In [35]:
df_adherent = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1hsk3Xp2IrwnUs59sgWjhT9E9vEsw4TN2WT3nKejlBOE/edit?usp=drive_link")

✅ Chargement des données réalisées
    Sheet : exportAdherents (1) (1)
    Feuille 1 : exportAdherents (1) (1).csv (48300 lignes et 25 colonnes)

### 7.11 Préparation

In [36]:
df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions, df_raw_Textile, df_raw_ProdResTextile = clean_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement, df_redcall, df_CAICHUCMCC, df_conventions, df_raw_Textile, df_raw_ProdResTextile)
df_alim = clean_alim(df_alim)
df_adherent = clean_adherent(df_adherent)

Point d'apport possible :  ['Boutique - La Boutique' 'Conteneur' 'Vestiaire' 'Boutique  - Mobile'
 'Autres' 'Boutique - Bébé' 'Boutique - Chez Henry' 'Ressourcerie CRi'
 'Boutique - Recylcerie / Meuble' 'Déchetterie' 'conteneur']
Unique values in 'Année de l'adhésion du contact': [2025]
Data type of 'Année de l'adhésion du contact': int64
Taille du DataFrame après suppression des doublons : (47424, 4)

/content/Code-PAT/scripts_data/manuelles.py:119: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['Grand Total', 'Exercice']] = df[['Grand Total', 'Exercice']].fillna(0)
/content/Code-PAT/scripts_data/manuelles.py:185: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Département"] = df["Département"].str.replace(
/content/Code-PAT/scripts_data/manuelles.py:228: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Departement"] = df["Departement"].str.replace(
/content/Code-PAT/scripts_data/manuelles.py:253: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[colonnes_oui_non] = df[colonnes_oui_non].applymap(
/content/Code-PAT/scripts_data/manuelles.py:253: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[colonnes_oui_non] = df[colonnes_oui_non].applymap(
/content/Code-PAT/scripts_data/manuelles.py:258: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Dispositifs_d_urgence Nb_conventions_operateurs'] = (
/content/Code-PAT/scripts_data/adherent.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_adherent["Année de l'adhésion du contact"] = pd.to_numeric(df_adherent["Année de l'adhésion du contact"], errors='coerce')

## 8. Maraudes

In [37]:
df_nb_personnes_rencontrees_sigma, df_Nb_maraudes_SIGMA, df_maraude, df_rattachement_court = clean_maraudes(client)

## 9. Base Contact

In [38]:
df_formation_session_resultat = clean_base_contact(client)

# FUSION DES TABLES

## 1. Fusion NOMINATION

In [39]:
df_NOMINATION = fusion_nomination(df_nomination, df_ref_nomination)

## 2. Fusion IMPACT

In [40]:
df_IMPACT = fusion_impact(df_impact, df_ref_impact)

Nombre de lignes après filtre 2025 : 369424

## 3. Fusion Données financières

### 3.1 Fusion des tables

In [41]:
df_financier_DT, df_financier_DT_UL = fusion_donnees_financieres(dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute,dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute, df_ref_structure)

### 3.2 Vérifications

In [42]:
verifier_colonne_structure(df_financier_DT, "DT_de_rattachement", df_ref_structure)

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [43]:
verifier_colonne_structure(df_financier_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## 4. Fusion DOMIFA

In [44]:
df_domiciliation = pd.merge(df_domiciliation, df_rattachement_court, on='n_structure', how="left") #a conserver dans le code principal

# Calcul des indicateurs

## PEGASS

In [45]:
pegass_output = calcul_PEGASS_indicateurs(df_ref_structure,
    ref_structure1,
    df_ref_action_groupe_action,
    df_ref_activite_benevole,
    df_pegass_activite,
    df_pegass_activite_seance,
    df_pegass_activite_seance_inscription,
    df_rattachement_court
)

## GAIA

In [46]:
nb_benevoles = indicateurs_gaia(df_gaia_rattachement_benevole)
nb_nvx_benevoles = indicateurs_gaia_nvx(df_gaia_rattachement_benevole)
nb_benevoles_DT = indicateurs_gaia_DT(nb_benevoles,rattachement_court)
nb_nvx_benevoles_DT = indicateurs_gaia_nvx_DT(nb_nvx_benevoles, rattachement_court)

Nombre de structures agrégées : 943
Nombre total de bénévoles uniques : 98624
Nombre de structures agrégées : 828
Nombre total de nouveaux bénévoles uniques : 21039
Nombre de structures agrégées : 108
Nombre total de bénévoles uniques DT : 96959
Nombre de structures agrégées : 106
Nombre total de nouveaux bénévoles uniques DT : 20727

## NOMINATION

- RTAEO & RLAEO
- RTOCR & RLOCR

In [47]:
referents_AEO = indicateurs_nomination_AEO(df_NOMINATION, annee=2025)
referents_OCR = indicateurs_nomination_OCR(df_NOMINATION, annee=2025)
referents_AEO_DT = indicateurs_nominationAEO_DT(referents_AEO, rattachement_court)
referents_OCR_DT = indicateurs_nominationOCR_DT(referents_OCR, rattachement_court)

Nombre de structures agrégées : 6
Nombre total de responsables AEO : 6
Nombre de structures agrégées : 20
Nombre total de responsables OCR : 21
Nombre de structures agrégées : 4
Nombre total de responsables AEO DT : 6
Nombre de structures agrégées : 15
Nombre total de responsables OCR DT : 21

## IMPACT

- Nombre d'agréments territoriaux (Dispos d'urgence)
- Nombre de personnes prises en charge (Dispos d'urgence)

In [48]:
IMPACT_ppc = indicateurs_impact_ppc(df_IMPACT)
IMPACT_agrementAB = indicateurs_impact_agrementAB(df_IMPACT)
IMPACT_agrementDPS = indicateurs_impact_agrementDPS(df_IMPACT)
IMPACT_ppc_DT = indicateurs_IMPACTppc_DT(IMPACT_ppc, rattachement_court)
IMPACT_agrementAB_DT = indicateurs_IMPACTagrementAB_DT(IMPACT_agrementAB, rattachement_court)
IMPACT_agrementDPS_DT = indicateurs_IMPACTagrementDPS_DT(IMPACT_agrementDPS, rattachement_court)

Nombre de lignes après filtre urgences : 1157
Nombre de structures agrégées : 108
Somme totale Dispositifs d'urgence - Nb personnes prises en charge : 15418
Nombre de structures agrégées : 74
Somme totale agréments AB : 0
Nombre de structures agrégées : 47
Somme totale agréments DPS : 0
Nombre de structures agrégées : 60
Somme totale personnes prises en charge DT : 15418
Nombre de structures agrégées : 57
Somme totale agréments AB DT : 0
Nombre de structures agrégées : 37
Somme totale agréments DPS DT: 0

/content/Code-PAT/scripts_data/impact.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (
/content/Code-PAT/scripts_data/impact.py:147: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (
/content/Code-PAT/scripts_data/impact.py:187: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (

## Financier DPS & FGP

In [49]:
df_Secours_ProduitsDPS = indicateur_financier_DPS(financier_DPS, df_ref_structure)
df_financier_DPS_DT = financier_DPS_DT(df_Secours_ProduitsDPS, rattachement_court)
df_financier_FGP = indicateur_financier_FGP(financier_FGP, df_ref_structure)
df_inancier_FGP_DT = financier_FGP_DT(df_financier_FGP, rattachement_court)

🔎 Vérification de la colonne 'libelle' et mapping associé 'n_structure'
   ✅ Mapping réalisé avec succès.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

🔎 Vérification de la colonne 'Nom Structure' et mapping associé 'n_structure'
   ✅ Mapping réalisé avec succès.

## Mobilité


Indicateurs qui nécessitent seulement les données mobilité :

- Nb de structures menant une activité AEO/AAD mobile
- Nombre de personnes accompagnées par des dispositifs AEO/AAD mobiles
<br>
Indicateurs qui nécessitent une fusion avec données AEO/AAD :

- Nombre de bénévoles impliqués dans les activités AEO ou AAD
- Nombre de bénévoles impliqués dans les activités AEO ou AAD

In [50]:
df_mobilite_DT = indicateurs_mobilite(df_mobilite, df_ref_structure, 'DT_de_rattachement')
df_mobilite_DT_UL = indicateurs_mobilite(df_mobilite, df_ref_structure, 'n_structure')

In [51]:
verifier_colonne_structure(df_mobilite_DT, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [52]:
verifier_colonne_structure(df_mobilite_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## Données manuelles

In [53]:
df_OCR_Nb_deployees, df_Dispositifs_d_urgence_PST, df_declenchement3, df_redcall2, df_CAICHUCMCC_VF, df_conventions2, df_raw_Textile, df_raw_ProdResTextile = indicateurs_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions, df_raw_Textile, df_raw_ProdResTextile, df_ref_structure)

Nb_OCR_DT,RedCall_DT = OCR_RedCall_DT(df_OCR_Nb_deployees, df_redcall2, rattachement_court)
df_Textile_DT, df_Textile_financier_DT = TEXTILE_DT(df_raw_Textile, df_raw_ProdResTextile, rattachement_court)

# ALIM
df_alim_U2A_sans_doublons, df_alim_epicerie_sociale, df_alim_accueil_alimentaire, df_alim_crsr = indicateurs_alim(df_alim, df_ref_structure)
df_alim_U2A_DT, df_alim_epicerie_sociale_DT, df_alim_accueil_alimentaire_DT, df_alim_crsr_DT = indicateurs_alim_DT(df_alim_U2A_sans_doublons, df_alim_epicerie_sociale, df_alim_accueil_alimentaire, df_alim_crsr, rattachement_court)

# ADHERENT
df_adherent = indicateurs_adherent(df_adherent, df_ref_structure)
df_adherent_DT = indicateurs_adherent_DT(df_adherent, rattachement_court)

# DOMIFA
df_personnes_domiciliees_struct, df_personnes_domiciliees_DT = indicateurs_domifa(df_domiciliation)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

🔎 Vérification de la colonne 'libelle' et mapping associé 'n_structure'
   ✅ Mapping réalisé avec succès.

/content/Code-PAT/scripts_data/manuelles.py:561: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Textile Produit_2024'] = df['Textile Produit_2024'].str.replace(r"\s+", "", regex=True)
/content/Code-PAT/scripts_data/manuelles.py:562: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Textile Produit_2024'] = df['Textile Produit_2024'].str.replace("-", "")
/content/Code-PAT/scripts_data/manuelles.py:563: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Textile Resultat_2024'] = df['Textile Resultat_2024'].str.replace(r"\s+", "", regex=True)
/content/Code-PAT/scripts_data/manuelles.py:564: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Textile Resultat_2024'] = df['Textile Resultat_2024'].str.replace("-", "")

In [54]:
verifier_colonne_structure(df_OCR_Nb_deployees, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Dispositifs_d_urgence_PST, "n_structure", df_ref_structure)
verifier_colonne_structure(df_declenchement3, "n_structure", df_ref_structure)
verifier_colonne_structure(df_redcall2, "n_structure", df_ref_structure)
verifier_colonne_structure(df_CAICHUCMCC_VF, "n_structure", df_ref_structure)
verifier_colonne_structure(df_conventions2, "n_structure", df_ref_structure)

# DOMIFA

verificiation_domifa(df_domiciliation, df_personnes_domiciliees_struct,df_personnes_domiciliees_DT,df_ref_structure,df_rattachement_court)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'Structure' et mapping associé 'n_structure'
   ✅ Mapping réalisé avec succès.
OK ✅ : sommes égales (30833) entre table struct[AEO Nb_personnes_domiciliees_crf] et table source[AEO Nb_personnes_domiciliees_crf]
OK ✅ : sommes égales (30833) entre table struct[AEO Nb_personnes_domiciliees_crf] et table source[AEO Nb_personnes_domiciliees_crf]

## Maraudes

In [55]:
df_Nb_maraudes_SIGMA

,maraude_id_fk,maraude_structure_id_fk,maraude_statut,maraude_date_debut,maraude_date_fin
0,2705541,1060,FINISHED,2025-01-01,2025-01-01
8,2632965,609,FINISHED,2025-01-01,2025-01-01
9,2673723,619,FINISHED,2025-01-01,2025-01-01
15,2663007,829,FINISHED,2025-01-01,2025-01-01
19,2615558,623,FINISHED,2025-01-01,2025-01-01
...,...,...,...,...,...
116130,2887306,4065,FINISHED,2025-04-30,2025-04-30
116279,2887251,4065,FINISHED,2025-03-17,2025-03-17
116309,3287327,4065,FINISHED,2025-01-06,2025-01-06
116391,3292636,83,FINISHED,2025-12-28,2025-12-28
116421,3287244,930,FINISHED,2025-12-27,2025-12-27

In [56]:
df_nb_personnes_rencontrees_sigma

,maraude_id_fk,maraude_structure_id_fk,maraude_statut,maraude_date_debut,maraude_date_fin,maraude_rencontre_beneficiaire_id_fk,maraude_rencontre_contact_realise,maraude_rencontre_typologie,maraude_rencontre_nb_hommes,maraude_rencontre_nb_femmes,maraude_rencontre_nb_transgenres,maraude_rencontre_nb_mineurs,maraude_rencontre_nb_inconnus
0,2705541,1060,FINISHED,2025-01-01,2025-01-01,396621,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
1,2705541,1060,FINISHED,2025-01-01,2025-01-01,396622,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
2,2705541,1060,FINISHED,2025-01-01,2025-01-01,396623,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
3,2705541,1060,FINISHED,2025-01-01,2025-01-01,396624,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
4,2705541,1060,FINISHED,2025-01-01,2025-01-01,396625,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...
116435,3022193,83,FINISHED,2025-08-26,2025-08-26,518108,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
116436,2132747,893,FINISHED,2025-10-07,2025-10-07,518109,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
116437,2132747,893,FINISHED,2025-10-07,2025-10-07,518112,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
116438,2132747,893,FINISHED,2025-10-07,2025-10-07,518116,Oui,individu,<NA>,<NA>,<NA>,<NA>,<NA>
116439,2132747,893,FINISHED,2025-10-07,2025-10-07,<NA>,Oui,groupe,2,0,0,0,0

In [57]:
df_Nb_maraudes_SIGMA,df_Nb_maraudes_SIGMA_DT, df_nb_personnes_rencontrees_SIGMA, df_nb_personnes_rencontrees_SIGMA_DT, df_max_nb_personnes, df_max_nb_personnes_struct = indicateurs_maraude(df_nb_personnes_rencontrees_sigma, df_Nb_maraudes_SIGMA,df_rattachement_court)
#verification_maraude(df_ref_structure,df_Nb_maraudes_SIGMA,df_Nb_maraudes_SIGMA_DT, df_nb_personnes_rencontrees_sigma, df_nb_personnes_rencontrees_SIGMA,df_nb_personnes_rencontrees_SIGMA_DT,df_maraude)

## Base contact

In [58]:
# Indicateurs
indicateurs_base_contact, indicateurs_base_contact_DT = indicateurs_base_contact(df_formation_session_resultat,df_ref_structure)

# Création du DataFrame final

La liste de tous les dataframes à fusionner sur df_ref_structure

In [128]:
indicateurs_base_contact_DT = indicateurs_base_contact_DT[indicateurs_base_contact_DT['n_structure'] != '']

In [129]:
liste_df_a_fusionner_toutes_structures = [nb_benevoles,nb_nvx_benevoles,referents_AEO,referents_OCR, IMPACT_ppc, IMPACT_agrementAB, IMPACT_agrementDPS,
                                          df_mobilite_DT_UL,df_OCR_Nb_deployees, df_Dispositifs_d_urgence_PST, df_declenchement3, df_redcall2,
                                          df_CAICHUCMCC_VF, df_conventions2,df_raw_Textile, df_alim_U2A_sans_doublons, df_alim_epicerie_sociale,
                                          df_alim_accueil_alimentaire, df_alim_crsr, df_adherent, df_personnes_domiciliees_struct, df_Nb_maraudes_SIGMA,
                                          df_nb_personnes_rencontrees_SIGMA, df_max_nb_personnes_struct, indicateurs_base_contact,
                                          df_financier_DT_UL,df_Secours_ProduitsDPS,df_financier_FGP, df_raw_ProdResTextile,
                                          pegass_output['Indics_pegass_struct']]

liste_df_a_fusionner_DT = [nb_benevoles_DT,nb_nvx_benevoles_DT,referents_AEO_DT,referents_OCR_DT,
                           IMPACT_ppc_DT, IMPACT_agrementAB_DT, IMPACT_agrementDPS_DT,df_mobilite_DT,Nb_OCR_DT,RedCall_DT,df_Textile_DT,
                           df_alim_U2A_DT, df_alim_epicerie_sociale_DT, df_alim_accueil_alimentaire_DT, df_alim_crsr_DT, df_adherent_DT,
                           df_personnes_domiciliees_DT, df_nb_personnes_rencontrees_SIGMA_DT,df_Nb_maraudes_SIGMA_DT, indicateurs_base_contact_DT,
                           df_financier_DT,df_financier_DPS_DT,df_inancier_FGP_DT, df_Textile_financier_DT,pegass_output['Indics_pegass_DT']]

In [130]:
for i,df in enumerate(liste_df_a_fusionner_toutes_structures):
  if type(df) != type(df_ref_structure):
    display(df)
    liste_df_a_fusionner_toutes_structures[i] = liste_df_a_fusionner_toutes_structures[i].to_frame()
  if len(liste_df_a_fusionner_toutes_structures[i].columns) < 2:
    liste_df_a_fusionner_toutes_structures[i] = liste_df_a_fusionner_toutes_structures[i].reset_index()

In [131]:
for i,df in enumerate(liste_df_a_fusionner_DT):
  if type(df) != type(df_ref_structure):
    display(df)
    liste_df_a_fusionner_DT[i] = liste_df_a_fusionner_DT[i].to_frame()
  if len(liste_df_a_fusionner_DT[i].columns) < 2:
    liste_df_a_fusionner_DT[i] = liste_df_a_fusionner_DT[i].reset_index()

DT_de_rattachement
17 - DT DES BOUCHES DU RHONE         1
26 - DT DE LA COTE D'OR              2
33 - DT D'EURE ET LOIR               4
34 - DT DU FINISTERE                 1
35 - DT DU GARD                      2
3667 - DT DE ST BARTHELEMY           1
38 - DT DE LA GIRONDE                2
3966 - DT DES VOSGES                12
3971 - DT DES COTES D'ARMOR          2
42 - DT D'INDRE ET LOIRE             1
4394 - DT DE HAUTE SAONE             1
48 - DT DE LA HAUTE LOIRE            1
52 - DT DU LOT ET GARONNE            1
54 - DT DU MAINE ET LOIRE            2
59 - DT DE MEURTHE ET MOSELLE        1
61 - DT DU MORBIHAN                  1
69 - DT DES PYRENEES ATLANTIQUES     1
74 - DT DU RHONE                     3
79 - DT DE LA HAUTE SAVOIE          10
82 - DT DE LA SEINE ET MARNE         1
83 - DT DES YVELINES                 3
86 - DT DU TARN                      3
Name: OCR Nb_deployees, dtype: int64

DT_de_rattachement
10 - DT DES ALPES MARITIMES         Oui
100 - DT DU VAL D'OISE              Oui
104 - DT DE NOUVELLE CALEDONIE      Oui
11 - DT DE L'ARDECHE                Oui
12 - DT DES ARDENNES                Oui
                                   ...
94 - DT DE L'YONNE                  Oui
95 - DT DU TERRITOIRE DE BELFORT    Oui
96 - DT DE L'ESSONNE                Oui
97 - DT DES HAUTS DE SEINE          Oui
99 - DT DU VAL DE MARNE             Oui
Name: Dispositifs_d_urgence Utilisation_RedCall, Length: 98, dtype: object

DT_de_rattachement
10 - DT DES ALPES MARITIMES         11
100 - DT DU VAL D'OISE              13
104 - DT DE NOUVELLE CALEDONIE       6
11 - DT DE L'ARDECHE                 9
12 - DT DES ARDENNES                 2
                                    ..
94 - DT DE L'YONNE                   8
95 - DT DU TERRITOIRE DE BELFORT     3
96 - DT DE L'ESSONNE                13
97 - DT DES HAUTS DE SEINE          13
99 - DT DU VAL DE MARNE             14
Name: Textile Nb_dispositifs, Length: 104, dtype: int64

DT_de_rattachement
10 - DT DES ALPES MARITIMES         226266.0
100 - DT DU VAL D'OISE              162236.0
102 - DT DE LA GUADELOUPE             2693.0
103 - DT DE LA MARTINIQUE            35758.0
104 - DT DE NOUVELLE CALEDONIE           0.0
                                      ...
94 - DT DE L'YONNE                   32909.0
95 - DT DU TERRITOIRE DE BELFORT     13258.0
96 - DT DE L'ESSONNE                124772.0
97 - DT DES HAUTS DE SEINE           77892.0
99 - DT DU VAL DE MARNE             161571.0
Name: Secours Produits_DPS_2025, Length: 107, dtype: float64

DT_de_rattachement
10 - DT DES ALPES MARITIMES         1679851.25
100 - DT DU VAL D'OISE              1493196.98
102 - DT DE LA GUADELOUPE            190848.28
103 - DT DE LA MARTINIQUE            190189.97
104 - DT DE NOUVELLE CALEDONIE      1136238.00
                                       ...
94 - DT DE L'YONNE                   489487.34
95 - DT DU TERRITOIRE DE BELFORT     371153.13
96 - DT DE L'ESSONNE                1636929.31
97 - DT DES HAUTS DE SEINE          3568821.35
99 - DT DU VAL DE MARNE             1235949.97
Name: Formation_grand_public Produits_2025, Length: 106, dtype: float64

In [132]:
for i,df in enumerate(liste_df_a_fusionner_toutes_structures):
  if 'n_structure' not in df.columns:
    print(i)
    display(df)

In [133]:
for i,df in enumerate(liste_df_a_fusionner_DT):
  if 'n_structure' not in df.columns:
    print(i)
    display(df)
    if 'DT_de_rattachement' in df.columns:
      liste_df_a_fusionner_DT[i] = liste_df_a_fusionner_DT[i].rename(columns={'DT_de_rattachement': 'n_structure'})

  if liste_df_a_fusionner_DT[i]['n_structure'].dtype == 'object':
    # 2️⃣ Vérifier s’il y a au moins une valeur contenant des lettres
    contient_lettres = liste_df_a_fusionner_DT[i]['n_structure'].astype(str).str.contains(r'[A-Za-z]', na=False).any()
    if contient_lettres:
      print(i)
      display(liste_df_a_fusionner_DT[i]['n_structure'])
      liste_df_a_fusionner_DT[i]['n_structure'] = liste_df_a_fusionner_DT[i]['n_structure'].apply(keep_integer).astype(int)

0

                   DT_de_rattachement  Structure Nb_Benevoles
0         10 - DT DES ALPES MARITIMES                    1717
1              100 - DT DU VAL D'OISE                    1036
2           102 - DT DE LA GUADELOUPE                     690
3           103 - DT DE LA MARTINIQUE                     465
4      104 - DT DE NOUVELLE CALEDONIE                     428
..                                ...                     ...
103                94 - DT DE L'YONNE                     517
104  95 - DT DU TERRITOIRE DE BELFORT                     126
105              96 - DT DE L'ESSONNE                    1472
106        97 - DT DES HAUTS DE SEINE                    3899
107           99 - DT DU VAL DE MARNE                    1817

[108 rows x 2 columns]

0

0           10 - DT DES ALPES MARITIMES
1                100 - DT DU VAL D'OISE
2             102 - DT DE LA GUADELOUPE
3             103 - DT DE LA MARTINIQUE
4        104 - DT DE NOUVELLE CALEDONIE
                     ...
103                  94 - DT DE L'YONNE
104    95 - DT DU TERRITOIRE DE BELFORT
105                96 - DT DE L'ESSONNE
106          97 - DT DES HAUTS DE SEINE
107             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 108, dtype: object

1

                   DT_de_rattachement  Structure Nb_nvx_Benevoles_2025
0         10 - DT DES ALPES MARITIMES                              209
1              100 - DT DU VAL D'OISE                              193
2           102 - DT DE LA GUADELOUPE                               60
3           103 - DT DE LA MARTINIQUE                               88
4      104 - DT DE NOUVELLE CALEDONIE                              104
..                                ...                              ...
101                94 - DT DE L'YONNE                              109
102  95 - DT DU TERRITOIRE DE BELFORT                               13
103              96 - DT DE L'ESSONNE                              427
104        97 - DT DES HAUTS DE SEINE                              646
105           99 - DT DU VAL DE MARNE                              336

[106 rows x 2 columns]

1

0           10 - DT DES ALPES MARITIMES
1                100 - DT DU VAL D'OISE
2             102 - DT DE LA GUADELOUPE
3             103 - DT DE LA MARTINIQUE
4        104 - DT DE NOUVELLE CALEDONIE
                     ...
101                  94 - DT DE L'YONNE
102    95 - DT DU TERRITOIRE DE BELFORT
103                96 - DT DE L'ESSONNE
104          97 - DT DES HAUTS DE SEINE
105             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 106, dtype: object

2

     DT_de_rattachement  AEO Nb_responsables
0  34 - DT DU FINISTERE                    1
1       64 - DT DU NORD                    1
2      80 - DT DE PARIS                    1
3  83 - DT DES YVELINES                    3

2

0    34 - DT DU FINISTERE
1         64 - DT DU NORD
2        80 - DT DE PARIS
3    83 - DT DES YVELINES
Name: n_structure, dtype: object

3

              DT_de_rattachement  OCR Nb_referents
0      103 - DT DE LA MARTINIQUE                 1
1            18 - DT DU CALVADOS                 1
2           34 - DT DU FINISTERE                 1
3        3959 - DT DE LA REUNION                 2
4         3986 - DT DE LA SAVOIE                 1
5       42 - DT D'INDRE ET LOIRE                 1
6       4394 - DT DE HAUTE SAONE                 1
7                44 - DT DU JURA                 2
8               74 - DT DU RHONE                 1
9      76 - DT DE SAONE ET LOIRE                 2
10    79 - DT DE LA HAUTE SAVOIE                 1
11              80 - DT DE PARIS                 2
12  81 - DT DE LA SEINE MARITIME                 1
13          83 - DT DES YVELINES                 3
14          96 - DT DE L'ESSONNE                 1

3

0        103 - DT DE LA MARTINIQUE
1              18 - DT DU CALVADOS
2             34 - DT DU FINISTERE
3          3959 - DT DE LA REUNION
4           3986 - DT DE LA SAVOIE
5         42 - DT D'INDRE ET LOIRE
6         4394 - DT DE HAUTE SAONE
7                  44 - DT DU JURA
8                 74 - DT DU RHONE
9        76 - DT DE SAONE ET LOIRE
10      79 - DT DE LA HAUTE SAVOIE
11                80 - DT DE PARIS
12    81 - DT DE LA SEINE MARITIME
13            83 - DT DES YVELINES
14            96 - DT DE L'ESSONNE
Name: n_structure, dtype: object

4

,DT_de_rattachement,Dispositifs_d_urgence Nb_personnes_prises_charge
0,10 - DT DES ALPES MARITIMES,40
1,100 - DT DU VAL D'OISE,126
2,12 - DT DES ARDENNES,38
3,15 - DT DE L'AUDE,0
4,17 - DT DES BOUCHES DU RHONE,0
5,18 - DT DU CALVADOS,222
6,20 - DT DE LA CHARENTE,23
7,23 - DT DE LA CORREZE,0
8,26 - DT DE LA COTE D'OR,0
9,31 - DT DE LA DROME,0
10,33 - DT D'EURE ET LOIR,1000
11,35 - DT DU GARD,32
12,37 - DT DU GERS,1573
13,38 - DT DE LA GIRONDE,0
14,39 - DT DE L'HERAULT,345
15,3959 - DT DE LA REUNION,54
16,3968 - DT DE LA DORDOGNE,49
17,3969 - DT DES HAUTES PYRENEES,37
18,3971 - DT DES COTES D'ARMOR,72
19,3986 - DT DE LA SAVOIE,1507
20,3997 - DT DES ALPES DE HAUTE PROVENCE,0
21,4017 - DT DU VAR,31
22,42 - DT D'INDRE ET LOIRE,1312
23,43 - DT DE L'ISERE,67
24,4394 - DT DE HAUTE SAONE,0
25,44 - DT DU JURA,0
26,4631 - DT DE SEINE SAINT DENIS,51
27,4649 - DT DE LA MEUSE,0
28,47 - DT DE LA LOIRE,0
29,49 - DT DE LA LOIRE ATLANTIQUE,57
30,50 - DT DU LOIRET,1466
31,52 - DT DU LOT ET GARONNE,427
32,54 - DT DU MAINE ET LOIRE,28
33,55 - DT DE LA MANCHE,133
34,57 - DT DE LA HAUTE MARNE,391
35,59 - DT DE MEURTHE ET MOSELLE,17
36,61 - DT DU MORBIHAN,0
37,62 - DT DE LA MOSELLE,42
38,63 - DT DE LA NIEVRE,0
39,64 - DT DU NORD,220
40,67 - DT DU PAS DE CALAIS,143
41,72 - DT DU BAS RHIN,418
42,73 - DT DU HAUT RHIN,15
43,76 - DT DE SAONE ET LOIRE,10
44,77 - DT DE LA SARTHE,1
45,80 - DT DE PARIS,642
46,81 - DT DE LA SEINE MARITIME,2141
47,82 - DT DE LA SEINE ET MARNE,34
48,83 - DT DES YVELINES,248
49,85 - DT DE LA SOMME,818
50,86 - DT DU TARN,1
51,87 - DT DU TARN ET GARONNE,3
52,89 - DT DU VAUCLUSE,78
53,90 - DT DE VENDEE,0
54,92 - DT DE LA HAUTE VIENNE,0
55,94 - DT DE L'YONNE,65
56,95 - DT DU TERRITOIRE DE BELFORT,429
57,96 - DT DE L'ESSONNE,144
58,97 - DT DES HAUTS DE SEINE,203
59,99 - DT DU VAL DE MARNE,665

4

0               10 - DT DES ALPES MARITIMES
1                    100 - DT DU VAL D'OISE
2                      12 - DT DES ARDENNES
3                         15 - DT DE L'AUDE
4              17 - DT DES BOUCHES DU RHONE
5                       18 - DT DU CALVADOS
6                    20 - DT DE LA CHARENTE
7                     23 - DT DE LA CORREZE
8                   26 - DT DE LA COTE D'OR
9                       31 - DT DE LA DROME
10                   33 - DT D'EURE ET LOIR
11                          35 - DT DU GARD
12                          37 - DT DU GERS
13                    38 - DT DE LA GIRONDE
14                     39 - DT DE L'HERAULT
15                  3959 - DT DE LA REUNION
16                 3968 - DT DE LA DORDOGNE
17            3969 - DT DES HAUTES PYRENEES
18              3971 - DT DES COTES D'ARMOR
19                   3986 - DT DE LA SAVOIE
20    3997 - DT DES ALPES DE HAUTE PROVENCE
21                         4017 - DT DU VAR
22                 42 - DT D'INDRE ET LOIRE
23                       43 - DT DE L'ISERE
24                 4394 - DT DE HAUTE SAONE
25                          44 - DT DU JURA
26           4631 - DT DE SEINE SAINT DENIS
27                    4649 - DT DE LA MEUSE
28                      47 - DT DE LA LOIRE
29           49 - DT DE LA LOIRE ATLANTIQUE
30                        50 - DT DU LOIRET
31                52 - DT DU LOT ET GARONNE
32                54 - DT DU MAINE ET LOIRE
33                     55 - DT DE LA MANCHE
34                57 - DT DE LA HAUTE MARNE
35            59 - DT DE MEURTHE ET MOSELLE
36                      61 - DT DU MORBIHAN
37                    62 - DT DE LA MOSELLE
38                     63 - DT DE LA NIEVRE
39                          64 - DT DU NORD
40                 67 - DT DU PAS DE CALAIS
41                      72 - DT DU BAS RHIN
42                     73 - DT DU HAUT RHIN
43                76 - DT DE SAONE ET LOIRE
44                     77 - DT DE LA SARTHE
45                         80 - DT DE PARIS
46             81 - DT DE LA SEINE MARITIME
47             82 - DT DE LA SEINE ET MARNE
48                     83 - DT DES YVELINES
49                      85 - DT DE LA SOMME
50                          86 - DT DU TARN
51               87 - DT DU TARN ET GARONNE
52                      89 - DT DU VAUCLUSE
53                        90 - DT DE VENDEE
54               92 - DT DE LA HAUTE VIENNE
55                       94 - DT DE L'YONNE
56         95 - DT DU TERRITOIRE DE BELFORT
57                     96 - DT DE L'ESSONNE
58               97 - DT DES HAUTS DE SEINE
59                  99 - DT DU VAL DE MARNE
Name: n_structure, dtype: object

5

                       DT_de_rattachement Dispositifs_d_urgence Nb_agrements
0             10 - DT DES ALPES MARITIMES                                  0
1                  100 - DT DU VAL D'OISE                                  0
2               102 - DT DE LA GUADELOUPE                                  0
3                    12 - DT DES ARDENNES                                  0
4                       15 - DT DE L'AUDE                                  0
5            17 - DT DES BOUCHES DU RHONE                                  0
6                     18 - DT DU CALVADOS                                  0
7                  20 - DT DE LA CHARENTE                                  0
8                   23 - DT DE LA CORREZE                                  0
9                  2570 - DT DE LA GUYANE                                  0
10                26 - DT DE LA COTE D'OR                                  0
11                    31 - DT DE LA DROME                                  0
12                 33 - DT D'EURE ET LOIR                                  0
13                        37 - DT DU GERS                                  0
14                  38 - DT DE LA GIRONDE                                  0
15                   39 - DT DE L'HERAULT                                  0
16                3959 - DT DE LA REUNION                                  0
17               3968 - DT DE LA DORDOGNE                                  0
18          3969 - DT DES HAUTES PYRENEES                                  0
19            3971 - DT DES COTES D'ARMOR                                  0
20                 3986 - DT DE LA SAVOIE                                  0
21  3997 - DT DES ALPES DE HAUTE PROVENCE                                  0
22                       4017 - DT DU VAR                                  0
23               42 - DT D'INDRE ET LOIRE                                  0
24               4394 - DT DE HAUTE SAONE                                  0
25                 4395 - DT DE L'AVEYRON                                  0
26                        44 - DT DU JURA                                  0
27         4631 - DT DE SEINE SAINT DENIS                                  0
28                  4649 - DT DE LA MEUSE                                  0
29                    47 - DT DE LA LOIRE                                  0
30         49 - DT DE LA LOIRE ATLANTIQUE                                  0
31                      50 - DT DU LOIRET                                  0
32              54 - DT DU MAINE ET LOIRE                                  0
33                   55 - DT DE LA MANCHE                                  0
34              57 - DT DE LA HAUTE MARNE                                  0
35          59 - DT DE MEURTHE ET MOSELLE                                  0
36                    61 - DT DU MORBIHAN                                  0
37                  62 - DT DE LA MOSELLE                                  0
38                   63 - DT DE LA NIEVRE                                  0
39                        64 - DT DU NORD                                  0
40                    72 - DT DU BAS RHIN                                  0
41                   73 - DT DU HAUT RHIN                                  0
42              76 - DT DE SAONE ET LOIRE                                  0
43                   77 - DT DE LA SARTHE                                  0
44                       80 - DT DE PARIS                                  0
45           81 - DT DE LA SEINE MARITIME                                  0
46                   83 - DT DES YVELINES                                  0
47                    85 - DT DE LA SOMME                                  0
48                        86 - DT DU TARN                                  0
49             87 - DT DU TARN ET GARONNE                                  0
50                    89 - DT DU VAUCLUSE                                  0
51                      90 - DT DE VENDEE                                  0
52             92 - DT DE LA HAUTE VIENNE                                  0
53                     94 - DT DE L'YONNE                                  0
54       95 - DT DU TERRITOIRE DE BELFORT                                  0
55             97 - DT DES HAUTS DE SEINE                                  0
56                99 - DT DU VAL DE MARNE                                  0

5

0               10 - DT DES ALPES MARITIMES
1                    100 - DT DU VAL D'OISE
2                 102 - DT DE LA GUADELOUPE
3                      12 - DT DES ARDENNES
4                         15 - DT DE L'AUDE
5              17 - DT DES BOUCHES DU RHONE
6                       18 - DT DU CALVADOS
7                    20 - DT DE LA CHARENTE
8                     23 - DT DE LA CORREZE
9                    2570 - DT DE LA GUYANE
10                  26 - DT DE LA COTE D'OR
11                      31 - DT DE LA DROME
12                   33 - DT D'EURE ET LOIR
13                          37 - DT DU GERS
14                    38 - DT DE LA GIRONDE
15                     39 - DT DE L'HERAULT
16                  3959 - DT DE LA REUNION
17                 3968 - DT DE LA DORDOGNE
18            3969 - DT DES HAUTES PYRENEES
19              3971 - DT DES COTES D'ARMOR
20                   3986 - DT DE LA SAVOIE
21    3997 - DT DES ALPES DE HAUTE PROVENCE
22                         4017 - DT DU VAR
23                 42 - DT D'INDRE ET LOIRE
24                 4394 - DT DE HAUTE SAONE
25                   4395 - DT DE L'AVEYRON
26                          44 - DT DU JURA
27           4631 - DT DE SEINE SAINT DENIS
28                    4649 - DT DE LA MEUSE
29                      47 - DT DE LA LOIRE
30           49 - DT DE LA LOIRE ATLANTIQUE
31                        50 - DT DU LOIRET
32                54 - DT DU MAINE ET LOIRE
33                     55 - DT DE LA MANCHE
34                57 - DT DE LA HAUTE MARNE
35            59 - DT DE MEURTHE ET MOSELLE
36                      61 - DT DU MORBIHAN
37                    62 - DT DE LA MOSELLE
38                     63 - DT DE LA NIEVRE
39                          64 - DT DU NORD
40                      72 - DT DU BAS RHIN
41                     73 - DT DU HAUT RHIN
42                76 - DT DE SAONE ET LOIRE
43                     77 - DT DE LA SARTHE
44                         80 - DT DE PARIS
45             81 - DT DE LA SEINE MARITIME
46                     83 - DT DES YVELINES
47                      85 - DT DE LA SOMME
48                          86 - DT DU TARN
49               87 - DT DU TARN ET GARONNE
50                      89 - DT DU VAUCLUSE
51                        90 - DT DE VENDEE
52               92 - DT DE LA HAUTE VIENNE
53                       94 - DT DE L'YONNE
54         95 - DT DU TERRITOIRE DE BELFORT
55               97 - DT DES HAUTS DE SEINE
56                  99 - DT DU VAL DE MARNE
Name: n_structure, dtype: object

6

                       DT_de_rattachement Secours Nb_agrements_DPS_2025
0               102 - DT DE LA GUADELOUPE                             0
1                    12 - DT DES ARDENNES                             0
2            17 - DT DES BOUCHES DU RHONE                             0
3                  2570 - DT DE LA GUYANE                             0
4                 26 - DT DE LA COTE D'OR                             0
5                  33 - DT D'EURE ET LOIR                             0
6                    39 - DT DE L'HERAULT                             0
7                 3959 - DT DE LA REUNION                             0
8                3968 - DT DE LA DORDOGNE                             0
9                  3986 - DT DE LA SAVOIE                             0
10  3997 - DT DES ALPES DE HAUTE PROVENCE                             0
11                       4017 - DT DU VAR                             0
12               42 - DT D'INDRE ET LOIRE                             0
13               4394 - DT DE HAUTE SAONE                             0
14                 4395 - DT DE L'AVEYRON                             0
15         4631 - DT DE SEINE SAINT DENIS                             0
16                    47 - DT DE LA LOIRE                             0
17                      50 - DT DU LOIRET                             0
18              54 - DT DU MAINE ET LOIRE                             0
19                   55 - DT DE LA MANCHE                             0
20          59 - DT DE MEURTHE ET MOSELLE                             0
21                  62 - DT DE LA MOSELLE                             0
22                    72 - DT DU BAS RHIN                             0
23                   73 - DT DU HAUT RHIN                             0
24              76 - DT DE SAONE ET LOIRE                             0
25                   77 - DT DE LA SARTHE                             0
26                       80 - DT DE PARIS                             0
27           81 - DT DE LA SEINE MARITIME                             0
28                   83 - DT DES YVELINES                             0
29                    85 - DT DE LA SOMME                             0
30                        86 - DT DU TARN                             0
31             87 - DT DU TARN ET GARONNE                             0
32                    89 - DT DU VAUCLUSE                             0
33                     94 - DT DE L'YONNE                             0
34       95 - DT DU TERRITOIRE DE BELFORT                             0
35             97 - DT DES HAUTS DE SEINE                             0
36                99 - DT DU VAL DE MARNE                             0

6

0                 102 - DT DE LA GUADELOUPE
1                      12 - DT DES ARDENNES
2              17 - DT DES BOUCHES DU RHONE
3                    2570 - DT DE LA GUYANE
4                   26 - DT DE LA COTE D'OR
5                    33 - DT D'EURE ET LOIR
6                      39 - DT DE L'HERAULT
7                   3959 - DT DE LA REUNION
8                  3968 - DT DE LA DORDOGNE
9                    3986 - DT DE LA SAVOIE
10    3997 - DT DES ALPES DE HAUTE PROVENCE
11                         4017 - DT DU VAR
12                 42 - DT D'INDRE ET LOIRE
13                 4394 - DT DE HAUTE SAONE
14                   4395 - DT DE L'AVEYRON
15           4631 - DT DE SEINE SAINT DENIS
16                      47 - DT DE LA LOIRE
17                        50 - DT DU LOIRET
18                54 - DT DU MAINE ET LOIRE
19                     55 - DT DE LA MANCHE
20            59 - DT DE MEURTHE ET MOSELLE
21                    62 - DT DE LA MOSELLE
22                      72 - DT DU BAS RHIN
23                     73 - DT DU HAUT RHIN
24                76 - DT DE SAONE ET LOIRE
25                     77 - DT DE LA SARTHE
26                         80 - DT DE PARIS
27             81 - DT DE LA SEINE MARITIME
28                     83 - DT DES YVELINES
29                      85 - DT DE LA SOMME
30                          86 - DT DU TARN
31               87 - DT DU TARN ET GARONNE
32                      89 - DT DU VAUCLUSE
33                       94 - DT DE L'YONNE
34         95 - DT DU TERRITOIRE DE BELFORT
35               97 - DT DES HAUTS DE SEINE
36                  99 - DT DU VAL DE MARNE
Name: n_structure, dtype: object

8

                  DT_de_rattachement  OCR Nb_deployees
0       17 - DT DES BOUCHES DU RHONE                 1
1            26 - DT DE LA COTE D'OR                 2
2             33 - DT D'EURE ET LOIR                 4
3               34 - DT DU FINISTERE                 1
4                    35 - DT DU GARD                 2
5         3667 - DT DE ST BARTHELEMY                 1
6              38 - DT DE LA GIRONDE                 2
7               3966 - DT DES VOSGES                12
8        3971 - DT DES COTES D'ARMOR                 2
9           42 - DT D'INDRE ET LOIRE                 1
10          4394 - DT DE HAUTE SAONE                 1
11         48 - DT DE LA HAUTE LOIRE                 1
12         52 - DT DU LOT ET GARONNE                 1
13         54 - DT DU MAINE ET LOIRE                 2
14     59 - DT DE MEURTHE ET MOSELLE                 1
15               61 - DT DU MORBIHAN                 1
16  69 - DT DES PYRENEES ATLANTIQUES                 1
17                  74 - DT DU RHONE                 3
18        79 - DT DE LA HAUTE SAVOIE                10
19      82 - DT DE LA SEINE ET MARNE                 1
20              83 - DT DES YVELINES                 3
21                   86 - DT DU TARN                 3

8

0         17 - DT DES BOUCHES DU RHONE
1              26 - DT DE LA COTE D'OR
2               33 - DT D'EURE ET LOIR
3                 34 - DT DU FINISTERE
4                      35 - DT DU GARD
5           3667 - DT DE ST BARTHELEMY
6                38 - DT DE LA GIRONDE
7                 3966 - DT DES VOSGES
8          3971 - DT DES COTES D'ARMOR
9             42 - DT D'INDRE ET LOIRE
10            4394 - DT DE HAUTE SAONE
11           48 - DT DE LA HAUTE LOIRE
12           52 - DT DU LOT ET GARONNE
13           54 - DT DU MAINE ET LOIRE
14       59 - DT DE MEURTHE ET MOSELLE
15                 61 - DT DU MORBIHAN
16    69 - DT DES PYRENEES ATLANTIQUES
17                    74 - DT DU RHONE
18          79 - DT DE LA HAUTE SAVOIE
19        82 - DT DE LA SEINE ET MARNE
20                83 - DT DES YVELINES
21                     86 - DT DU TARN
Name: n_structure, dtype: object

9

                  DT_de_rattachement Dispositifs_d_urgence Utilisation_RedCall
0        10 - DT DES ALPES MARITIMES                                       Oui
1             100 - DT DU VAL D'OISE                                       Oui
2     104 - DT DE NOUVELLE CALEDONIE                                       Oui
3               11 - DT DE L'ARDECHE                                       Oui
4               12 - DT DES ARDENNES                                       Oui
..                               ...                                       ...
93                94 - DT DE L'YONNE                                       Oui
94  95 - DT DU TERRITOIRE DE BELFORT                                       Oui
95              96 - DT DE L'ESSONNE                                       Oui
96        97 - DT DES HAUTS DE SEINE                                       Oui
97           99 - DT DU VAL DE MARNE                                       Oui

[98 rows x 2 columns]

9

0          10 - DT DES ALPES MARITIMES
1               100 - DT DU VAL D'OISE
2       104 - DT DE NOUVELLE CALEDONIE
3                 11 - DT DE L'ARDECHE
4                 12 - DT DES ARDENNES
                    ...
93                  94 - DT DE L'YONNE
94    95 - DT DU TERRITOIRE DE BELFORT
95                96 - DT DE L'ESSONNE
96          97 - DT DES HAUTS DE SEINE
97             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 98, dtype: object

10

                   DT_de_rattachement  Textile Nb_dispositifs
0         10 - DT DES ALPES MARITIMES                      11
1              100 - DT DU VAL D'OISE                      13
2      104 - DT DE NOUVELLE CALEDONIE                       6
3                11 - DT DE L'ARDECHE                       9
4                12 - DT DES ARDENNES                       2
..                                ...                     ...
99                 94 - DT DE L'YONNE                       8
100  95 - DT DU TERRITOIRE DE BELFORT                       3
101              96 - DT DE L'ESSONNE                      13
102        97 - DT DES HAUTS DE SEINE                      13
103           99 - DT DU VAL DE MARNE                      14

[104 rows x 2 columns]

10

0           10 - DT DES ALPES MARITIMES
1                100 - DT DU VAL D'OISE
2        104 - DT DE NOUVELLE CALEDONIE
3                  11 - DT DE L'ARDECHE
4                  12 - DT DES ARDENNES
                     ...
99                   94 - DT DE L'YONNE
100    95 - DT DU TERRITOIRE DE BELFORT
101                96 - DT DE L'ESSONNE
102          97 - DT DES HAUTS DE SEINE
103             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 104, dtype: object

11

                  DT_de_rattachement  Aide_alimentaire Nb_U2A
0        10 - DT DES ALPES MARITIMES                       14
1             100 - DT DU VAL D'OISE                        9
2          102 - DT DE LA GUADELOUPE                        1
3          103 - DT DE LA MARTINIQUE                        1
4               11 - DT DE L'ARDECHE                        3
..                               ...                      ...
94                94 - DT DE L'YONNE                        8
95  95 - DT DU TERRITOIRE DE BELFORT                        3
96              96 - DT DE L'ESSONNE                       10
97        97 - DT DES HAUTS DE SEINE                        5
98           99 - DT DU VAL DE MARNE                       10

[99 rows x 2 columns]

11

0          10 - DT DES ALPES MARITIMES
1               100 - DT DU VAL D'OISE
2            102 - DT DE LA GUADELOUPE
3            103 - DT DE LA MARTINIQUE
4                 11 - DT DE L'ARDECHE
                    ...
94                  94 - DT DE L'YONNE
95    95 - DT DU TERRITOIRE DE BELFORT
96                96 - DT DE L'ESSONNE
97          97 - DT DES HAUTS DE SEINE
98             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 99, dtype: object

12

                  DT_de_rattachement  Aide_alimentaire Nb_epiceries_sociales
0        10 - DT DES ALPES MARITIMES                                       1
1               1286 - DT DE MAYOTTE                                       1
2       17 - DT DES BOUCHES DU RHONE                                       3
3            26 - DT DE LA COTE D'OR                                       1
4                31 - DT DE LA DROME                                       3
5           36 - DT DE HAUTE GARONNE                                       2
6              38 - DT DE LA GIRONDE                                       1
7               39 - DT DE L'HERAULT                                       1
8        3971 - DT DES COTES D'ARMOR                                       2
9             3986 - DT DE LA SAVOIE                                       3
10          42 - DT D'INDRE ET LOIRE                                       8
11                43 - DT DE L'ISERE                                       1
12         4381 - DT DES DEUX SEVRES                                       6
13                   44 - DT DU JURA                                       2
14    4631 - DT DE SEINE SAINT DENIS                                       3
15                   5 - DT DE L'AIN                                       1
16         52 - DT DU LOT ET GARONNE                                       1
17         57 - DT DE LA HAUTE MARNE                                       1
18     59 - DT DE MEURTHE ET MOSELLE                                       1
19                 6 - DT DE L'AISNE                                       1
20             62 - DT DE LA MOSELLE                                       1
21          67 - DT DU PAS DE CALAIS                                       1
22  69 - DT DES PYRENEES ATLANTIQUES                                       3
23   71 - DT DES PYRENEES ORIENTALES                                       1
24              73 - DT DU HAUT RHIN                                       1
25                  74 - DT DU RHONE                                       1
26         76 - DT DE SAONE ET LOIRE                                       3
27        79 - DT DE LA HAUTE SAVOIE                                       2
28                  80 - DT DE PARIS                                       4
29      81 - DT DE LA SEINE MARITIME                                       1
30      82 - DT DE LA SEINE ET MARNE                                       1
31              83 - DT DES YVELINES                                       4
32        87 - DT DU TARN ET GARONNE                                       1
33               89 - DT DU VAUCLUSE                                       3
34              96 - DT DE L'ESSONNE                                       3
35        97 - DT DES HAUTS DE SEINE                                       3
36           99 - DT DU VAL DE MARNE                                       1

12

0          10 - DT DES ALPES MARITIMES
1                 1286 - DT DE MAYOTTE
2         17 - DT DES BOUCHES DU RHONE
3              26 - DT DE LA COTE D'OR
4                  31 - DT DE LA DROME
5             36 - DT DE HAUTE GARONNE
6                38 - DT DE LA GIRONDE
7                 39 - DT DE L'HERAULT
8          3971 - DT DES COTES D'ARMOR
9               3986 - DT DE LA SAVOIE
10            42 - DT D'INDRE ET LOIRE
11                  43 - DT DE L'ISERE
12           4381 - DT DES DEUX SEVRES
13                     44 - DT DU JURA
14      4631 - DT DE SEINE SAINT DENIS
15                     5 - DT DE L'AIN
16           52 - DT DU LOT ET GARONNE
17           57 - DT DE LA HAUTE MARNE
18       59 - DT DE MEURTHE ET MOSELLE
19                   6 - DT DE L'AISNE
20               62 - DT DE LA MOSELLE
21            67 - DT DU PAS DE CALAIS
22    69 - DT DES PYRENEES ATLANTIQUES
23     71 - DT DES PYRENEES ORIENTALES
24                73 - DT DU HAUT RHIN
25                    74 - DT DU RHONE
26           76 - DT DE SAONE ET LOIRE
27          79 - DT DE LA HAUTE SAVOIE
28                    80 - DT DE PARIS
29        81 - DT DE LA SEINE MARITIME
30        82 - DT DE LA SEINE ET MARNE
31                83 - DT DES YVELINES
32          87 - DT DU TARN ET GARONNE
33                 89 - DT DU VAUCLUSE
34                96 - DT DE L'ESSONNE
35          97 - DT DES HAUTS DE SEINE
36             99 - DT DU VAL DE MARNE
Name: n_structure, dtype: object

13

,DT_de_rattachement,Aide_alimentaire Nb_Centre_distribution_alimentaire
0,10 - DT DES ALPES MARITIMES,13
1,100 - DT DU VAL D'OISE,9
2,102 - DT DE LA GUADELOUPE,1
3,11 - DT DE L'ARDECHE,3
4,12 - DT DES ARDENNES,3
...,...,...
89,94 - DT DE L'YONNE,7
90,95 - DT DU TERRITOIRE DE BELFORT,3
91,96 - DT DE L'ESSONNE,6
92,97 - DT DES HAUTS DE SEINE,2
93,99 - DT DU VAL DE MARNE,9

13

0          10 - DT DES ALPES MARITIMES
1               100 - DT DU VAL D'OISE
2            102 - DT DE LA GUADELOUPE
3                 11 - DT DE L'ARDECHE
4                 12 - DT DES ARDENNES
                    ...
89                  94 - DT DE L'YONNE
90    95 - DT DU TERRITOIRE DE BELFORT
91                96 - DT DE L'ESSONNE
92          97 - DT DES HAUTS DE SEINE
93             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 94, dtype: object

14

                  DT_de_rattachement  Aide_alimentaire Nb_crsr
0          103 - DT DE LA MARTINIQUE                         1
1               1286 - DT DE MAYOTTE                         1
2                18 - DT DU CALVADOS                         1
3              23 - DT DE LA CORREZE                         1
4                   30 - DT DU DOUBS                         2
5                    37 - DT DU GERS                         1
6            3959 - DT DE LA REUNION                         2
7               3966 - DT DES VOSGES                         1
8           42 - DT D'INDRE ET LOIRE                         1
9                 43 - DT DE L'ISERE                         3
10          4394 - DT DE HAUTE SAONE                         1
11                   44 - DT DU JURA                         1
12                45 - DT DES LANDES                         1
13           46 - DT DU LOIR ET CHER                         1
14               47 - DT DE LA LOIRE                         5
15    49 - DT DE LA LOIRE ATLANTIQUE                         1
16                   5 - DT DE L'AIN                         2
17                 50 - DT DU LOIRET                         1
18                 6 - DT DE L'AISNE                         1
19               61 - DT DU MORBIHAN                         2
20                   64 - DT DU NORD                         1
21  69 - DT DES PYRENEES ATLANTIQUES                         1
22         76 - DT DE SAONE ET LOIRE                         1
23              83 - DT DES YVELINES                         1
24                   86 - DT DU TARN                         2
25               89 - DT DU VAUCLUSE                         1
26           9 - DT DES HAUTES ALPES                         1
27                94 - DT DE L'YONNE                         1
28              96 - DT DE L'ESSONNE                         1

14

0            103 - DT DE LA MARTINIQUE
1                 1286 - DT DE MAYOTTE
2                  18 - DT DU CALVADOS
3                23 - DT DE LA CORREZE
4                     30 - DT DU DOUBS
5                      37 - DT DU GERS
6              3959 - DT DE LA REUNION
7                 3966 - DT DES VOSGES
8             42 - DT D'INDRE ET LOIRE
9                   43 - DT DE L'ISERE
10            4394 - DT DE HAUTE SAONE
11                     44 - DT DU JURA
12                  45 - DT DES LANDES
13             46 - DT DU LOIR ET CHER
14                 47 - DT DE LA LOIRE
15      49 - DT DE LA LOIRE ATLANTIQUE
16                     5 - DT DE L'AIN
17                   50 - DT DU LOIRET
18                   6 - DT DE L'AISNE
19                 61 - DT DU MORBIHAN
20                     64 - DT DU NORD
21    69 - DT DES PYRENEES ATLANTIQUES
22           76 - DT DE SAONE ET LOIRE
23                83 - DT DES YVELINES
24                     86 - DT DU TARN
25                 89 - DT DU VAUCLUSE
26             9 - DT DES HAUTES ALPES
27                  94 - DT DE L'YONNE
28                96 - DT DE L'ESSONNE
Name: n_structure, dtype: object

15

                   DT_de_rattachement  Structure Nb_Adherents
0         10 - DT DES ALPES MARITIMES                     708
1              100 - DT DU VAL D'OISE                     646
2           102 - DT DE LA GUADELOUPE                     183
3           103 - DT DE LA MARTINIQUE                     279
4      104 - DT DE NOUVELLE CALEDONIE                     107
..                                ...                     ...
103                94 - DT DE L'YONNE                     300
104  95 - DT DU TERRITOIRE DE BELFORT                      79
105              96 - DT DE L'ESSONNE                     655
106        97 - DT DES HAUTS DE SEINE                    1915
107           99 - DT DU VAL DE MARNE                     894

[108 rows x 2 columns]

15

0           10 - DT DES ALPES MARITIMES
1                100 - DT DU VAL D'OISE
2             102 - DT DE LA GUADELOUPE
3             103 - DT DE LA MARTINIQUE
4        104 - DT DE NOUVELLE CALEDONIE
                     ...
103                  94 - DT DE L'YONNE
104    95 - DT DU TERRITOIRE DE BELFORT
105                96 - DT DE L'ESSONNE
106          97 - DT DES HAUTS DE SEINE
107             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 108, dtype: object

16

                  DT_de_rattachement  AEO Nb_personnes_domiciliees_crf
0             100 - DT DU VAL D'OISE                              1067
1                   30 - DT DU DOUBS                               133
2             33 - DT D'EURE ET LOIR                               864
3           36 - DT DE HAUTE GARONNE                             10116
4              38 - DT DE LA GIRONDE                                72
5       40 - DT DE L'ILLE ET VILAINE                              3342
6                    64 - DT DU NORD                              2404
7   69 - DT DES PYRENEES ATLANTIQUES                               224
8                72 - DT DU BAS RHIN                              3872
9               77 - DT DE LA SARTHE                              1350
10                  80 - DT DE PARIS                              1115
11              83 - DT DES YVELINES                              3328
12               89 - DT DU VAUCLUSE                               205
13              91 - DT DE LA VIENNE                              1356
14        97 - DT DES HAUTS DE SEINE                              1385

16

0               100 - DT DU VAL D'OISE
1                     30 - DT DU DOUBS
2               33 - DT D'EURE ET LOIR
3             36 - DT DE HAUTE GARONNE
4                38 - DT DE LA GIRONDE
5         40 - DT DE L'ILLE ET VILAINE
6                      64 - DT DU NORD
7     69 - DT DES PYRENEES ATLANTIQUES
8                  72 - DT DU BAS RHIN
9                 77 - DT DE LA SARTHE
10                    80 - DT DE PARIS
11                83 - DT DES YVELINES
12                 89 - DT DU VAUCLUSE
13                91 - DT DE LA VIENNE
14          97 - DT DES HAUTS DE SEINE
Name: n_structure, dtype: object

17

                  DT_de_rattachement  Maraude Nb_personnes_rencontrees
0        10 - DT DES ALPES MARITIMES                               137
1             100 - DT DU VAL D'OISE                               385
2               11 - DT DE L'ARDECHE                                90
3               12 - DT DES ARDENNES                               978
4                13 - DT DE L'ARIEGE                              3293
5       17 - DT DES BOUCHES DU RHONE                              2972
6            26 - DT DE LA COTE D'OR                              5458
7                31 - DT DE LA DROME                                38
8             33 - DT D'EURE ET LOIR                                86
9               34 - DT DU FINISTERE                             16402
10          36 - DT DE HAUTE GARONNE                               641
11                   37 - DT DU GERS                              1359
12             38 - DT DE LA GIRONDE                                 5
13              39 - DT DE L'HERAULT                                73
14           3959 - DT DE LA REUNION                              4257
15                 3970 - DT DU CHER                                 2
16       3971 - DT DES COTES D'ARMOR                              7760
17                41 - DT DE L'INDRE                              1556
18               4284 - DT DE L'ORNE                               145
19                43 - DT DE L'ISERE                               687
20         4381 - DT DES DEUX SEVRES                                69
21                   44 - DT DU JURA                               138
22                45 - DT DES LANDES                              1576
23           46 - DT DU LOIR ET CHER                               113
24    4631 - DT DE SEINE SAINT DENIS                               339
25                  4674 - DT DU LOT                              1824
26               47 - DT DE LA LOIRE                              1907
27    49 - DT DE LA LOIRE ATLANTIQUE                               100
28                   5 - DT DE L'AIN                              7988
29         52 - DT DU LOT ET GARONNE                                 8
30              55 - DT DE LA MANCHE                               447
31               56 - DT DE LA MARNE                              2341
32               61 - DT DU MORBIHAN                              3684
33                   64 - DT DU NORD                               667
34  69 - DT DES PYRENEES ATLANTIQUES                              1820
35              73 - DT DU HAUT RHIN                               926
36                  74 - DT DU RHONE                              1940
37         76 - DT DE SAONE ET LOIRE                              3834
38              77 - DT DE LA SARTHE                                 7
39        79 - DT DE LA HAUTE SAVOIE                               426
40                  80 - DT DE PARIS                              4624
41      81 - DT DE LA SEINE MARITIME                               148
42      82 - DT DE LA SEINE ET MARNE                              4518
43              83 - DT DES YVELINES                              6246
44           9 - DT DES HAUTES ALPES                               377
45                 90 - DT DE VENDEE                                 1
46              91 - DT DE LA VIENNE                              6517
47                94 - DT DE L'YONNE                               308
48  95 - DT DU TERRITOIRE DE BELFORT                               320
49              96 - DT DE L'ESSONNE                               994
50           99 - DT DU VAL DE MARNE                              1482

17

0          10 - DT DES ALPES MARITIMES
1               100 - DT DU VAL D'OISE
2                 11 - DT DE L'ARDECHE
3                 12 - DT DES ARDENNES
4                  13 - DT DE L'ARIEGE
5         17 - DT DES BOUCHES DU RHONE
6              26 - DT DE LA COTE D'OR
7                  31 - DT DE LA DROME
8               33 - DT D'EURE ET LOIR
9                 34 - DT DU FINISTERE
10            36 - DT DE HAUTE GARONNE
11                     37 - DT DU GERS
12               38 - DT DE LA GIRONDE
13                39 - DT DE L'HERAULT
14             3959 - DT DE LA REUNION
15                   3970 - DT DU CHER
16         3971 - DT DES COTES D'ARMOR
17                  41 - DT DE L'INDRE
18                 4284 - DT DE L'ORNE
19                  43 - DT DE L'ISERE
20           4381 - DT DES DEUX SEVRES
21                     44 - DT DU JURA
22                  45 - DT DES LANDES
23             46 - DT DU LOIR ET CHER
24      4631 - DT DE SEINE SAINT DENIS
25                    4674 - DT DU LOT
26                 47 - DT DE LA LOIRE
27      49 - DT DE LA LOIRE ATLANTIQUE
28                     5 - DT DE L'AIN
29           52 - DT DU LOT ET GARONNE
30                55 - DT DE LA MANCHE
31                 56 - DT DE LA MARNE
32                 61 - DT DU MORBIHAN
33                     64 - DT DU NORD
34    69 - DT DES PYRENEES ATLANTIQUES
35                73 - DT DU HAUT RHIN
36                    74 - DT DU RHONE
37           76 - DT DE SAONE ET LOIRE
38                77 - DT DE LA SARTHE
39          79 - DT DE LA HAUTE SAVOIE
40                    80 - DT DE PARIS
41        81 - DT DE LA SEINE MARITIME
42        82 - DT DE LA SEINE ET MARNE
43                83 - DT DES YVELINES
44             9 - DT DES HAUTES ALPES
45                   90 - DT DE VENDEE
46                91 - DT DE LA VIENNE
47                  94 - DT DE L'YONNE
48    95 - DT DU TERRITOIRE DE BELFORT
49                96 - DT DE L'ESSONNE
50             99 - DT DU VAL DE MARNE
Name: n_structure, dtype: object

18

                  DT_de_rattachement  Maraude Nb_maraudes_SIGMA
0        10 - DT DES ALPES MARITIMES                          5
1             100 - DT DU VAL D'OISE                         24
2               11 - DT DE L'ARDECHE                         37
3               12 - DT DES ARDENNES                        125
4                13 - DT DE L'ARIEGE                        233
5       17 - DT DES BOUCHES DU RHONE                        291
6            26 - DT DE LA COTE D'OR                        223
7                31 - DT DE LA DROME                          3
8             33 - DT D'EURE ET LOIR                         10
9               34 - DT DU FINISTERE                        415
10          36 - DT DE HAUTE GARONNE                        200
11                   37 - DT DU GERS                         38
12             38 - DT DE LA GIRONDE                          2
13              39 - DT DE L'HERAULT                         17
14           3959 - DT DE LA REUNION                        466
15              3966 - DT DES VOSGES                          1
16                 3970 - DT DU CHER                          3
17       3971 - DT DES COTES D'ARMOR                        314
18                41 - DT DE L'INDRE                         61
19               4284 - DT DE L'ORNE                         90
20                43 - DT DE L'ISERE                        103
21         4381 - DT DES DEUX SEVRES                          5
22                   44 - DT DU JURA                         50
23                45 - DT DES LANDES                         90
24           46 - DT DU LOIR ET CHER                         15
25    4631 - DT DE SEINE SAINT DENIS                         38
26                  4674 - DT DU LOT                        114
27               47 - DT DE LA LOIRE                         95
28    49 - DT DE LA LOIRE ATLANTIQUE                         84
29                   5 - DT DE L'AIN                        457
30         52 - DT DU LOT ET GARONNE                          6
31              55 - DT DE LA MANCHE                        114
32               56 - DT DE LA MARNE                        254
33               61 - DT DU MORBIHAN                        135
34                   64 - DT DU NORD                        174
35          67 - DT DU PAS DE CALAIS                         27
36  69 - DT DES PYRENEES ATLANTIQUES                        106
37              73 - DT DU HAUT RHIN                        120
38                  74 - DT DU RHONE                        255
39         76 - DT DE SAONE ET LOIRE                        188
40              77 - DT DE LA SARTHE                          1
41        79 - DT DE LA HAUTE SAVOIE                         36
42                  80 - DT DE PARIS                        723
43      81 - DT DE LA SEINE MARITIME                         44
44      82 - DT DE LA SEINE ET MARNE                        336
45              83 - DT DES YVELINES                        726
46           9 - DT DES HAUTES ALPES                         38
47                 90 - DT DE VENDEE                          3
48              91 - DT DE LA VIENNE                        345
49                94 - DT DE L'YONNE                         49
50  95 - DT DU TERRITOIRE DE BELFORT                         39
51              96 - DT DE L'ESSONNE                        216
52           99 - DT DU VAL DE MARNE                        335

18

0          10 - DT DES ALPES MARITIMES
1               100 - DT DU VAL D'OISE
2                 11 - DT DE L'ARDECHE
3                 12 - DT DES ARDENNES
4                  13 - DT DE L'ARIEGE
5         17 - DT DES BOUCHES DU RHONE
6              26 - DT DE LA COTE D'OR
7                  31 - DT DE LA DROME
8               33 - DT D'EURE ET LOIR
9                 34 - DT DU FINISTERE
10            36 - DT DE HAUTE GARONNE
11                     37 - DT DU GERS
12               38 - DT DE LA GIRONDE
13                39 - DT DE L'HERAULT
14             3959 - DT DE LA REUNION
15                3966 - DT DES VOSGES
16                   3970 - DT DU CHER
17         3971 - DT DES COTES D'ARMOR
18                  41 - DT DE L'INDRE
19                 4284 - DT DE L'ORNE
20                  43 - DT DE L'ISERE
21           4381 - DT DES DEUX SEVRES
22                     44 - DT DU JURA
23                  45 - DT DES LANDES
24             46 - DT DU LOIR ET CHER
25      4631 - DT DE SEINE SAINT DENIS
26                    4674 - DT DU LOT
27                 47 - DT DE LA LOIRE
28      49 - DT DE LA LOIRE ATLANTIQUE
29                     5 - DT DE L'AIN
30           52 - DT DU LOT ET GARONNE
31                55 - DT DE LA MANCHE
32                 56 - DT DE LA MARNE
33                 61 - DT DU MORBIHAN
34                     64 - DT DU NORD
35            67 - DT DU PAS DE CALAIS
36    69 - DT DES PYRENEES ATLANTIQUES
37                73 - DT DU HAUT RHIN
38                    74 - DT DU RHONE
39           76 - DT DE SAONE ET LOIRE
40                77 - DT DE LA SARTHE
41          79 - DT DE LA HAUTE SAVOIE
42                    80 - DT DE PARIS
43        81 - DT DE LA SEINE MARITIME
44        82 - DT DE LA SEINE ET MARNE
45                83 - DT DES YVELINES
46             9 - DT DES HAUTES ALPES
47                   90 - DT DE VENDEE
48                91 - DT DE LA VIENNE
49                  94 - DT DE L'YONNE
50    95 - DT DU TERRITOIRE DE BELFORT
51                96 - DT DE L'ESSONNE
52             99 - DT DU VAL DE MARNE
Name: n_structure, dtype: object

20

,DT_de_rattachement,n_dept,Financier Prod_2024,libelle_structure,Financier ResNet_2024,Financier ResCorrProd_2024,Financier TresoBrute_2024,Financier Mois_AvanceTreso_2024
0,95 - DT DU TERRITOIRE DE BELFORT,90,371153.13,DT - TERRITOIRE-DE-BELFORT,5174.82,0.013943,439146.13,13.890856
1,48 - DT DE LA HAUTE LOIRE,43,319290.45,DT - HAUTE-LOIRE,24919.92,0.078048,655591.68,26.174435
2,3970 - DT DU CHER,18,238379.24,DT - CHER,2797.52,0.011736,55989.64,3.640181
3,3965 - DT DE LA CORSE DU SUD,2A,146007.64,DT - CORSE-DU-SUD,10322.60,0.070699,125813.48,11.670411
4,3967 - DT DE LA HAUTE CORSE,2B,207120.51,DT - HAUTE-CORSE,4395.64,0.021223,372021.23,22.959576
...,...,...,...,...,...,...,...,...
103,92 - DT DE LA HAUTE VIENNE,87,360290.22,DT - HAUTE-VIENNE,-39555.42,-0.109788,727311.68,21.531738
104,94 - DT DE L'YONNE,89,489487.34,DT - YONNE,53515.15,0.109329,675805.08,19.342680
105,96 - DT DE L'ESSONNE,91,1636929.31,DT - ESSONNE,-10866.67,-0.006638,1547551.36,11.772285
106,97 - DT DES HAUTS DE SEINE,92,3568821.35,DT - HAUTS-DE-SEINE,460756.15,0.129106,7158583.91,26.185043
107,99 - DT DU VAL DE MARNE,94,1235949.97,DT - VAL-DE-MARNE,-152720.48,-0.123565,2653772.29,21.799823

20

0      95 - DT DU TERRITOIRE DE BELFORT
1             48 - DT DE LA HAUTE LOIRE
2                     3970 - DT DU CHER
3          3965 - DT DE LA CORSE DU SUD
4           3967 - DT DE LA HAUTE CORSE
                     ...
103          92 - DT DE LA HAUTE VIENNE
104                  94 - DT DE L'YONNE
105                96 - DT DE L'ESSONNE
106          97 - DT DES HAUTS DE SEINE
107             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 108, dtype: object

21

                   DT_de_rattachement  Secours Produits_DPS_2025
0         10 - DT DES ALPES MARITIMES                   226266.0
1              100 - DT DU VAL D'OISE                   162236.0
2           102 - DT DE LA GUADELOUPE                     2693.0
3           103 - DT DE LA MARTINIQUE                    35758.0
4      104 - DT DE NOUVELLE CALEDONIE                        0.0
..                                ...                        ...
102                94 - DT DE L'YONNE                    32909.0
103  95 - DT DU TERRITOIRE DE BELFORT                    13258.0
104              96 - DT DE L'ESSONNE                   124772.0
105        97 - DT DES HAUTS DE SEINE                    77892.0
106           99 - DT DU VAL DE MARNE                   161571.0

[107 rows x 2 columns]

21

0           10 - DT DES ALPES MARITIMES
1                100 - DT DU VAL D'OISE
2             102 - DT DE LA GUADELOUPE
3             103 - DT DE LA MARTINIQUE
4        104 - DT DE NOUVELLE CALEDONIE
                     ...
102                  94 - DT DE L'YONNE
103    95 - DT DU TERRITOIRE DE BELFORT
104                96 - DT DE L'ESSONNE
105          97 - DT DES HAUTS DE SEINE
106             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 107, dtype: object

22

                   DT_de_rattachement  Formation_grand_public Produits_2025
0         10 - DT DES ALPES MARITIMES                            1679851.25
1              100 - DT DU VAL D'OISE                            1493196.98
2           102 - DT DE LA GUADELOUPE                             190848.28
3           103 - DT DE LA MARTINIQUE                             190189.97
4      104 - DT DE NOUVELLE CALEDONIE                            1136238.00
..                                ...                                   ...
101                94 - DT DE L'YONNE                             489487.34
102  95 - DT DU TERRITOIRE DE BELFORT                             371153.13
103              96 - DT DE L'ESSONNE                            1636929.31
104        97 - DT DES HAUTS DE SEINE                            3568821.35
105           99 - DT DU VAL DE MARNE                            1235949.97

[106 rows x 2 columns]

22

0           10 - DT DES ALPES MARITIMES
1                100 - DT DU VAL D'OISE
2             102 - DT DE LA GUADELOUPE
3             103 - DT DE LA MARTINIQUE
4        104 - DT DE NOUVELLE CALEDONIE
                     ...
101                  94 - DT DE L'YONNE
102    95 - DT DU TERRITOIRE DE BELFORT
103                96 - DT DE L'ESSONNE
104          97 - DT DES HAUTS DE SEINE
105             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 106, dtype: object

23

,DT_de_rattachement,Textile Produit_2025,Textile Resultat_2025
0,10 - DT DES ALPES MARITIMES,355142,231825
1,100 - DT DU VAL D'OISE,63097,26759
2,102 - DT DE LA GUADELOUPE,,
3,103 - DT DE LA MARTINIQUE,11919,9017
4,104 - DT DE NOUVELLE CALEDONIE,,
...,...,...,...
102,94 - DT DE L'YONNE,115892,104838
103,95 - DT DU TERRITOIRE DE BELFORT,24674,22848
104,96 - DT DE L'ESSONNE,226087,122937
105,97 - DT DES HAUTS DE SEINE,332286,230258
106,99 - DT DU VAL DE MARNE,74434,51823

23

0           10 - DT DES ALPES MARITIMES
1                100 - DT DU VAL D'OISE
2             102 - DT DE LA GUADELOUPE
3             103 - DT DE LA MARTINIQUE
4        104 - DT DE NOUVELLE CALEDONIE
                     ...
102                  94 - DT DE L'YONNE
103    95 - DT DU TERRITOIRE DE BELFORT
104                96 - DT DE L'ESSONNE
105          97 - DT DES HAUTS DE SEINE
106             99 - DT DU VAL DE MARNE
Name: n_structure, Length: 107, dtype: object

In [134]:
liste_df_a_fusionner_DT[18] = liste_df_a_fusionner_DT[18][liste_df_a_fusionner_DT[18]['n_structure'] !='']

In [135]:
for i,df in enumerate(liste_df_a_fusionner_toutes_structures):
  if liste_df_a_fusionner_toutes_structures[i]['n_structure'].dtype != df_ref_structure['n_structure'].dtype:
    liste_df_a_fusionner_toutes_structures[i]['n_structure'] = liste_df_a_fusionner_toutes_structures[i]['n_structure'].astype(int)

for i,df in enumerate(liste_df_a_fusionner_DT):
  if liste_df_a_fusionner_DT[i]['n_structure'].dtype != df_ref_structure['n_structure'].dtype:
    liste_df_a_fusionner_DT[i]['n_structure'] = liste_df_a_fusionner_DT[i]['n_structure'].astype(int)

In [136]:
def merge_left_on_df1(df1, l, on):

    def safe_merge(left, right):
        # Supprime les colonnes déjà présentes (sauf la clé)
        cols_to_drop = [col for col in right.columns if col in left.columns and col != on]
        right_clean = right.drop(columns=cols_to_drop)

        return left.merge(right_clean, how='left', on=on)

    return reduce(safe_merge, l, df1)

In [137]:
def find_duplicates_in_list_of_dfs(dfs, column):
    """
    Pour chaque DataFrame dans une liste, trouve les doublons dans la colonne spécifiée.

    Args:
        dfs (list of pd.DataFrame): Liste de DataFrames à analyser
        column (str): Nom de la colonne sur laquelle chercher les doublons

    Returns:
        dict: Clé = index du DataFrame, Valeur = DataFrame des doublons
    """
    duplicates_dict = {}

    for i, df in enumerate(dfs):
        if column not in df.columns:
            print(f"⚠️ DataFrame {i} : la colonne '{column}' n'existe pas.")
            continue

        # Trouve les doublons
        df_duplicates = df[df.duplicated(subset=[column], keep=False)]

        if not df_duplicates.empty:
            duplicates_dict[i] = df_duplicates
            print(f"🔹 DataFrame {i} : {len(df_duplicates)} doublons trouvés dans '{column}'")
        else:
            print(f"✅ DataFrame {i} : aucun doublon dans '{column}'")

    return duplicates_dict

duplicates = find_duplicates_in_list_of_dfs(liste_df_a_fusionner_toutes_structures, column='n_structure')

✅ DataFrame 0 : aucun doublon dans 'n_structure'
✅ DataFrame 1 : aucun doublon dans 'n_structure'
✅ DataFrame 2 : aucun doublon dans 'n_structure'
✅ DataFrame 3 : aucun doublon dans 'n_structure'
✅ DataFrame 4 : aucun doublon dans 'n_structure'
✅ DataFrame 5 : aucun doublon dans 'n_structure'
✅ DataFrame 6 : aucun doublon dans 'n_structure'
✅ DataFrame 7 : aucun doublon dans 'n_structure'
✅ DataFrame 8 : aucun doublon dans 'n_structure'
✅ DataFrame 9 : aucun doublon dans 'n_structure'
✅ DataFrame 10 : aucun doublon dans 'n_structure'
✅ DataFrame 11 : aucun doublon dans 'n_structure'
✅ DataFrame 12 : aucun doublon dans 'n_structure'
✅ DataFrame 13 : aucun doublon dans 'n_structure'
✅ DataFrame 14 : aucun doublon dans 'n_structure'
✅ DataFrame 15 : aucun doublon dans 'n_structure'
✅ DataFrame 16 : aucun doublon dans 'n_structure'
✅ DataFrame 17 : aucun doublon dans 'n_structure'
✅ DataFrame 18 : aucun doublon dans 'n_structure'
✅ DataFrame 19 : aucun doublon dans 'n_structure'
✅ DataFrame 20 : aucun doublon dans 'n_structure'
✅ DataFrame 21 : aucun doublon dans 'n_structure'
✅ DataFrame 22 : aucun doublon dans 'n_structure'
✅ DataFrame 23 : aucun doublon dans 'n_structure'
✅ DataFrame 24 : aucun doublon dans 'n_structure'
✅ DataFrame 25 : aucun doublon dans 'n_structure'
✅ DataFrame 26 : aucun doublon dans 'n_structure'
🔹 DataFrame 27 : 2 doublons trouvés dans 'n_structure'
✅ DataFrame 28 : aucun doublon dans 'n_structure'
✅ DataFrame 29 : aucun doublon dans 'n_structure'

In [157]:
liste_df_a_fusionner_toutes_structures[27][liste_df_a_fusionner_toutes_structures[27]['n_structure'] == 50]

    n_structure  Formation_grand_public Produits_2025
6            50                            1182357.83
29           50                             863119.62

In [138]:
colonnes_indicateurs = ['n_structure',
    "Financier Prod_2024",
    "Financier ResNet_2024",
    "Financier ResCorrProd_2024",
    "Financier TresoBrute_2024",
    "Financier Mois_AvanceTreso_2024",
    "Structure Nb_Benevoles",
    "Structure Nb_nvx_Benevoles_2025",
    "Structure Nb_Adherents",
    "Structure Nb_formes_TCAS_2025",
    "Structure Nb_formes_CRB_2025",
    "Structure Taux_formation_CRB",
    "Structure Nb_nvx_formes_CRB_2025",
    "Structure Nb_formateurs_CRB_2025",
    "Dispositifs_d_urgence Structures_menant_activite_TCAU",
    "Dispositifs_d_urgence Structures_menant_activite_PSP",
    "Dispositifs_d_urgence Structures_menant_activite_GQS",
    "Dispositifs_d_urgence Nb_conventions_prefecture",
    "Dispositifs_d_urgence Nb_conventions_operateurs",
    "Dispositifs_d_urgence Nb_agrements",
    "Dispositifs_d_urgence Nb_declenchements",
    "Dispositifs_d_urgence Nb_operations",
    "Dispositifs_d_urgence Nb_personnes_prises_charge",
    "Dispositifs_d_urgence Nb_lots_CAI",
    "Dispositifs_d_urgence Nb_lots_CHU",
    "Dispositifs_d_urgence Nb_lots_CMCC",
    "Dispositifs_d_urgence Utilisation_RedCall",
    "Dispositifs_d_urgence Utilisation_Minutis",
    "Dispositifs_d_urgence Nb_exercices",
    "Dispositifs_d_urgence PST",
    "Dispositifs_d_urgence Taux_formation_TCAU_2025",
    "Dispositifs_d_urgence Taux_formation_IPSP_2025",
    "Dispositifs_d_urgence Taux_formation_GQS_2025",
    "Dispositifs_d_urgence Taux_formation_TCEO_2025",
    "Dispositifs_d_urgence Taux_formation_IRR_2025",
    "Formation_grand_public Nb_FPSC",
    "Formation_grand_public Structures_menant_activite",
    "Formation_grand_public Produits_2025",
    "Formation_grand_public Nb_formes_PSC_2025",
    "Formation_grand_public Nb_sessions_PSC_2025",
    "Formation_grand_public Nb_FPSC",
    "Formation_grand_public Nb_formes_GQS_2025",
    "Formation_grand-public Nb_sessions_GQS_2025",
    "Formation_grand_public Nb_AGQS",
    "Formation_grand_public Nb_formes_IPSEN_2025",
    "Formation_grand-public Nb_sessions_IPSEN_2025",
    "Formation_grand_public Nb_FIPSEN",
    "Formation_grand_public Nb_formes_IPS_2025",
    "Formation_grand-public Nb_sessions_IPS_2025",
    "Formation_grand_public Nb_formes_PREVIC_2025",
    "Formation_grand-public Nb_sessions_PREVIC_2025",
    "Formation_grand_public Activite_Conso_Etat",
    "Formation_grand_public Activite_Conso_Non_Etat",
    "OCR Structures_menant_activite",
    "OCR Nb_deployees",
    "OCR Nb_referents",
    "nb_Maraude_Pegass",
    "Maraude Nb_maraudes_SIGMA",
    "Maraudes Structures_menant_activite",
    "Maraude Nb_benevoles_actifs",
    "Maraude Nb_benevoles_actifs_formes",
    "Maraude Nb_SOLIDAR",
    "Maraude Nb_SOLIDAR2020",
    "Maraude Nb_contacts",
    "Maraude Nb_personnes_rencontrees",
    "Secours Produits_DPS_2025",
    "Secours Structures_menant_activite",
    "Secours Nb_DPS_2025",
    "Secours Nb_agrements_DPS_2025",
    "Secours Taux_IS_actifs",
    "Secours Nb_PAPS_2025",
    "Secours Nb_DPS_PE_2025",
    "Secours Nb_DPS_ME_2025",
    "Secours Nb_DPS_GE_2025",
    "Secours Nb_PSE1",
    "Secours Nb_PSE2",
    "Secours Nb_CI",
    "Secours Taux_recy26_PSE1",
    "Secours Taux_recy26_PSE2",
    "Secours Taux_recy26_CI",
    "Secours Taux_ren25_PSE1",
    "Secours Taux_ren25_PSE2",
    "Secours Taux_ren25_CI",
    "Secours Nb_sessions_PSE",
    "Secours Nb_sessions_CI",
    "Secours Nb_sessions_FPSE",
    "AEO Structures_menant_activite",
    "AEO Structure_activite_fixe",
    "AEO Structure_activite_mobile",
    "AEO Nb_benevoles_actifs",
    "AEO Nb_responsables",
    "AEO Nb_AAD",
    "AEO Nb_FAAD",
    "AEO Nb_PA_AEO_AAD",
    "AEO Nb_personnes_domiciliees_crf",
    "AEO Nb_PA_dispos_mobiles",
    "Aide_alimentaire Nb_U2A",
    "Aide_alimentaire Nb_Centre_distribution_alimentaire",
    "Aide_alimentaire Nb_epiceries_sociales",
    "Aide_alimentaire Nb_crsr",
    "Textile Nb_dispositifs",
    "Textile Produit_2025",
    "Textile Resultat_2025"
]

In [139]:
cleaned_dfs = []

for i, df in enumerate(liste_df_a_fusionner_toutes_structures):
    # Colonnes à supprimer
    cols_to_drop = [col for col in liste_df_a_fusionner_toutes_structures[i].columns if col not in colonnes_indicateurs]

    if cols_to_drop:
        print(f"🧹 DataFrame {i} : suppression des colonnes {cols_to_drop}")

    df_clean = liste_df_a_fusionner_toutes_structures[i].drop(columns=cols_to_drop)

    liste_df_a_fusionner_toutes_structures[i] = df_clean

🧹 DataFrame 9 : suppression des colonnes ['Territoire', 'PST constitué', 'Nom structure DT', 'N° Département', 'nom_structure']
🧹 DataFrame 10 : suppression des colonnes ['Département', 'Etablissements', 'Exercice', 'Fonctionnement', 'Opérations', 'Grand Total', 'Unnamed: 6', 'n_dept', 'DT', 'nom_structure']
🧹 DataFrame 11 : suppression des colonnes ['Nom de la structure', 'nom_structure']
🧹 DataFrame 12 : suppression des colonnes ['Dépt', 'Région', 'Département', 'nom_structure']
🧹 DataFrame 13 : suppression des colonnes ['Departement', 'nom_structure']
🧹 DataFrame 20 : suppression des colonnes ['DT_de_rattachement']
🧹 DataFrame 21 : suppression des colonnes ['DT_de_rattachement']
🧹 DataFrame 22 : suppression des colonnes ['DT_de_rattachement']
🧹 DataFrame 23 : suppression des colonnes ['DT_de_rattachement']
🧹 DataFrame 24 : suppression des colonnes ['Dispositifs_d_urgence Nb_formes_TCAU_2025', 'Dispositifs_d_urgence Nb_formes_TCEO_2025', 'Dispositifs_d_urgence Nb_formes_IPSP_2025', 'Dispositifs_d_urgence Nb_formes_IRR_2025', 'Dispositifs_d_urgence Nb_formes_GQS_2025']
🧹 DataFrame 25 : suppression des colonnes ['libelle_structure']
🧹 DataFrame 27 : suppression des colonnes ['nom_structure']

In [140]:
for i, df in enumerate(liste_df_a_fusionner_DT):
    # Colonnes à supprimer
    cols_to_drop = [col for col in liste_df_a_fusionner_DT[i].columns if col not in colonnes_indicateurs]

    if cols_to_drop:
        print(f"🧹 DataFrame {i} : suppression des colonnes {cols_to_drop}")

    df_clean = liste_df_a_fusionner_DT[i].drop(columns=cols_to_drop)

    liste_df_a_fusionner_DT[i] = df_clean

🧹 DataFrame 19 : suppression des colonnes ['Dispositifs_d_urgence Nb_formes_TCAU_2025', 'Dispositifs_d_urgence Nb_formes_TCEO_2025', 'Dispositifs_d_urgence Nb_formes_IPSP_2025', 'Dispositifs_d_urgence Nb_formes_IRR_2025', 'Dispositifs_d_urgence Nb_formes_GQS_2025']
🧹 DataFrame 20 : suppression des colonnes ['n_dept', 'libelle_structure']
🧹 DataFrame 24 : suppression des colonnes ['DT_de_rattachement']

In [141]:
mask = df_ref_structure['n_structure'].to_list()

for i, df in enumerate(liste_df_a_fusionner_toutes_structures):
    # Colonnes à supprimer
    liste_df_a_fusionner_toutes_structures[i] = liste_df_a_fusionner_toutes_structures[i][liste_df_a_fusionner_toutes_structures[i]['n_structure'].isin(mask)]


for i, df in enumerate(liste_df_a_fusionner_DT):
    # Colonnes à supprimer
    liste_df_a_fusionner_DT[i] = liste_df_a_fusionner_DT[i][liste_df_a_fusionner_DT[i]['n_structure'].isin(mask)]

In [142]:
all_data  = merge_left_on_df1(df_ref_structure, liste_df_a_fusionner_toutes_structures, on = 'n_structure')
all_data_DT  = merge_left_on_df1(df_ref_structure_DT, liste_df_a_fusionner_DT, on = 'n_structure')

In [143]:
from typing import List, Dict
import pandas as pd

def check_sums_against_final(
    df_final: pd.DataFrame,
    list_of_dfs: List[pd.DataFrame],
    key_col: str = "n_structure",
    dropna: bool = True,
    atol: float = 0.0,
    rtol: float = 0.0
) -> List[Dict]:

    report = []

    for i, df in enumerate(list_of_dfs):
        print(f"\n🔎 Vérification DataFrame {i}")

        cols_to_check = [col for col in df.columns if col != key_col]

        for col in cols_to_check:

            if col not in df_final.columns:
                print(f"   ⚠️ Colonne '{col}' absente du df_final → ignorée")
                continue

            try:
                result, ok = check_same_col_sum(
                    df_left=df,
                    df_right=df_final,
                    col=col,
                    dropna=dropna,
                    atol=atol,
                    rtol=rtol
                )

                summary = {
                    "df_index": i,
                    "col": col,
                    "sum_df_individual": result["sum_df_left"],
                    "sum_df_final": result["sum_df_right"],
                    "atol": atol,
                    "rtol": rtol,
                    "ok": ok
                }

                report.append(summary)

                if ok:
                    print(
                        f"   ✅ '{col}' OK | "
                        f"individuel = {summary['sum_df_individual']} | "
                        f"final = {summary['sum_df_final']}"
                    )
                else:
                    print(
                        f"   ❌ '{col}' KO | "
                        f"individuel = {summary['sum_df_individual']} | "
                        f"final = {summary['sum_df_final']}"
                    )

            except Exception as e:
                print(f"   ⚠️ Erreur sur '{col}' : {e}")

    return report


report = check_sums_against_final(
    df_final=all_data,
    list_of_dfs=liste_df_a_fusionner_toutes_structures,
    key_col="n_structure",
    atol=1e-6
)

🔎 Vérification DataFrame 0
   ❌ 'Structure Nb_Benevoles' KO | individuel = 96959.0 | final = 97410.0

🔎 Vérification DataFrame 1
   ❌ 'Structure Nb_nvx_Benevoles_2025' KO | individuel = 20727.0 | final = 20814.0

🔎 Vérification DataFrame 2
   ✅ 'AEO Nb_responsables' OK | individuel = 6.0 | final = 6.0

🔎 Vérification DataFrame 3
   ✅ 'OCR Nb_referents' OK | individuel = 21.0 | final = 21.0

🔎 Vérification DataFrame 4
   ❌ 'Dispositifs_d_urgence Nb_personnes_prises_charge' KO | individuel = 15418.0 | final = 16884.0

🔎 Vérification DataFrame 5
   ✅ 'Dispositifs_d_urgence Nb_agrements' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 6
   ✅ 'Secours Nb_agrements_DPS_2025' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 7
   ❌ 'AEO Structure_activite_mobile' KO | individuel = 214.0 | final = 216.0
   ❌ 'AEO Nb_PA_dispos_mobiles' KO | individuel = 17179.0 | final = 17364.0

🔎 Vérification DataFrame 8
   ✅ 'OCR Nb_deployees' OK | individuel = 56.0 | final = 56.0

🔎 Vérification DataFrame 9
   ✅ 'Dispositifs_d_urgence PST' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 10
   ❌ 'Dispositifs_d_urgence Nb_declenchements' KO | individuel = 602.0 | final = 607.0

🔎 Vérification DataFrame 11
   ✅ 'Dispositifs_d_urgence Utilisation_RedCall' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 12
   ❌ 'Dispositifs_d_urgence Nb_lots_CAI' KO | individuel = 239.0 | final = 241.0
   ❌ 'Dispositifs_d_urgence Nb_lots_CHU' KO | individuel = 174.0 | final = 175.0
   ✅ 'Dispositifs_d_urgence Nb_lots_CMCC' OK | individuel = 281.0 | final = 281.0

🔎 Vérification DataFrame 13
   ✅ 'Dispositifs_d_urgence Nb_conventions_prefecture' OK | individuel = 0.0 | final = 0.0
   ❌ 'Dispositifs_d_urgence Nb_conventions_operateurs' KO | individuel = 334.0 | final = 340.0

🔎 Vérification DataFrame 14
   ❌ 'Textile Nb_dispositifs' KO | individuel = 895.0 | final = 902.0

🔎 Vérification DataFrame 15
   ❌ 'Aide_alimentaire Nb_U2A' KO | individuel = 627.0 | final = 630.0

🔎 Vérification DataFrame 16
   ✅ 'Aide_alimentaire Nb_epiceries_sociales' OK | individuel = 77.0 | final = 77.0

🔎 Vérification DataFrame 17
   ❌ 'Aide_alimentaire Nb_Centre_distribution_alimentaire' KO | individuel = 510.0 | final = 512.0

🔎 Vérification DataFrame 18
   ❌ 'Aide_alimentaire Nb_crsr' KO | individuel = 40.0 | final = 41.0

🔎 Vérification DataFrame 19
   ❌ 'Structure Nb_Adherents' KO | individuel = 47403.0 | final = 47567.0

🔎 Vérification DataFrame 20
   ✅ 'AEO Nb_personnes_domiciliees_crf' OK | individuel = 30833.0 | final = 30833.0

🔎 Vérification DataFrame 21
   ✅ 'Maraude Nb_maraudes_SIGMA' OK | individuel = 7879.0 | final = 7879.0

🔎 Vérification DataFrame 22
   ✅ 'Maraude Nb_contacts' OK | individuel = 127109.0 | final = 127109.0

🔎 Vérification DataFrame 23
   ✅ 'Maraude Nb_personnes_rencontrees' OK | individuel = 102013.0 | final = 102013.0

🔎 Vérification DataFrame 24
   ❌ 'Maraude Nb_SOLIDAR' KO | individuel = 8141.0 | final = 8234.0
   ❌ 'Maraude Nb_SOLIDAR2020' KO | individuel = 6221.0 | final = 6300.0
   ✅ 'AEO Nb_AAD' OK | individuel = 892.0 | final = 892.0
   ✅ 'AEO Nb_FAAD' OK | individuel = 0.0 | final = 0.0
   ❌ 'Formation_grand_public Nb_formes_PSC_2025' KO | individuel = 11900.0 | final = 12002.0
   ❌ 'Formation_grand_public Nb_formes_GQS_2025' KO | individuel = 75371.0 | final = 75765.0
   ❌ 'Formation_grand_public Nb_formes_IPS_2025' KO | individuel = 78440.0 | final = 78882.0
   ❌ 'Formation_grand_public Nb_formes_IPSEN_2025' KO | individuel = 8759.0 | final = 8778.0
   ❌ 'Structure Nb_formes_CRB_2025' KO | individuel = 3199.0 | final = 3200.0
   ✅ 'Structure Nb_formateurs_CRB_2025' OK | individuel = 44.0 | final = 44.0
   ❌ 'Structure Nb_formes_TCAS_2025' KO | individuel = 2141.0 | final = 2151.0
   ❌ 'Formation_grand_public Nb_sessions_PSC_2025' KO | individuel = 520.0 | final = 524.0
   ❌ 'Formation_grand-public Nb_sessions_GQS_2025' KO | individuel = 2153.0 | final = 2164.0
   ❌ 'Formation_grand-public Nb_sessions_IPS_2025' KO | individuel = 2219.0 | final = 2230.0
   ✅ 'Formation_grand-public Nb_sessions_IPSEN_2025' OK | individuel = 83.0 | final = 83.0
   ✅ 'Formation_grand-public Nb_sessions_PREVIC_2025' OK | individuel = 13.0 | final = 13.0
   ❌ 'Formation_grand_public Nb_FPSC' KO | individuel = 1471.0 | final = 1477.0
   ❌ 'Formation_grand_public Nb_AGQS' KO | individuel = 222.0 | final = 228.0
   ✅ 'Formation_grand_public Nb_FIPSEN' OK | individuel = 243.0 | final = 243.0
   ❌ 'Secours Nb_PSE1' KO | individuel = 4491.0 | final = 4526.0
   ❌ 'Secours Nb_PSE2' KO | individuel = 7610.0 | final = 7668.0
   ❌ 'Secours Nb_CI' KO | individuel = 1252.0 | final = 1263.0
   ❌ 'Secours Taux_recy26_PSE1' KO | individuel = 128.40206165998606 | final = 129.00671282277676
   ❌ 'Secours Taux_recy26_PSE2' KO | individuel = 129.9554138934856 | final = 130.34903091476218
   ❌ 'Secours Taux_recy26_CI' KO | individuel = 69.93818909847697 | final = 70.41644996804217
   ❌ 'Secours Taux_ren25_PSE1' KO | individuel = 33.68233111920409 | final = 33.98788667475965
   ❌ 'Secours Taux_ren25_PSE2' KO | individuel = 20.37038329256905 | final = 20.5229256654504
   ✅ 'Secours Taux_ren25_CI' OK | individuel = 0.11147186147186147 | final = 0.11147186147186147

🔎 Vérification DataFrame 25
   ❌ 'Financier Prod_2024' KO | individuel = 88893716.98 | final = 89428653.15
   ❌ 'Financier ResNet_2024' KO | individuel = 4610056.17 | final = 4679513.62
   ❌ 'Financier ResCorrProd_2024' KO | individuel = -37.858541662141995 | final = -37.72869916149375
   ✅ 'Financier TresoBrute_2024' OK | individuel = 112924889.39999999 | final = 112924889.4
   ✅ 'Financier Mois_AvanceTreso_2024' OK | individuel = 19621.90469935163 | final = 19621.904699351628

🔎 Vérification DataFrame 26
   ❌ 'Secours Produits_DPS_2025' KO | individuel = 8975398.0 | final = 9038794.0

🔎 Vérification DataFrame 27
   ✅ 'Formation_grand_public Produits_2025' OK | individuel = 91388923.98 | final = 91388923.98

🔎 Vérification DataFrame 28
   ❌ 'Textile Produit_2025' KO | individuel = 22573754.0 | final = 22769471.0
   ❌ 'Textile Resultat_2025' KO | individuel = 13470366.0 | final = 13521198.0

🔎 Vérification DataFrame 29
   ❌ 'nb_Maraude_Pegass' KO | individuel = 19392.0 | final = 19921.0
   ❌ 'Dispositifs_d_urgence Nb_operations' KO | individuel = 2442.0 | final = 2451.0
   ❌ 'Dispositifs_d_urgence Nb_exercices' KO | individuel = 269.0 | final = 272.0
   ✅ 'AEO Structure_activite_fixe' OK | individuel = 0.0 | final = 0.0

In [152]:
all_data[all_data['n_structure'].duplicated() == True]

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,...,Financier TresoBrute_2024,Financier Mois_AvanceTreso_2024,Secours Produits_DPS_2025,Formation_grand_public Produits_2025,Textile Produit_2025,Textile Resultat_2025,nb_Maraude_Pegass,Dispositifs_d_urgence Nb_operations,Dispositifs_d_urgence Nb_exercices,AEO Structure_activite_fixe
235,50,DELEGATION TERRITORIALE - DT,DT DU LOIRET,45650.0,45286,ST JEAN LE BLANC,"69 bis Rue DES ANGUIGNIS, 45650 ST JEAN LE BLANC",45,1986-12-10 00:00:00,NaT,...,NaN,NaN,63396.0,863119.62,195717,50832,529.0,9.0,3.0,NaN

In [144]:
report = check_sums_against_final(
  df_final=all_data_DT,
  list_of_dfs=liste_df_a_fusionner_DT,
  key_col="n_structure",
  atol=1e-6
  )

🔎 Vérification DataFrame 0
   ✅ 'Structure Nb_Benevoles' OK | individuel = 96959.0 | final = 96959.0

🔎 Vérification DataFrame 1
   ✅ 'Structure Nb_nvx_Benevoles_2025' OK | individuel = 20727.0 | final = 20727.0

🔎 Vérification DataFrame 2
   ✅ 'AEO Nb_responsables' OK | individuel = 6.0 | final = 6.0

🔎 Vérification DataFrame 3
   ✅ 'OCR Nb_referents' OK | individuel = 21.0 | final = 21.0

🔎 Vérification DataFrame 4
   ✅ 'Dispositifs_d_urgence Nb_personnes_prises_charge' OK | individuel = 15418.0 | final = 15418.0

🔎 Vérification DataFrame 5
   ✅ 'Dispositifs_d_urgence Nb_agrements' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 6
   ✅ 'Secours Nb_agrements_DPS_2025' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 7
   ✅ 'AEO Structure_activite_mobile' OK | individuel = 214.0 | final = 214.0
   ✅ 'AEO Nb_PA_dispos_mobiles' OK | individuel = 17179.0 | final = 17179.0

🔎 Vérification DataFrame 8
   ✅ 'OCR Nb_deployees' OK | individuel = 56.0 | final = 56.0

🔎 Vérification DataFrame 9
   ✅ 'Dispositifs_d_urgence Utilisation_RedCall' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 10
   ✅ 'Textile Nb_dispositifs' OK | individuel = 895.0 | final = 895.0

🔎 Vérification DataFrame 11
   ✅ 'Aide_alimentaire Nb_U2A' OK | individuel = 627.0 | final = 627.0

🔎 Vérification DataFrame 12
   ✅ 'Aide_alimentaire Nb_epiceries_sociales' OK | individuel = 77.0 | final = 77.0

🔎 Vérification DataFrame 13
   ✅ 'Aide_alimentaire Nb_Centre_distribution_alimentaire' OK | individuel = 510.0 | final = 510.0

🔎 Vérification DataFrame 14
   ✅ 'Aide_alimentaire Nb_crsr' OK | individuel = 40.0 | final = 40.0

🔎 Vérification DataFrame 15
   ✅ 'Structure Nb_Adherents' OK | individuel = 47403.0 | final = 47403.0

🔎 Vérification DataFrame 16
   ✅ 'AEO Nb_personnes_domiciliees_crf' OK | individuel = 30833.0 | final = 30833.0

🔎 Vérification DataFrame 17
   ✅ 'Maraude Nb_personnes_rencontrees' OK | individuel = 102013.0 | final = 102013.0

🔎 Vérification DataFrame 18
   ✅ 'Maraude Nb_maraudes_SIGMA' OK | individuel = 7879.0 | final = 7879.0

🔎 Vérification DataFrame 19
   ✅ 'Maraude Nb_SOLIDAR' OK | individuel = 8086.0 | final = 8086.0
   ✅ 'Maraude Nb_SOLIDAR2020' OK | individuel = 6214.0 | final = 6214.0
   ✅ 'AEO Nb_AAD' OK | individuel = 891.0 | final = 891.0
   ✅ 'AEO Nb_FAAD' OK | individuel = 0.0 | final = 0.0
   ✅ 'Formation_grand_public Nb_formes_PSC_2025' OK | individuel = 11872.0 | final = 11872.0
   ✅ 'Formation_grand_public Nb_formes_GQS_2025' OK | individuel = 75369.0 | final = 75369.0
   ✅ 'Formation_grand_public Nb_formes_IPS_2025' OK | individuel = 78434.0 | final = 78434.0
   ✅ 'Formation_grand_public Nb_formes_IPSEN_2025' OK | individuel = 8738.0 | final = 8738.0
   ✅ 'Structure Nb_formes_CRB_2025' OK | individuel = 3191.0 | final = 3191.0
   ✅ 'Structure Nb_formateurs_CRB_2025' OK | individuel = 44.0 | final = 44.0
   ✅ 'Structure Nb_formes_TCAS_2025' OK | individuel = 2141.0 | final = 2141.0
   ✅ 'Formation_grand_public Nb_sessions_PSC_2025' OK | individuel = 520.0 | final = 520.0
   ✅ 'Formation_grand-public Nb_sessions_GQS_2025' OK | individuel = 2153.0 | final = 2153.0
   ✅ 'Formation_grand-public Nb_sessions_IPS_2025' OK | individuel = 2219.0 | final = 2219.0
   ✅ 'Formation_grand-public Nb_sessions_IPSEN_2025' OK | individuel = 83.0 | final = 83.0
   ✅ 'Formation_grand-public Nb_sessions_PREVIC_2025' OK | individuel = 13.0 | final = 13.0
   ✅ 'Formation_grand_public Nb_FPSC' OK | individuel = 1471.0 | final = 1471.0
   ✅ 'Formation_grand_public Nb_AGQS' OK | individuel = 222.0 | final = 222.0
   ✅ 'Formation_grand_public Nb_FIPSEN' OK | individuel = 243.0 | final = 243.0
   ✅ 'Secours Nb_PSE1' OK | individuel = 4491.0 | final = 4491.0
   ✅ 'Secours Nb_PSE2' OK | individuel = 7610.0 | final = 7610.0
   ✅ 'Secours Nb_CI' OK | individuel = 1252.0 | final = 1252.0
   ✅ 'Secours Taux_recy26_PSE1' OK | individuel = 85.12930202958107 | final = 85.12930202958107
   ✅ 'Secours Taux_recy26_PSE2' OK | individuel = 86.19748897928939 | final = 86.1974889792894
   ✅ 'Secours Taux_recy26_CI' OK | individuel = 60.411580187585876 | final = 60.411580187585876
   ✅ 'Secours Taux_ren25_PSE1' OK | individuel = 29.39837838197167 | final = 29.398378381971668
   ✅ 'Secours Taux_ren25_PSE2' OK | individuel = 17.61493912315351 | final = 17.614939123153505
   ✅ 'Secours Taux_ren25_CI' OK | individuel = 0.11147186147186147 | final = 0.11147186147186147

🔎 Vérification DataFrame 20
   ✅ 'Financier Prod_2024' OK | individuel = 91392120.06 | final = 91392120.05999999
   ✅ 'Financier ResNet_2024' OK | individuel = 4605741.17 | final = 4605741.17
   ✅ 'Financier ResCorrProd_2024' OK | individuel = 6.12414552710691 | final = 6.124145527106909
   ✅ 'Financier TresoBrute_2024' OK | individuel = 137289986.72 | final = 137289986.72
   ✅ 'Financier Mois_AvanceTreso_2024' OK | individuel = 2458.6916621011387 | final = 2458.6916621011387

🔎 Vérification DataFrame 21
   ✅ 'Secours Produits_DPS_2025' OK | individuel = 8975398.0 | final = 8975398.0

🔎 Vérification DataFrame 22
   ✅ 'Formation_grand_public Produits_2025' OK | individuel = 91388923.97999999 | final = 91388923.97999999

🔎 Vérification DataFrame 23
   ✅ 'Textile Produit_2025' OK | individuel = 22573754.0 | final = 22573754.0
   ✅ 'Textile Resultat_2025' OK | individuel = 13470366.0 | final = 13470366.0

🔎 Vérification DataFrame 24
   ❌ 'nb_Maraude_Pegass' KO | individuel = 4114.0 | final = 3025.0
   ❌ 'Dispositifs_d_urgence Nb_operations' KO | individuel = 587.0 | final = 457.0
   ❌ 'Dispositifs_d_urgence Nb_exercices' KO | individuel = 59.0 | final = 53.0
   ❌ 'AEO Structure_activite_fixe' KO | individuel = 1247.0 | final = 757.0

In [145]:
mask = df_ref_structure['n_structure'].to_list()

for i, df in enumerate(liste_df_a_fusionner_toutes_structures):
    # Colonnes à supprimer
    df = df[~df['n_structure'].isin(mask)]
    if df['n_structure'].shape[0] > 0:
      print(i)
      print(df['n_structure'].to_list())

In [146]:

for i, df in enumerate(liste_df_a_fusionner_DT):
    # Colonnes à supprimer
    df = df[~df['n_structure'].isin(mask)]
    if df['n_structure'].shape[0] > 0:
      print(i)
      print(df['n_structure'].to_list())

In [147]:
def vision_conso():
  # sélection des colonnes pour vision consolidée FPG

  formations_certifiantes = [
      'Formation_grand_public Nb_formes_PSC_2025',
      'Formation_grand_public Nb_formes_GQS_2025',
      'Formation_grand_public Nb_sessions_PSC_2025',
      'Formation_grand_public Nb_sessions_GQS_2025'
  ]

  df_FGP['vision_conso_FGP_certifiantes'] = (
      df_FGP[formations_certifiantes]
      .fillna(0)
      .sum(axis=1)
      .gt(0)
      .map({True: 'Action menée', False: 'Non menée'})
  )



  formations_non_certifiantes = [
      'Formation_grand_public Nb_formes_IPSEN_2025',
      'Formation_grand_public Nb_formes_IPS_2025',
      'Formation_grand_public Nb_formes_PREVIC_2025',
      'Formation_grand_public Nb_sessions_IPSEN_2025',
      'Formation_grand_public Nb_sessions_IPS_2025',
      'Formation_grand_public Nb_sessions_PREVIC_2025'
  ]

  df_FGP['vision_conso_FGP_noncertifiantes'] = (
      df_FGP[formations_non_certifiantes]
      .fillna(0)
      .sum(axis=1)
      .gt(0)
      .map({True: 'Action menée', False: 'Non menée'})
  )



  df_alldata['vision_territoriale_activite_DPS'] = (
      df_alldata['Secours Nb_DPS_2025']
      .fillna(0)
      .sum(axis=1)
      .gt(0)
      .map({True: 'Action menée', False: 'Non menée'})
  )


  formations_secours = [
      'Secours Nb_PSE1',
      'Secours Nb_PSE2',
      'Secours Nb_CI'
  ]

  df_alldata['vision_territoriale_formation_DPS'] = (
      df_alldata['formations_secours']
      .fillna(0)
      .sum(axis=1)
      .gt(0)
      .map({True: 'Action menée', False: 'Non menée'})
  )




  # Ajout du 'Action non menée' sur les autres colonnes

  colonnes_non_menee = [
      'OCR Nb_deployees',
      'Maraude Nb_maraudes_SIGMA',
      'Secours Nb_DPS_2025',
      'Textile Nb_dispositifs',
      'Aide_alimentaire Nb_U2A'
  ]

  df_alldata[colonnes_non_menee] = (
      df_alldata[colonnes_non_menee]
      .fillna('Non menée')
  )



  # Nb de structures menant l'activité

  colonnes_nb_structure = [
      'OCR Nb_deployees',
      'Maraude Nb_maraudes_SIGMA',
      'Secours Nb_DPS_2025',
      'Textile Nb_dispositifs',
      'Aide_alimentaire Nb_U2A',
      'vision_conso_FGP_certifiantes',
      'vision_conso_FGP_noncertifiantes',
      'AEO Structure_activite_fixe',
      'AEO Structure_activite_mobile',
      'Dispositifs_d_urgence Nb_formes_TCAU_2025',
      'Dispositifs_d_urgence Nb_formes_PSP_2025',
      'Dispositifs_d_urgence Nb_formes_GQS_2025'
  ]

  dico_nb_structures = {}

  for col in colonnes_nb_structure:

      nom_activite = col.split(' ')[0]   # texte avant espace

      if df_alldata[col].dtype == 'object':
          masque = df_alldata[col] == 'Action menée'
      else:
          masque = df_alldata[col].fillna(0) > 0

      nb_structures = df_alldata.loc[masque, 'Structure'].nunique()

      dico_nb_structures[f"{nom_activite}.sa"] = nb_structures

In [148]:
all_data

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,...,Financier TresoBrute_2024,Financier Mois_AvanceTreso_2024,Secours Produits_DPS_2025,Formation_grand_public Produits_2025,Textile Produit_2025,Textile Resultat_2025,nb_Maraude_Pegass,Dispositifs_d_urgence Nb_operations,Dispositifs_d_urgence Nb_exercices,AEO Structure_activite_fixe
0,2615,ANTENNE LOCALE - AL,AL DE DELLE,90100.0,90033,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",90,2010-02-08 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2669,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43220.0,43087,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",43,2011-01-01 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2670,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43600.0,43224,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",43,2011-01-01 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2671,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43300.0,43112,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",43,2011-01-01 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2672,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43000.0,43157,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",43,2011-01-01 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1181,993,UNITE LOCALE - UL,UL DE HAUTE PICARDIE,80320.0,80186,CHAULNES,"36 Avenue Roger Salengro, 80320 CHAULNES",80,1919-12-10 00:00:00,NaT,...,104090.52,40.685326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1182,995,UNITE LOCALE - UL,UL DE DOULLENNAIS,80600.0,80253,DOULLENS,"1 Avenue du Général de Gaulle, 80600 DOULLENS",80,1916-12-10 00:00:00,NaT,...,14323.75,4.965841,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN
1183,996,UNITE LOCALE - UL,UL DU PAYS HAMOIS,80400.0,80410,HAM,"25 Boulevard du Général de Gaulle, 80400 HAM",80,1894-12-10 00:00:00,NaT,...,34358.86,10.307592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1184,998,UNITE LOCALE - UL,UL DU VAL D'AVRE,80500.0,80561,MONTDIDIER,"6 Rue AMAND DE VIENNE, 80500 MONTDIDIER",80,1914-12-10 00:00:00,NaT,...,183196.64,19.014265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1185,999,UNITE LOCALE - UL,UL DU PAYS NESLOIS,80190.0,80585,NESLE,"2 bis Avenue Clémenceau, 80190 NESLE",80,1917-12-10 00:00:00,NaT,...,97243.57,29.022377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [149]:
all_data_DT

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,...,Financier TresoBrute_2024,Financier Mois_AvanceTreso_2024,Secours Produits_DPS_2025,Formation_grand_public Produits_2025,Textile Produit_2025,Textile Resultat_2025,nb_Maraude_Pegass,Dispositifs_d_urgence Nb_operations,Dispositifs_d_urgence Nb_exercices,AEO Structure_activite_fixe
0,10,DELEGATION TERRITORIALE - DT,DT DES ALPES MARITIMES,6700.0,06123,ST LAURENT DU VAR,"658 Boulevard JEAN OSSOLA, 06700 ST LAURENT DU...",6,1986-12-10 00:00:00,NaT,...,3207611.24,28.730802,226266.0,1679851.25,355142,231825,NaN,NaN,NaN,NaN
1,100,DELEGATION TERRITORIALE - DT,DT DU VAL D'OISE,95460.0,95229,EZANVILLE,"1 bis Rue Henri Dunant, 95460 EZANVILLE",95,1986-12-10 00:00:00,NaT,...,1930418.47,17.038343,162236.0,1493196.98,63097,26759,NaN,NaN,NaN,NaN
2,102,DELEGATION TERRITORIALE - DT,DT DE LA GUADELOUPE,97139.0,97101,LES ABYMES,"Rue des écoles, 97139 LES ABYMES",971,1986-12-10 00:00:00,NaT,...,-138952.44,2.164438,2693.0,190848.28,,,0.0,1.0,0.0,0.0
3,103,DELEGATION TERRITORIALE - DT,DT DE LA MARTINIQUE,97200.0,97209,FORT DE FRANCE,"195 Avenue Leona Gabriel, 97200 FORT DE FRANCE",972,1986-12-10 00:00:00,NaT,...,165405.65,5.575564,35758.0,190189.97,11919,9017,NaN,NaN,NaN,NaN
4,104,DELEGATION TERRITORIALE - DT,DT DE NOUVELLE CALEDONIE,98800.0,98818,NOUMEA,"26 Rue DU DOCTEUR GEORGES COLLARD, 98800 NOUMEA",988,1956-12-10 00:00:00,NaT,...,272333.05,3.835414,0.0,1136238.00,,,0.0,3.0,7.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,94,DELEGATION TERRITORIALE - DT,DT DE L'YONNE,89300.0,89206,JOIGNY,"Rue JEAN FRANÇOIS DE LA PÉROUSE, 89300 JOIGNY",89,1986-12-10 00:00:00,NaT,...,675805.08,19.342680,32909.0,489487.34,115892,104838,NaN,NaN,NaN,NaN
104,95,DELEGATION TERRITORIALE - DT,DT DU TERRITOIRE DE BELFORT,90000.0,90010,BELFORT,"15 Avenue du Général Sarrail, 90000 BELFORT",90,1986-12-10 00:00:00,NaT,...,439146.13,13.890856,13258.0,371153.13,24674,22848,44.0,72.0,4.0,0.0
105,96,DELEGATION TERRITORIALE - DT,DT DE L'ESSONNE,91080.0,91228,EVRY COURCOURONNES,"12 Rue Jean Mermoz, 91080 EVRY COURCOURONNES",91,1986-12-10 00:00:00,NaT,...,1547551.36,11.772285,124772.0,1636929.31,226087,122937,NaN,NaN,NaN,NaN
106,97,DELEGATION TERRITORIALE - DT,DT DES HAUTS DE SEINE,92100.0,92012,BOULOGNE BILLANCOURT,"14 Rue de l'Est, 92100 BOULOGNE BILLANCOURT",92,1986-12-10 00:00:00,NaT,...,7158583.91,26.185043,77892.0,3568821.35,332286,230258,NaN,NaN,NaN,NaN
107,99,DELEGATION TERRITORIALE - DT,DT DU VAL DE MARNE,94450.0,94044,LIMEIL BREVANNES,"2 Rue ALBERT GARRY, 94450 LIMEIL BREVANNES",94,1986-12-10 00:00:00,NaT,...,2653772.29,21.799823,161571.0,1235949.97,74434,51823,NaN,NaN,NaN,NaN

# Enregistrement des données

In [78]:
# Entregistrement du DataFrame
save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", gspread_client, all_data, sheet_name = 'UL')
save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", gspread_client, all_data_DT, sheet_name = 'DT')

# save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", client, df_rattachement_court)

📄 Feuille existante 'UL' sélectionnée.
🗑️ Les anciennes données ont été supprimées de la feuille 'UL'
💾 Données sauvegardées dans 'all_data_2025' → feuille 'UL'
    Nombre de lignes : 1186
    Nombre de colonnes : 84
📄 Feuille existante 'DT' sélectionnée.
🗑️ Les anciennes données ont été supprimées de la feuille 'DT'
💾 Données sauvegardées dans 'all_data_2025' → feuille 'DT'
    Nombre de lignes : 108
    Nombre de colonnes : 76