In [4]:
!git config --global user.email "clement.dilasser@croix-rouge.fr"
!git clone https://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@github.com/clementsouk-aloun-dot/Code-PAT.git

Cloning into 'Code-PAT'...
remote: Enumerating objects: 2263, done.
remote: Counting objects: 100% (276/276), done.
remote: Compressing objects: 100% (194/194), done.
remote: Total 2263 (delta 154), reused 112 (delta 75), pack-reused 1987 (from 2)
Receiving objects: 100% (2263/2263), 8.94 MiB | 16.12 MiB/s, done.
Resolving deltas: 100% (1608/1608), done.

In [88]:
%cd ..

/content/Code-PAT

In [89]:
%cd Code-PAT
!git checkout main

[Errno 2] No such file or directory: 'Code-PAT'
/content/Code-PAT
D	__pycache__/utils.cpython-312.pyc
D	scripts_data/__pycache__/adherent.cpython-312.pyc
D	scripts_data/__pycache__/alim.cpython-312.pyc
D	scripts_data/__pycache__/base_contact.cpython-312.pyc
D	scripts_data/__pycache__/domifa.cpython-312.pyc
D	scripts_data/__pycache__/dps.cpython-312.pyc
D	scripts_data/__pycache__/financier.cpython-312.pyc
D	scripts_data/__pycache__/gaia.cpython-312.pyc
D	scripts_data/__pycache__/impact.cpython-312.pyc
D	scripts_data/__pycache__/manuelles.cpython-312.pyc
D	scripts_data/__pycache__/maraude.cpython-312.pyc
D	scripts_data/__pycache__/mobilite.cpython-312.pyc
D	scripts_data/__pycache__/nomination.cpython-312.pyc
D	scripts_data/__pycache__/pegass.cpython-312.pyc
Already on 'main'
Your branch is behind 'origin/main' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

In [4]:
!git add .

In [5]:
!git commit -m "Correction base contact"

[main 25a3773] Correction base contact
 1 file changed, 8 insertions(+), 1 deletion(-)

In [90]:
!git fetch origin

In [ ]:
!git config pull.rebase true

In [91]:
!git pull

Updating cd0919f..9eea384
Fast-forward
 __pycache__/utils.cpython-312.pyc                  | Bin 40599 -> 40599 bytes
 scripts_data/__pycache__/adherent.cpython-312.pyc  | Bin 4381 -> 4381 bytes
 scripts_data/__pycache__/alim.cpython-312.pyc      | Bin 7033 -> 7033 bytes
 .../__pycache__/base_contact.cpython-312.pyc       | Bin 32980 -> 33357 bytes
 scripts_data/__pycache__/domifa.cpython-312.pyc    | Bin 6129 -> 6129 bytes
 scripts_data/__pycache__/dps.cpython-312.pyc       | Bin 2329 -> 2329 bytes
 scripts_data/__pycache__/financier.cpython-312.pyc | Bin 15978 -> 15978 bytes
 scripts_data/__pycache__/gaia.cpython-312.pyc      | Bin 6131 -> 6131 bytes
 scripts_data/__pycache__/impact.cpython-312.pyc    | Bin 9912 -> 9912 bytes
 scripts_data/__pycache__/manuelles.cpython-312.pyc | Bin 21906 -> 21906 bytes
 scripts_data/__pycache__/maraude.cpython-312.pyc   | Bin 18439 -> 18439 bytes
 scripts_data/__pycache__/mobilite.cpython-312.pyc  | Bin 4693 -> 4693 bytes
 .../__pycache__/nomination.cpython-312.pyc         | Bin 6363 -> 6363 bytes
 scripts_data/__pycache__/pegass.cpython-312.pyc    | Bin 26084 -> 26084 bytes
 scripts_data/dps.py                                |  24 +++++++++++++++++++++
 15 files changed, 24 insertions(+)

In [6]:
!git push

Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 471 bytes | 471.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/clementsouk-aloun-dot/Code-PAT.git
   4f1ff63..25a3773  main -> main

In [6]:
!gcloud auth application-default login

Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=tRbY8zwRSQvR7rrjLZB2ZEMFDotcxQ&prompt=consent&token_usage=remote&access_type=offline&code_challenge=W1BT50UDVjnKOz3oK3JhEj5L12rQvS4iWXDc9sUG-sw&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0AfrIepAKYcrBDz-XNySN3ClSt4KzSruXTQhT9CevKjGKMprT7zlCDRiNmz1rTWlsn1ZgLg

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.


To take a quick anonymous survey, run:
  $ gcloud survey

In [7]:
!pip install PyPDF2
!pip install reportlab
!pip install PyMuPDF tools
!pip install xlsxwriter

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 5.4 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1
Collecting reportlab
  Downloading reportlab-4.4.10-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.4)
Downloading reportlab-4.4.10-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 23.2 MB/s eta 0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-4.4.10
Collecting PyMuPDF
  Downloading pymupdf-1.27.1-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Collecting tools
  Downloading tools-1.0.23-py3-none-any.whl.metadata (1.3 kB)
Downloading pymupdf-1.27.1-cp310-abi3-manylinux_2_28_x86_64.whl (24.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 MB 65.0 MB/s eta 0:00:00
Downloading tools-1.0.23-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 2.6 MB/s eta 0:00:00
Installing collected packages: tools, PyMuPDF
Successfully installed PyMuPDF-1.27.1 tools-1.0.23
Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 4.4 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9

# Imports

In [8]:
import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import sys
import io
import re
import shutil
import zipfile
from google.colab import drive, files

from google.colab import auth
from google.auth import default
import unicodedata
import re
import torch
from sentence_transformers import SentenceTransformer, util
from google.cloud import bigquery
from pyspark.sql import SparkSession
import gc
from functools import reduce

Imports des fichiers .py

In [9]:
sys.path.append(os.path.abspath("/content/Code-PAT/scripts_data"))
sys.path.append(os.path.abspath("/content/Code-PAT"))

from adherent import *
from alim import *
from domifa import *
from financier import *
from gaia import *
from impact import *
from manuelles import *
from maraude import *
from base_contact import*
from mobilite import *
from nomination import *
from pegass import *
from dps import *

from utils import *

#AUTHENTIFICATION

In [10]:
PROJECT_ID = "crf-pat"
client = bigquery.Client(project=PROJECT_ID)

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [11]:
# Etape 0 : Préparation de l'environnement

CREDENTIALS_JSON = """
{
  "type": "service_account",
  "project_id": "alexandrevalent",
  "private_key_id": "dba39c84ba4135ce5ede6479a186ad8cde499dee",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvGU4ZJFrBwCBb\nu8s4aPA5bQTOKDkPZEVdNyY//RneR6RC9JPrcbfVfIUaQU7A036sfdhDGFKJbw20\nTZ55fafcH9yCMiUO+Nzek0eogON4TXrXsh8UFtdw8BOuaVkFitU5yg8kFhTnEZtd\ntPfZHW3Aqhd/aDoTOBNgRuF/hVTKQ2ytbCbE77fL2/pz9kvpZ2Zrz3u1lmksSJls\nHIolNwX9R05YqmrkpZ/TMAULFk4bT0VRQng5pmN9AeB61eJLWhlLaEdeu79NWV4B\n7tZd6RzzTFors804aJkmXHM63VRtvGD0UlR0O7w1QlI3ymUxpy5hrjbz6n9bmpMI\nfebvydLnAgMBAAECggEADipn7RTJ2t7mP0WkHT4wIRU2zE7ovtwH2JC7oXWigB8f\npOMQjH24t6bJReR+sI7rspzDwDnZg5DedPXKml2WFPLm7gmMgfeUNtWHeJRk0rjB\n9W1NolxutY5WqUeQkig3M+Oq8epvano8LYqUepYs6OdZ207dU+y3dJSHbb+lqm9D\ntQZR2oBj7W1iZ8fJ+SQLSjU5BztS1CvWuayRd/tLd9Spp0NUn5uQFTKwel9Gazmz\n28IsPPm6SudplFhaGd4kCPvhcg0jGEKe61VYdgHoBzp+EXRWXUvQ+SbMafXtMvoB\nLoUH4X3creKzJQKXnjlDpAzRHMYhJTvHinHXaggdcQKBgQDcJszFOECfSovXFZNq\nMyQOWbesyDb2OQhJLFZCD2QraZm3jPaIPeMfFkmFAumcVal6EzpR5IE8g9jBuLo+\ng6j3NTo5jbGO9WEn4361yEotb+S8t3/DTHvWqXBK7HdUB/KHlyGtctm8yErdMZQB\nvzo03aTwwStNTeFG8GzT1Nd7JQKBgQDLnHIMbx9iAG3K21XCq0Dot2Q63hklJC26\nsJlrTkdXMOIlhpwJ6LTOJe2paHbR56IrKOHQCuLxQFhRd8Eidz1ahjO7D8fKr/TG\nS8/V32FrpONyxhKinLsccSb86S3vvpKCI265z5EEjk/1qnx3TOo6oqA/2DQLv0Q4\nYinmNSOeGwKBgHGjYY3n9IuE6lwy2e42ycTSkNoSWzSLyfgjd78PvNAf6WXy0IsR\nDvzL/1U2ZKn7GclWxYLiJce78xZEKXb9dSluA0kUF/RIO0dgydZBtfBwUq0LN1rz\nTvVGbx1tpEbu90UAQTUMFNK6vNIitliUghIp2usfex+jNMbuce6Cblw1AoGBAKDH\n1gtZiFeT7R7d2jfRkXzyrBQMI6D/k5izMULZ2l3QfROS2w68EmIi8yvuEL2qApXA\nP6hPoGtPGy6huQHlVK5yANF7IZI9JbWcUe8Z6MzetLiCDl8YEmzgMSBPZXXGb9yR\n7DKP5HzLf/qG+KggNWm913ry2A5ap506bsmZNpn3AoGBAM6vvI9tb+AcNfd4ewmY\nAWSb4GLliRTaBIGHYmotfyBEBWpXZq2/0JG32RRf3rYUJWWn/r7K+zrRUqeMwlD+\nz7GuSU+OaSDzYj7fwDyuxOwTJMLrh+AkKbUYBsMF7YH1qIRjBjKNdj1LOznASQMe\nu1E4sNa9RRRujbQw4AEP3Xjl\n-----END PRIVATE KEY-----\n",
  "client_email": "crf-slidemanager@alexandrevalent.iam.gserviceaccount.com",
  "client_id": "101959630014487618959",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/crf-slidemanager%40alexandrevalent.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly']


# Authentification
credentials = service_account.Credentials.from_service_account_info(json.loads(CREDENTIALS_JSON, strict=False), scopes=SCOPES)

# Initialisation des services
slides_service = build('slides', 'v1', credentials=credentials)
drive_service = build('drive', 'v3', credentials=credentials)
gspread_client  = gspread.authorize(credentials)

# Variables globales

In [12]:
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

# CHARGEMENT DE TOUTES LES DONNEES PAR TABLE

## 0. Ref_structure

In [13]:
df_ref_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw/').worksheet('Feuille 1'))

In [14]:
df_ref_structure = renommer_par_nom_table(df_ref_structure, "AS_Informations_structures", mapping_df)
df_ref_structure['n_structure'] = df_ref_structure['n_structure'].astype(int)
df_ref_structure = df_ref_structure[df_ref_structure["type_structure"].isin(["UNITE LOCALE - UL", "DELEGATION TERRITORIALE - DT", 'IMPLANTATION LOCALE HORS AL - IL', 'ANTENNE LOCALE - AL','INSTANCES NATIONALES - IN'])]
df_ref_structure = df_ref_structure[df_ref_structure['n_structure'] != 1]

df_ref_structure.head()

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,Structure_de_rattachement,Rattachements_successifs,DT_de_rattachement,lon,lat
0,2615,ANTENNE LOCALE - AL,AL DE DELLE,90100.0,90033,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",90,2010-02-08 00:00:00,NaT,95 - DT DU TERRITOIRE DE BELFORT,AL 2615,95 - DT DU TERRITOIRE DE BELFORT,7.000705,47.506725
1,2669,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43220.0,43087,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2669,48 - DT DE LA HAUTE LOIRE,4.346423,45.214392
2,2670,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43600.0,43224,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2670,48 - DT DE LA HAUTE LOIRE,4.235474,45.242445
3,2671,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43300.0,43112,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2671,48 - DT DE LA HAUTE LOIRE,3.495645,45.098285
4,2672,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43000.0,43157,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2672,48 - DT DE LA HAUTE LOIRE,3.879748,45.044677

In [15]:
df_ref_structure_DT = df_ref_structure[df_ref_structure['nom_structure'].str.contains('DT')].astype(str)
df_ref_structure_DT['n_structure'] = df_ref_structure['n_structure'].astype(int)

### 0.1 rattachement_court

In [16]:
rattachement_court = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU/edit?usp=sharing').worksheet('Feuille 1'))

## 1. PEGASS

In [17]:
df_ref_activite_benevole, df_pegass_activite, df_pegass_activite_seance, df_pegass_activite_seance_inscription,ref_structure1,df_rattachement_court,df_ref_action_groupe_action = import_tables_PEGASS(client)

##2. GAIA

In [18]:
df_gaia_rattachement_benevole = clean_gaia(client, df_ref_structure)

## 3. NOMINATION

In [19]:
df_ref_nomination, df_nomination = clean_nomination(client, df_ref_structure)

## 4. IMPACT

In [20]:
df_ref_impact, df_impact = clean_impact(client,df_ref_structure)

## 5. Données financières

In [21]:
financier = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c')

In [22]:
dt_ul_ant_prod = get_as_dataframe(financier.worksheet('DT-UL-Ant_Prod'), skiprows=3, evaluate_formulas=True)

In [23]:
dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute, dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute = import_clean_donnees_financieres(financier,df_ref_structure,mapping_df)

Financier DPS & FGP

In [24]:
financier_DPS = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/145xeh1LkmYzTSW2zeAwHqmLyjmw_tobICHf-oXZmUFI/').worksheet('Base Smtw 03.03.25'))

In [25]:
financier_FGP = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13J2zfbmLTILtGYtE_sM-ME8B0pNEwBeGJ1Gg5vKLeOc/').worksheet('DT_Prod'))

## 6. Mobilité

In [26]:
mobilite = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1dvxT58WR-FqdT-4r-A9ca4vaA9FG7IXHJJaTbnjio8A/')

In [27]:
df_mobilite = filtres_mobilite(mobilite,mapping_df, df_ref_structure)

## 7. Données manuelles

### 7.1 OCR

In [28]:
df_OCR = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ccRoyPycFDwvQvacvmHjfE87LtnlzUgtoRbITkC0pVQ/').worksheet('Feuille 1'))

### 7.2 PST

In [29]:
df_PST = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1yifNna4Hsn5RihkRg50g9h1yKjuRjfolrjsWonEHnrQ').worksheet('Données'))

### 7.3 Déclenchements

In [30]:
df_declenchement = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1y9jehT5fStcEWCF0pxAP7BdiI62VY3JM_hQzFftbcZA').worksheet('Feuille 1'))

### 7.4 Redcall

In [31]:
df_redcall = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1EQzq0K8RY2Liyq-jtggX0bTlnOk9cwUTmf4t6c5_CiI').worksheet('structure-stats_2025-01-01_2025-12-31_min-1 (1)'))

### 7.5 CHAI CHU CMCC

In [32]:
df_CAICHUCMCC = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/12nZY2leRCMn71NGAEUUtA0Pes598gOfeufDStxSCcnY').worksheet('Toutes données'))

### 7.6 Conventions

In [33]:
df_conventions = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1u6E6SUydE7zB1bbcjPzjDt9m5YtGszl0MATPbDQeOhg').worksheet('Feuille 1'))

### 7.7 Textile

In [34]:
df_raw_Textile_c = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1QYuKZo5lVI0HN4BWtk0v7bVFY2a2p4c72a0gU0ltWac/').worksheet('Liste des PAV'))

df_raw_ProdResTextile_c = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1l7KMjiav3usmLVJIbE2uENfNQCeQuxVeU1h13Cep3qk/",sheet_name="Compil Détail",header_row=7)

✅ Chargement des données réalisées
    Sheet : Résultat Textile_2020-2024_V1_13 févr 2025
    Feuille  : Compil Détail (1338 lignes et 29 colonnes)

### 7.8 DOMIFA

In [35]:
df_domiciliation, df_rattachement_court = clean_domifa(client,df_ref_structure)

/content/Code-PAT/utils.py:199: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ref['nom_structure'] = df_ref['nom_structure'].fillna('').astype(str)
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

### 7.9 Alim

In [36]:
df_alim = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1bk_ktsT9hBPJS5EY70teq80NzOs_cm3JfrRkX4AYTF4/edit?gid=0#gid=0")

✅ Chargement des données réalisées
    Sheet : Liste U2A a jour - 21/01/2026
    Feuille 1 : Feuille 1 (628 lignes et 10 colonnes)

### 7.10 Adherent

In [37]:
df_adherent = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1hsk3Xp2IrwnUs59sgWjhT9E9vEsw4TN2WT3nKejlBOE/edit?usp=drive_link")

✅ Chargement des données réalisées
    Sheet : exportAdherents (1) (1)
    Feuille 1 : exportAdherents (1) (1).csv (48300 lignes et 25 colonnes)

### 7.11 Préparation

In [38]:
# DPS a pour source le fichier conventions
df_dps = clean_dps(df_conventions)

df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions, df_raw_Textile, df_raw_ProdResTextile = clean_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement, df_redcall, df_CAICHUCMCC, df_conventions, df_raw_Textile_c, df_raw_ProdResTextile_c, df_ref_structure)
df_alim = clean_alim(df_alim)
df_adherent = clean_adherent(df_adherent)

Point d'apport possible :  ['Boutique - La Boutique' 'Conteneur' 'Vestiaire' 'Boutique  - Mobile'
 'Autres' 'Boutique - Bébé' 'Boutique - Chez Henry' 'Ressourcerie CRi'
 'Boutique - Recylcerie / Meuble' 'Déchetterie' 'conteneur']
Unique values in 'Année de l'adhésion du contact': [2025]
Data type of 'Année de l'adhésion du contact': int64
Taille du DataFrame après suppression des doublons : (47424, 4)

/content/Code-PAT/scripts_data/dps.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Departement"] = df["Departement"].str.replace(
/content/Code-PAT/scripts_data/manuelles.py:119: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['Grand Total', 'Exercice']] = df[['Grand Total', 'Exercice']].fillna(0)
/content/Code-PAT/scripts_data/manuelles.py:185: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Département"] = df["Département"].str.replace(
/content/Code-PAT/scripts_data/adherent.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_adherent["Année de l'adhésion du contact"] = pd.to_numeric(df_adherent["Année de l'adhésion du contact"], errors='coerce')

## 8. Maraudes

In [39]:
# 1) import
df_maraude, df_rattachement_court = import_maraude(client)

In [40]:
#~rattachement successif
ref_structure_m , c , rattachement_successif, df_maraude = apply_rattachement_successif(df_ref_structure, df_maraude)

In [41]:
# 3) ✅ Filtre : on CHANGE df_maraude ici
df_maraude = filter_maraude_on_ref_structure(
    df_maraude,
    ref_structure_m,
    col_maraude="maraude_structure_id_fk",
    col_ref="n_structure",
    verbose=True
)

📌 Filtre structures ref: 114,451/116,440 lignes conservées (supprimées: 1,989).

In [42]:
# 3) clean/prep
df_nb_personnes_rencontrees_sigma, df_Nb_maraudes_SIGMA = clean_maraudes(df_maraude)

## 9. Base Contact

In [43]:
df_formation_session_resultat, df_formation_count_session_2025 = clean_base_contact(client, df_ref_structure)

# FUSION DES TABLES

## 1. Fusion NOMINATION

In [44]:
df_NOMINATION = fusion_nomination(df_nomination, df_ref_nomination)

## 2. Fusion IMPACT

In [45]:
df_IMPACT = fusion_impact(df_impact, df_ref_impact)

Nombre de lignes après filtre 2025 : 369424

## 3. Fusion Données financières

### 3.1 Fusion des tables

In [46]:
df_financier_DT, df_financier_DT_UL = fusion_donnees_financieres(dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute,dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute, df_ref_structure)

### 3.2 Vérifications

In [47]:
verifier_colonne_structure(df_financier_DT, "DT_de_rattachement", df_ref_structure)

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [48]:
verifier_colonne_structure(df_financier_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## 4. Fusion DOMIFA

In [49]:
df_domiciliation = pd.merge(df_domiciliation, df_rattachement_court, on='n_structure', how="left") #a conserver dans le code principal

# Calcul des indicateurs

## PEGASS

In [50]:
pegass_output = calcul_PEGASS_indicateurs(df_ref_structure,
    ref_structure1,
    df_ref_action_groupe_action,
    df_ref_activite_benevole,
    df_pegass_activite,
    df_pegass_activite_seance,
    df_pegass_activite_seance_inscription,
    df_rattachement_court
)

## GAIA

In [51]:
nb_benevoles = indicateurs_gaia(df_gaia_rattachement_benevole)
nb_nvx_benevoles = indicateurs_gaia_nvx(df_gaia_rattachement_benevole)
nb_benevoles_DT = indicateurs_gaia_DT(nb_benevoles,rattachement_court)
nb_nvx_benevoles_DT = indicateurs_gaia_nvx_DT(nb_nvx_benevoles, rattachement_court)

Nombre de structures agrégées : 844
Nombre total de bénévoles uniques : 98418
Nombre de structures agrégées : 776
Nombre total de nouveaux bénévoles uniques : 20980
Nombre de structures agrégées : 108
Nombre total de bénévoles uniques DT : 96753
Nombre de structures agrégées : 106
Nombre total de nouveaux bénévoles uniques DT : 20668

## NOMINATION

- RTAEO & RLAEO
- RTOCR & RLOCR

In [52]:
referents_AEO = indicateurs_nomination_AEO(df_NOMINATION, annee=2025)
referents_OCR = indicateurs_nomination_OCR(df_NOMINATION, annee=2025)
referents_AEO_DT = indicateurs_nominationAEO_DT(referents_AEO, rattachement_court)
referents_OCR_DT = indicateurs_nominationOCR_DT(referents_OCR, rattachement_court)

Nombre de structures agrégées : 27
Nombre total de responsables AEO : 41
Nombre de structures agrégées : 20
Nombre total de responsables OCR : 21
Nombre de structures agrégées : 17
Nombre total de responsables AEO DT : 41
Nombre de structures agrégées : 15
Nombre total de responsables OCR DT : 21

## IMPACT

- Nombre d'agréments territoriaux (Dispos d'urgence)
- Nombre de personnes prises en charge (Dispos d'urgence)

In [53]:
IMPACT_ppc = indicateurs_impact_ppc(df_IMPACT)
IMPACT_agrementAB = indicateurs_impact_agrementAB(df_IMPACT)
IMPACT_agrementDPS = indicateurs_impact_agrementDPS(df_IMPACT)
IMPACT_ppc_DT = indicateurs_IMPACTppc_DT(IMPACT_ppc, rattachement_court)
IMPACT_agrementAB_DT = indicateurs_IMPACTagrementAB_DT(IMPACT_agrementAB, rattachement_court)
IMPACT_agrementDPS_DT = indicateurs_IMPACTagrementDPS_DT(IMPACT_agrementDPS, rattachement_court)

Nombre de lignes après filtre urgences : 1157
Nombre de structures agrégées : 108
Somme totale Dispositifs d'urgence - Nb personnes prises en charge : 15418
Nombre de structures agrégées : 74
Somme totale agréments AB : 0
Nombre de structures agrégées : 47
Somme totale agréments DPS : 0
Nombre de structures agrégées : 60
Somme totale personnes prises en charge DT : 15418
Nombre de structures agrégées : 57
Somme totale agréments AB DT : 0
Nombre de structures agrégées : 37
Somme totale agréments DPS DT: 0

/content/Code-PAT/scripts_data/impact.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (
/content/Code-PAT/scripts_data/impact.py:149: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (
/content/Code-PAT/scripts_data/impact.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (

## Financier DPS & FGP

In [54]:
df_Secours_ProduitsDPS = indicateur_financier_DPS(financier_DPS, df_ref_structure)
df_financier_DPS_DT = financier_DPS_DT(df_Secours_ProduitsDPS, rattachement_court)
df_financier_FGP_DT = indicateur_financier_FGP(financier_FGP, df_ref_structure)
#df_inancier_FGP_DT = financier_FGP_DT(df_financier_FGP, rattachement_court)

🔎 Vérification de la colonne 'libelle' et mapping associé 'n_structure'
   ✅ Mapping réalisé avec succès.

## Mobilité


Indicateurs qui nécessitent seulement les données mobilité :

- Nb de structures menant une activité AEO/AAD mobile
- Nombre de personnes accompagnées par des dispositifs AEO/AAD mobiles
<br>
Indicateurs qui nécessitent une fusion avec données AEO/AAD :

- Nombre de bénévoles impliqués dans les activités AEO ou AAD
- Nombre de bénévoles impliqués dans les activités AEO ou AAD

In [55]:
df_mobilite_DT = indicateurs_mobilite(df_mobilite, df_ref_structure, 'DT_de_rattachement')
df_mobilite_DT_UL = indicateurs_mobilite(df_mobilite, df_ref_structure, 'n_structure')

In [56]:
verifier_colonne_structure(df_mobilite_DT, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [57]:
verifier_colonne_structure(df_mobilite_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## Données manuelles

In [58]:
df_OCR_Nb_deployees, df_Dispositifs_d_urgence_PST, df_declenchement3, df_redcall2, df_CAICHUCMCC_VF, df_conventions2, df_raw_Textile, df_raw_ProdResTextile = indicateurs_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions, df_raw_Textile, df_raw_ProdResTextile, df_ref_structure)

Nb_OCR_DT,RedCall_DT = OCR_RedCall_DT(df_OCR_Nb_deployees, df_redcall2, rattachement_court)
df_Textile_DT, df_Textile_financier_DT = TEXTILE_DT(df_raw_Textile, df_raw_ProdResTextile, rattachement_court)

# ALIM
df_alim_U2A_sans_doublons, df_alim_epicerie_sociale, df_alim_accueil_alimentaire, df_alim_crsr = indicateurs_alim(df_alim, df_ref_structure)
df_alim_U2A_DT, df_alim_epicerie_sociale_DT, df_alim_accueil_alimentaire_DT, df_alim_crsr_DT = indicateurs_alim_DT(df_alim_U2A_sans_doublons, df_alim_epicerie_sociale, df_alim_accueil_alimentaire, df_alim_crsr, rattachement_court)

# ADHERENT
df_adherent = indicateurs_adherent(df_adherent, df_ref_structure)
df_adherent_DT = indicateurs_adherent_DT(df_adherent, rattachement_court)

# DOMIFA
df_personnes_domiciliees_struct, df_personnes_domiciliees_DT = indicateurs_domifa(df_domiciliation)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

🔎 Vérification de la colonne 'libelle' et mapping associé 'n_structure'
   ✅ Mapping réalisé avec succès.

/content/Code-PAT/scripts_data/manuelles.py:564: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Textile Produit_2024'] = df['Textile Produit_2024'].str.replace(r"\s+", "", regex=True)
/content/Code-PAT/scripts_data/manuelles.py:565: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Textile Produit_2024'] = df['Textile Produit_2024'].str.replace("-", "")
/content/Code-PAT/scripts_data/manuelles.py:566: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Textile Resultat_2024'] = df['Textile Resultat_2024'].str.replace(r"\s+", "", regex=True)
/content/Code-PAT/scripts_data/manuelles.py:567: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Textile Resultat_2024'] = df['Textile Resultat_2024'].str.replace("-", "")

In [59]:
verifier_colonne_structure(df_OCR_Nb_deployees, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Dispositifs_d_urgence_PST, "n_structure", df_ref_structure)
verifier_colonne_structure(df_declenchement3, "n_structure", df_ref_structure)
verifier_colonne_structure(df_redcall2, "n_structure", df_ref_structure)
verifier_colonne_structure(df_CAICHUCMCC_VF, "n_structure", df_ref_structure)
verifier_colonne_structure(df_conventions2, "n_structure", df_ref_structure)

# TEXTILE
verif_textile(df_raw_Textile_c, df_raw_ProdResTextile_c, df_raw_Textile, df_Textile_DT,df_raw_ProdResTextile, df_Textile_financier_DT, df_ref_structure, rattachement_court)

# DOMIFA

verifs_domifa(client, df_personnes_domiciliees_struct, df_personnes_domiciliees_DT, df_ref_structure, df_rattachement_court)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.
✅ df_Textile_DT est bien calculé (suomme de l indicateur == au nombre de lignes des données)
✅ df_Textile_DT est bien calculé (suomme de l indicateur == au nombre de lignes des données)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.
#1 Vérification qu on a bien la même somme de personnes domiciliées entre le fichier de base et le fichier df_personnes_domiciliees_struct
OK ✅ : sommes égales (30833) entre table struct[AEO Nb_personnes_domiciliees_crf] et table source[Nombre total de domiciliations]
#2 Vérification qu on a bien la même somme de personnes domiciliées entre le fichier structure et le fichier df_personnes_domiciliees_DT
OK ✅ : sommes égales (30833) entre table struct[AEO Nb_personnes_domiciliees_crf] et table DT[AEO Nb_personnes_domiciliees_crf]
#3 on vérifie que l ensemble des N° structure du nb personnes domicilées correspnd au ref structure

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.
#4 on vérifie que l ensemble des N° DTdu nb personnes domicilées correspnd au ref structure

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.
#5 On verifie que le nb de structure du df_personnes_domiciliees_struct est bien égal au nombre de ligne du df source
 ✅ n ligne = 30

## Maraudes

In [60]:
(
    df_Nb_maraudes_SIGMA_struct,
    df_Nb_maraudes_SIGMA_DT,
    df_nb_contacts_SIGMA_struct,
    df_nb_contacts_SIGMA_DT,
    df_personnes_diff_base,                 # <- nouveau (base par bénéficiaire)
    df_nb_personnes_rencontrees_SIGMA_struct,
    df_nb_personnes_rencontrees_SIGMA_DT
) = indicateurs_maraude(
    df_nb_personnes_rencontrees_sigma,
    df_Nb_maraudes_SIGMA,
    df_rattachement_court
)

In [61]:
verifier_colonne_structure(df_Nb_maraudes_SIGMA_struct, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Nb_maraudes_SIGMA_DT, "DT_de_rattachement", df_ref_structure)
verifier_colonne_structure(df_nb_contacts_SIGMA_struct, "n_structure", df_ref_structure)
verifier_colonne_structure( df_nb_contacts_SIGMA_DT, "DT_de_rattachement", df_ref_structure)
verifier_colonne_structure(df_nb_personnes_rencontrees_SIGMA_struct, "n_structure", df_ref_structure)
verifier_colonne_structure(df_nb_personnes_rencontrees_SIGMA_DT, "DT_de_rattachement", df_ref_structure)

df_maraude_verif= prep_nb_personnes_rencontrees_sigma(df_maraude, filtre_annee_fn=None)

df_maraude_verif= add_nb_personnes(df_maraude_verif,
                     out_col="nb personnes",
                     cols=None,
                     col_typologie="maraude_rencontre_typologie")

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [62]:
run_verif_maraude(
    df_Nb_maraudes_SIGMA_struct=df_Nb_maraudes_SIGMA_struct,
    df_Nb_maraudes_SIGMA_DT=df_Nb_maraudes_SIGMA_DT,
    df_nb_contacts_SIGMA_struct=df_nb_contacts_SIGMA_struct,
    df_nb_contacts_SIGMA_DT=df_nb_contacts_SIGMA_DT,
    df_nb_personnes_rencontrees_SIGMA_struct=df_nb_personnes_rencontrees_SIGMA_struct,
    df_nb_personnes_rencontrees_SIGMA_DT=df_nb_personnes_rencontrees_SIGMA_DT,
    df_Nb_maraudes_SIGMA=df_Nb_maraudes_SIGMA,
    df_maraude_verif=df_maraude_verif,
    df_personnes_diff_base=df_personnes_diff_base,
)

====================
VERIF MARAUDE
====================

✅ #1 Nb maraudes (Struct vs DT) - OK : somme(df_left['Maraude Nb_maraudes_SIGMA']) = somme(df_right['Maraude Nb_maraudes_SIGMA']) (total=7879)
✅ #2 Nb contacts (Struct vs DT) - OK : somme(df_left['Maraude Nb_contacts']) = somme(df_right['Maraude Nb_contacts']) (total=127109)
✅ #3 Nb personnes rencontrées (Struct vs DT) - OK : somme(df_left['Maraude Nb_personnes_rencontrees']) = somme(df_right['Maraude Nb_personnes_rencontrees']) (total=102013)
✅ #4 OK : somme maraudes structure (7879) = len(df_Nb_maraudes_SIGMA) (7879)
✅ #5 OK : personnes différentes rencontrées — somme df_base = 102013 = somme df_struct = 102013
✅ #6 OK Somme contact  OK : somme 'Maraude Nb contacts struct' df struct = somme Nb contacts df maraude verif = 127109

## Base contact

In [63]:
# Indicateurs
indicateurs_base_contact, indicateurs_base_contact_DT = indicateurs_base_contact(client, df_formation_session_resultat, df_formation_count_session_2025, df_ref_structure)

===== Vérification des codes =====

Indicateur : Maraude Nb_SOLIDAR
  Codes attendus : {'SOLIDAR1', 'SOLIDAR2', 'SOLIDAR'}
  Codes trouvés  : {'SOLIDAR1', 'SOLIDAR2', 'SOLIDAR'}
  Codes manquants: set()

Indicateur : Maraude Nb_SOLIDAR2020
  Codes attendus : {'ESOLIDAR2026', 'SOLIDAR2020', 'PASSOLIDAR2020'}
  Codes trouvés  : {'ESOLIDAR2026', 'SOLIDAR2020', 'PASSOLIDAR2020'}
  Codes manquants: set()

Indicateur : AEO Nb_AAD
  Codes attendus : {'AAD'}
  Codes trouvés  : {'AAD'}
  Codes manquants: set()

Indicateur : AEO Nb_FAAD
  Codes attendus : {'FAAAD', 'FAAD', 'EPIAF FAAD'}
  Codes trouvés  : {'FAAAD', 'FAAD', 'EPIAF FAAD'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_TCAU_2025
  Codes attendus : {'TCAU', 'ETCAU'}
  Codes trouvés  : {'TCAU', 'ETCAU'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_TCEO_2025
  Codes attendus : {'TCEO', 'ESE'}
  Codes trouvés  : {'TCEO', 'ESE'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_PSP_2025
  Codes attendus : {'PSP'}
  Codes trouvés  : {'PSP'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_IRR_2025
  Codes attendus : {'IRRJ', 'IRRA', 'IRR'}
  Codes trouvés  : {'IRRJ', 'IRR', 'IRRA'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_GQS_2025
  Codes attendus : {'GQS AC', 'GQS'}
  Codes trouvés  : {'GQS'}
  Codes manquants: {'GQS AC'}

===== Somme globale par indicateur =====
Maraude Nb_SOLIDAR : 8261
Maraude Nb_SOLIDAR2020 : 6076
AEO Nb_AAD : 1207
AEO Nb_FAAD : 52
Dispositifs_d_urgence Nb_formes_TCAU_2025 : 12340
Dispositifs_d_urgence Nb_formes_TCEO_2025 : 1813
Dispositifs_d_urgence Nb_formes_PSP_2025 : 5009
Dispositifs_d_urgence Nb_formes_IRR_2025 : 26941
Dispositifs_d_urgence Nb_formes_GQS_2025 : 28102

===== Vérification des codes =====

Indicateur : Maraude Nb_SOLIDAR
  Codes attendus : {'SOLIDAR1', 'SOLIDAR2', 'SOLIDAR'}
  Codes trouvés  : {'SOLIDAR1', 'SOLIDAR2', 'SOLIDAR'}
  Codes manquants: set()

Indicateur : Maraude Nb_SOLIDAR2020
  Codes attendus : {'ESOLIDAR2026', 'SOLIDAR2020', 'PASSOLIDAR2020'}
  Codes trouvés  : {'ESOLIDAR2026', 'SOLIDAR2020', 'PASSOLIDAR2020'}
  Codes manquants: set()

Indicateur : AEO Nb_AAD
  Codes attendus : {'AAD'}
  Codes trouvés  : {'AAD'}
  Codes manquants: set()

Indicateur : AEO Nb_FAAD
  Codes attendus : {'FAAAD', 'FAAD', 'EPIAF FAAD'}
  Codes trouvés  : {'FAAAD', 'FAAD', 'EPIAF FAAD'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_TCAU_2025
  Codes attendus : {'TCAU', 'ETCAU'}
  Codes trouvés  : {'TCAU', 'ETCAU'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_TCEO_2025
  Codes attendus : {'TCEO', 'ESE'}
  Codes trouvés  : {'TCEO', 'ESE'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_PSP_2025
  Codes attendus : {'PSP'}
  Codes trouvés  : {'PSP'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_IRR_2025
  Codes attendus : {'IRRJ', 'IRRA', 'IRR'}
  Codes trouvés  : {'IRRJ', 'IRR', 'IRRA'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_GQS_2025
  Codes attendus : {'GQS AC', 'GQS'}
  Codes trouvés  : {'GQS'}
  Codes manquants: {'GQS AC'}

===== Somme globale par indicateur =====
Maraude Nb_SOLIDAR : 8268
Maraude Nb_SOLIDAR2020 : 6076
AEO Nb_AAD : 1207
AEO Nb_FAAD : 52
Dispositifs_d_urgence Nb_formes_TCAU_2025 : 12345
Dispositifs_d_urgence Nb_formes_TCEO_2025 : 1815
Dispositifs_d_urgence Nb_formes_PSP_2025 : 5009
Dispositifs_d_urgence Nb_formes_IRR_2025 : 26971
Dispositifs_d_urgence Nb_formes_GQS_2025 : 28110

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_formes_PSC_2025
  Codes attendus : {'RECPSC1', 'PSC1', 'EPSC1', 'PSC', 'PSC AC', 'PSC1 AC', 'PSC IRR', 'PSC1 IRR', 'EPSC'}
  Codes trouvés  : {'RECPSC1', 'PSC1', 'PSC', 'PSC AC', 'PSC1 IRR', 'PSC1 AC', 'PSC IRR', 'EPSC1', 'EPSC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_GQS_2025
  Codes attendus : {'GQS AC', 'GQS'}
  Codes trouvés  : {'GQS AC', 'GQS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_IPS_2025
  Codes attendus : {'IPS', 'IPS AC', 'IPSM', 'IPSJP', 'IPSP', 'IPS SR', 'IPSEF', 'IPSE', 'IPSJ'}
  Codes trouvés  : {'IPS', 'IPS AC', 'IPSJP', 'IPSP', 'IPS SR', 'IPSEF', 'IPSE', 'IPSJ'}
  Codes manquants: {'IPSM'}

Indicateur : Formation_grand_public Nb_formes_IPSEN_2025
  Codes attendus : {'IPSEN'}
  Codes trouvés  : {'IPSEN'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_PREVIC_2025
  Codes attendus : {'PREVIC'}
  Codes trouvés  : {'PREVIC'}
  Codes manquants: set()

Indicateur : Structure Nb_formes_CRB_2025
  Codes attendus : {'CRB', 'VI', 'ECRB'}
  Codes trouvés  : {'CRB', 'ECRB'}
  Codes manquants: {'VI'}

Indicateur : Structure Nb_formateurs_CRB_2025
  Codes attendus : {'ACRB2', 'ACRB3', 'ACRB', 'ACRB2024'}
  Codes trouvés  : {'ACRB2', 'ACRB2024'}
  Codes manquants: {'ACRB3', 'ACRB'}

Indicateur : Structure Nb_formes_TCAS_2025
  Codes attendus : {'ETCAS', 'TCAS'}
  Codes trouvés  : {'ETCAS', 'TCAS'}
  Codes manquants: set()

===== Somme globale par indicateur =====
Formation_grand_public Nb_formes_PSC_2025 : 69328
Formation_grand_public Nb_formes_GQS_2025 : 77503
Formation_grand_public Nb_formes_IPS_2025 : 89331
Formation_grand_public Nb_formes_IPSEN_2025 : 8229
Formation_grand_public Nb_formes_PREVIC_2025 : 139
Structure Nb_formes_CRB_2025 : 3132
Structure Nb_formateurs_CRB_2025 : 127
Structure Nb_formes_TCAS_2025 : 2179

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_formes_PSC_2025
  Codes attendus : {'RECPSC1', 'PSC1', 'EPSC1', 'PSC', 'PSC AC', 'PSC1 AC', 'PSC IRR', 'PSC1 IRR', 'EPSC'}
  Codes trouvés  : {'RECPSC1', 'PSC1', 'PSC', 'PSC AC', 'PSC1 IRR', 'PSC1 AC', 'PSC IRR', 'EPSC1', 'EPSC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_GQS_2025
  Codes attendus : {'GQS AC', 'GQS'}
  Codes trouvés  : {'GQS AC', 'GQS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_IPS_2025
  Codes attendus : {'IPS', 'IPS AC', 'IPSM', 'IPSJP', 'IPSP', 'IPS SR', 'IPSEF', 'IPSE', 'IPSJ'}
  Codes trouvés  : {'IPS', 'IPS AC', 'IPSJP', 'IPSP', 'IPS SR', 'IPSEF', 'IPSE', 'IPSJ'}
  Codes manquants: {'IPSM'}

Indicateur : Formation_grand_public Nb_formes_IPSEN_2025
  Codes attendus : {'IPSEN'}
  Codes trouvés  : {'IPSEN'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_PREVIC_2025
  Codes attendus : {'PREVIC'}
  Codes trouvés  : {'PREVIC'}
  Codes manquants: set()

Indicateur : Structure Nb_formes_CRB_2025
  Codes attendus : {'CRB', 'VI', 'ECRB'}
  Codes trouvés  : {'CRB', 'ECRB'}
  Codes manquants: {'VI'}

Indicateur : Structure Nb_formateurs_CRB_2025
  Codes attendus : {'ACRB2', 'ACRB3', 'ACRB', 'ACRB2024'}
  Codes trouvés  : {'ACRB2', 'ACRB2024'}
  Codes manquants: {'ACRB3', 'ACRB'}

Indicateur : Structure Nb_formes_TCAS_2025
  Codes attendus : {'ETCAS', 'TCAS'}
  Codes trouvés  : {'ETCAS', 'TCAS'}
  Codes manquants: set()

===== Somme globale par indicateur =====
Formation_grand_public Nb_formes_PSC_2025 : 69342
Formation_grand_public Nb_formes_GQS_2025 : 77508
Formation_grand_public Nb_formes_IPS_2025 : 89334
Formation_grand_public Nb_formes_IPSEN_2025 : 8228
Formation_grand_public Nb_formes_PREVIC_2025 : 140
Structure Nb_formes_CRB_2025 : 3133
Structure Nb_formateurs_CRB_2025 : 128
Structure Nb_formes_TCAS_2025 : 2179

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_sessions_PSC_2025
  Codes attendus : {'RECPSC1', 'PSC1', 'EPSC1', 'PSC', 'PSC AC', 'PSC1 AC', 'PSC IRR', 'PSC1 IRR', 'EPSC'}
  Codes trouvés  : {'RECPSC1', 'PSC1', 'PSC', 'PSC AC', 'PSC1 IRR', 'PSC1 AC', 'PSC IRR', 'EPSC1', 'EPSC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_GQS_2025
  Codes attendus : {'GQS AC', 'GQS'}
  Codes trouvés  : {'GQS AC', 'GQS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_IPS_2025
  Codes attendus : {'IPS', 'IPS AC', 'IPSM', 'IPSJP', 'IPSP', 'IPS SR', 'IPSEF', 'IPSE', 'IPSJ'}
  Codes trouvés  : {'IPS', 'IPS AC', 'IPSJP', 'IPSP', 'IPS SR', 'IPSEF', 'IPSE', 'IPSJ'}
  Codes manquants: {'IPSM'}

Indicateur : Formation_grand_public Nb_sessions_IPSEN_2025
  Codes attendus : {'IPSEN'}
  Codes trouvés  : {'IPSEN'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_PREVIC_2025
  Codes attendus : {'PREVIC'}
  Codes trouvés  : {'PREVIC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_PSE
  Codes attendus : {'RECPSE2', 'RATPSE1', 'PSE', 'APTE PSE1', 'RATPSE2', 'PSE2', 'PSE1', 'RECPSE1'}
  Codes trouvés  : {'RECPSE2', 'RATPSE1', 'PSE', 'RATPSE2', 'PSE2', 'PSE1', 'RECPSE1', 'APTE PSE1'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_CI
  Codes attendus : {'CI', 'CIP3', 'CI EXT', 'FCCI', 'RECCI', 'CI P1 P2', 'REC PSECI', 'RATCI', 'RECPSECI', 'CIP2', 'CIP1'}
  Codes trouvés  : {'CI', 'CIP3', 'FCCI', 'RECCI', 'RATCI'}
  Codes manquants: {'CI EXT', 'CI P1 P2', 'REC PSECI', 'RECPSECI', 'CIP2', 'CIP1'}

Indicateur : Formation_grand_public Nb_sessions_FPSE
  Codes attendus : {'RECFPS', 'FPSE', 'FPS', 'RATFCFPSE', 'FCFPSE'}
  Codes trouvés  : {'RECFPS', 'FPSE', 'FPS', 'RATFCFPSE', 'FCFPSE'}
  Codes manquants: set()

===== Somme globale par indicateur =====
Formation_grand_public Nb_sessions_PSC_2025 : 8238
Formation_grand_public Nb_sessions_GQS_2025 : 9066
Formation_grand_public Nb_sessions_IPS_2025 : 10452
Formation_grand_public Nb_sessions_IPSEN_2025 : 1014
Formation_grand_public Nb_sessions_PREVIC_2025 : 25
Formation_grand_public Nb_sessions_PSE : 1288
Formation_grand_public Nb_sessions_CI : 349
Formation_grand_public Nb_sessions_FPSE : 132

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_sessions_PSC_2025
  Codes attendus : {'RECPSC1', 'PSC1', 'EPSC1', 'PSC', 'PSC AC', 'PSC1 AC', 'PSC IRR', 'PSC1 IRR', 'EPSC'}
  Codes trouvés  : {'RECPSC1', 'PSC1', 'PSC', 'PSC AC', 'PSC1 IRR', 'PSC1 AC', 'PSC IRR', 'EPSC1', 'EPSC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_GQS_2025
  Codes attendus : {'GQS AC', 'GQS'}
  Codes trouvés  : {'GQS AC', 'GQS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_IPS_2025
  Codes attendus : {'IPS', 'IPS AC', 'IPSM', 'IPSJP', 'IPSP', 'IPS SR', 'IPSEF', 'IPSE', 'IPSJ'}
  Codes trouvés  : {'IPS', 'IPS AC', 'IPSJP', 'IPSP', 'IPS SR', 'IPSEF', 'IPSE', 'IPSJ'}
  Codes manquants: {'IPSM'}

Indicateur : Formation_grand_public Nb_sessions_IPSEN_2025
  Codes attendus : {'IPSEN'}
  Codes trouvés  : {'IPSEN'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_PREVIC_2025
  Codes attendus : {'PREVIC'}
  Codes trouvés  : {'PREVIC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_PSE
  Codes attendus : {'RECPSE2', 'RATPSE1', 'PSE', 'APTE PSE1', 'RATPSE2', 'PSE2', 'PSE1', 'RECPSE1'}
  Codes trouvés  : {'RECPSE2', 'RATPSE1', 'PSE', 'RATPSE2', 'PSE2', 'PSE1', 'RECPSE1', 'APTE PSE1'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_CI
  Codes attendus : {'CI', 'CIP3', 'CI EXT', 'FCCI', 'RECCI', 'CI P1 P2', 'REC PSECI', 'RATCI', 'RECPSECI', 'CIP2', 'CIP1'}
  Codes trouvés  : {'CI', 'CIP3', 'FCCI', 'RECCI', 'RATCI'}
  Codes manquants: {'CI EXT', 'CI P1 P2', 'REC PSECI', 'RECPSECI', 'CIP2', 'CIP1'}

Indicateur : Formation_grand_public Nb_sessions_FPSE
  Codes attendus : {'RECFPS', 'FPSE', 'FPS', 'RATFCFPSE', 'FCFPSE'}
  Codes trouvés  : {'RECFPS', 'FPSE', 'FPS', 'RATFCFPSE', 'FCFPSE'}
  Codes manquants: set()

===== Somme globale par indicateur =====
Formation_grand_public Nb_sessions_PSC_2025 : 8238
Formation_grand_public Nb_sessions_GQS_2025 : 9066
Formation_grand_public Nb_sessions_IPS_2025 : 10452
Formation_grand_public Nb_sessions_IPSEN_2025 : 1014
Formation_grand_public Nb_sessions_PREVIC_2025 : 25
Formation_grand_public Nb_sessions_PSE : 1288
Formation_grand_public Nb_sessions_CI : 349
Formation_grand_public Nb_sessions_FPSE : 132

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_FPSC
  Codes attendus : {'RATFCFPSC', 'FCFPSC'}
  Codes trouvés  : {'RATFCFPSC', 'FCFPSC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_AGQS
  Codes attendus : {'AGQS'}
  Codes trouvés  : {'AGQS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_FIPSEN
  Codes attendus : {'RECFIPSEN', 'FIPSEN'}
  Codes trouvés  : {'FIPSEN'}
  Codes manquants: {'RECFIPSEN'}

Indicateur : Secours Nb_PSE1
  Codes attendus : {'RATPSE1', 'PSE', 'APTE PSE1', 'PSE1', 'RECPSE1'}
  Codes trouvés  : {'RATPSE1', 'PSE', 'APTE PSE1', 'PSE1', 'RECPSE1'}
  Codes manquants: set()

Indicateur : Secours Nb_PSE2
  Codes attendus : {'PSE', 'RATPSE2', 'RECPSE2', 'PSE2'}
  Codes trouvés  : {'PSE', 'RECPSE2', 'RATPSE2', 'PSE2'}
  Codes manquants: set()

Indicateur : Secours Nb_CI
  Codes attendus : {'CI', 'CIP3', 'CI EXT', 'FCCI', 'RECCI', 'CI P1 P2', 'REC PSECI', 'RATCI', 'RECPSECI', 'CIP2', 'CIP1'}
  Codes trouvés  : {'CI', 'CIP3', 'FCCI', 'RECCI', 'RATCI'}
  Codes manquants: {'CI EXT', 'CI P1 P2', 'REC PSECI', 'RECPSECI', 'CIP2', 'CIP1'}

===== Somme globale par indicateur =====
Formation_grand_public Nb_FPSC : 1939
Formation_grand_public Nb_AGQS : 334
Formation_grand_public Nb_FIPSEN : 351
Secours Nb_PSE1 : 5045
Secours Nb_PSE2 : 8174
Secours Nb_CI : 1761

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_FPSC
  Codes attendus : {'RATFCFPSC', 'FCFPSC'}
  Codes trouvés  : {'RATFCFPSC', 'FCFPSC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_AGQS
  Codes attendus : {'AGQS'}
  Codes trouvés  : {'AGQS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_FIPSEN
  Codes attendus : {'RECFIPSEN', 'FIPSEN'}
  Codes trouvés  : {'FIPSEN'}
  Codes manquants: {'RECFIPSEN'}

Indicateur : Secours Nb_PSE1
  Codes attendus : {'RATPSE1', 'PSE', 'APTE PSE1', 'PSE1', 'RECPSE1'}
  Codes trouvés  : {'RATPSE1', 'PSE', 'APTE PSE1', 'PSE1', 'RECPSE1'}
  Codes manquants: set()

Indicateur : Secours Nb_PSE2
  Codes attendus : {'PSE', 'RATPSE2', 'RECPSE2', 'PSE2'}
  Codes trouvés  : {'PSE', 'RECPSE2', 'RATPSE2', 'PSE2'}
  Codes manquants: set()

Indicateur : Secours Nb_CI
  Codes attendus : {'CI', 'CIP3', 'CI EXT', 'FCCI', 'RECCI', 'CI P1 P2', 'REC PSECI', 'RATCI', 'RECPSECI', 'CIP2', 'CIP1'}
  Codes trouvés  : {'CI', 'CIP3', 'FCCI', 'RECCI', 'RATCI'}
  Codes manquants: {'CI EXT', 'CI P1 P2', 'REC PSECI', 'RECPSECI', 'CIP2', 'CIP1'}

===== Somme globale par indicateur =====
Formation_grand_public Nb_FPSC : 1939
Formation_grand_public Nb_AGQS : 334
Formation_grand_public Nb_FIPSEN : 351
Secours Nb_PSE1 : 5045
Secours Nb_PSE2 : 8174
Secours Nb_CI : 1761

===== Vérification des codes =====

Indicateur : Maraude Nb_benevoles_actifs_formes
  Codes attendus : {'SOLIDAR2020', 'SOLIDAR1', 'SOLIDAR2', 'SOLIDAR', 'PASSOLIDAR2020', 'ESOLIDAR2026'}
  Codes trouvés  : {'SOLIDAR2020', 'SOLIDAR1', 'SOLIDAR2', 'SOLIDAR', 'PASSOLIDAR2020', 'ESOLIDAR2026'}
  Codes manquants: set()

===== Somme globale par indicateur =====
Maraude Nb_benevoles_actifs_formes : 1937

===== Vérification des codes =====

Indicateur : Maraude Nb_benevoles_actifs_formes
  Codes attendus : {'SOLIDAR2020', 'SOLIDAR1', 'SOLIDAR2', 'SOLIDAR', 'PASSOLIDAR2020', 'ESOLIDAR2026'}
  Codes trouvés  : {'SOLIDAR2020', 'SOLIDAR1', 'SOLIDAR2', 'SOLIDAR', 'PASSOLIDAR2020', 'ESOLIDAR2026'}
  Codes manquants: set()

===== Somme globale par indicateur =====
Maraude Nb_benevoles_actifs_formes : 1554

===== Vérification des codes =====

Indicateur : Nb_IS
  Codes attendus : {'RATPSE1', 'RECPSE2', 'PSE', 'RECCI', 'RATCI', 'PSE1', 'CIP3', 'CI EXT', 'FCCI', 'RATPSE2', 'CI P1 P2', 'CIP2', 'APTE PSE1', 'CI', 'REC PSECI', 'RECPSECI', 'PSE2', 'CIP1', 'RECPSE1'}
  Codes trouvés  : {'CI', 'CIP3', 'RECPSE2', 'RATPSE1', 'PSE', 'FCCI', 'RATPSE2', 'RECCI', 'RATCI', 'CI P1 P2', 'PSE2', 'PSE1', 'RECPSECI', 'CIP2', 'RECPSE1', 'CIP1', 'APTE PSE1'}
  Codes manquants: {'CI EXT', 'REC PSECI'}

===== Somme globale par indicateur =====
Nb_IS : 8830

===== Vérification des codes =====

Indicateur : Nb_IS
  Codes attendus : {'RATPSE1', 'RECPSE2', 'PSE', 'RECCI', 'RATCI', 'PSE1', 'CIP3', 'CI EXT', 'FCCI', 'RATPSE2', 'CI P1 P2', 'CIP2', 'APTE PSE1', 'CI', 'REC PSECI', 'RECPSECI', 'PSE2', 'CIP1', 'RECPSE1'}
  Codes trouvés  : {'CI', 'CIP3', 'RECPSE2', 'RATPSE1', 'PSE', 'FCCI', 'RATPSE2', 'RECCI', 'RATCI', 'CI P1 P2', 'PSE2', 'PSE1', 'RECPSECI', 'CIP2', 'RECPSE1', 'CIP1', 'APTE PSE1'}
  Codes manquants: {'CI EXT', 'REC PSECI'}

===== Somme globale par indicateur =====
Nb_IS : 5241

===== Vérification des codes =====

Indicateur : Structure Nb_nvx_formes_CRB_2025
  Codes attendus : {'CRB', 'VI', 'ECRB'}
  Codes trouvés  : {'CRB', 'ECRB'}
  Codes manquants: {'VI'}

===== Somme globale par indicateur =====
Structure Nb_nvx_formes_CRB_2025 : 1592

===== Vérification des codes =====

Indicateur : Structure Nb_nvx_formes_CRB_2025
  Codes attendus : {'CRB', 'VI', 'ECRB'}
  Codes trouvés  : {'CRB', 'ECRB'}
  Codes manquants: {'VI'}

===== Somme globale par indicateur =====
Structure Nb_nvx_formes_CRB_2025 : 1592

## DPS

In [64]:
df_indicateurs_dps = indicateurs_dps(df_dps, df_ref_structure)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

===== Somme globale par indicateur DPS =====
Secours Nb_PAPS_2025 : 10938.5
Secours Nb_DPS_PE_2025 : 28004.5
Secours Nb_DPS_ME_2025 : 9268.0
Secours Nb_DPS_GE_2025 : 4258.0
Secours Nb_DPS_2025 : 52469.0

In [ ]:
verifications_dps(df_conventions, df_indicateurs_dps)

# Création du DataFrame final

In [65]:
df_ref_structure

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,Structure_de_rattachement,Rattachements_successifs,DT_de_rattachement,lon,lat
0,2615,ANTENNE LOCALE - AL,AL DE DELLE,90100.0,90033,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",90,2010-02-08 00:00:00,NaT,95 - DT DU TERRITOIRE DE BELFORT,AL 2615,95 - DT DU TERRITOIRE DE BELFORT,7.000705,47.506725
1,2669,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43220.0,43087,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2669,48 - DT DE LA HAUTE LOIRE,4.346423,45.214392
2,2670,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43600.0,43224,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2670,48 - DT DE LA HAUTE LOIRE,4.235474,45.242445
3,2671,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43300.0,43112,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2671,48 - DT DE LA HAUTE LOIRE,3.495645,45.098285
4,2672,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43000.0,43157,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2672,48 - DT DE LA HAUTE LOIRE,3.879748,45.044677
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1193,993,UNITE LOCALE - UL,UL DE HAUTE PICARDIE,80320.0,80186,CHAULNES,"36 Avenue Roger Salengro, 80320 CHAULNES",80,1919-12-10 00:00:00,NaT,85 - DT DE LA SOMME,UL 993,85 - DT DE LA SOMME,2.803641,49.815545
1194,995,UNITE LOCALE - UL,UL DE DOULLENNAIS,80600.0,80253,DOULLENS,"1 Avenue du Général de Gaulle, 80600 DOULLENS",80,1916-12-10 00:00:00,NaT,85 - DT DE LA SOMME,UL 995,85 - DT DE LA SOMME,2.334222,50.161354
1195,996,UNITE LOCALE - UL,UL DU PAYS HAMOIS,80400.0,80410,HAM,"25 Boulevard du Général de Gaulle, 80400 HAM",80,1894-12-10 00:00:00,NaT,85 - DT DE LA SOMME,UL 996,85 - DT DE LA SOMME,3.070287,49.748496
1196,998,UNITE LOCALE - UL,UL DU VAL D'AVRE,80500.0,80561,MONTDIDIER,"6 Rue AMAND DE VIENNE, 80500 MONTDIDIER",80,1914-12-10 00:00:00,NaT,85 - DT DE LA SOMME,UL 998,85 - DT DE LA SOMME,2.573187,49.647729
1197,999,UNITE LOCALE - UL,UL DU PAYS NESLOIS,80190.0,80585,NESLE,"2 bis Avenue Clémenceau, 80190 NESLE",80,1917-12-10 00:00:00,NaT,85 - DT DE LA SOMME,UL 999,85 - DT DE LA SOMME,2.909659,49.762293

La liste de tous les dataframes à fusionner sur df_ref_structure

In [66]:
# On ne filtre pas les implantations locales avant à cause du rattachement successif
df_ref_structure = df_ref_structure[df_ref_structure["type_structure"].isin(["UNITE LOCALE - UL", "DELEGATION TERRITORIALE - DT", 'ANTENNE LOCALE - AL','INSTANCES NATIONALES - IN'])]

In [67]:
liste_df_a_fusionner_toutes_structures = [nb_benevoles,nb_nvx_benevoles,referents_AEO,referents_OCR, IMPACT_ppc, IMPACT_agrementAB, IMPACT_agrementDPS,
                                          df_mobilite_DT_UL,df_OCR_Nb_deployees, df_redcall2,
                                          df_raw_Textile, df_alim_U2A_sans_doublons, df_alim_epicerie_sociale,
                                          df_alim_accueil_alimentaire, df_alim_crsr, df_adherent, df_personnes_domiciliees_struct, df_Nb_maraudes_SIGMA_struct,
                                          df_nb_personnes_rencontrees_SIGMA_struct, df_nb_contacts_SIGMA_struct, indicateurs_base_contact,
                                          df_financier_DT_UL,df_Secours_ProduitsDPS, df_raw_ProdResTextile,
                                          pegass_output['Indics_pegass_struct'], df_indicateurs_dps]

liste_df_a_fusionner_DT = [nb_benevoles_DT,nb_nvx_benevoles_DT,referents_AEO_DT,referents_OCR_DT,
                           IMPACT_ppc_DT, IMPACT_agrementAB_DT, IMPACT_agrementDPS_DT,df_mobilite_DT,Nb_OCR_DT,RedCall_DT,df_Dispositifs_d_urgence_PST, df_declenchement3,
                           df_CAICHUCMCC_VF, df_conventions2,
                           df_Textile_DT, df_alim_U2A_DT, df_alim_epicerie_sociale_DT, df_alim_accueil_alimentaire_DT, df_alim_crsr_DT, df_adherent_DT,
                           df_personnes_domiciliees_DT,df_Nb_maraudes_SIGMA_DT,df_nb_personnes_rencontrees_SIGMA_DT,df_nb_contacts_SIGMA_DT, indicateurs_base_contact_DT,
                           df_financier_DT,df_financier_DPS_DT,df_financier_FGP_DT, df_Textile_financier_DT,pegass_output['Indics_pegass_DT'], df_indicateurs_dps]

In [68]:
all_data, all_data_DT, liste_df_a_fusionner_toutes_structures_processed, liste_df_a_fusionner_DT_processed = traitement_all_data(liste_df_a_fusionner_toutes_structures, liste_df_a_fusionner_DT, df_ref_structure,df_ref_structure_DT)

TRAITEMENT DES INDICATEURS POUR TOUTES LES STRUCTURES

🧹 DataFrame 16 : suppression des colonnes ['DT_de_rattachement']
🧹 DataFrame 17 : suppression des colonnes ['DT_de_rattachement']
🧹 DataFrame 18 : suppression des colonnes ['DT_de_rattachement']
🧹 DataFrame 19 : suppression des colonnes ['DT_de_rattachement']
🧹 DataFrame 21 : suppression des colonnes ['libelle_structure']
🧹 DataFrame 24 : suppression des colonnes ['IS Nb_benevoles_actifs']
🧹 DataFrame 25 : suppression des colonnes ['Departement', 'nom_structure']
✅ DataFrame 0 : aucun doublon dans 'n_structure'
✅ DataFrame 1 : aucun doublon dans 'n_structure'
✅ DataFrame 2 : aucun doublon dans 'n_structure'
✅ DataFrame 3 : aucun doublon dans 'n_structure'
✅ DataFrame 4 : aucun doublon dans 'n_structure'
✅ DataFrame 5 : aucun doublon dans 'n_structure'
✅ DataFrame 6 : aucun doublon dans 'n_structure'
✅ DataFrame 7 : aucun doublon dans 'n_structure'
✅ DataFrame 8 : aucun doublon dans 'n_structure'
✅ DataFrame 9 : aucun doublon dans 'n_structure'
✅ DataFrame 10 : aucun doublon dans 'n_structure'
✅ DataFrame 11 : aucun doublon dans 'n_structure'
✅ DataFrame 12 : aucun doublon dans 'n_structure'
✅ DataFrame 13 : aucun doublon dans 'n_structure'
✅ DataFrame 14 : aucun doublon dans 'n_structure'
✅ DataFrame 15 : aucun doublon dans 'n_structure'
✅ DataFrame 16 : aucun doublon dans 'n_structure'
✅ DataFrame 17 : aucun doublon dans 'n_structure'
✅ DataFrame 18 : aucun doublon dans 'n_structure'
✅ DataFrame 19 : aucun doublon dans 'n_structure'
✅ DataFrame 20 : aucun doublon dans 'n_structure'
✅ DataFrame 21 : aucun doublon dans 'n_structure'
✅ DataFrame 22 : aucun doublon dans 'n_structure'
✅ DataFrame 23 : aucun doublon dans 'n_structure'
✅ DataFrame 24 : aucun doublon dans 'n_structure'
✅ DataFrame 25 : aucun doublon dans 'n_structure'
TRAITEMENT DES INDICATEURS POUR LES DTs

🧹 DataFrame 10 : suppression des colonnes ['Territoire', 'PST constitué', 'Nom structure DT', 'N° Département', 'nom_structure']
🧹 DataFrame 11 : suppression des colonnes ['Département', 'Etablissements', 'Exercice', 'Fonctionnement', 'Opérations', 'Grand Total', 'Unnamed: 6', 'n_dept', 'DT', 'nom_structure']
🧹 DataFrame 12 : suppression des colonnes ['Dépt', 'Région', 'Département', 'nom_structure']
🧹 DataFrame 13 : suppression des colonnes ['Departement', 'nom_structure']
🧹 DataFrame 25 : suppression des colonnes ['n_dept', 'libelle_structure']
🧹 DataFrame 27 : suppression des colonnes ['n_dept']
🧹 DataFrame 29 : suppression des colonnes ['nb_activite_AEO', 'IS Nb_benevoles_actifs']
🧹 DataFrame 30 : suppression des colonnes ['Departement', 'nom_structure']
✅ DataFrame 0 : aucun doublon dans 'n_structure'
✅ DataFrame 1 : aucun doublon dans 'n_structure'
✅ DataFrame 2 : aucun doublon dans 'n_structure'
✅ DataFrame 3 : aucun doublon dans 'n_structure'
✅ DataFrame 4 : aucun doublon dans 'n_structure'
✅ DataFrame 5 : aucun doublon dans 'n_structure'
✅ DataFrame 6 : aucun doublon dans 'n_structure'
✅ DataFrame 7 : aucun doublon dans 'n_structure'
✅ DataFrame 8 : aucun doublon dans 'n_structure'
✅ DataFrame 9 : aucun doublon dans 'n_structure'
✅ DataFrame 10 : aucun doublon dans 'n_structure'
✅ DataFrame 11 : aucun doublon dans 'n_structure'
✅ DataFrame 12 : aucun doublon dans 'n_structure'
✅ DataFrame 13 : aucun doublon dans 'n_structure'
✅ DataFrame 14 : aucun doublon dans 'n_structure'
✅ DataFrame 15 : aucun doublon dans 'n_structure'
✅ DataFrame 16 : aucun doublon dans 'n_structure'
✅ DataFrame 17 : aucun doublon dans 'n_structure'
✅ DataFrame 18 : aucun doublon dans 'n_structure'
✅ DataFrame 19 : aucun doublon dans 'n_structure'
✅ DataFrame 20 : aucun doublon dans 'n_structure'
✅ DataFrame 21 : aucun doublon dans 'n_structure'
✅ DataFrame 22 : aucun doublon dans 'n_structure'
✅ DataFrame 23 : aucun doublon dans 'n_structure'
✅ DataFrame 24 : aucun doublon dans 'n_structure'
✅ DataFrame 25 : aucun doublon dans 'n_structure'
✅ DataFrame 26 : aucun doublon dans 'n_structure'
✅ DataFrame 27 : aucun doublon dans 'n_structure'
✅ DataFrame 28 : aucun doublon dans 'n_structure'
✅ DataFrame 29 : aucun doublon dans 'n_structure'
✅ DataFrame 30 : aucun doublon dans 'n_structure'

In [69]:
report = check_sums_against_final(
    df_final=all_data,
    list_of_dfs=liste_df_a_fusionner_toutes_structures,
    key_col="n_structure",
    atol=1e-6
)

🔎 Vérification DataFrame 0
   ✅ 'Structure Nb_Benevoles' OK | individuel = 96753.0 | final = 96753.0

🔎 Vérification DataFrame 1
   ✅ 'Structure Nb_nvx_Benevoles_2025' OK | individuel = 20668.0 | final = 20668.0

🔎 Vérification DataFrame 2
   ✅ 'AEO Nb_responsables' OK | individuel = 41.0 | final = 41.0

🔎 Vérification DataFrame 3
   ✅ 'OCR Nb_referents' OK | individuel = 21.0 | final = 21.0

🔎 Vérification DataFrame 4
   ✅ 'Dispositifs_d_urgence Nb_personnes_prises_charge' OK | individuel = 15418.0 | final = 15418.0

🔎 Vérification DataFrame 5
   ✅ 'Dispositifs_d_urgence Nb_agrements' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 6
   ✅ 'Secours Nb_agrements_DPS_2025' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 7
   ✅ 'AEO Structure_activite_mobile' OK | individuel = 216.0 | final = 216.0
   ✅ 'AEO Nb_PA_dispos_mobiles' OK | individuel = 17208.0 | final = 17208.0

🔎 Vérification DataFrame 8
   ✅ 'OCR Nb_deployees' OK | individuel = 80.0 | final = 80.0

🔎 Vérification DataFrame 9
   ✅ 'Dispositifs_d_urgence Utilisation_RedCall' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 10
   ✅ 'Textile Nb_dispositifs' OK | individuel = 895.0 | final = 895.0

🔎 Vérification DataFrame 11
   ✅ 'Aide_alimentaire Nb_U2A' OK | individuel = 627.0 | final = 627.0

🔎 Vérification DataFrame 12
   ✅ 'Aide_alimentaire Nb_epiceries_sociales' OK | individuel = 77.0 | final = 77.0

🔎 Vérification DataFrame 13
   ✅ 'Aide_alimentaire Nb_Centre_distribution_alimentaire' OK | individuel = 510.0 | final = 510.0

🔎 Vérification DataFrame 14
   ✅ 'Aide_alimentaire Nb_crsr' OK | individuel = 40.0 | final = 40.0

🔎 Vérification DataFrame 15
   ✅ 'Structure Nb_Adherents' OK | individuel = 47403.0 | final = 47403.0

🔎 Vérification DataFrame 16
   ✅ 'AEO Nb_personnes_domiciliees_crf' OK | individuel = 30833.0 | final = 30833.0

🔎 Vérification DataFrame 17
   ✅ 'Maraude Nb_maraudes_SIGMA' OK | individuel = 7879.0 | final = 7879.0

🔎 Vérification DataFrame 18
   ✅ 'Maraude Nb_personnes_rencontrees' OK | individuel = 102013.0 | final = 102013.0

🔎 Vérification DataFrame 19
   ✅ 'Maraude Nb_contacts' OK | individuel = 127109.0 | final = 127109.0

🔎 Vérification DataFrame 20
   ✅ 'Maraude Nb_SOLIDAR' OK | individuel = 8201.0 | final = 8201.0
   ✅ 'Maraude Nb_SOLIDAR2020' OK | individuel = 6032.0 | final = 6032.0
   ✅ 'AEO Nb_AAD' OK | individuel = 1202.0 | final = 1202.0
   ✅ 'AEO Nb_FAAD' OK | individuel = 51.0 | final = 51.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCAU_2025' OK | individuel = 12295.0 | final = 12295.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCEO_2025' OK | individuel = 1789.0 | final = 1789.0
   ✅ 'Dispositifs_d_urgence Nb_formes_PSP_2025' OK | individuel = 4998.0 | final = 4998.0
   ✅ 'Dispositifs_d_urgence Nb_formes_IRR_2025' OK | individuel = 26722.0 | final = 26722.0
   ✅ 'Dispositifs_d_urgence Nb_formes_GQS_2025' OK | individuel = 27919.0 | final = 27919.0
   ✅ 'Formation_grand_public Nb_formes_PSC_2025' OK | individuel = 66792.0 | final = 66792.0
   ✅ 'Formation_grand_public Nb_formes_GQS_2025' OK | individuel = 74818.0 | final = 74818.0
   ✅ 'Formation_grand_public Nb_formes_IPS_2025' OK | individuel = 86540.0 | final = 86540.0
   ✅ 'Formation_grand_public Nb_formes_IPSEN_2025' OK | individuel = 8205.0 | final = 8205.0
   ✅ 'Formation_grand_public Nb_formes_PREVIC_2025' OK | individuel = 109.0 | final = 109.0
   ✅ 'Structure Nb_formes_CRB_2025' OK | individuel = 3115.0 | final = 3115.0
   ✅ 'Structure Nb_formateurs_CRB_2025' OK | individuel = 123.0 | final = 123.0
   ✅ 'Structure Nb_formes_TCAS_2025' OK | individuel = 2173.0 | final = 2173.0
   ✅ 'Formation_grand_public Nb_sessions_PSC_2025' OK | individuel = 7862.0 | final = 7862.0
   ✅ 'Formation_grand_public Nb_sessions_GQS_2025' OK | individuel = 8699.0 | final = 8699.0
   ✅ 'Formation_grand_public Nb_sessions_IPS_2025' OK | individuel = 10051.0 | final = 10051.0
   ✅ 'Formation_grand_public Nb_sessions_IPSEN_2025' OK | individuel = 1010.0 | final = 1010.0
   ✅ 'Formation_grand_public Nb_sessions_PREVIC_2025' OK | individuel = 13.0 | final = 13.0
   ✅ 'Formation_grand_public Nb_sessions_PSE' OK | individuel = 1151.0 | final = 1151.0
   ✅ 'Formation_grand_public Nb_sessions_CI' OK | individuel = 312.0 | final = 312.0
   ✅ 'Formation_grand_public Nb_sessions_FPSE' OK | individuel = 87.0 | final = 87.0
   ✅ 'Formation_grand_public Nb_FPSC' OK | individuel = 1936.0 | final = 1936.0
   ✅ 'Formation_grand_public Nb_AGQS' OK | individuel = 334.0 | final = 334.0
   ✅ 'Formation_grand_public Nb_FIPSEN' OK | individuel = 351.0 | final = 351.0
   ✅ 'Secours Nb_PSE1' OK | individuel = 5045.0 | final = 5045.0
   ✅ 'Secours Nb_PSE2' OK | individuel = 8173.0 | final = 8173.0
   ✅ 'Secours Nb_CI' OK | individuel = 1760.0 | final = 1760.0
   ✅ 'Secours Taux_recy26_PSE1' OK | individuel = 0.029411764705882353 | final = 0.029411764705882353
   ✅ 'Secours Taux_recy26_PSE2' OK | individuel = 0.0 | final = 0.0
   ✅ 'Secours Taux_recy26_CI' OK | individuel = 0.0 | final = 0.0
   ✅ 'Secours Taux_ren25_PSE1' OK | individuel = 241.05490722302278 | final = 241.05490722302275
   ✅ 'Secours Taux_ren25_PSE2' OK | individuel = 272.06679157827125 | final = 272.06679157827125
   ✅ 'Secours Taux_ren25_CI' OK | individuel = 134.2664454976568 | final = 134.26644549765678
   ✅ 'Maraude Nb_benevoles_actifs_formes' OK | individuel = 1841.0 | final = 1841.0
   ✅ 'Secours Taux_IS_actifs' OK | individuel = 163.69984195926997 | final = 163.69984195926997
   ✅ 'Structure Nb_nvx_formes_CRB_2025' OK | individuel = 1592.0 | final = 1592.0

🔎 Vérification DataFrame 21
   ✅ 'Financier Prod_2024' OK | individuel = 88893716.97999999 | final = 88893716.97999999
   ✅ 'Financier ResNet_2024' OK | individuel = 4610056.17 | final = 4610056.17
   ✅ 'Financier ResCorrProd_2024' OK | individuel = -38.49364332951876 | final = -38.493643329518775
   ✅ 'Financier TresoBrute_2024' OK | individuel = 112924889.4 | final = 112924889.39999999
   ✅ 'Financier Mois_AvanceTreso_2024' OK | individuel = 19621.90469935163 | final = 19621.904699351628

🔎 Vérification DataFrame 22
   ✅ 'Secours Produits_DPS_2025' OK | individuel = 8975398.0 | final = 8975398.0

🔎 Vérification DataFrame 23
   ✅ 'Textile Produit_2025' OK | individuel = 22573754.0 | final = 22573754.0
   ✅ 'Textile Resultat_2025' OK | individuel = 13470366.0 | final = 13470366.0

🔎 Vérification DataFrame 24
   ✅ 'nb_Maraude_Pegass' OK | individuel = 19392.0 | final = 19392.0
   ✅ 'Dispositifs_d_urgence Nb_operations' OK | individuel = 2442.0 | final = 2442.0
   ✅ 'Dispositifs_d_urgence Nb_exercices' OK | individuel = 269.0 | final = 269.0
   ✅ 'AEO Structure_activite_fixe' OK | individuel = 0.0 | final = 0.0
   ✅ 'Maraude Nb_benevoles_actifs' OK | individuel = 7900.0 | final = 7900.0
   ✅ 'AEO Nb_benevoles_actifs' OK | individuel = 1012.0 | final = 1012.0

🔎 Vérification DataFrame 25
   ✅ 'Secours Nb_PAPS_2025' OK | individuel = 10938.5 | final = 10938.5
   ✅ 'Secours Nb_DPS_PE_2025' OK | individuel = 28004.5 | final = 28004.5
   ✅ 'Secours Nb_DPS_ME_2025' OK | individuel = 9268.0 | final = 9268.0
   ✅ 'Secours Nb_DPS_GE_2025' OK | individuel = 4258.0 | final = 4258.0
   ✅ 'Secours Nb_DPS_2025' OK | individuel = 52469.0 | final = 52469.0

In [70]:
report = check_sums_against_final(
  df_final=all_data_DT,
  list_of_dfs=liste_df_a_fusionner_DT,
  key_col="n_structure",
  atol=1e-6
  )

🔎 Vérification DataFrame 0
   ✅ 'Structure Nb_Benevoles' OK | individuel = 96753.0 | final = 96753.0

🔎 Vérification DataFrame 1
   ✅ 'Structure Nb_nvx_Benevoles_2025' OK | individuel = 20668.0 | final = 20668.0

🔎 Vérification DataFrame 2
   ✅ 'AEO Nb_responsables' OK | individuel = 41.0 | final = 41.0

🔎 Vérification DataFrame 3
   ✅ 'OCR Nb_referents' OK | individuel = 21.0 | final = 21.0

🔎 Vérification DataFrame 4
   ✅ 'Dispositifs_d_urgence Nb_personnes_prises_charge' OK | individuel = 15418.0 | final = 15418.0

🔎 Vérification DataFrame 5
   ✅ 'Dispositifs_d_urgence Nb_agrements' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 6
   ✅ 'Secours Nb_agrements_DPS_2025' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 7
   ✅ 'AEO Structure_activite_mobile' OK | individuel = 216.0 | final = 216.0
   ✅ 'AEO Nb_PA_dispos_mobiles' OK | individuel = 17208.0 | final = 17208.0

🔎 Vérification DataFrame 8
   ✅ 'OCR Nb_deployees' OK | individuel = 80.0 | final = 80.0

🔎 Vérification DataFrame 9
   ✅ 'Dispositifs_d_urgence Utilisation_RedCall' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 10
   ✅ 'Dispositifs_d_urgence PST' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 11
   ✅ 'Dispositifs_d_urgence Nb_declenchements' OK | individuel = 602.0 | final = 602.0

🔎 Vérification DataFrame 12
   ✅ 'Dispositifs_d_urgence Nb_lots_CAI' OK | individuel = 239.0 | final = 239.0
   ✅ 'Dispositifs_d_urgence Nb_lots_CHU' OK | individuel = 174.0 | final = 174.0
   ✅ 'Dispositifs_d_urgence Nb_lots_CMCC' OK | individuel = 281.0 | final = 281.0

🔎 Vérification DataFrame 13
   ✅ 'Dispositifs_d_urgence Nb_conventions_prefecture' OK | individuel = 0.0 | final = 0.0
   ✅ 'Dispositifs_d_urgence Nb_conventions_operateurs' OK | individuel = 358.0 | final = 358.0

🔎 Vérification DataFrame 14
   ✅ 'Textile Nb_dispositifs' OK | individuel = 895.0 | final = 895.0

🔎 Vérification DataFrame 15
   ✅ 'Aide_alimentaire Nb_U2A' OK | individuel = 627.0 | final = 627.0

🔎 Vérification DataFrame 16
   ✅ 'Aide_alimentaire Nb_epiceries_sociales' OK | individuel = 77.0 | final = 77.0

🔎 Vérification DataFrame 17
   ✅ 'Aide_alimentaire Nb_Centre_distribution_alimentaire' OK | individuel = 510.0 | final = 510.0

🔎 Vérification DataFrame 18
   ✅ 'Aide_alimentaire Nb_crsr' OK | individuel = 40.0 | final = 40.0

🔎 Vérification DataFrame 19
   ✅ 'Structure Nb_Adherents' OK | individuel = 47403.0 | final = 47403.0

🔎 Vérification DataFrame 20
   ✅ 'AEO Nb_personnes_domiciliees_crf' OK | individuel = 30833.0 | final = 30833.0

🔎 Vérification DataFrame 21
   ✅ 'Maraude Nb_maraudes_SIGMA' OK | individuel = 7879.0 | final = 7879.0

🔎 Vérification DataFrame 22
   ✅ 'Maraude Nb_personnes_rencontrees' OK | individuel = 102013.0 | final = 102013.0

🔎 Vérification DataFrame 23
   ✅ 'Maraude Nb_contacts' OK | individuel = 127109.0 | final = 127109.0

🔎 Vérification DataFrame 24
   ✅ 'Maraude Nb_SOLIDAR' OK | individuel = 8201.0 | final = 8201.0
   ✅ 'Maraude Nb_SOLIDAR2020' OK | individuel = 6032.0 | final = 6032.0
   ✅ 'AEO Nb_AAD' OK | individuel = 1202.0 | final = 1202.0
   ✅ 'AEO Nb_FAAD' OK | individuel = 51.0 | final = 51.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCAU_2025' OK | individuel = 12295.0 | final = 12295.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCEO_2025' OK | individuel = 1789.0 | final = 1789.0
   ✅ 'Dispositifs_d_urgence Nb_formes_PSP_2025' OK | individuel = 4998.0 | final = 4998.0
   ✅ 'Dispositifs_d_urgence Nb_formes_IRR_2025' OK | individuel = 26722.0 | final = 26722.0
   ✅ 'Dispositifs_d_urgence Nb_formes_GQS_2025' OK | individuel = 27919.0 | final = 27919.0
   ✅ 'Formation_grand_public Nb_formes_PSC_2025' OK | individuel = 67359.0 | final = 67359.0
   ✅ 'Formation_grand_public Nb_formes_GQS_2025' OK | individuel = 75376.0 | final = 75376.0
   ✅ 'Formation_grand_public Nb_formes_IPS_2025' OK | individuel = 87087.0 | final = 87087.0
   ✅ 'Formation_grand_public Nb_formes_IPSEN_2025' OK | individuel = 8222.0 | final = 8222.0
   ✅ 'Formation_grand_public Nb_formes_PREVIC_2025' OK | individuel = 109.0 | final = 109.0
   ✅ 'Structure Nb_formes_CRB_2025' OK | individuel = 3115.0 | final = 3115.0
   ✅ 'Structure Nb_formateurs_CRB_2025' OK | individuel = 123.0 | final = 123.0
   ✅ 'Structure Nb_formes_TCAS_2025' OK | individuel = 2173.0 | final = 2173.0
   ✅ 'Formation_grand_public Nb_sessions_PSC_2025' OK | individuel = 7941.0 | final = 7941.0
   ✅ 'Formation_grand_public Nb_sessions_GQS_2025' OK | individuel = 8773.0 | final = 8773.0
   ✅ 'Formation_grand_public Nb_sessions_IPS_2025' OK | individuel = 10128.0 | final = 10128.0
   ✅ 'Formation_grand_public Nb_sessions_IPSEN_2025' OK | individuel = 1012.0 | final = 1012.0
   ✅ 'Formation_grand_public Nb_sessions_PREVIC_2025' OK | individuel = 13.0 | final = 13.0
   ✅ 'Formation_grand_public Nb_sessions_PSE' OK | individuel = 1191.0 | final = 1191.0
   ✅ 'Formation_grand_public Nb_sessions_CI' OK | individuel = 320.0 | final = 320.0
   ✅ 'Formation_grand_public Nb_sessions_FPSE' OK | individuel = 92.0 | final = 92.0
   ✅ 'Formation_grand_public Nb_FPSC' OK | individuel = 1936.0 | final = 1936.0
   ✅ 'Formation_grand_public Nb_AGQS' OK | individuel = 334.0 | final = 334.0
   ✅ 'Formation_grand_public Nb_FIPSEN' OK | individuel = 351.0 | final = 351.0
   ✅ 'Secours Nb_PSE1' OK | individuel = 5045.0 | final = 5045.0
   ✅ 'Secours Nb_PSE2' OK | individuel = 8173.0 | final = 8173.0
   ✅ 'Secours Nb_CI' OK | individuel = 1760.0 | final = 1760.0
   ✅ 'Secours Taux_recy26_PSE1' OK | individuel = 0.008403361344537815 | final = 0.008403361344537815
   ✅ 'Secours Taux_recy26_PSE2' OK | individuel = 0.0 | final = 0.0
   ✅ 'Secours Taux_recy26_CI' OK | individuel = 0.0 | final = 0.0
   ✅ 'Secours Taux_ren25_PSE1' OK | individuel = 47.04929429138176 | final = 47.04929429138176
   ✅ 'Secours Taux_ren25_PSE2' OK | individuel = 49.864534736692995 | final = 49.864534736692995
   ✅ 'Secours Taux_ren25_CI' OK | individuel = 29.97742468821853 | final = 29.97742468821853
   ✅ 'Maraude Nb_benevoles_actifs_formes' OK | individuel = 1494.0 | final = 1494.0
   ✅ 'Secours Taux_IS_actifs' OK | individuel = 43.34852831153891 | final = 43.34852831153891
   ✅ 'Structure Nb_nvx_formes_CRB_2025' OK | individuel = 1592.0 | final = 1592.0

🔎 Vérification DataFrame 25
   ✅ 'Financier Prod_2024' OK | individuel = 91392120.06 | final = 91392120.05999999
   ✅ 'Financier ResNet_2024' OK | individuel = 4605741.17 | final = 4605741.17
   ✅ 'Financier ResCorrProd_2024' OK | individuel = 6.12414552710691 | final = 6.124145527106909
   ✅ 'Financier TresoBrute_2024' OK | individuel = 137289986.72 | final = 137289986.72
   ✅ 'Financier Mois_AvanceTreso_2024' OK | individuel = 2458.6916621011387 | final = 2458.6916621011387

🔎 Vérification DataFrame 26
   ✅ 'Secours Produits_DPS_2025' OK | individuel = 8975398.0 | final = 8975398.0

🔎 Vérification DataFrame 27
   ✅ 'Formation_grand_public Produits_2025' OK | individuel = 88457195.10999998 | final = 88457195.10999998

🔎 Vérification DataFrame 28
   ✅ 'Textile Produit_2025' OK | individuel = 22573754.0 | final = 22573754.0
   ✅ 'Textile Resultat_2025' OK | individuel = 13470366.0 | final = 13470366.0

🔎 Vérification DataFrame 29
   ✅ 'nb_Maraude_Pegass' OK | individuel = 19392.0 | final = 19392.0
   ✅ 'Dispositifs_d_urgence Nb_operations' OK | individuel = 2442.0 | final = 2442.0
   ✅ 'Dispositifs_d_urgence Nb_exercices' OK | individuel = 269.0 | final = 269.0
   ✅ 'Maraude Nb_benevoles_actifs' OK | individuel = 7900.0 | final = 7900.0
   ✅ 'AEO Nb_benevoles_actifs' OK | individuel = 1012.0 | final = 1012.0
   ✅ 'AEO Structure_activite_fixe' OK | individuel = 126.0 | final = 126.0

🔎 Vérification DataFrame 30
   ✅ 'Secours Nb_PAPS_2025' OK | individuel = 10938.5 | final = 10938.5
   ✅ 'Secours Nb_DPS_PE_2025' OK | individuel = 28004.5 | final = 28004.5
   ✅ 'Secours Nb_DPS_ME_2025' OK | individuel = 9268.0 | final = 9268.0
   ✅ 'Secours Nb_DPS_GE_2025' OK | individuel = 4258.0 | final = 4258.0
   ✅ 'Secours Nb_DPS_2025' OK | individuel = 52469.0 | final = 52469.0

In [71]:
all_data, all_data_DT = vision_conso(all_data, all_data_DT)

In [72]:
all_data = ajouter_colonnes_taux(all_data, 'Structure Nb_Benevoles')
all_data_DT = ajouter_colonnes_taux(all_data_DT, 'Structure Nb_Benevoles')

In [73]:
all_data = ajouter_colonne_somme(all_data, 'AEO Nb_personnes_domiciliees_crf', 'AEO Nb_PA_dispos_mobiles')
all_data_DT = ajouter_colonne_somme(all_data_DT, 'AEO Nb_personnes_domiciliees_crf', 'AEO Nb_PA_dispos_mobiles')

In [74]:
all_data

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,...,Dispositifs_d_urgence Structures_menant_activite_GQS,AEO Structures_menant_activite,Formation_grand_public Structures_menant_activite,Dispositifs_d_urgence Taux_formation_TCAU_2025,Dispositifs_d_urgence Taux_formation_TCEO_2025,Dispositifs_d_urgence Taux_formation_PSP_2025,Dispositifs_d_urgence Taux_formation_IRR_2025,Dispositifs_d_urgence Taux_formation_GQS_2025,Structure Taux_formation_CRB,AEO Nb_PA_AEO_AAD
0,2615,ANTENNE LOCALE - AL,AL DE DELLE,90100.0,90033,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",90,2010-02-08 00:00:00,NaT,...,Action menée,Activité AEO/AAD non menée,Action non menée,0.000000,0.000000,0.000000,0.470588,0.470588,NaN,<NA>
1,2669,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43220.0,43087,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",43,2011-01-01 00:00:00,NaT,...,Action non menée,Activité AEO/AAD non menée,Action non menée,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
2,2670,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43600.0,43224,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",43,2011-01-01 00:00:00,NaT,...,Action non menée,Activité AEO/AAD non menée,Action non menée,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
3,2671,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43300.0,43112,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",43,2011-01-01 00:00:00,NaT,...,Action non menée,Activité AEO/AAD non menée,Action non menée,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
4,2672,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43000.0,43157,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",43,2011-01-01 00:00:00,NaT,...,Action non menée,Activité AEO/AAD non menée,Action non menée,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
852,993,UNITE LOCALE - UL,UL DE HAUTE PICARDIE,80320.0,80186,CHAULNES,"36 Avenue Roger Salengro, 80320 CHAULNES",80,1919-12-10 00:00:00,NaT,...,Action non menée,Activité AEO/AAD non menée,Action non menée,0.000000,0.000000,0.000000,0.095238,0.000000,NaN,<NA>
853,995,UNITE LOCALE - UL,UL DE DOULLENNAIS,80600.0,80253,DOULLENS,"1 Avenue du Général de Gaulle, 80600 DOULLENS",80,1916-12-10 00:00:00,NaT,...,Action menée,Activité AEO/AAD non menée,Action menée,0.192308,0.000000,0.000000,0.102564,0.102564,0.000000,<NA>
854,996,UNITE LOCALE - UL,UL DU PAYS HAMOIS,80400.0,80410,HAM,"25 Boulevard du Général de Gaulle, 80400 HAM",80,1894-12-10 00:00:00,NaT,...,Action non menée,Activité AEO/AAD non menée,Action non menée,0.342105,0.000000,0.131579,0.368421,0.000000,NaN,<NA>
855,998,UNITE LOCALE - UL,UL DU VAL D'AVRE,80500.0,80561,MONTDIDIER,"6 Rue AMAND DE VIENNE, 80500 MONTDIDIER",80,1914-12-10 00:00:00,NaT,...,Action menée,Activité AEO/AAD non menée,Action menée,0.196429,0.017857,0.000000,0.214286,0.098214,0.080357,<NA>
856,999,UNITE LOCALE - UL,UL DU PAYS NESLOIS,80190.0,80585,NESLE,"2 bis Avenue Clémenceau, 80190 NESLE",80,1917-12-10 00:00:00,NaT,...,Action menée,Activité AEO/AAD non menée,Action non menée,0.000000,0.000000,0.000000,0.133333,0.066667,NaN,<NA>

In [75]:
all_data_DT

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,...,Dispositifs_d_urgence Structures_menant_activite_GQS,AEO Structures_menant_activite,Formation_grand_public Structures_menant_activite,Dispositifs_d_urgence Taux_formation_TCAU_2025,Dispositifs_d_urgence Taux_formation_TCEO_2025,Dispositifs_d_urgence Taux_formation_PSP_2025,Dispositifs_d_urgence Taux_formation_IRR_2025,Dispositifs_d_urgence Taux_formation_GQS_2025,Structure Taux_formation_CRB,AEO Nb_PA_AEO_AAD
0,10,DELEGATION TERRITORIALE - DT,DT DES ALPES MARITIMES,6700.0,06123,ST LAURENT DU VAR,"658 Boulevard JEAN OSSOLA, 06700 ST LAURENT DU...",6,1986-12-10 00:00:00,NaT,...,8,1,8,0.072801,0.012231,0.026791,0.259173,0.182877,0.012231,<NA>
1,100,DELEGATION TERRITORIALE - DT,DT DU VAL D'OISE,95460.0,95229,EZANVILLE,"1 bis Rue Henri Dunant, 95460 EZANVILLE",95,1986-12-10 00:00:00,NaT,...,13,3,13,0.079151,0.014479,0.071429,0.510618,0.443050,0.000965,1067.0
2,102,DELEGATION TERRITORIALE - DT,DT DE LA GUADELOUPE,97139.0,97101,LES ABYMES,"Rue des écoles, 97139 LES ABYMES",971,1986-12-10 00:00:00,NaT,...,1,0,1,0.076812,0.044928,0.046377,0.289855,0.204348,0.040580,<NA>
3,103,DELEGATION TERRITORIALE - DT,DT DE LA MARTINIQUE,97200.0,97209,FORT DE FRANCE,"195 Avenue Leona Gabriel, 97200 FORT DE FRANCE",972,1986-12-10 00:00:00,NaT,...,1,1,1,0.156989,0.038710,0.060215,0.258065,0.249462,0.045161,<NA>
4,104,DELEGATION TERRITORIALE - DT,DT DE NOUVELLE CALEDONIE,98800.0,98818,NOUMEA,"26 Rue DU DOCTEUR GEORGES COLLARD, 98800 NOUMEA",988,1956-12-10 00:00:00,NaT,...,2,0,2,0.163551,0.042056,0.147196,0.292056,0.299065,0.063084,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,94,DELEGATION TERRITORIALE - DT,DT DE L'YONNE,89300.0,89206,JOIGNY,"Rue JEAN FRANÇOIS DE LA PÉROUSE, 89300 JOIGNY",89,1986-12-10 00:00:00,NaT,...,5,3,4,0.071567,0.005803,0.017408,0.245648,0.228240,0.017408,<NA>
104,95,DELEGATION TERRITORIALE - DT,DT DU TERRITOIRE DE BELFORT,90000.0,90010,BELFORT,"15 Avenue du Général Sarrail, 90000 BELFORT",90,1986-12-10 00:00:00,NaT,...,4,0,1,0.055556,0.000000,0.039683,0.444444,0.412698,0.000000,<NA>
105,96,DELEGATION TERRITORIALE - DT,DT DE L'ESSONNE,91080.0,91228,EVRY COURCOURONNES,"12 Rue Jean Mermoz, 91080 EVRY COURCOURONNES",91,1986-12-10 00:00:00,NaT,...,14,6,13,0.269022,0.019022,0.059103,0.290761,0.386549,0.045516,<NA>
106,97,DELEGATION TERRITORIALE - DT,DT DES HAUTS DE SEINE,92100.0,92012,BOULOGNE BILLANCOURT,"14 Rue de l'Est, 92100 BOULOGNE BILLANCOURT",92,1986-12-10 00:00:00,NaT,...,31,14,30,0.218518,0.051552,0.078225,0.510387,0.414209,0.034368,4385.0
107,99,DELEGATION TERRITORIALE - DT,DT DU VAL DE MARNE,94450.0,94044,LIMEIL BREVANNES,"2 Rue ALBERT GARRY, 94450 LIMEIL BREVANNES",94,1986-12-10 00:00:00,NaT,...,19,1,19,0.274078,0.020914,0.037424,0.503027,0.458998,0.061090,<NA>

# Enregistrement des données

In [76]:
# Entregistrement du DataFrame
#save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", gspread_client, all_data, sheet_name = 'UL')
#save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", gspread_client, all_data_DT, sheet_name = 'DT')

# save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", client, df_rattachement_court)