#Imports

In [1]:
import time
start = time.time()

In [2]:


!pip install PyPDF2
!pip install reportlab
!pip install PyMuPDF tools
!pip install xlsxwriter

import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import io
import re
import shutil
import zipfile
from google.colab import drive, files

from google.colab import auth
from google.auth import default
import unicodedata
import re

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 7.4 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1
Collecting reportlab
  Downloading reportlab-4.4.7-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.4)
Downloading reportlab-4.4.7-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 36.5 MB/s eta 0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-4.4.7
Collecting PyMuPDF
  Downloading pymupdf-1.26.7-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Collecting tools
  Downloading tools-1.0.15-py3-none-any.whl.metadata (1.3 kB)
Downloading pymupdf-1.26.7-cp310-abi3-manylinux_2_28_x86_64.whl (24.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 98.4 MB/s eta 0:00:00
Downloading tools-1.0.15-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.6/41.6 kB 3.1 MB/s eta 0:00:00
Installing collected packages: tools, PyMuPDF
Successfully installed PyMuPDF-1.26.7 tools-1.0.15
Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 13.0 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9

#AUTHENTIFICATION

## 1. Authentification du google **service**

In [3]:


def get_google_client():
    """
    Authentifie l'utilisateur et renvoie un client Google Sheets pour interagir avec les feuilles de calcul.

    Cette fonction configure l'environnement pour désactiver l'authentification éphémère,
    authentifie l'utilisateur à l'aide de l'API de Google Colab et initialise un client Google Sheets autorisé.

    Returns:
        gspread.Client: Une instance de gspread.Client autorisée, permettant l'interaction avec Google Sheets.
    """

    # Désactive l'authentification éphémère
    os.environ['USE_AUTH_EPHEM'] = '0'

    # Authentifie l'utilisateur
    auth.authenticate_user()

    # Obtient les informations d'identification par défaut
    creds, _ = default()

    # Crée et retourne le client Google Sheets autorisé
    client = gspread.authorize(creds)

    print("🌐 Connexion au client Google réalisée")

    return client

In [4]:
# Etape 0 : Préparation de l'environnement

CREDENTIALS_JSON = """
{
  "type": "service_account",
  "project_id": "alexandrevalent",
  "private_key_id": "dba39c84ba4135ce5ede6479a186ad8cde499dee",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvGU4ZJFrBwCBb\nu8s4aPA5bQTOKDkPZEVdNyY//RneR6RC9JPrcbfVfIUaQU7A036sfdhDGFKJbw20\nTZ55fafcH9yCMiUO+Nzek0eogON4TXrXsh8UFtdw8BOuaVkFitU5yg8kFhTnEZtd\ntPfZHW3Aqhd/aDoTOBNgRuF/hVTKQ2ytbCbE77fL2/pz9kvpZ2Zrz3u1lmksSJls\nHIolNwX9R05YqmrkpZ/TMAULFk4bT0VRQng5pmN9AeB61eJLWhlLaEdeu79NWV4B\n7tZd6RzzTFors804aJkmXHM63VRtvGD0UlR0O7w1QlI3ymUxpy5hrjbz6n9bmpMI\nfebvydLnAgMBAAECggEADipn7RTJ2t7mP0WkHT4wIRU2zE7ovtwH2JC7oXWigB8f\npOMQjH24t6bJReR+sI7rspzDwDnZg5DedPXKml2WFPLm7gmMgfeUNtWHeJRk0rjB\n9W1NolxutY5WqUeQkig3M+Oq8epvano8LYqUepYs6OdZ207dU+y3dJSHbb+lqm9D\ntQZR2oBj7W1iZ8fJ+SQLSjU5BztS1CvWuayRd/tLd9Spp0NUn5uQFTKwel9Gazmz\n28IsPPm6SudplFhaGd4kCPvhcg0jGEKe61VYdgHoBzp+EXRWXUvQ+SbMafXtMvoB\nLoUH4X3creKzJQKXnjlDpAzRHMYhJTvHinHXaggdcQKBgQDcJszFOECfSovXFZNq\nMyQOWbesyDb2OQhJLFZCD2QraZm3jPaIPeMfFkmFAumcVal6EzpR5IE8g9jBuLo+\ng6j3NTo5jbGO9WEn4361yEotb+S8t3/DTHvWqXBK7HdUB/KHlyGtctm8yErdMZQB\nvzo03aTwwStNTeFG8GzT1Nd7JQKBgQDLnHIMbx9iAG3K21XCq0Dot2Q63hklJC26\nsJlrTkdXMOIlhpwJ6LTOJe2paHbR56IrKOHQCuLxQFhRd8Eidz1ahjO7D8fKr/TG\nS8/V32FrpONyxhKinLsccSb86S3vvpKCI265z5EEjk/1qnx3TOo6oqA/2DQLv0Q4\nYinmNSOeGwKBgHGjYY3n9IuE6lwy2e42ycTSkNoSWzSLyfgjd78PvNAf6WXy0IsR\nDvzL/1U2ZKn7GclWxYLiJce78xZEKXb9dSluA0kUF/RIO0dgydZBtfBwUq0LN1rz\nTvVGbx1tpEbu90UAQTUMFNK6vNIitliUghIp2usfex+jNMbuce6Cblw1AoGBAKDH\n1gtZiFeT7R7d2jfRkXzyrBQMI6D/k5izMULZ2l3QfROS2w68EmIi8yvuEL2qApXA\nP6hPoGtPGy6huQHlVK5yANF7IZI9JbWcUe8Z6MzetLiCDl8YEmzgMSBPZXXGb9yR\n7DKP5HzLf/qG+KggNWm913ry2A5ap506bsmZNpn3AoGBAM6vvI9tb+AcNfd4ewmY\nAWSb4GLliRTaBIGHYmotfyBEBWpXZq2/0JG32RRf3rYUJWWn/r7K+zrRUqeMwlD+\nz7GuSU+OaSDzYj7fwDyuxOwTJMLrh+AkKbUYBsMF7YH1qIRjBjKNdj1LOznASQMe\nu1E4sNa9RRRujbQw4AEP3Xjl\n-----END PRIVATE KEY-----\n",
  "client_email": "crf-slidemanager@alexandrevalent.iam.gserviceaccount.com",
  "client_id": "101959630014487618959",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/crf-slidemanager%40alexandrevalent.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly']


# Authentification
credentials = service_account.Credentials.from_service_account_info(json.loads(CREDENTIALS_JSON, strict=False), scopes=SCOPES)

# Initialisation des services
slides_service = build('slides', 'v1', credentials=credentials)
drive_service = build('drive', 'v3', credentials=credentials)
gspread_client  = gspread.authorize(credentials)

#FONCTIONS UTILES

#1. fonction de mensualisation

In [5]:
def monthly_parsing(df, year):
  def month_conditions(date):
    months = ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet' , 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre']
    for i in range(len(months)):
      if date.month == i+1:
        return months[i]
  df['Mois'] = df.apply(lambda x: month_conditions(x['date']), axis=1)
  df['Année'] = year
  return df

##2. Exporter le fichier de sortie en xlsx

In [6]:
def export_to_excel_download(dataframe, file_name='data.xlsx'):
    """
    Exporte un DataFrame en fichier Excel et le télécharge depuis Google Colab.

    Parameters:
        dataframe (pd.DataFrame): Le DataFrame à exporter.
        file_name (str): Le nom du fichier Excel à télécharger (par défaut 'data.xlsx').
    """
    dataframe.to_excel(file_name, index=False)
    files.download(file_name)

## 3. Ouvrir un google sheet

In [7]:
def sheet_to_dataframe(client, url, sheet_index=0, sheet_name=None, header_row=1):
    """
    Ouvre une feuille Google Sheets et crée un DataFrame Pandas à partir de ses données.

    Cette fonction prend en entrée l'URL de la feuille Google Sheets, un client Google Sheets autorisé,
    l'index de la page souhaitée ou le nom de la feuille, et la ligne utilisée comme en-tête. Elle renvoie les données de la
    feuille sous forme de DataFrame Pandas.

    Args:
        url (str): L'URL de la feuille Google Sheets.
        client (gspread.Client): Client Google Sheets autorisé.
        sheet_index (int, optional): L'index de la page à ouvrir dans la feuille. Par défaut, 0 (première page).
        sheet_name (str, optional): Le nom de la feuille à ouvrir. Si fourni, prioritaire sur sheet_index.
        header_row (int, optional): Le numéro de la ligne à utiliser comme en-têtes de colonnes pour le DataFrame.
                                   Par défaut, 1 (la première ligne de données après l'en-tête de feuille).

    Returns:
        pd.DataFrame: Un DataFrame Pandas contenant les données de la feuille avec la première ligne spécifiée
                      comme en-tête des colonnes.
    """

    # Ouvre la feuille Google Sheets à partir de l'URL
    sheet = client.open_by_url(url)

    # Sélectionne la page (worksheet) souhaitée
    if sheet_name:
        worksheet = sheet.worksheet(sheet_name)
    else:
        worksheet = sheet.get_worksheet(sheet_index)

    # Récupère toutes les valeurs de la page
    data = worksheet.get_all_values()

    # Crée le DataFrame en utilisant la ligne spécifiée comme en-tête
    df = pd.DataFrame(data[header_row:], columns=data[header_row - 1])

    print(f"✅ Chargement des données réalisées")
    print(f"    Sheet : {sheet.title}")
    print(f"    Feuille {sheet_index + 1 if not sheet_name else ''} : {worksheet.title} ({len(data) - header_row} lignes et {len(data[header_row - 1])} colonnes)\n")

    return df

##4. Défintion des filtres "classiques"

In [8]:

# #Fonction filtre simple (on met le nom de la colonne)
# def filtre(df, col, key, filters=FILTERS):
#     values = filters[col][key]
#     return df.loc[df[col].isin(values)].copy()

# #Fonction filtre et remplace
# def filtre_et_remplace(df, col, key, filters=FILTERS):
#   values = filters[col][key]
#   mask = df[col].isin(values)
#   df.drop(df.index[~mask], inplace=True)

In [9]:
# # def filtre(df, key, filters=FILTERS):
# def filtre(df, key, filters=FILTERS_PEGASS):
#     rule = filters[key]
#     col = rule["col"]
#     values = rule["values"]
#     return df.loc[df[col].isin(values)]


#Fonction filtre date

def filtre_2025(df, date_col="debut_inscription", dayfirst=True):
    s = pd.to_datetime(df[date_col], errors="coerce", dayfirst=dayfirst)
    return df.loc[s.between("2025-01-01 00:00", "2026-01-01 00:00", inclusive="left")]

#Fonction utile pour renommer automatiquement les variables
#Attention pour simplifier la fonction il faut que le nom initial de la Dataframe soit le même avec la colonne "nom tablme du dictionnaire de données :  Pegass_Inscription_rename = renommer_par_nom_table(PEGASS_PegassInscription, "PEGASS_PegassInscription", mapping_df)"

#On récupère la table qui sera la table "dictionnaire de données" = sans doute un url
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))
def renommer_par_nom_table(df, nom_table, mapping_df=mapping_df):
    # On filtre le mapping sur cette table
    mapping_table = mapping_df[mapping_df["nom_table"] == nom_table]
    mapping_dict = dict(zip(mapping_table["nom_variable"], mapping_table["rename"]))
    return df.rename(columns=mapping_dict)

In [10]:
def filtre(df, key, filters=None):
    # Applique un filtre défini dans un dictionnaire de règles :
    # filters = {
    #     "nom_filtre": {"col": "nom_colonne", "values": [...]}
    # }

    # Si filters n'est pas fourni, on utilise le dict global FILTERS_PEGASS.
    # ⚠ Ici, on ne touche à FILTERS_PEGASS qu'au moment de l'APPEL, pas à la définition

    if filters is None:
        filters = globals()["FILTERS_PEGASS"]  # va chercher le dict global au moment de l'appel

    rule = filters[key]
    col = rule["col"]
    values = rule["values"]

    # si values est une seule valeur, on l'encapsule dans une liste
    if not isinstance(values, (list, tuple, set)):
        values = [values]

    return df.loc[df[col].isin(values)]

##5. Sauvegarder les données dans un sheet

In [11]:
def save_dataframe_to_sheet(spreadsheet_id, client, df):
    """
    Sauvegarde un DataFrame dans une feuille Google Sheets.

    Cette fonction ouvre une feuille Google Sheets par son identifiant, sélectionne la première page,
    supprime les données existantes, et enregistre le DataFrame fourni dans la feuille.

    Args:
        spreadsheet_id (str): L'identifiant de la feuille Google Sheets (spreadsheet key).
        client (gspread.Client): Client Google Sheets autorisé.
        df (pd.DataFrame): Le DataFrame Pandas contenant les données à sauvegarder.

    Returns:
        None

    Raises:
        gspread.exceptions.APIError: Si la feuille ou la page demandée ne peut être ouverte ou modifiée.
        ValueError: Si le DataFrame fourni est vide ou invalide.
    """
    # Étape 1: Ouvre la feuille Google Sheets par son identifiant
    spreadsheet = client.open_by_key(spreadsheet_id)

    # Étape 2: Sélectionne la première feuille
    worksheet = spreadsheet.get_worksheet(0)

    # Étape 3: Supprime les données existantes dans la feuille
    worksheet.clear()
    print(f"🗑️ Les anciennes données ont été supprimées de la feuille '{worksheet.title}'")

    # Étape 4: Convertit le DataFrame en chaînes de caractères pour éviter les erreurs de format
    df_to_save = df.copy().astype(str)

    # Étape 5: Écrit le DataFrame dans la feuille Google Sheets
    worksheet.update([df_to_save.columns.values.tolist()] + df_to_save.values.tolist())

    # Confirmation de la sauvegarde
    print(f"💾 Les nouvelles données ont été sauvegardées dans le fichier '{spreadsheet.title}', feuille '{worksheet.title}'")
    print(f"    Nombre de lignes sauvegardées : {len(df_to_save)}")
    print(f"    Nombre de colonnes sauvegardées : {len(df_to_save.columns)}")

# Variables globales

# CHARGEMENT DE TOUTES LES DONNEES PAR TABLE

# 1. PEGASS

In [12]:
# EXEMPLE :  Charger le DataFrame
# spreadsheet = gspread_client.open_by_url("https://docs.google.com/spreadsheets/d/1WEoWR3dnhy7NL5ISoD6o-58krsttfHkiqaJz30Vvg74/")
# worksheet = spreadsheet.worksheet("Feuille 1")
# df_raw = get_as_dataframe(worksheet)

##1.1 rattachement_court

In [13]:
rattachement_court = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU/edit?usp=sharing').worksheet('Feuille 1'))

In [14]:
rattachement_court.head()

   n_structure                DT_de_rattachement
0         2615  95 - DT DU TERRITOIRE DE BELFORT
1         2669         48 - DT DE LA HAUTE LOIRE
2         2670         48 - DT DE LA HAUTE LOIRE
3         2671         48 - DT DE LA HAUTE LOIRE
4         2672         48 - DT DE LA HAUTE LOIRE

In [15]:
rattachement_court.columns

Index(['n_structure', 'DT_de_rattachement'], dtype='object')

## 1.2 Activité_benevole ref activité

In [16]:
Ref_activité_benevole = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1rf1gXTylNEHEt72UfwZO62gIfgzf9eY8lPqhXLJ5hs8/edit').worksheet('Feuille 1'))

In [17]:
Ref_activité_benevole.head()

   id   libelle  actionid
0  87  M4O6DRFA        19
1  58  M85NOLCG        81
2  86  5Z7PXHVZ        32
3  39  VAO31CNW         5
4   5  GZQNTZQN        13

In [18]:
Ref_activité_benevole.columns

Index(['id', 'libelle', 'actionid'], dtype='object')

## 1.3 Pegass_activite / Activite

In [19]:
Pegass_activite = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13Ygh1goryIgp2UCh19tKaTv3AWkfsSMInuS8-VMbmeU/edit').worksheet('Feuille 1'))

In [20]:
Pegass_activite.head()

,typeActiviteId,Type,externalID,id,libelle,structureMenanActiviteId,structureOrganisatriceId
0,74,3324,8171,97,JM748191,19884,1146
1,60,4879,16563,77,LZXLWE0B,7189,7252
2,65,3186,1174,45,OWLODJGL,15527,10543
3,75,16759,6861,44,E9HB7T5R,13392,1951
4,79,9846,9597,25,YFUHXPZD,10940,19260

In [21]:
Pegass_activite.dtypes

typeActiviteId               int64
Type                         int64
externalID                   int64
id                           int64
libelle                     object
structureMenanActiviteId     int64
structureOrganisatriceId     int64
dtype: object

In [22]:
Pegass_activite.columns

Index(['typeActiviteId', 'Type', 'externalID', 'id', 'libelle',
       'structureMenanActiviteId', 'structureOrganisatriceId'],
      dtype='object')

## 1.4 PegassInscription / Inscription

In [23]:
Pegass_inscription = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1wCYPGwDVKZC6BBuMnOc7kB98agof5IMkdn9W7xn5UUg/edit').worksheet('Feuille 1'))

In [24]:
Pegass_inscription.dtypes

utilisateurId    object
debut            object
fin              object
statut             bool
activite_id       int64
dtype: object

In [25]:
Pegass_inscription.columns

Index(['utilisateurId', 'debut', 'fin', 'statut', 'activite_id'], dtype='object')

In [26]:
Pegass_inscription.head()

  utilisateurId       debut         fin  statut  activite_id
0      UMSA0P47  2025-03-03  2025-04-27    True        17109
1      QJX4DGNL  2025-06-16  2025-09-25   False        13865
2      7XP58P25  2025-06-30  2025-02-09    True        12105
3      VDX9JSKS  2025-01-18  2025-08-07   False        12358
4      RIXHN1J3  2025-05-27  2025-04-10    True        13057

## 1.5. PREPARATION DE LA BASE DE DONNEES

##1.5.1 Renommer les variables

In [27]:
#On récupère la table qui sera la table "dictionnaire de données" = sans doute un url
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

In [28]:
Pegass_inscription = renommer_par_nom_table(Pegass_inscription, "Pegass_inscription", mapping_df)

In [29]:
Pegass_inscription.head()

      nivol debut_inscription fin_inscription  statut_inscription  activite_id
0  UMSA0P47        2025-03-03      2025-04-27                True        17109
1  QJX4DGNL        2025-06-16      2025-09-25               False        13865
2  7XP58P25        2025-06-30      2025-02-09                True        12105
3  VDX9JSKS        2025-01-18      2025-08-07               False        12358
4  RIXHN1J3        2025-05-27      2025-04-10                True        13057

In [30]:
Pegass_inscription.columns

Index(['nivol', 'debut_inscription', 'fin_inscription', 'statut_inscription',
       'activite_id'],
      dtype='object')

In [31]:
Pegass_inscription.dtypes

nivol                 object
debut_inscription     object
fin_inscription       object
statut_inscription      bool
activite_id            int64
dtype: object

Verifier que les données soient au bon format

In [32]:
#mettre les dates en format date
Pegass_inscription["debut_inscription"] = pd.to_datetime( Pegass_inscription["debut_inscription"])
Pegass_inscription["fin_inscription"] = pd.to_datetime( Pegass_inscription["fin_inscription"])

In [33]:
Pegass_activite = renommer_par_nom_table(Pegass_activite, "Pegass_activite", mapping_df)
Pegass_activite.head()

,activite_benevole_id,Type,dps_id,activite_id,libelle_activite,structure_menant_activite_id,structure_organisatrice_id
0,74,3324,8171,97,JM748191,19884,1146
1,60,4879,16563,77,LZXLWE0B,7189,7252
2,65,3186,1174,45,OWLODJGL,15527,10543
3,75,16759,6861,44,E9HB7T5R,13392,1951
4,79,9846,9597,25,YFUHXPZD,10940,19260

In [34]:
Pegass_activite.columns

Index(['activite_benevole_id', 'Type', 'dps_id', 'activite_id',
       'libelle_activite', 'structure_menant_activite_id',
       'structure_organisatrice_id'],
      dtype='object')

In [35]:
Ref_activité_benevole = renommer_par_nom_table(Ref_activité_benevole, "Ref_activité_benevole", mapping_df)
Ref_activité_benevole.head()

   activite_benevole_id libelle_activite_benevole  action_id
0                    87                  M4O6DRFA         19
1                    58                  M85NOLCG         81
2                    86                  5Z7PXHVZ         32
3                    39                  VAO31CNW          5
4                     5                  GZQNTZQN         13

In [36]:
Ref_activité_benevole.columns

Index(['activite_benevole_id', 'libelle_activite_benevole', 'action_id'], dtype='object')

# 2. GAIA

## 2.1. GAIA_contact

In [37]:
GAIA_contact = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1k4-nMZqUulcZBPMplZLWHcvSTvzISqF9uMnlITdikmI/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.2. GAIA_action

In [38]:
GAIA_action = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1XvfYhne_YxMBVfgkDUzKhhOle9-bmEP3j0gpBYZsKuo/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.3. GAIA_rattachement_action

In [39]:
GAIA_rattachement_action = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1vtC3hpxh6RIcmhMjifVFoi169uhdi0f9fpKXP9FqEd8/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.4 GAIA_act_str

In [40]:
GAIA_act_str = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1PrK18aa8dllTjXOEyPHXMEgqP4gm1ZeJdnCmlUG78EA/edit?usp=drive_link').worksheet('Feuille 1'))

In [41]:
GAIA_act_str.head()

   act_id    date_fin  str_id
0    8229  2024-10-20   16706
1   15289  2023-01-10    4399
2    9045  2024-08-01     844
3     634  2024-03-29   18956
4    9445  2024-01-24    6595

## 2.5. GAIA_structure

In [42]:
GAIA_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1forcw_rC0WCcwu6K8-AUhm1sur9pp5XZX_YTCKaBA6g/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.6. Preparation de la base

### 2.6.1. Renommer les variables

In [43]:
#On récupère la table qui sera la table "dictionnaire de données" = sans doute un url
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

In [44]:
GAIA_action = renommer_par_nom_table(GAIA_action, "GAIA_action", mapping_df)
GAIA_rattachement_action = renommer_par_nom_table(GAIA_rattachement_action, "GAIA_rattachement_action", mapping_df)
GAIA_contact = renommer_par_nom_table(GAIA_contact, "GAIA_contact", mapping_df)
GAIA_structure = renommer_par_nom_table(GAIA_structure, "GAIA_structure", mapping_df)
GAIA_act_str = renommer_par_nom_table(GAIA_act_str, "GAIA_act_str", mapping_df)

In [45]:
GAIA_structure.head()

   id_structure n_structure
0          5964    DUHEF576
1         10554    B0894MQ9
2          7228    9CPRGHX3
3         19290    NLN17U9Y
4         13274    K8L0YGL2

# 3. NOMINATION

## 3.1. NOMINATION_nomination

In [49]:
NOMINATION_nomination = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ywCGFgW5eLONMNK64o4NZrQQzasqfEGnnQL6LfDXbbM/edit?gid=614834196').worksheet('NOMINATION_nomination'))

In [50]:
NOMINATION_nomination.head()

        id  code       nom groupe_nomination
0   5398.0  34.0  9JAZ5TZC          IRMXGWYS
1  16994.0  90.0  HRBKUXVW          JTEXZC5K
2   6624.0  59.0  SAVTNA9Z          95HU6MQS
3  17095.0  79.0  1C7EKQXD          35WAVBZL
4  10213.0  29.0  APULAIGE          RP0Y9FLP

## 3.2 NOMINATION_attribution_nomination

In [51]:
NOMINATION_attribution_nomination = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1BzCcfO1NLM5oMmBD1cBELIuvBvVjucsK6Wm4zPTaO-Q/').worksheet('NOMINATION_attribution_nomination'))

In [52]:
NOMINATION_attribution_nomination.head()

,structure_id,nomination_id,sous_titre,date_debut_nomination,date_fin_nomination,statut,contact_id
0,8229.0,66.0,UASOM780,2025-08-01,2025-01-21,0.0,17370.0
1,15289.0,47.0,VVSQZZOZ,2024-01-02,2025-02-06,1.0,9594.0
2,9045.0,91.0,4KAZKMBR,2024-05-07,2025-12-27,0.0,9503.0
3,634.0,76.0,RKG6NTRH,2023-11-02,2025-12-28,0.0,5711.0
4,9445.0,12.0,6OUYCPHS,2024-07-09,2025-04-03,0.0,11100.0

## 3.3. Préparation de la base

### 3.3.1. Renommer les variables

In [121]:
#On récupère la table qui sera la table "dictionnaire de données" = sans doute un url
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

In [127]:
NOMINATION_nomination = renommer_par_nom_table(NOMINATION_nomination, "nomination", mapping_df)
NOMINATION_attribution_nomination = renommer_par_nom_table(NOMINATION_attribution_nomination, "attribution_nomination", mapping_df)

# 4. IMPACT

## 4.1 Impact_indicateurs

In [ ]:
IMPACT_indicateurs = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.2 Impact_indicateur_value

In [ ]:
IMPACT_indicateur_value = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.3 Impact_donnees_activite

In [ ]:
IMPACT_donnees_activite = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.4 Impact_abstract_donnees_activite

In [ ]:
IMPACT_abstract_donnees_activite = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.5. Preparation de la base

### 4.5.1. Renommer les variables

In [ ]:
#On récupère la table qui sera la table "dictionnaire de données" = sans doute un url
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

In [ ]:
IMPACT_indicateurs = renommer_par_nom_table(IMPACT_indicateurs, "IMPACT_indicateurs", mapping_df)
IMPACT_indicateur_value = renommer_par_nom_table(IMPACT_indicateur_value, "IMPACT_indicateur_value", mapping_df)
IMPACT_donnees_activite = renommer_par_nom_table(IMPACT_donnees_activite, "IMPACT_donnees_activite", mapping_df)
IMPACT_abstract_donnees_activite = renommer_par_nom_table(IMPACT_abstract_donnees_activite, "IMPACT_abstract_donnees_activite", mapping_df)

# FUSION DES TABLES

# 1. Fusion PEGASS activité, inscription, ref_activité_bénévole, rattachement_court

# 1.1 Filtres généraux à appliquer

In [66]:
FILTERS = {
    "filtres_activites_ben_test": {"col": "activite_benevole_id", "values": [1, 2, 3, 4]}, #variables numeric
     "statut_inscription" : {"col": "statut_inscription", "values": [1]},
    "vulne_core": {"col": "Indicateur", "values": ["Indice de vulnérabilité global", "Revenu median"]}, #variables textuelles
}

# 1.2. Fusion des tables

In [67]:
# left join (tous les id de df1, et ce qu'on trouve dans df2)
# left = pd.merge(df1, df2, on="id", how="left")

df1 = pd.merge(Pegass_inscription, Pegass_activite, left_on="activite_id", right_on="activite_id", how="left")

In [68]:
df1.head()

,nivol,debut_inscription,fin_inscription,statut_inscription,activite_id,activite_benevole_id,Type,dps_id,libelle_activite,structure_menant_activite_id,structure_organisatrice_id
0,UMSA0P47,2025-03-03,2025-04-27,True,17109,NaN,NaN,NaN,NaN,NaN,NaN
1,QJX4DGNL,2025-06-16,2025-09-25,False,13865,NaN,NaN,NaN,NaN,NaN,NaN
2,7XP58P25,2025-06-30,2025-02-09,True,12105,NaN,NaN,NaN,NaN,NaN,NaN
3,VDX9JSKS,2025-01-18,2025-08-07,False,12358,NaN,NaN,NaN,NaN,NaN,NaN
4,RIXHN1J3,2025-05-27,2025-04-10,True,13057,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
df2 = pd.merge(df1, Ref_activité_benevole, left_on="activite_benevole_id", right_on="activite_benevole_id", how="left")

In [70]:
df2.head()

,nivol,debut_inscription,fin_inscription,statut_inscription,activite_id,activite_benevole_id,Type,dps_id,libelle_activite,structure_menant_activite_id,structure_organisatrice_id,libelle_activite_benevole,action_id
0,UMSA0P47,2025-03-03,2025-04-27,True,17109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,QJX4DGNL,2025-06-16,2025-09-25,False,13865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7XP58P25,2025-06-30,2025-02-09,True,12105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,VDX9JSKS,2025-01-18,2025-08-07,False,12358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,RIXHN1J3,2025-05-27,2025-04-10,True,13057,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
df2.to_csv("df2.csv", index=False, encoding="utf-8-sig")

In [72]:
df2 = df2.rename(columns={"structureMenanActiviteId": "structure_menant_activite_id"}) #renomage temporaire à  supprimer après

In [73]:
#Merge sur la structure de ratachement
df2 = pd.merge(df2, rattachement_court, left_on="structure_menant_activite_id", right_on="n_structure", how="left").drop(columns=["n_structure"])

In [74]:
df2.columns

Index(['nivol', 'debut_inscription', 'fin_inscription', 'statut_inscription',
       'activite_id', 'activite_benevole_id', 'Type', 'dps_id',
       'libelle_activite', 'structure_menant_activite_id',
       'structure_organisatrice_id', 'libelle_activite_benevole', 'action_id',
       'DT_de_rattachement'],
      dtype='object')

# 2. Fusion GAIA rattachement_action, action, act_str, structure

# 2.1. Filtres généraux à appliquer

In [75]:
#FTILRE SUR ANNEE NULLE OU FIN EN 2025

# Vérification que la colonne est au format datetime
GAIA_act_str['date_fin_activite_struct'] = pd.to_datetime(GAIA_act_str['date_fin_activite_struct'], errors='coerce')

# Filtrage : date nulle ou année = 2025
GAIA_act_str = GAIA_act_str[
    GAIA_act_str['date_fin_activite_struct'].isna() | (GAIA_act_str['date_fin_activite_struct'].dt.year == 2025)
]

# 2.2. Fusion des tables

In [80]:
# left = pd.merge(df1, df2, on="id", how="left")

# 1) Join avec action sur act_id
df_GAIA = pd.merge(GAIA_rattachement_action, GAIA_action, on="n_action_ben", how="left")

# 2) Join avec rattachement_action sur act_id + str_id
df_GAIA = pd.merge(df_GAIA, GAIA_act_str, on="n_action_ben", how="left")

# 3) Join avec contact sur cob_idrp
df_GAIA = pd.merge(df_GAIA, GAIA_structure, on="id_structure", how="left")

# df final disponible dans df_GAIA
df_GAIA.head()

,n_action_ben,id_gaia,date_fin_ratachement_ben_structure,id_structure,libelle_action_ben,n_groupe_action,date_fin_activite_struct,n_structure_x,n_structure_y
0,11940,10772,2023-11-20,19474,NaN,NaN,NaT,NaN,QVGHLEJY
1,6432,755,2025-02-14,19718,4UA9GNWT,50.0,NaT,NaN,NaN
2,9680,13409,2024-01-26,11982,NaN,NaN,NaT,NaN,NaN
3,6109,7691,2023-10-04,3539,NaN,NaN,NaT,NaN,NaN
4,11975,14276,2024-01-27,14193,EWBWNDKD,21.0,NaT,NaN,3J0LCQ2N

# 3. Fusion NOMINATION nomination, attribution_nomination

## 3.1. Filtres généraux à appliquer

In [81]:
#FTILRE SUR ANNEE NULLE OU FIN EN 2025

# Vérification que la colonne est au format datetime
NOMINATION_attribution_nomination['date_fin_nomination'] = pd.to_datetime(NOMINATION_attribution_nomination['date_fin_nomination'], errors='coerce')
NOMINATION_attribution_nomination['date_debut_nomination'] = pd.to_datetime(NOMINATION_attribution_nomination['date_debut_nomination'], errors='coerce')

# Filtrage : date nulle ou année = 2025
NOMINATION_attribution_nomination = NOMINATION_attribution_nomination[
    NOMINATION_attribution_nomination['date_fin_nomination'].isna() | (NOMINATION_attribution_nomination['date_fin_nomination'].dt.year == 2025)
]

## 3.2. Fusion des tables

In [129]:
# left join (tous les id de df1, et ce qu'on trouve dans df2)
# left = pd.merge(df1, df2, on="id", how="left")

df_NOMINATION = pd.merge(NOMINATION_nomination, NOMINATION_attribution_nomination,on="nomination_id", how="left") #VERIFIER LA FOREIGN KEY!

# 4. Fusion IMPACT indicateurs, indicateurs_value, donnees_activite, abstract_donnes_activite

## 4.1. Filtres généraux à appliquer

In [ ]:
#FTILRE SUR ANNEE 2025

# Vérification que la colonne est au format datetime
IMPACT_donnees_activite['date_fin_activite'] = pd.to_datetime(IMPACT_donnees_activite['date_fin_activite'], errors='coerce')
IMPACT_donnees_activite['date_debut_activite'] = pd.to_datetime(IMPACT_donnees_activite['date_debut_activite'], errors='coerce')

# Filtrage : date nulle ou année = 2025
IMPACT_donnees_activite = IMPACT_donnees_activite[ (IMPACT_donnees_activite['date_debut_activite'].dt.year == 2025)]

## 4.2. Fusion des tables

In [ ]:
# left = pd.merge(df1, df2, on="id", how="left")

# 1) Join avec action sur act_id
df_IMPACT = pd.merge(IMPACT_indicateur_value, IMPACT_indicateurs, on="n_indicateurs", how="left")

# 2) Join avec rattachement_action sur act_id + str_id
df_IMPACT = pd.merge(df_IMPACT, IMPACT_donnees_activite, on="id_activite", how="left")

# 3) Join avec contact sur cob_idrp
df_IMPACT = pd.merge(df_IMPACT, IMPACT_abstract_donnees_activite, on="id_activite", how="left")

# df final disponible dans df_GAIA
df_IMPACT.head()

# Calcul des indicateurs

#1. Nombre de bénévoles par activité benevole

##1.1 Selection des colonnes qui nous serons utiles

### 1.1.1 Filtres génériques par indicateur

### 1.1.2 définition des filtres génériques à appliquer

In [130]:
# NOMBRE DE BENEVOLES PAR ACTIVITE BENEVOLES
# Fonction filtre encore plus sophistiqué

FILTERS_PEGASS = {
    "filtres_activites_ben_test": {"col": "activite_benevole_id", "values": [1, 2, 3, 4]}, #variables numeric
     "statut_inscription" : {"col": "statut_inscription", "values": [1]},
    "vulne_core": {"col": "Indicateur", "values": ["Indice de vulnérabilité global", "Revenu median"]}, #variables textuelles
}

### 1.1.3 Application des filtres primaires

In [131]:
df2 = filtre_2025(df2,date_col="debut_inscription" )

df2 = filtre(df2,"statut_inscription")

df2 = filtre(df2,"filtres_activites_ben_test")

### 1.1.4 Ajout de la variable mensuelle

In [132]:
df2['debut_inscription'] = pd.to_datetime(df2['debut_inscription'])
df2["mois_debut_inscription"] = df2["debut_inscription"].dt.month

In [133]:
Pegass_inscription.head()

      nivol debut_inscription fin_inscription  statut_inscription  activite_id
0  UMSA0P47        2025-03-03      2025-04-27                True        17109
1  QJX4DGNL        2025-06-16      2025-09-25               False        13865
2  7XP58P25        2025-06-30      2025-02-09                True        12105
3  VDX9JSKS        2025-01-18      2025-08-07               False        12358
4  RIXHN1J3        2025-05-27      2025-04-10                True        13057

##1.2 Definition de l'indicateur générique *annuel*

In [134]:
# On compte le nb de NivolS unniques par Structure
Nb_benevoles_distincts = (df2.groupby('structure_menant_activite_id')['nivol'].nunique()).rename("nb_benevoles_distincts")
# A voir si on peut pas remplacer reset_index par .rename()

In [135]:
##Definition pour calcul benevoles distincts
def nb_benevoles_distincts_gen(df, filtre=None,
                              col_structure="structure_menant_activite_id",
                              col_user="nivol",
                              out_col="nb_benevoles_distincts"):
    d = df.query(filtre) if filtre else df
    return (d.groupby(col_structure)[col_user]
              .nunique()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

In [136]:
Nb_benevoles_distincts.head()

structure_menant_activite_id
876.0     1
880.0     3
899.0     1
908.0     1
1240.0    1
Name: nb_benevoles_distincts, dtype: int64

In [137]:
# A faire sur la base du code de Clément D

### 1.2.1 Calcul des indicateurs un par un

In [138]:
activite_ben_cible = "Distribution alimentaire"  # l'intitulé que l'on souhaite

Nb_benevoles_Distribution_alimentaire = (
    df2[df2['libelle_activite_benevole'] == activite_ben_cible]  # filtre sur l’intitulé
      .nunique()
      .reset_index(name='nb_benevoles_distincts')
)

In [139]:
Nb_benevoles_Distribution_alimentaire.head()

                index  nb_benevoles_distincts
0               nivol                       0
1   debut_inscription                       0
2     fin_inscription                       0
3  statut_inscription                       0
4         activite_id                       0

### 1.2.1 Calcul indicateur avec def

In [140]:
# 2) Indicateur avec filtre
activite_ben_cible = "Distribution alimentaire"
Nb_benevoles_Distribution_alimentaire1 = nb_benevoles_distincts_gen(
    df2,
    filtre=f"libelle_activite_benevole == @activite_ben_cible"
)

### 1.2.2 Calcul des indicateurs par type d'activités bénévole ( avec boucle)

In [141]:
##Automatisation en créant une boucle

#Il faut prendre activite_id pour le numero d'activité mais là je teste direct avec le libellé
liste_activite_ben= [
    "Distribution alimentaire",
    "Épicerie sociale",
    "Colis alimentaire",
    "Aide d'urgence",
    "Autre dispositif"
]

In [142]:

def make_var_name(libelle_activite_benevole):
    # Supprimer les accents
    s = unicodedata.normalize("NFKD", libelle_activite_benevole)
    s = "".join(c for c in s if not unicodedata.combining(c))
    # Minuscules + remplacer tout ce qui n'est pas lettre/chiffre par "_"
    s = s.lower()
    s = re.sub(r"[^0-9a-zA-Z]+", "_", s).strip("_")
    return f"df_{s}"

In [143]:
for activite in liste_activite_ben:
    df_tmp = (
        df2[df2['libelle_activite_benevole'] == activite]
          .groupby('structure_menant_activite_id')['nivol']
          .nunique()
          .reset_index(name='nb_benevoles_distincts')
    )

    var_name = make_var_name(activite)
    globals()[var_name] = df_tmp  # crée une variable df_<nom_simplifié>

    print(f"Créé : {var_name} (libelle_activite_benevole = {activite})")

Créé : df_distribution_alimentaire (libelle_activite_benevole = Distribution alimentaire)
Créé : df_epicerie_sociale (libelle_activite_benevole = Épicerie sociale)
Créé : df_colis_alimentaire (libelle_activite_benevole = Colis alimentaire)
Créé : df_aide_d_urgence (libelle_activite_benevole = Aide d'urgence)
Créé : df_autre_dispositif (libelle_activite_benevole = Autre dispositif)

In [144]:
df_distribution_alimentaire.head()

Empty DataFrame
Columns: [structure_menant_activite_id, nb_benevoles_distincts]
Index: []

## 1.3. Calcul de l'indicateur annuel par DT de rattachement

In [145]:
##Definition pour calcul benevoles distincts
def nb_benevoles_distincts_DT_gen(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="nivol",
                              out_col="nb_benevoles_distincts"):
    d = df.query(filtre) if filtre else df
    return (d.groupby(col_structure)[col_user]
              .nunique()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

In [146]:
# 2) Indicateur avec filtre
activite_ben_cible = "Distribution alimentaire"
Nb_benevoles_Distribution_alimentaire2 = nb_benevoles_distincts_gen(
    df2,
    filtre=f"libelle_activite_benevole == @activite_ben_cible"
)

In [147]:
Nb_benevoles_Distribution_alimentaire2

Empty DataFrame
Columns: [structure_menant_activite_id, nb_benevoles_distincts]
Index: []

## 1.4 Calcul de l'indicateur générique mensuel

In [148]:
##Definition pour calcul benevoles distincts
def nb_benevoles_distincts_mois_gen(df, filtre=None,
                              col_structure="structure_menant_activite_id",
                              col_user="nivol",
                              col_mois = "mois_debut_inscription",
                              out_col="nb_benevoles_distincts_mois"):
    d = df.query(filtre) if filtre else df
    return (d.groupby([col_structure, col_mois])[col_user]
              .nunique()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

In [149]:
# 2) Indicateur avec filtre
activite_ben_cible = "Distribution alimentaire"
Nb_benevoles_Distribution_alimentaire3 = nb_benevoles_distincts_mois_gen(
    df2,
    filtre=f"libelle_activite_benevole == @activite_ben_cible"
)

In [150]:
Nb_benevoles_Distribution_alimentaire3.head()

Empty DataFrame
Columns: [structure_menant_activite_id, mois_debut_inscription, nb_benevoles_distincts_mois]
Index: []

## 1.5 Calcul de l'indicateur mensuel par DT de rattachement

In [151]:
##Definition pour calcul benevoles distincts
def nb_benevoles_distincts_mois_DT_gen(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="nivol",
                              col_mois = "mois_debut_inscription",
                              out_col="nb_benevoles_distincts_mois"):
    d = df.query(filtre) if filtre else df
    return (d.groupby([col_structure, col_mois])[col_user]
              .nunique()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

In [152]:
# 2) Indicateur avec filtre
activite_ben_cible = "Distribution alimentaire"
Nb_benevoles_Distribution_alimentaire4 = nb_benevoles_distincts_mois_DT_gen(
    df2,
    filtre=f"libelle_activite_benevole == @activite_ben_cible"
)

In [153]:
Nb_benevoles_Distribution_alimentaire4.head()

Empty DataFrame
Columns: [DT_de_rattachement, mois_debut_inscription, nb_benevoles_distincts_mois]
Index: []

# Nombre de bénévoles déclarés sur une activitée

##10.1. Calcul nb de volontaires de l'urgence

In [154]:
# Filtre sur le libelle approprié
df_urgence = df_GAIA[df_GAIA["libelle_action_ben"] == "Urgences et autres opérations"]

In [155]:
# On compte le nb de volontaires de l'urgence
NbBeneDecla_GAIA = (df_urgence.groupby('n_structure_x')['id_gaia'].nunique())

In [156]:
# NbBeneDecla_GAIA.head()

# 3. RTAEO & RLAEO

In [157]:
df_NOMINATION.columns

Index([        'nomination_id',       'code_nomination',
          'libelle_nomination',     'groupe_nomination',
                'structure_id',                     nan,
       'date_debut_nomination',   'date_fin_nomination',
           'statut_nomination',            'contact_id'],
      dtype='object')

In [158]:
# Filtre sur le libelle approprié
referents_AEO = df_NOMINATION[df_NOMINATION["libelle_nomination"] == "RTAEO"]

# Filtre sur le libelle approprié
referents_OCR = df_NOMINATION[df_NOMINATION["libelle_nomination"] == "RTOCR"]

In [160]:
# On compte le nb de RTAEO & RLAEO
referents_AEO = (referents_AEO.groupby('structure_id')['libelle_nomination'].nunique())

In [161]:
# DF par mois
annee = 2025

# Mois de l'année
mois = pd.date_range(
    start=f"{annee}-01-01",
    end=f"{annee}-12-01",
    freq="MS"
)

resultats = []

for m in mois:
    debut_mois = m
    fin_mois = m + pd.offsets.MonthEnd(1)

    actifs = referents_AEO[
        (referents_AEO["date_debut_nomination"] <= fin_mois) &
        (referents_AEO["date_fin_nomination"] >= debut_mois)
    ]

    comptage = (
        actifs
        .groupby("structure")
        .size()
        .reset_index(name="nb")
    )

    comptage["mois"] = m.strftime("%Y-%m")
    resultats.append(comptage)

# Concaténation
referents_AEO_mois = pd.concat(resultats)

# Tableau croisé
referents_AEO_mois = referents_AEO_mois.pivot(
    index="structure_id",
    columns="mois",
    values="nb"
).fillna(0).astype(int)

print(pivot)

KeyError: 'date_debut_nomination'

# 4. RTOCR & RLOCR

In [ ]:
# On compte le nb de RTAEO & RLAeo
referents_OCR = (referents_OCR.groupby('structure_id')['nom'].nunique())

In [ ]:
# DF par mois
annee = 2025

# Mois de l'année
mois = pd.date_range(
    start=f"{annee}-01-01",
    end=f"{annee}-12-01",
    freq="MS"
)

resultats = []

for m in mois:
    debut_mois = m
    fin_mois = m + pd.offsets.MonthEnd(1)

    actifs = referents_OCR[
        (referents_OCR["date_debut_nomination"] <= fin_mois) &
        (referents_OCR["date_fin_nomination"] >= debut_mois)
    ]

    comptage = (
        actifs
        .groupby("structure")
        .size()
        .reset_index(name="nb")
    )

    comptage["mois"] = m.strftime("%Y-%m")
    resultats.append(comptage)

# Concaténation
referents_OCR_mois = pd.concat(resultats)

# Tableau croisé
referents_OCR_mois = referents_OCR_mois.pivot(
    index="structure_id",
    columns="mois",
    values="nb"
).fillna(0).astype(int)

print(pivot)

# Nombre d'agréments territoriaux (Dispos d'urgence)

# Nombre de personnes prises en charge (Dispos d'urgence)

#Enregistrement des données

In [ ]:
# Entregistrement du DataFrame
# save_dataframe_to_sheet("1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw", client, df_structure)
# save_dataframe_to_sheet("1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU", client, df_rattachement_court)

In [ ]:
# ... tu lances ton notebook ...
print("Temps total (min):", (time.time() - start)/60)