In [1]:
# !git config --global user.email "clement.dilasser@croix-rouge.fr"
# !git clone https://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@github.com/clementsouk-aloun-dot/Code-PAT.git

In [2]:
# !gcloud auth application-default login

In [3]:
# !pip install PyPDF2
# !pip install reportlab
# !pip install PyMuPDF tools
# !pip install xlsxwriter

# Imports

In [4]:
# 🔹 Compatibilité Google Colab pour code local
try:
    from google.colab import drive, files
    from google.colab import auth
except ModuleNotFoundError:
    # Crée un faux module google.colab pour que le code ne plante pas
    import types
    drive = types.SimpleNamespace(mount=lambda path: print(f"[Mock] drive.mount({path})"))
    files = types.SimpleNamespace(upload=lambda: print("[Mock] files.upload()"))
    auth = types.SimpleNamespace(authenticate_user=lambda: print("[Mock] auth.authenticate_user()"))

In [5]:
import traceback
import sys
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import seaborn as sns
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import re
import shutil
import zipfile
from google.auth import default
from google.cloud import bigquery
import unicodedata
import torch
from sentence_transformers import SentenceTransformer, util
import gc
from functools import reduce

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Imports des fichiers .py

In [6]:
from utils import *

sys.path.append(os.path.abspath("./data")) 

from adherent import *
from alim import *
from domifa import *
from financier import *
from gaia import *
from impact import *
from manuelles import *
from maraude import *
from maraude_manuel import *
from base_contact import *
from mobilite import *
from nomination import *
from pegass import *
from dps import *
from main_merge import *
from indicateurs_ambition_pat import *
from alim2026 import *

sys.path.append(os.path.abspath("./checks")) 

from helpers import *

# AUTHENTIFICATION

In [7]:
json_key_bq_url = r'service_account\s_acc.json'

with open(json_key_bq_url, 'r') as f:
    json_key_bq = json.load(f)

SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly','https://www.googleapis.com/auth/bigquery']

credentials_bq = service_account.Credentials.from_service_account_info(json_key_bq, scopes=SCOPES)

In [8]:
PROJECT_ID = "crf-pat"
client = bigquery.Client(project=PROJECT_ID, credentials = credentials_bq)

In [9]:
# Etape 0 : Préparation de l'environnement

CREDENTIALS_JSON_url = r'service_account\old.json'

with open(CREDENTIALS_JSON_url, 'r') as f:
    CREDENTIALS_JSON = json.load(f)
SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly']


# Authentification
credentials = service_account.Credentials.from_service_account_info(CREDENTIALS_JSON, scopes=SCOPES)

# Initialisation des services
slides_service = build('slides', 'v1', credentials=credentials)
drive_service = build('drive', 'v3', credentials=credentials)
gspread_client  = gspread.authorize(credentials)

# Variables globales

In [10]:
# Define target date and year once for all functions
TARGET_DATE = "2026-05-05"
TARGET_YEAR = pd.Timestamp(TARGET_DATE).year

mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

In [11]:
mapping_df

,Source,nom_table,nom_variable,rename,Description,Type de valeurs,Présent extract DSI ?,Commentaires
0,Annuaire structure,AS_Actions_par_structure,N_structure,n_structure,Identifiant de la structure,INT,Optionnel,NaN
1,Annuaire structure,AS_Actions_par_structure,Type_de_lien,action_statut,Action menée/ Non menée,VARCHAR,Optionnel,NaN
2,Annuaire structure,AS_Actions_par_structure,Groupe_action,groupe_action_ben,Regroupement / famille d’actions,VARCHAR,Optionnel,NaN
3,Annuaire structure,AS_Actions_par_structure,Action,lib_action_ben,Libellé de l’action précise,VARCHAR,Optionnel,NaN
4,Annuaire structure,AS_Actions_par_structure,Date_demarrage_action_dans_la_structure,date_demarrage_action_structure,Date à laquelle l’action a effectivement démar...,DATE,Optionnel,NaN
...,...,...,...,...,...,...,...,...
242,GAIA ?,crf_pat_2025_rattachement_action,action_menee_date_fin,NaN,NaN,DATE,Présent & bon format,NaN
244,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_nivol_fk,NaN,NaN,STR,Présent & bon format,NaN
245,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_structure_id_fk,NaN,NaN,INT,Présent & bon format,NaN
246,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_date_debut,NaN,NaN,DATE,Présent & bon format,NaN
247,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_date_fin,NaN,NaN,DATE,Présent & bon format,NaN

# CHARGEMENT DE TOUTES LES DONNEES PAR TABLE

## 0. Ref_structure

In [12]:
df_ref_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1PUdny0DiyOjSSYLte2o9r1Xyh02O9INFlzLJVHl92ic/').worksheet('Ref_structure RP 2026'))

In [13]:
df_ref_structure = renommer_par_nom_table(df_ref_structure, "AS_Informations_structures", mapping_df)
df_ref_structure['n_structure'] = df_ref_structure['n_structure'].astype(int)
df_ref_structure = df_ref_structure[df_ref_structure["type_structure"].isin(["UNITE LOCALE - UL", "DELEGATION TERRITORIALE - DT", 'IMPLANTATION LOCALE HORS AL - IL', 'ANTENNE LOCALE - AL','INSTANCES NATIONALES - IN'])]
df_ref_structure.head()

,n_structure,n_structure-ratt,type_structure,nom_structure,n_dept,adresse_physique_cp,adresse_physique_commune,adresse_complete,date_demarrage_activite_ben_struct,date_arret_activite_struct,Structure_de_rattachement,Rattachements_successifs,DT_de_rattachement,lon,lat,code_insee
0,2615,2615,ANTENNE LOCALE - AL,AL DE DELLE,90,90100,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",2010-02-08 00:00:00,NaT,95 - DT DU TERRITOIRE DE BELFORT,AL 2615,95 - DT DU TERRITOIRE DE BELFORT,7.000705,47.506725,90033
1,2669,2669,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43,43220,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2669,48 - DT DE LA HAUTE LOIRE,4.346423,45.214392,43087
2,2670,2670,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43,43600,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2670,48 - DT DE LA HAUTE LOIRE,4.235474,45.242445,43224
3,2671,2671,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43,43300,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2671,48 - DT DE LA HAUTE LOIRE,3.495645,45.098285,43112
4,2672,2672,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43,43000,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2672,48 - DT DE LA HAUTE LOIRE,3.879748,45.044677,43157

In [14]:
df_ref_structure_DT = df_ref_structure[df_ref_structure['nom_structure'].str.contains('DT')].astype(str)
df_ref_structure_DT['n_structure'] = df_ref_structure['n_structure'].astype(int)

### 0.1 rattachement_court

In [15]:
rattachement_court = df_ref_structure_DT[['n_structure', 'DT_de_rattachement']].copy().drop_duplicates()

## 1. GAIA

In [16]:
df_gaia_rattachement_benevole = clean_gaia(client, df_ref_structure, target_date=TARGET_DATE)

df_nivols_gaia = import_table_GAIA_date_fixe(client, target_date=TARGET_DATE)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 2. PEGASS

In [17]:
df_ref_activite_benevole, df_pegass_activite, df_pegass_activite_seance, df_pegass_activite_seance_inscription,df_rattachement_court,df_ref_action_groupe_action = import_tables_PEGASS(client,target_date = TARGET_DATE)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 3. NOMINATION

In [18]:
df_ref_nomination, df_nomination = clean_nomination(client, df_ref_structure, target_date=TARGET_DATE)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 4. IMPACT

In [19]:
df_ref_impact, df_impact = clean_impact(client,df_ref_structure, target_date=TARGET_DATE)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 5. Données financières

In [20]:
financier_2023_2024 = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c')
financier_2025 = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1esF1OgTGD_HtkJVZq0ZDsqXs-7rzeRK2NMp0fMabMpM/')

Financier DPS & FGP & Textile

In [21]:
financier_DPS = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1PcNXO-Fv8BGzGv-GKzFxBoEIfYl8TWAsAU2wpezH7_Y/').worksheet('Données'), evaluate_formulas=True)
financier_textile = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1k6FKahQJj0JIvc3qGimqRCt7Y9Ow1vrCRwp1Li_hmUA/').worksheet('Données'), evaluate_formulas=True)

In [22]:
financier_FGP = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13J2zfbmLTILtGYtE_sM-ME8B0pNEwBeGJ1Gg5vKLeOc/').worksheet('DT_Prod'))

## 6. Mobilité

In [23]:
mobilite = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1dvxT58WR-FqdT-4r-A9ca4vaA9FG7IXHJJaTbnjio8A/')

In [24]:
df_mobilite = filtres_mobilite(mobilite,mapping_df, df_ref_structure)

## 7. Données manuelles

### 7.1 OCR

In [25]:
df_OCR = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ccRoyPycFDwvQvacvmHjfE87LtnlzUgtoRbITkC0pVQ/').worksheet('Feuille 1'), evaluate_formulas=True)

### 7.2 PST

In [26]:
df_PST = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1yifNna4Hsn5RihkRg50g9h1yKjuRjfolrjsWonEHnrQ').worksheet('Données'), evaluate_formulas=True)

### 7.3 Déclenchements

In [27]:
# df_declenchement = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1y9jehT5fStcEWCF0pxAP7BdiI62VY3JM_hQzFftbcZA').worksheet('Feuille 1'), evaluate_formulas=True)

### 7.4 Redcall

In [28]:
# df_redcall = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1EQzq0K8RY2Liyq-jtggX0bTlnOk9cwUTmf4t6c5_CiI').worksheet('structure-stats_2025-01-01_2025-12-31_min-1 (1)'), evaluate_formulas=True)

### 7.5 CHAI CHU CMCC

In [29]:
df_CAICHUCMCC_conventions = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1H5PFGbCc5wtfELPyKU97GxOx6ib0hqFEY8cm3h6wR80').worksheet('Feuille 1'), evaluate_formulas=True)

### 7.6 Conventions

In [30]:
df_CRope = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1DCzcs3emUsc1b8WDH5y3F2sezxFptktYUzXQRLQEZGc').worksheet('Feuille 1'), evaluate_formulas=True)

### 7.7 Textile

In [31]:
df_raw_Textile = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1QYuKZo5lVI0HN4BWtk0v7bVFY2a2p4c72a0gU0ltWac/').worksheet('Liste des PAV'))

df_tracabilite_textile = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1EwL2bcqaw2Or7F7fTWK5q2naOZGxAN4tvheLAaddb1s').worksheet('Feuille 1'), evaluate_formulas=True)

#df_raw_ProdResTextile_c = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1l7KMjiav3usmLVJIbE2uENfNQCeQuxVeU1h13Cep3qk/",sheet_name="Compil Détail",header_row=7)

### 7.8 DOMIFA

In [32]:
df_domiciliation, df_rattachement_court = clean_domifa(client,df_ref_structure)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\utils.py:162: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ref['nom_structure'] = df_ref['nom_structure'].fillna('').astype(str)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2692.48it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

### 7.9 Alim

In [33]:
# df_alim = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1bk_ktsT9hBPJS5EY70teq80NzOs_cm3JfrRkX4AYTF4/edit?gid=0#gid=0") # Rapports v2 (2025)

df_U2A_statut= get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1tJRRI5kkcVKQ-n_A2-jqk9sPMSsFKjhcGrvx94gX1gk/edit?gid=1582718806#gid=1582718806').worksheet('10_liste_statuts_data'))
df_U2A_actions= get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1bq_SEJeks8NTaw2uFlk6J0wLFT3epRbCFz597HxUGj0/edit?gid=440288067#gid=440288067').worksheet('1. Détail des U2A _data (1)'))

### 7.10 DPS

In [34]:
df_dps_source = df_CAICHUCMCC_conventions.copy()

### 7.11 Adherent

In [35]:
df_adherent = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1hsk3Xp2IrwnUs59sgWjhT9E9vEsw4TN2WT3nKejlBOE/edit?usp=drive_link")

✅ Chargement des données réalisées
    Sheet : exportAdherents (1) (1)
    Feuille 1 : exportAdherents (1) (1).csv (48300 lignes et 25 colonnes)

### 7.12 Préparation

In [37]:
# DPS a pour source le fichier conventions
# df_dps = clean_dps(df_dps_source)

df_OCR_clean, df_PST_clean, df_CAIconv_clean, df_raw_Textile_clean, df_CRope_clean = clean_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_CAICHUCMCC_conventions, df_raw_Textile, df_CRope, df_ref_structure)
#df_alim = clean_alim(df_alim)
df_adherent = clean_adherent(df_adherent)

KeyError: "None of [Index(['Horodateur', 'Typologie',\n       'Département concerné par l'opération ou l'exercice :', 'DT',\n       'Date et heure du début de l'opération :',\n       'Date et heure de la fin de l'opération :',\n       'Origine du déclenchement :', 'Description de l'événement :',\n       'Agrément concerné :',\n       'Nombre de personnes accompagnées ou prises en charge :'],\n      dtype='object')] are in the [columns]"

## 8. Maraudes

In [ ]:
# 1) import
df_maraude = import_maraude(client, target_date=TARGET_DATE)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

In [ ]:
#~rattachement successif
df_maraude = apply_rattachement_successif(df_ref_structure, df_maraude, col = 'maraude_structure_id_fk')

In [ ]:
# 3) ✅ Filtre : on CHANGE df_maraude ici
df_maraude = filter_maraude_on_ref_structure(
    df_maraude,
    df_ref_structure,
    col_maraude="maraude_structure_id_fk",
    col_ref="n_structure",
    verbose=True
)

📌 Filtre structures ref: 43,955/44,492 lignes conservées (supprimées: 537).

In [ ]:
# 3) clean/prep
df_nb_personnes_rencontrees_sigma, df_Nb_maraudes_SIGMA = clean_maraudes(df_maraude)

Données manuelles

In [ ]:
#Import données maraude manuelles
df_Maraude_donnees_manuelles = Import_Maraude_manuel(client,df_ref_structure)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1879.36it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

## 9. Base Contact

In [ ]:
df_formation_session_resultat, df_formation_count_session_2025, df_formation_session_resultat_fpg = clean_base_contact(client, df_ref_structure, target_date=TARGET_DATE)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 10. Ambition

In [ ]:
df_indic_ambition = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1tdM09TkAGaJQEQx1ddGDUjU7h79gtFU0_7ViNMyknYM/edit?gid=736259206#gid=736259206').worksheet('Consolidation PATV2'),evaluate_formulas=True)

# FUSION DES TABLES

## 1. Fusion NOMINATION

In [ ]:
df_NOMINATION = fusion_nomination(df_nomination, df_ref_nomination)

## 2. Fusion IMPACT

In [ ]:
df_IMPACT = fusion_impact(df_impact, df_ref_impact)

Nombre de lignes après filtre 2025 : 142338

## 3. Fusion DOMIFA

In [ ]:
df_domiciliation = pd.merge(df_domiciliation, df_rattachement_court, on='n_structure', how="left") #a conserver dans le code principal

# Calcul des indicateurs

## PEGASS

In [ ]:
pegass_output = calcul_PEGASS_indicateurs(df_ref_structure,
    df_ref_action_groupe_action,
    df_ref_activite_benevole,
    df_pegass_activite,
    df_pegass_activite_seance,
    df_pegass_activite_seance_inscription,
    df_rattachement_court,
    df_nivols_gaia
)

In [ ]:
df_pegass_ben_activite_synthetique = pegass_output["df_pegass_ben_activite_synthetique"]
Indics_pegass_DT = pegass_output["Indics_pegass_DT"]
Indics_pegass_DT = add_nb_benevoles_DT_distincts(
    Indics_pegass_DT,
    df_pegass_ben_activite_synthetique,
    df_rattachement_court
)

## GAIA

In [ ]:
df_indicateurs_gaia, df_indicateurs_gaia_DT = calcul_indicateurs_gaia(df_gaia_rattachement_benevole,rattachement_court,target_date=TARGET_DATE)

Nombre de structures agrégées : 839
Nombre total de bénévoles uniques : 81281
Nombre de structures agrégées : 670
Nombre total de nouveaux bénévoles uniques : 6548
Nombre de structures agrégées : 104
Nombre total de bénévoles uniques DT : 8208
Nombre de structures agrégées : 64
Nombre total de nouveaux bénévoles uniques DT : 609

## NOMINATION

- RTAEO & RLAEO
- RTOCR & RLOCR

In [ ]:
referents_AEO = indicateurs_nomination_AEO(df_NOMINATION,df_nivols_gaia)
referents_OCR = indicateurs_nomination_OCR(df_NOMINATION,df_nivols_gaia)
referents_AEO_DT = indicateurs_nominationAEO_DT(referents_AEO, rattachement_court)
referents_OCR_DT = indicateurs_nominationOCR_DT(referents_OCR, rattachement_court)

Nombre de structures agrégées : 42
Nombre total de responsables AEO : 52
Nombre de structures agrégées : 21
Nombre total de responsables OCR : 21
Nombre de structures agrégées : 3
Nombre total de responsables AEO DT : 3
Nombre de structures agrégées : 14
Nombre total de responsables OCR DT : 14

## IMPACT

- Nombre d'agréments territoriaux (Dispos d'urgence)
- Nombre de personnes prises en charge (Dispos d'urgence)

In [ ]:
IMPACT_ppc = indicateurs_impact_ppc(df_IMPACT)
IMPACT_agrementAB = indicateurs_impact_agrementAB(df_IMPACT)
IMPACT_agrementDPS = indicateurs_impact_agrementDPS(df_IMPACT, year = TARGET_YEAR)
IMPACT_ppc_DT = indicateurs_IMPACTppc_DT(IMPACT_ppc, rattachement_court)
IMPACT_agrementAB_DT = indicateurs_IMPACTagrementAB_DT(IMPACT_agrementAB, rattachement_court)
IMPACT_agrementDPS_DT = indicateurs_IMPACTagrementDPS_DT(IMPACT_agrementDPS, rattachement_court, year = TARGET_YEAR)

Nombre de lignes après filtre urgences : 603
Nombre de structures agrégées : 87
Somme totale Dispositifs d'urgence - Nb personnes prises en charge : 8145
Nombre de structures agrégées : 50
Somme totale agréments AB : 0
Nombre de structures agrégées : 14
Somme totale agréments DPS : 0
Nombre de structures agrégées : 46
Somme totale personnes prises en charge DT : 7321
Nombre de structures agrégées : 38
Somme totale agréments AB DT : 0
Nombre de structures agrégées : 12
Somme totale agréments DPS DT: 0

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\impact.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\impact.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\impact.py:151: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (

## Financier

In [ ]:
df_financier, df_financier_DT,financier = import_clean_donnees_financieres_bigquery(financier_2025,financier_2023_2024,financier_textile,financier_DPS,df_ref_structure, mapping_df)

In [ ]:
# Vérifications données financières
#verifications_financiers(df_financier, df_financier_DT, df_ref_structure, financier, financier_2025)

In [ ]:
df_financier_FGP_DT = indicateur_financier_FGP_2024(financier_FGP, df_ref_structure)
#df_inancier_FGP_DT = financier_FGP_DT(df_financier_FGP, rattachement_court)

## Mobilité


Indicateurs qui nécessitent seulement les données mobilité :

- Nb de structures menant une activité AEO/AAD mobile
- Nombre de personnes accompagnées par des dispositifs AEO/AAD mobiles
<br>
Indicateurs qui nécessitent une fusion avec données AEO/AAD :

- Nombre de bénévoles impliqués dans les activités AEO ou AAD

In [ ]:
df_mobilite_DT = indicateurs_mobilite(df_mobilite, df_ref_structure, 'DT_de_rattachement')
df_mobilite_DT_UL = indicateurs_mobilite(df_mobilite, df_ref_structure, 'n_structure')

In [ ]:
verifier_colonne_structure(df_mobilite_DT, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [ ]:
verifier_colonne_structure(df_mobilite_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## Données manuelles

In [ ]:
df_tracabilite_textile

,ART,Région,Département,Nom dpt,Code structure,Structure,Type,Remonte des données chaque trimestre
0,Louise,ARA,01,Ain,3943.0,UNITE LOCALE COTIERE DOMBES,UL,Oui
1,Louise,ARA,01,Ain,3886.0,UNITE LOCALE DE BRESSE REVERMONT,UL,Oui
2,Louise,ARA,01,Ain,3941.0,UNITE LOCALE DE BUGEY,UL,Non
3,Louise,ARA,01,Ain,3873.0,UNITE LOCALE DE PORTE DE LA DOMBES,UL,Oui
4,Louise,ARA,01,Ain,135.0,UNITE LOCALE DES PAYS DE LA VEYLE,UL,Non
...,...,...,...,...,...,...,...,...
531,Nicolas,OM,977,St Barth,3667.0,DT DE ST BARTHELEMY,DTA,Non
532,Nicolas,OM,978,St Martin,3668.0,DT DE ST MARTIN,DTA,Non
533,Nicolas,OM,986,Wallis et Futuna,4303.0,DT DE WALLIS,DTA,Non
534,Nicolas,OM,987,Polynésie française,1285.0,DT DE TAHITI,DTA,Non
535,Nicolas,OM,988,Nouvelle-Calédonie,104.0,DT DE NOUVELLE CALEDONIE,DTA,Non

In [ ]:
df_OCR_Nb_deployees, df_Dispositifs_d_urgence_PST, df_CAICHUCMCC_conventionsVF, df_raw_TextileVF, df_CRopeVF, df_tracabilite_textileVF = indicateurs_OCR_PST_DEC_RED_CAI_CONV(df_OCR_clean, df_PST_clean, df_CAIconv_clean, df_raw_Textile_clean, df_CRope_clean,df_tracabilite_textile, df_ref_structure)

Nb_OCR_DT = indicateurs_OCR_DT(df_OCR_Nb_deployees, rattachement_court)
df_Textile_DT = Textile_DT(df_raw_TextileVF, rattachement_court)

# ALIM
df_U2A_final, df_U2A_Structure, df_struct_DT, df_U2A_DT = calcul_u2a(


        df_ref_structure,


        df_U2A_statut,


        df_U2A_actions


    )

# ADHERENT
df_adherent = indicateurs_adherent(df_adherent, df_ref_structure)
df_adherent_DT = indicateurs_adherent_DT(df_adherent, rattachement_court)

# DOMIFA
df_personnes_domiciliees_struct, df_personnes_domiciliees_DT = indicateurs_domifa(df_domiciliation)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3611.85it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3654.16it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3936.09it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2966.70it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\alim2026.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_U2A_statut["Date de dernière distribution"] = pd.to_datetime(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\alim2026.py:153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_struct_DT["Aide_alimentaire Nb_struct"] = 1

In [ ]:
verifier_colonne_structure(df_OCR_Nb_deployees, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Dispositifs_d_urgence_PST, "n_structure", df_ref_structure)
# verifier_colonne_structure(df_declenchement3, "n_structure", df_ref_structure)
# verifier_colonne_structure(df_redcall2, "n_structure", df_ref_structure)
verifier_colonne_structure(df_CAICHUCMCC_conventionsVF, "n_structure", df_ref_structure)
verifier_colonne_structure(df_CRopeVF, "n_structure", df_ref_structure)


# TEXTILE
verif_textile(df_raw_Textile_clean, df_raw_TextileVF, df_Textile_DT, df_ref_structure, rattachement_court)

# DOMIFA

verifs_domifa(client, df_personnes_domiciliees_struct, df_personnes_domiciliees_DT, df_ref_structure, df_rattachement_court)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.
❌ df_Textile_DT n'est pas bien calculé (suomme de l indicateur != au nombre de lignes des données), différence : -729
❌ df_Textile_DT n'est pas bien calculé (suomme de l indicateur != au nombre de lignes des données), différence : -729
❌ df_Textile_DT n'est pas bien calculé (suomme de l indicateur != au nombre de lignes des données), différence : -864
❌ df_Textile_DT n'est pas bien calculé (suomme de l indicateur != au nombre de lignes des données), différence : -864

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.
#1 Vérification qu on a bien la même somme de personnes domiciliées entre le fichier de base et le fichier df_personnes_domiciliees_struct
OK ✅ : sommes égales (30833) entre table struct[AEO Nb_personnes_domiciliees_crf] et table source[Nombre total de domiciliations]
#2 Vérification qu on a bien la même somme de personnes domiciliées entre le fichier structure et le fichier df_personnes_domiciliees_DT
OK ✅ : sommes égales (30833) entre table struct[AEO Nb_personnes_domiciliees_crf] et table DT[AEO Nb_personnes_domiciliees_crf]
#3 on vérifie que l ensemble des N° structure du nb personnes domicilées correspnd au ref structure

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.
#4 on vérifie que l ensemble des N° DTdu nb personnes domicilées correspnd au ref structure
#5 On verifie que le nb de structure du df_personnes_domiciliees_struct est bien égal au nombre de ligne du df source
 ✅ n ligne = 30

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## Maraudes

In [ ]:
(
    df_Nb_maraudes_SIGMA_struct,
    df_Nb_maraudes_SIGMA_DT,
    df_nb_contacts_SIGMA_struct,
    df_nb_contacts_SIGMA_DT,
    df_personnes_diff_base,                 # <- nouveau (base par bénéficiaire)
    df_nb_personnes_rencontrees_SIGMA_struct,
    df_nb_personnes_rencontrees_SIGMA_DT
) = indicateurs_maraude(
    df_nb_personnes_rencontrees_sigma,
    df_Nb_maraudes_SIGMA,
    df_rattachement_court
)

In [ ]:
verifier_colonne_structure(df_Nb_maraudes_SIGMA_struct, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Nb_maraudes_SIGMA_DT, "DT_de_rattachement", df_ref_structure)
verifier_colonne_structure(df_nb_contacts_SIGMA_struct, "n_structure", df_ref_structure)
verifier_colonne_structure( df_nb_contacts_SIGMA_DT, "DT_de_rattachement", df_ref_structure)
verifier_colonne_structure(df_nb_personnes_rencontrees_SIGMA_struct, "n_structure", df_ref_structure)
verifier_colonne_structure(df_nb_personnes_rencontrees_SIGMA_DT, "DT_de_rattachement", df_ref_structure)

df_maraude_verif= prep_nb_personnes_rencontrees_sigma(df_maraude, filtre_annee_fn=None)

df_maraude_verif= add_nb_personnes(df_maraude_verif,
                     out_col="nb personnes",
                     cols=None,
                     col_typologie="maraude_rencontre_typologie")

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.

   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [ ]:
run_verif_maraude(
    df_Nb_maraudes_SIGMA_struct=df_Nb_maraudes_SIGMA_struct,
    df_Nb_maraudes_SIGMA_DT=df_Nb_maraudes_SIGMA_DT,
    df_nb_contacts_SIGMA_struct=df_nb_contacts_SIGMA_struct,
    df_nb_contacts_SIGMA_DT=df_nb_contacts_SIGMA_DT,
    df_nb_personnes_rencontrees_SIGMA_struct=df_nb_personnes_rencontrees_SIGMA_struct,
    df_nb_personnes_rencontrees_SIGMA_DT=df_nb_personnes_rencontrees_SIGMA_DT,
    df_Nb_maraudes_SIGMA=df_Nb_maraudes_SIGMA,
    df_maraude_verif=df_maraude_verif,
    df_personnes_diff_base=df_personnes_diff_base,
)

====================
VERIF MARAUDE
====================

✅ #1 Nb maraudes (Struct vs DT) - OK : somme(df_left['Maraude Nb_maraudes_SIGMA']) = somme(df_right['Maraude Nb_maraudes_SIGMA']) (total=3180)
✅ #2 Nb contacts (Struct vs DT) - OK : somme(df_left['Maraude Nb_contacts']) = somme(df_right['Maraude Nb_contacts']) (total=49448)
✅ #3 Nb personnes rencontrées (Struct vs DT) - OK : somme(df_left['Maraude Nb_personnes_rencontrees']) = somme(df_right['Maraude Nb_personnes_rencontrees']) (total=38610)
✅ #4 OK : somme maraudes structure (3180) = len(df_Nb_maraudes_SIGMA) (3180)
✅ #5 OK : personnes différentes rencontrées — somme df_base = 38610 = somme df_struct = 38610
✅ #6 OK Somme contact  OK : somme 'Maraude Nb contacts struct' df struct = somme Nb contacts df maraude verif = 49448

Données manuelles maraude

In [ ]:
#Calcul données maraude manuelles
df_Maraude_donnees_manuelles_DT_2, df_Maraude_donnees_manuelles_structure_2 = calcul_indic_maraude_manuelles(df_ref_structure, df_Maraude_donnees_manuelles, rattachement_court)

#Verif données maraude manuelles
check_maraude_sums(df_Maraude_donnees_manuelles, df_Maraude_donnees_manuelles_DT_2)
check_maraude_sums(df_Maraude_donnees_manuelles, df_Maraude_donnees_manuelles_structure_2)

AttributeError: 'tuple' object has no attribute 'copy'

## Base contact

In [ ]:
# Indicateurs
indicateurs_base_contact, indicateurs_base_contact_DT = indicateurs_base_contact(client, df_formation_session_resultat, df_formation_count_session_2025, df_formation_session_resultat_fpg, df_ref_structure, target_date=TARGET_DATE)
indicateurs_base_contact_DT = correction_indic_BC_DT(df_ref_structure, indicateurs_base_contact, indicateurs_base_contact_DT, year = TARGET_YEAR)

===== Vérification des codes =====

Indicateur : AEO Nb_AAD
  Codes attendus : {'AAD'}
  Codes trouvés  : {'AAD'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_TCAU_2026
  Codes attendus : {'TCAU', 'ETCAU'}
  Codes trouvés  : {'TCAU', 'ETCAU'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_TCEO_2026
  Codes attendus : {'TCEO', 'ESE'}
  Codes trouvés  : {'TCEO', 'ESE'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_PSP_2026
  Codes attendus : {'PSP'}
  Codes trouvés  : {'PSP'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_IRR_2026
  Codes attendus : {'IRRA', 'IRRJ', 'IRR'}
  Codes trouvés  : {'IRRA', 'IRR', 'IRRJ'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_GQS_2026
  Codes attendus : {'PSC1', 'PSC AC', 'EPSC', 'EPSC1', 'FCPSE1', 'RATPSE2', 'FCPSC', 'PSC1 AC', 'PSC', 'RECPSE2', 'PSE2', 'PSE AGSU', 'FIPS', 'RECPSC1', 'PSE1', 'RECPSE1', 'FCPSE2', 'GQS AC', 'GQS', 'PSC IRR', 'FCPSE', 'PSE', 'PSC1 IRR', 'RATPSE1', 'FIPS2', 'APTE PSE1'}
  Codes trouvés  : {'PSC1', 'PSC AC', 'EPSC', 'EPSC1', 'FCPSE1', 'RATPSE2', 'FCPSC', 'PSC1 AC', 'PSC', 'RECPSE2', 'PSE2', 'FIPS', 'RECPSC1', 'PSE1', 'RECPSE1', 'FCPSE2', 'GQS', 'PSC IRR', 'FCPSE', 'PSE', 'PSC1 IRR', 'RATPSE1', 'FIPS2', 'APTE PSE1'}
  Codes manquants: {'GQS AC', 'PSE AGSU'}

Indicateur : Structure Nb_formes_CRB_2026
  Codes attendus : {'CRB', 'ECRB', 'VI'}
  Codes trouvés  : {'CRB', 'ECRB', 'VI'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:174: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
AEO Nb_AAD : 1270
Dispositifs_d_urgence Nb_formes_TCAU_2026 : 11434
Dispositifs_d_urgence Nb_formes_TCEO_2026 : 1749
Dispositifs_d_urgence Nb_formes_PSP_2026 : 4934
Dispositifs_d_urgence Nb_formes_IRR_2026 : 22744
Dispositifs_d_urgence Nb_formes_GQS_2026 : 34468
Structure Nb_formes_CRB_2026 : 19974

===== Vérification des codes =====

Indicateur : AEO Nb_AAD
  Codes attendus : {'AAD'}
  Codes trouvés  : {'AAD'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_TCAU_2026
  Codes attendus : {'TCAU', 'ETCAU'}
  Codes trouvés  : {'TCAU', 'ETCAU'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_TCEO_2026
  Codes attendus : {'TCEO', 'ESE'}
  Codes trouvés  : {'TCEO', 'ESE'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_PSP_2026
  Codes attendus : {'PSP'}
  Codes trouvés  : {'PSP'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_IRR_2026
  Codes attendus : {'IRRA', 'IRRJ', 'IRR'}
  Codes trouvés  : {'IRRA', 'IRR', 'IRRJ'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_GQS_2026
  Codes attendus : {'PSC1', 'PSC AC', 'EPSC', 'EPSC1', 'FCPSE1', 'RATPSE2', 'FCPSC', 'PSC1 AC', 'PSC', 'RECPSE2', 'PSE2', 'PSE AGSU', 'FIPS', 'RECPSC1', 'PSE1', 'RECPSE1', 'FCPSE2', 'GQS AC', 'GQS', 'PSC IRR', 'FCPSE', 'PSE', 'PSC1 IRR', 'RATPSE1', 'FIPS2', 'APTE PSE1'}
  Codes trouvés  : {'PSC1', 'PSC AC', 'EPSC', 'EPSC1', 'FCPSE1', 'RATPSE2', 'FCPSC', 'PSC1 AC', 'PSC', 'RECPSE2', 'PSE2', 'FIPS', 'RECPSC1', 'PSE1', 'RECPSE1', 'FCPSE2', 'GQS', 'PSC IRR', 'FCPSE', 'PSE', 'PSC1 IRR', 'RATPSE1', 'FIPS2', 'APTE PSE1'}
  Codes manquants: {'GQS AC', 'PSE AGSU'}

Indicateur : Structure Nb_formes_CRB_2026
  Codes attendus : {'CRB', 'ECRB', 'VI'}
  Codes trouvés  : {'CRB', 'ECRB', 'VI'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:174: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
AEO Nb_AAD : 1270
Dispositifs_d_urgence Nb_formes_TCAU_2026 : 11434
Dispositifs_d_urgence Nb_formes_TCEO_2026 : 1749
Dispositifs_d_urgence Nb_formes_PSP_2026 : 4934
Dispositifs_d_urgence Nb_formes_IRR_2026 : 22744
Dispositifs_d_urgence Nb_formes_GQS_2026 : 34468
Structure Nb_formes_CRB_2026 : 19974

===== Vérification des codes =====

Indicateur : Maraude Nb_SOLIDAR
  Codes attendus : {'SOLIDAR2020', 'SOLIDAR', 'PASSOLIDAR2020', 'SOLIDAR1', 'SOLIDAR2', 'ESOLIDAR2026'}
  Codes trouvés  : {'SOLIDAR', 'PASSOLIDAR2020', 'ESOLIDAR2026', 'SOLIDAR1', 'SOLIDAR2', 'SOLIDAR2020'}
  Codes manquants: set()

Indicateur : Maraude Nb_SOLIDAR2020
  Codes attendus : {'SOLIDAR2020', 'PASSOLIDAR2020', 'ESOLIDAR2026'}
  Codes trouvés  : {'PASSOLIDAR2020', 'SOLIDAR2020', 'ESOLIDAR2026'}
  Codes manquants: set()

Indicateur : AEO Nb_FAAD
  Codes attendus : {'EPIAF FAAD', 'FAAD'}
  Codes trouvés  : {'EPIAF FAAD', 'FAAD'}
  Codes manquants: set()

Indicateur : Structure Nb_formateurs_CRB_2026
  Codes attendus : {'ACRB2024', 'ACRB3', 'ACRB2', 'ACRB'}
  Codes trouvés  : {'ACRB2024', 'ACRB3', 'ACRB2', 'ACRB'}
  Codes manquants: set()

Indicateur : Structure Nb_formes_TCAS_2026
  Codes attendus : {'ETCAS', 'TCAS'}
  Codes trouvés  : {'ETCAS', 'TCAS'}
  Codes manquants: set()

Indicateur : Textile Animateurs_textile
  Codes attendus : {'FTEX'}
  Codes trouvés  : set()
  Codes manquants: {'FTEX'}

Indicateur : Aide_alimentaire nb_SAH
  Codes attendus : {'SAH', 'TASA'}
  Codes trouvés  : {'SAH', 'TASA'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:227: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Maraude Nb_SOLIDAR : 7307
Maraude Nb_SOLIDAR2020 : 5492
AEO Nb_FAAD : 50
Structure Nb_formateurs_CRB_2026 : 818
Structure Nb_formes_TCAS_2026 : 10934
Textile Animateurs_textile : 0
Aide_alimentaire nb_SAH : 2208

===== Vérification des codes =====

Indicateur : Maraude Nb_SOLIDAR
  Codes attendus : {'SOLIDAR2020', 'SOLIDAR', 'PASSOLIDAR2020', 'SOLIDAR1', 'SOLIDAR2', 'ESOLIDAR2026'}
  Codes trouvés  : {'SOLIDAR', 'PASSOLIDAR2020', 'ESOLIDAR2026', 'SOLIDAR1', 'SOLIDAR2', 'SOLIDAR2020'}
  Codes manquants: set()

Indicateur : Maraude Nb_SOLIDAR2020
  Codes attendus : {'SOLIDAR2020', 'PASSOLIDAR2020', 'ESOLIDAR2026'}
  Codes trouvés  : {'PASSOLIDAR2020', 'SOLIDAR2020', 'ESOLIDAR2026'}
  Codes manquants: set()

Indicateur : AEO Nb_FAAD
  Codes attendus : {'EPIAF FAAD', 'FAAD'}
  Codes trouvés  : {'EPIAF FAAD', 'FAAD'}
  Codes manquants: set()

Indicateur : Structure Nb_formateurs_CRB_2026
  Codes attendus : {'ACRB2024', 'ACRB3', 'ACRB2', 'ACRB'}
  Codes trouvés  : {'ACRB2024', 'ACRB3', 'ACRB2', 'ACRB'}
  Codes manquants: set()

Indicateur : Structure Nb_formes_TCAS_2026
  Codes attendus : {'ETCAS', 'TCAS'}
  Codes trouvés  : {'ETCAS', 'TCAS'}
  Codes manquants: set()

Indicateur : Textile Animateurs_textile
  Codes attendus : {'FTEX'}
  Codes trouvés  : set()
  Codes manquants: {'FTEX'}

Indicateur : Aide_alimentaire nb_SAH
  Codes attendus : {'SAH', 'TASA'}
  Codes trouvés  : {'SAH', 'TASA'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:227: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Maraude Nb_SOLIDAR : 7307
Maraude Nb_SOLIDAR2020 : 5492
AEO Nb_FAAD : 50
Structure Nb_formateurs_CRB_2026 : 818
Structure Nb_formes_TCAS_2026 : 10934
Textile Animateurs_textile : 0
Aide_alimentaire nb_SAH : 2208

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_formes_PSC_2026
  Codes attendus : {'RECPSC1', 'PSC', 'PSC1 IRR', 'PSC1', 'PSC AC', 'PSC IRR', 'EPSC', 'EPSC1', 'FCPSC', 'PSC1 AC'}
  Codes trouvés  : {'RECPSC1', 'PSC', 'PSC1 IRR', 'PSC1', 'PSC AC', 'PSC IRR', 'EPSC', 'EPSC1', 'FCPSC'}
  Codes manquants: {'PSC1 AC'}

Indicateur : Formation_grand_public Nb_formes_GQS_2026
  Codes attendus : {'GQS', 'FIPS2', 'GQS AC', 'FIPS'}
  Codes trouvés  : {'GQS', 'GQS AC', 'FIPS2', 'FIPS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_IPS_2026
  Codes attendus : {'IPSP', 'IPSJP', 'IPS AC', 'IPSEF', 'IPSE', 'IPS', 'IPS SR', 'IPSJ', 'IPSM'}
  Codes trouvés  : {'IPSJP', 'IPS AC', 'IPSE', 'IPSEF', 'IPS', 'IPSJ'}
  Codes manquants: {'IPSP', 'IPS SR', 'IPSM'}

Indicateur : Formation_grand_public Nb_formes_IPSEN_2026
  Codes attendus : {'IPSEN'}
  Codes trouvés  : {'IPSEN'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_PREVIC_2026
  Codes attendus : {'PREVIC'}
  Codes trouvés  : set()
  Codes manquants: {'PREVIC'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:282: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Formation_grand_public Nb_formes_PSC_2026 : 26608
Formation_grand_public Nb_formes_GQS_2026 : 3141
Formation_grand_public Nb_formes_IPS_2026 : 33067
Formation_grand_public Nb_formes_IPSEN_2026 : 3218
Formation_grand_public Nb_formes_PREVIC_2026 : 0

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_formes_PSC_2026
  Codes attendus : {'RECPSC1', 'PSC', 'PSC1 IRR', 'PSC1', 'PSC AC', 'PSC IRR', 'EPSC', 'EPSC1', 'FCPSC', 'PSC1 AC'}
  Codes trouvés  : {'RECPSC1', 'PSC', 'PSC1 IRR', 'PSC1', 'PSC AC', 'PSC IRR', 'EPSC', 'EPSC1', 'FCPSC'}
  Codes manquants: {'PSC1 AC'}

Indicateur : Formation_grand_public Nb_formes_GQS_2026
  Codes attendus : {'GQS', 'FIPS2', 'GQS AC', 'FIPS'}
  Codes trouvés  : {'GQS', 'GQS AC', 'FIPS2', 'FIPS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_IPS_2026
  Codes attendus : {'IPSP', 'IPSJP', 'IPS AC', 'IPSEF', 'IPSE', 'IPS', 'IPS SR', 'IPSJ', 'IPSM'}
  Codes trouvés  : {'IPSJP', 'IPS AC', 'IPSE', 'IPSEF', 'IPS', 'IPSJ'}
  Codes manquants: {'IPSP', 'IPS SR', 'IPSM'}

Indicateur : Formation_grand_public Nb_formes_IPSEN_2026
  Codes attendus : {'IPSEN'}
  Codes trouvés  : {'IPSEN'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_PREVIC_2026
  Codes attendus : {'PREVIC'}
  Codes trouvés  : set()
  Codes manquants: {'PREVIC'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:282: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Formation_grand_public Nb_formes_PSC_2026 : 26538
Formation_grand_public Nb_formes_GQS_2026 : 3140
Formation_grand_public Nb_formes_IPS_2026 : 33067
Formation_grand_public Nb_formes_IPSEN_2026 : 3214
Formation_grand_public Nb_formes_PREVIC_2026 : 0

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_sessions_PSC_2026
  Codes attendus : {'RECPSC1', 'PSC', 'PSC1 IRR', 'PSC1', 'PSC AC', 'PSC IRR', 'EPSC', 'EPSC1', 'FCPSC', 'PSC1 AC'}
  Codes trouvés  : {'RECPSC1', 'PSC', 'PSC1 IRR', 'PSC1', 'PSC AC', 'PSC IRR', 'EPSC', 'EPSC1', 'FCPSC'}
  Codes manquants: {'PSC1 AC'}

Indicateur : Formation_grand_public Nb_sessions_GQS_2026
  Codes attendus : {'GQS', 'FIPS2', 'GQS AC', 'FIPS'}
  Codes trouvés  : {'GQS', 'GQS AC', 'FIPS2', 'FIPS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_IPS_2026
  Codes attendus : {'IPSP', 'IPSJP', 'IPS AC', 'IPSEF', 'IPSE', 'IPS', 'IPS SR', 'IPSJ', 'IPSM'}
  Codes trouvés  : {'IPSP', 'IPSJP', 'IPS AC', 'IPSEF', 'IPSE', 'IPS', 'IPSJ'}
  Codes manquants: {'IPSM', 'IPS SR'}

Indicateur : Formation_grand_public Nb_sessions_IPSEN_2026
  Codes attendus : {'IPSEN'}
  Codes trouvés  : {'IPSEN'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_PREVIC_2026
  Codes attendus : {'PREVIC'}
  Codes trouvés  : {'PREVIC'}
  Codes manquants: set()

Indicateur : Secours Nb_sessions_PSE
  Codes attendus : {'RECPSE2', 'RECPSE1', 'PSE1', 'FCPSE2', 'RATPSE1', 'RATPSE2', 'FCPSE1', 'FCPSE', 'APTE PSE1', 'PSE2', 'PSE'}
  Codes trouvés  : {'RECPSE2', 'PSE1', 'RECPSE1', 'FCPSE2', 'RATPSE1', 'PSE2', 'FCPSE1', 'FCPSE', 'APTE PSE1', 'RATPSE2', 'PSE'}
  Codes manquants: set()

Indicateur : Secours Nb_sessions_CI
  Codes attendus : {'RECCI', 'CI P1 P2', 'CI', 'REC PSECI', 'FCCI', 'CIP2', 'RECPSECI'}
  Codes trouvés  : {'RECCI', 'CI', 'FCCI'}
  Codes manquants: {'RECPSECI', 'CIP2', 'CI P1 P2', 'REC PSECI'}

Indicateur : Secours Nb_sessions_FPSE
  Codes attendus : {'RECFPS', 'FPSE', 'RATFCFPSE', 'FPS', 'FCFPSE', 'PICF FPS', 'PICF FPSE'}
  Codes trouvés  : {'FPSE', 'RATFCFPSE', 'FPS', 'FCFPSE', 'PICF FPS', 'PICF FPSE'}
  Codes manquants: {'RECFPS'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:347: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Formation_grand_public Nb_sessions_PSC_2026 : 3282
Formation_grand_public Nb_sessions_GQS_2026 : 416
Formation_grand_public Nb_sessions_IPS_2026 : 4134
Formation_grand_public Nb_sessions_IPSEN_2026 : 378
Formation_grand_public Nb_sessions_PREVIC_2026 : 1
Secours Nb_sessions_PSE : 726
Secours Nb_sessions_CI : 169
Secours Nb_sessions_FPSE : 9

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_sessions_PSC_2026
  Codes attendus : {'RECPSC1', 'PSC', 'PSC1 IRR', 'PSC1', 'PSC AC', 'PSC IRR', 'EPSC', 'EPSC1', 'FCPSC', 'PSC1 AC'}
  Codes trouvés  : {'RECPSC1', 'PSC', 'PSC1 IRR', 'PSC1', 'PSC AC', 'PSC IRR', 'EPSC', 'EPSC1', 'FCPSC'}
  Codes manquants: {'PSC1 AC'}

Indicateur : Formation_grand_public Nb_sessions_GQS_2026
  Codes attendus : {'GQS', 'FIPS2', 'GQS AC', 'FIPS'}
  Codes trouvés  : {'GQS', 'GQS AC', 'FIPS2', 'FIPS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_IPS_2026
  Codes attendus : {'IPSP', 'IPSJP', 'IPS AC', 'IPSEF', 'IPSE', 'IPS', 'IPS SR', 'IPSJ', 'IPSM'}
  Codes trouvés  : {'IPSP', 'IPSJP', 'IPS AC', 'IPSEF', 'IPSE', 'IPS', 'IPSJ'}
  Codes manquants: {'IPSM', 'IPS SR'}

Indicateur : Formation_grand_public Nb_sessions_IPSEN_2026
  Codes attendus : {'IPSEN'}
  Codes trouvés  : {'IPSEN'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_PREVIC_2026
  Codes attendus : {'PREVIC'}
  Codes trouvés  : {'PREVIC'}
  Codes manquants: set()

Indicateur : Secours Nb_sessions_PSE
  Codes attendus : {'RECPSE2', 'RECPSE1', 'PSE1', 'FCPSE2', 'RATPSE1', 'RATPSE2', 'FCPSE1', 'FCPSE', 'APTE PSE1', 'PSE2', 'PSE'}
  Codes trouvés  : {'RECPSE2', 'PSE1', 'RECPSE1', 'FCPSE2', 'RATPSE1', 'PSE2', 'FCPSE1', 'FCPSE', 'APTE PSE1', 'RATPSE2', 'PSE'}
  Codes manquants: set()

Indicateur : Secours Nb_sessions_CI
  Codes attendus : {'RECCI', 'CI P1 P2', 'CI', 'REC PSECI', 'FCCI', 'CIP2', 'RECPSECI'}
  Codes trouvés  : {'RECCI', 'CI', 'FCCI'}
  Codes manquants: {'RECPSECI', 'CIP2', 'CI P1 P2', 'REC PSECI'}

Indicateur : Secours Nb_sessions_FPSE
  Codes attendus : {'RECFPS', 'FPSE', 'RATFCFPSE', 'FPS', 'FCFPSE', 'PICF FPS', 'PICF FPSE'}
  Codes trouvés  : {'FPSE', 'RATFCFPSE', 'FPS', 'FCFPSE', 'PICF FPS', 'PICF FPSE'}
  Codes manquants: {'RECFPS'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:347: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Formation_grand_public Nb_sessions_PSC_2026 : 3282
Formation_grand_public Nb_sessions_GQS_2026 : 416
Formation_grand_public Nb_sessions_IPS_2026 : 4134
Formation_grand_public Nb_sessions_IPSEN_2026 : 378
Formation_grand_public Nb_sessions_PREVIC_2026 : 1
Secours Nb_sessions_PSE : 726
Secours Nb_sessions_CI : 169
Secours Nb_sessions_FPSE : 9

===== Vérification des codes =====

Indicateur : Dispositifs_d_urgence Structures_menant_activite_TCAU
  Codes attendus : {'TCAU', 'ETCAU'}
  Codes trouvés  : {'TCAU', 'ETCAU'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Structures_menant_activite_PSP
  Codes attendus : {'PSP'}
  Codes trouvés  : {'PSP'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Structures_menant_activite_GQS
  Codes attendus : {'GQS', 'FIPS2', 'GQS AC', 'FIPS'}
  Codes trouvés  : {'GQS', 'GQS AC', 'FIPS2', 'FIPS'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:404: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Dispositifs_d_urgence Structures_menant_activite_TCAU : 48
Dispositifs_d_urgence Structures_menant_activite_PSP : 37
Dispositifs_d_urgence Structures_menant_activite_GQS : 435

===== Vérification des codes =====

Indicateur : Dispositifs_d_urgence Structures_menant_activite_TCAU
  Codes attendus : {'TCAU', 'ETCAU'}
  Codes trouvés  : {'TCAU', 'ETCAU'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Structures_menant_activite_PSP
  Codes attendus : {'PSP'}
  Codes trouvés  : {'PSP'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Structures_menant_activite_GQS
  Codes attendus : {'GQS', 'FIPS2', 'GQS AC', 'FIPS'}
  Codes trouvés  : {'GQS', 'GQS AC', 'FIPS2', 'FIPS'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:404: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Dispositifs_d_urgence Structures_menant_activite_TCAU : 48
Dispositifs_d_urgence Structures_menant_activite_PSP : 37
Dispositifs_d_urgence Structures_menant_activite_GQS : 435

===== Vérification des codes =====

Indicateur : Secours Nb_PSE1
  Codes attendus : {'RECPSE1', 'PSE1', 'RATPSE1', 'FCPSE1', 'APTE PSE1'}
  Codes trouvés  : {'PSE1', 'RECPSE1', 'RATPSE1', 'FCPSE1', 'APTE PSE1'}
  Codes manquants: set()

Indicateur : Secours Nb_PSE2
  Codes attendus : {'RECPSE2', 'FCPSE2', 'RATPSE2', 'FCPSE', 'PSE2', 'PSE AGSU', 'PSE'}
  Codes trouvés  : {'RECPSE2', 'FCPSE2', 'RATPSE2', 'FCPSE', 'PSE2', 'PSE'}
  Codes manquants: {'PSE AGSU'}

Indicateur : Secours Nb_CI
  Codes attendus : {'RECCI', 'CI P1 P2', 'CI', 'REC PSECI', 'FCCI', 'CIP2', 'RECPSECI'}
  Codes trouvés  : {'RECCI', 'CI', 'FCCI'}
  Codes manquants: {'RECPSECI', 'CIP2', 'CI P1 P2', 'REC PSECI'}

Indicateur : Secours Nb_FPSE
  Codes attendus : {'FPSE'}
  Codes trouvés  : {'FPSE'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:506: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: pd.Series({

===== Somme globale par indicateur =====
Secours Nb_PSE1 : 368
Secours Nb_PSE2 : 6117
Secours Nb_CI : 1286
Secours Nb_FPSE : 117

===== Vérification des codes =====

Indicateur : Secours Nb_PSE1
  Codes attendus : {'RECPSE1', 'PSE1', 'RATPSE1', 'FCPSE1', 'APTE PSE1'}
  Codes trouvés  : {'PSE1', 'RECPSE1', 'RATPSE1', 'FCPSE1', 'APTE PSE1'}
  Codes manquants: set()

Indicateur : Secours Nb_PSE2
  Codes attendus : {'RECPSE2', 'FCPSE2', 'RATPSE2', 'FCPSE', 'PSE2', 'PSE AGSU', 'PSE'}
  Codes trouvés  : {'RECPSE2', 'FCPSE2', 'RATPSE2', 'FCPSE', 'PSE2', 'PSE'}
  Codes manquants: {'PSE AGSU'}

Indicateur : Secours Nb_CI
  Codes attendus : {'RECCI', 'CI P1 P2', 'CI', 'REC PSECI', 'FCCI', 'CIP2', 'RECPSECI'}
  Codes trouvés  : {'RECCI', 'CI', 'FCCI'}
  Codes manquants: {'RECPSECI', 'CIP2', 'CI P1 P2', 'REC PSECI'}

Indicateur : Secours Nb_FPSE
  Codes attendus : {'FPSE'}
  Codes trouvés  : {'FPSE'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:506: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: pd.Series({

===== Somme globale par indicateur =====
Secours Nb_PSE1 : 368
Secours Nb_PSE2 : 6117
Secours Nb_CI : 1286
Secours Nb_FPSE : 117

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_FPSC
  Codes attendus : {'FPSC', 'PAE3', 'PICF FPSC', 'RECFPSC', 'FCFPSC', 'RATFCFPSC'}
  Codes trouvés  : {'FPSC', 'PICF FPSC', 'RECFPSC', 'FCFPSC', 'RATFCFPSC'}
  Codes manquants: {'PAE3'}

Indicateur : Formation_grand_public Nb_AGQS
  Codes attendus : {'AGQS'}
  Codes trouvés  : {'AGQS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_FIPSEN
  Codes attendus : {'FIPSEN', 'RECFIPSEN'}
  Codes trouvés  : {'FIPSEN'}
  Codes manquants: {'RECFIPSEN'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:579: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Formation_grand_public Nb_FPSC : 1152
Formation_grand_public Nb_AGQS : 144
Formation_grand_public Nb_FIPSEN : 11

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_FPSC
  Codes attendus : {'FPSC', 'PAE3', 'PICF FPSC', 'RECFPSC', 'FCFPSC', 'RATFCFPSC'}
  Codes trouvés  : {'FPSC', 'PICF FPSC', 'RECFPSC', 'FCFPSC', 'RATFCFPSC'}
  Codes manquants: {'PAE3'}

Indicateur : Formation_grand_public Nb_AGQS
  Codes attendus : {'AGQS'}
  Codes trouvés  : {'AGQS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_FIPSEN
  Codes attendus : {'FIPSEN', 'RECFIPSEN'}
  Codes trouvés  : {'FIPSEN'}
  Codes manquants: {'RECFIPSEN'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:579: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Formation_grand_public Nb_FPSC : 1152
Formation_grand_public Nb_AGQS : 144
Formation_grand_public Nb_FIPSEN : 11

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:633: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:633: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:633: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:633: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(

nb_recy_PSE1 : 242.0
nb_recy_PSE2 : 4887.0
nb_recy_CI : 170.0
nb_recy_FPSE : 117.0

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:633: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:633: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:633: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:633: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(

nb_recy_PSE1 : 242.0
nb_recy_PSE2 : 4887.0
nb_recy_CI : 170.0
nb_recy_FPSE : 117.0

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:692: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:692: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:692: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:692: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(

nb_ren_PSE1 : 166.0
nb_ren_PSE2 : 1878.0
nb_ren_CI : 194.0
nb_ren_FPSE : 117.0

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:692: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:692: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:692: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:692: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(

nb_ren_PSE1 : 166.0
nb_ren_PSE2 : 1878.0
nb_ren_CI : 194.0
nb_ren_FPSE : 117.0

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

===== Vérification des codes =====

Indicateur : Maraude Nb_benevoles_actifs_formes
  Codes attendus : {'SOLIDAR2020', 'SOLIDAR', 'PASSOLIDAR2020', 'SOLIDAR1', 'SOLIDAR2', 'ESOLIDAR2026'}
  Codes trouvés  : {'SOLIDAR1', 'SOLIDAR2020', 'SOLIDAR', 'ESOLIDAR2026'}
  Codes manquants: {'SOLIDAR2', 'PASSOLIDAR2020'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:1013: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Maraude Nb_benevoles_actifs_formes : 628

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

===== Vérification des codes =====

Indicateur : Maraude Nb_benevoles_actifs_formes
  Codes attendus : {'SOLIDAR2020', 'SOLIDAR', 'PASSOLIDAR2020', 'SOLIDAR1', 'SOLIDAR2', 'ESOLIDAR2026'}
  Codes trouvés  : {'SOLIDAR1', 'SOLIDAR2020', 'SOLIDAR', 'ESOLIDAR2026'}
  Codes manquants: {'SOLIDAR2', 'PASSOLIDAR2020'}

===== Somme globale par indicateur =====
Maraude Nb_benevoles_actifs_formes : 564

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:1013: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

===== Vérification des codes =====

Indicateur : Nb_IS
  Codes attendus : {'RECCI', 'CI', 'FCCI', 'FCPSE1', 'CIP2', 'RATPSE2', 'RECPSE2', 'CI P1 P2', 'PSE2', 'PSE AGSU', 'RECPSECI', 'RECPSE1', 'PSE1', 'FCPSE2', 'FCPSE', 'PSE', 'RATPSE1', 'REC PSECI', 'APTE PSE1'}
  Codes trouvés  : {'RECPSE2', 'RECPSE1', 'PSE1', 'FCPSE2', 'RECCI', 'CI', 'FCCI', 'FCPSE', 'FCPSE1', 'PSE2', 'APTE PSE1', 'RATPSE2', 'PSE'}
  Codes manquants: {'CI P1 P2', 'RATPSE1', 'REC PSECI', 'CIP2', 'PSE AGSU', 'RECPSECI'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:935: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Nb_IS : 7771

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

===== Vérification des codes =====

Indicateur : Nb_IS
  Codes attendus : {'RECCI', 'CI', 'FCCI', 'FCPSE1', 'CIP2', 'RATPSE2', 'RECPSE2', 'CI P1 P2', 'PSE2', 'PSE AGSU', 'RECPSECI', 'RECPSE1', 'PSE1', 'FCPSE2', 'FCPSE', 'PSE', 'RATPSE1', 'REC PSECI', 'APTE PSE1'}
  Codes trouvés  : {'RECPSE2', 'RECPSE1', 'PSE1', 'FCPSE2', 'RECCI', 'CI', 'FCCI', 'FCPSE', 'FCPSE1', 'PSE2', 'APTE PSE1', 'RATPSE2', 'PSE'}
  Codes manquants: {'CI P1 P2', 'RATPSE1', 'REC PSECI', 'CIP2', 'PSE AGSU', 'RECPSECI'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:935: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Nb_IS : 7771

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

===== Vérification des codes =====

Indicateur : Structure Nb_nvx_formes_CRB_2026
  Codes attendus : {'CRB', 'ECRB', 'VI'}
  Codes trouvés  : {'CRB', 'ECRB'}
  Codes manquants: {'VI'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:835: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Structure Nb_nvx_formes_CRB_2026 : 531

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

===== Vérification des codes =====

Indicateur : Structure Nb_nvx_formes_CRB_2026
  Codes attendus : {'CRB', 'ECRB', 'VI'}
  Codes trouvés  : {'CRB', 'ECRB'}
  Codes manquants: {'VI'}

===== Somme globale par indicateur =====
Structure Nb_nvx_formes_CRB_2026 : 531

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:835: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

## DPS

In [ ]:
#df_indicateurs_dps = indicateurs_dps(df_dps, df_ref_structure)

In [ ]:
#verifications_dps(df_dps_source, df_indicateurs_dps)

## AMBITION

In [ ]:
df_indic_ambition_pat = charger_indicateurs_ambition_pat(df_indic_ambition, df_ref_structure)

# Création du DataFrame final

La liste de tous les dataframes à fusionner sur df_ref_structure

In [ ]:
# On ne filtre pas les implantations locales avant à cause du rattachement successif
df_ref_structure = df_ref_structure[df_ref_structure["type_structure"].isin(["UNITE LOCALE - UL", "DELEGATION TERRITORIALE - DT", 'ANTENNE LOCALE - AL','INSTANCES NATIONALES - IN'])]

In [ ]:
liste_df_a_fusionner_toutes_structures = [df_indicateurs_gaia,referents_AEO,referents_OCR,IMPACT_ppc,df_CRopeVF,IMPACT_agrementAB, IMPACT_agrementDPS,
                                          df_mobilite_DT_UL,df_OCR_Nb_deployees,
                                          df_raw_TextileVF,
                                          df_adherent, df_personnes_domiciliees_struct,df_Maraude_donnees_manuelles_structure_2, indicateurs_base_contact,
                                          df_financier,
                                          pegass_output['Indics_pegass_struct']]

liste_df_a_fusionner_DT = [df_indicateurs_gaia_DT,referents_AEO_DT,referents_OCR_DT,IMPACT_ppc_DT,df_CRopeVF,
                           IMPACT_agrementAB_DT, IMPACT_agrementDPS_DT,df_mobilite_DT,Nb_OCR_DT,df_Dispositifs_d_urgence_PST,
                           df_CAICHUCMCC_conventionsVF,
                           df_Textile_DT, df_adherent_DT,
                           df_personnes_domiciliees_DT, df_Maraude_donnees_manuelles_DT_2, indicateurs_base_contact_DT,
                           df_financier_DT,df_financier_FGP_DT,Indics_pegass_DT,df_indic_ambition_pat]

In [ ]:
all_data, all_data_DT, liste_df_a_fusionner_toutes_structures_processed, liste_df_a_fusionner_DT_processed = traitement_all_data(liste_df_a_fusionner_toutes_structures, liste_df_a_fusionner_DT, df_ref_structure,df_ref_structure_DT,year = TARGET_YEAR)

TRAITEMENT DES INDICATEURS POUR TOUTES LES STRUCTURES

🧹 DataFrame 5 : suppression des colonnes ['Dispositifs_d_urgence Nb_agrements']
🧹 DataFrame 11 : suppression des colonnes ['DT_de_rattachement']
🧹 DataFrame 13 : suppression des colonnes ['Formation_grand_public Nb_formes_PREVIC_2026', 'Formation_grand_public Nb_sessions_PREVIC_2026']
🧹 DataFrame 14 : suppression des colonnes ['libelle_structure_x', 'libelle_structure_y', 'Région', 'n_dept', 'N° Smartview', 'Nom structure']
🧹 DataFrame 15 : suppression des colonnes ['IS Nb_benevoles_actifs']
✅ DataFrame 0 : aucun doublon dans 'n_structure'
✅ DataFrame 1 : aucun doublon dans 'n_structure'
✅ DataFrame 2 : aucun doublon dans 'n_structure'
✅ DataFrame 3 : aucun doublon dans 'n_structure'
✅ DataFrame 4 : aucun doublon dans 'n_structure'
✅ DataFrame 5 : aucun doublon dans 'n_structure'
✅ DataFrame 6 : aucun doublon dans 'n_structure'
✅ DataFrame 7 : aucun doublon dans 'n_structure'
✅ DataFrame 8 : aucun doublon dans 'n_structure'
✅ DataFrame 9 : aucun doublon dans 'n_structure'
✅ DataFrame 10 : aucun doublon dans 'n_structure'
✅ DataFrame 11 : aucun doublon dans 'n_structure'
✅ DataFrame 12 : aucun doublon dans 'n_structure'
✅ DataFrame 13 : aucun doublon dans 'n_structure'
✅ DataFrame 14 : aucun doublon dans 'n_structure'
✅ DataFrame 15 : aucun doublon dans 'n_structure'
TRAITEMENT DES INDICATEURS POUR LES DTs

🧹 DataFrame 5 : suppression des colonnes ['Dispositifs_d_urgence Nb_agrements']
🧹 DataFrame 9 : suppression des colonnes ['Territoire', 'PST constitué', 'Nom structure DT', 'N° Département', 'nom_structure']
🧹 DataFrame 10 : suppression des colonnes ['Departement', 'nom_structure']
🧹 DataFrame 15 : suppression des colonnes ['Formation_grand_public Nb_formes_PREVIC_2026', 'Formation_grand_public Nb_sessions_PREVIC_2026', 'Dispositifs_d_urgence Structures_menant_activite_TCAU', 'Dispositifs_d_urgence Structures_menant_activite_PSP', 'Dispositifs_d_urgence Structures_menant_activite_GQS']
🧹 DataFrame 16 : suppression des colonnes ['n_dept_x', 'libelle_structure_x', 'n_dept_y', 'libelle_structure_y', 'n_dept']
🧹 DataFrame 17 : suppression des colonnes ['n_dept']
🧹 DataFrame 18 : suppression des colonnes ['nb_activite_AEO', 'IS Nb_benevoles_actifs']
🧹 DataFrame 19 : suppression des colonnes ['n_dept', 'DT', '% Completion PAT', 'PAT FGP_Nb_sessions_PREVIC']
✅ DataFrame 0 : aucun doublon dans 'n_structure'
✅ DataFrame 1 : aucun doublon dans 'n_structure'
✅ DataFrame 2 : aucun doublon dans 'n_structure'
✅ DataFrame 3 : aucun doublon dans 'n_structure'
✅ DataFrame 4 : aucun doublon dans 'n_structure'
✅ DataFrame 5 : aucun doublon dans 'n_structure'
✅ DataFrame 6 : aucun doublon dans 'n_structure'
✅ DataFrame 7 : aucun doublon dans 'n_structure'
✅ DataFrame 8 : aucun doublon dans 'n_structure'
✅ DataFrame 9 : aucun doublon dans 'n_structure'
✅ DataFrame 10 : aucun doublon dans 'n_structure'
✅ DataFrame 11 : aucun doublon dans 'n_structure'
✅ DataFrame 12 : aucun doublon dans 'n_structure'
✅ DataFrame 13 : aucun doublon dans 'n_structure'
✅ DataFrame 14 : aucun doublon dans 'n_structure'
✅ DataFrame 15 : aucun doublon dans 'n_structure'
✅ DataFrame 16 : aucun doublon dans 'n_structure'
✅ DataFrame 17 : aucun doublon dans 'n_structure'
✅ DataFrame 18 : aucun doublon dans 'n_structure'
✅ DataFrame 19 : aucun doublon dans 'n_structure'

In [ ]:
report = check_sums_against_final(
    df_final=all_data,
    list_of_dfs=liste_df_a_fusionner_toutes_structures,
    key_col="n_structure",
    atol=1e-6
)

🔎 Vérification DataFrame 0
   ✅ 'Structure Nb_Benevoles' OK | individuel = 80878.0 | final = 80878.0
   ✅ 'Structure Nb_nvx_Benevoles_2026' OK | individuel = 6505.0 | final = 6505.0
   ✅ 'Structure Taux_nvx_Benevoles' OK | individuel = 6806.652442710888 | final = 6806.652442710889

🔎 Vérification DataFrame 1
   ✅ 'AEO Nb_responsables' OK | individuel = 52.0 | final = 52.0

🔎 Vérification DataFrame 2
   ✅ 'OCR Nb_referents' OK | individuel = 21.0 | final = 21.0

🔎 Vérification DataFrame 3
   ✅ 'Dispositifs_d_urgence Nb_personnes_prises_charge' OK | individuel = 8145.0 | final = 8145.0

🔎 Vérification DataFrame 4
   ✅ 'Dispositifs_d_urgence Nb_operations' OK | individuel = 74.0 | final = 74.0
   ✅ 'Dispositifs_d_urgence Nb_jours_operations' OK | individuel = 55.06111111111111 | final = 55.0611111111111
   ✅ 'Dispositifs_d_urgence Ope_secours' OK | individuel = 27.0 | final = 27.0
   ✅ 'Dispositifs_d_urgence Ope_soutien_pop' OK | individuel = 70.0 | final = 70.0
   ❌ 'Dispositifs_d_urgence Nb_personnes_prises_charge' KO | individuel = 7772.0 | final = 8145.0

🔎 Vérification DataFrame 5

🔎 Vérification DataFrame 6
   ✅ 'Secours Nb_agrements_DPS_2026' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 7
   ✅ 'AEO Structure_activite_mobile' OK | individuel = 169.0 | final = 169.0
   ✅ 'AEO Nb_PA_dispos_mobiles' OK | individuel = 17208.0 | final = 17208.0

🔎 Vérification DataFrame 8
   ✅ 'OCR Nb_deployees' OK | individuel = 100.0 | final = 100.0

🔎 Vérification DataFrame 9
   ✅ 'Textile Nb_boutiques' OK | individuel = 756.0 | final = 756.0
   ✅ 'Textile Nb_vestiaires' OK | individuel = 139.0 | final = 139.0

🔎 Vérification DataFrame 10
   ✅ 'Structure Nb_Adherents' OK | individuel = 47424.0 | final = 47424.0

🔎 Vérification DataFrame 11
   ✅ 'AEO Nb_personnes_domiciliees_crf' OK | individuel = 30833.0 | final = 30833.0

🔎 Vérification DataFrame 12
   ✅ 'Maraude Nb_maraudes_SIGMA' OK | individuel = 7639.0 | final = 7639.0
   ✅ 'Maraude Nb_personnes_rencontrees' OK | individuel = 26001.0 | final = 26001.0
   ✅ 'Maraude Nb_contacts' OK | individuel = 130884.0 | final = 130884.0

🔎 Vérification DataFrame 13
   ✅ 'AEO Nb_AAD' OK | individuel = 1255.0 | final = 1255.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCAU_2026' OK | individuel = 11378.0 | final = 11378.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCEO_2026' OK | individuel = 1745.0 | final = 1745.0
   ✅ 'Dispositifs_d_urgence Nb_formes_PSP_2026' OK | individuel = 4913.0 | final = 4913.0
   ✅ 'Dispositifs_d_urgence Nb_formes_IRR_2026' OK | individuel = 22616.0 | final = 22616.0
   ✅ 'Dispositifs_d_urgence Nb_formes_GQS_2026' OK | individuel = 34242.0 | final = 34242.0
   ✅ 'Structure Nb_formes_CRB_2026' OK | individuel = 19751.0 | final = 19751.0
   ✅ 'Maraude Nb_SOLIDAR' OK | individuel = 7274.0 | final = 7274.0
   ✅ 'Maraude Nb_SOLIDAR2020' OK | individuel = 5474.0 | final = 5474.0
   ✅ 'AEO Nb_FAAD' OK | individuel = 50.0 | final = 50.0
   ✅ 'Structure Nb_formateurs_CRB_2026' OK | individuel = 814.0 | final = 814.0
   ✅ 'Structure Nb_formes_TCAS_2026' OK | individuel = 10839.0 | final = 10839.0
   ✅ 'Textile Animateurs_textile' OK | individuel = 0.0 | final = 0.0
   ✅ 'Aide_alimentaire nb_SAH' OK | individuel = 2141.0 | final = 2141.0
   ✅ 'Formation_grand_public Nb_formes_PSC_2026' OK | individuel = 26608.0 | final = 26608.0
   ✅ 'Formation_grand_public Nb_formes_GQS_2026' OK | individuel = 3141.0 | final = 3141.0
   ✅ 'Formation_grand_public Nb_formes_IPS_2026' OK | individuel = 33067.0 | final = 33067.0
   ✅ 'Formation_grand_public Nb_formes_IPSEN_2026' OK | individuel = 3218.0 | final = 3218.0
   ✅ 'Formation_grand_public Nb_sessions_PSC_2026' OK | individuel = 3282.0 | final = 3282.0
   ✅ 'Formation_grand_public Nb_sessions_GQS_2026' OK | individuel = 416.0 | final = 416.0
   ✅ 'Formation_grand_public Nb_sessions_IPS_2026' OK | individuel = 4134.0 | final = 4134.0
   ✅ 'Formation_grand_public Nb_sessions_IPSEN_2026' OK | individuel = 378.0 | final = 378.0
   ✅ 'Secours Nb_sessions_PSE' OK | individuel = 726.0 | final = 726.0
   ✅ 'Secours Nb_sessions_CI' OK | individuel = 169.0 | final = 169.0
   ✅ 'Secours Nb_sessions_FPSE' OK | individuel = 9.0 | final = 9.0
   ✅ 'Secours Nb_PSE1' OK | individuel = 368.0 | final = 368.0
   ✅ 'Secours Nb_PSE2' OK | individuel = 6104.0 | final = 6104.0
   ✅ 'Secours Nb_CI' OK | individuel = 1285.0 | final = 1285.0
   ✅ 'Secours Nb_FPSE' OK | individuel = 116.0 | final = 116.0
   ✅ 'Secours Nb_IS' OK | individuel = 7757.0 | final = 7757.0
   ✅ 'Formation_grand_public Nb_FPSC' OK | individuel = 1151.0 | final = 1151.0
   ✅ 'Formation_grand_public Nb_AGQS' OK | individuel = 144.0 | final = 144.0
   ✅ 'Formation_grand_public Nb_FIPSEN' OK | individuel = 11.0 | final = 11.0
   ✅ 'Secours Taux_recy27_PSE1' OK | individuel = 128.81944444444443 | final = 128.81944444444443
   ✅ 'Secours Taux_recy27_PSE2' OK | individuel = 395.5776739613418 | final = 395.5776739613418
   ✅ 'Secours Taux_recy27_CI' OK | individuel = 50.063483592430956 | final = 50.063483592430956
   ✅ 'Secours Taux_recy27_FPSE' OK | individuel = 76.0 | final = 76.0
   ✅ 'Secours Taux_ren26_PSE1' OK | individuel = 85.09404761904763 | final = 85.09404761904763
   ✅ 'Secours Taux_ren26_PSE2' OK | individuel = 161.28567852488288 | final = 161.28567852488288
   ✅ 'Secours Taux_ren26_CI' OK | individuel = 57.03328937144726 | final = 57.03328937144726
   ✅ 'Secours Taux_ren26_FPSE' OK | individuel = 76.0 | final = 76.0
   ✅ 'Maraude Nb_benevoles_actifs_formes' OK | individuel = 627.0 | final = 627.0
   ✅ 'Secours Taux_IS_actifs' OK | individuel = 327.19269632230635 | final = 327.19269632230635
   ✅ 'Structure Nb_nvx_formes_CRB_2026' OK | individuel = 527.0 | final = 527.0

🔎 Vérification DataFrame 14
   ✅ 'Financier Prod_2025' OK | individuel = 92522349.0 | final = 92522349.0
   ✅ 'Financier ResNet_2025' OK | individuel = 2933238.0 | final = 2933238.0
   ✅ 'Financier ResCorrProd_2025' OK | individuel = -439.77086728494737 | final = -439.77086728494737
   ✅ 'Financier Prod_2023' OK | individuel = 87137686.19 | final = 87137686.19
   ✅ 'Financier ResNet_2023' OK | individuel = 5514287.5600000005 | final = 5514287.5600000005
   ✅ 'Financier ResCorrProd_2023' OK | individuel = -29.05920166825136 | final = -29.05920166825136
   ✅ 'Financier Prod_2024' OK | individuel = 88744753.2 | final = 88744753.2
   ✅ 'Financier ResNet_2024' OK | individuel = 4733061.050000001 | final = 4733061.050000001
   ✅ 'Financier ResCorrProd_2024' OK | individuel = -39.588478014266656 | final = -39.588478014266656
   ✅ 'Financier caf_2025' OK | individuel = 11943298.0 | final = 11943298.0
   ✅ 'Financier TresoBrute_2025' OK | individuel = 145661681.0 | final = 145661681.0
   ✅ 'Financier Mois_AvanceTreso_2025' OK | individuel = 18602.972448424283 | final = 18602.972448424283
   ✅ 'Textile Produit_2025' OK | individuel = 19477584.0 | final = 19477584.0
   ✅ 'Secours Produits_DPS_2025' OK | individuel = 9739183.0 | final = 9739183.0

🔎 Vérification DataFrame 15
   ✅ 'Maraude Nb_maraudes_PEGASS' OK | individuel = 7681.0 | final = 7681.0
   ❌ 'Dispositifs_d_urgence Nb_operations' KO | individuel = 1325.0 | final = 74.0
   ✅ 'Dispositifs_d_urgence Nb_exercices' OK | individuel = 60.0 | final = 60.0
   ✅ 'AEO Structure_activite_fixe' OK | individuel = 0.0 | final = 0.0
   ✅ 'Maraude Nb_benevoles_actifs' OK | individuel = 5287.0 | final = 5287.0
   ✅ 'AEO Nb_benevoles_actifs' OK | individuel = 663.0 | final = 663.0
   ✅ 'Activités AAD facultatives' OK | individuel = 0.0 | final = 0.0

In [ ]:
report = check_sums_against_final(
  df_final=all_data_DT,
  list_of_dfs=liste_df_a_fusionner_DT,
  key_col="n_structure",
  atol=1e-6
  )

🔎 Vérification DataFrame 0
   ✅ 'Structure Nb_Benevoles' OK | individuel = 79694.0 | final = 79694.0
   ✅ 'Structure Nb_nvx_Benevoles_2026' OK | individuel = 6452.0 | final = 6452.0
   ✅ 'Structure Taux_nvx_Benevoles' OK | individuel = 855.6746114569407 | final = 855.6746114569407

🔎 Vérification DataFrame 1
   ✅ 'AEO Nb_responsables' OK | individuel = 52.0 | final = 52.0

🔎 Vérification DataFrame 2
   ✅ 'OCR Nb_referents' OK | individuel = 21.0 | final = 21.0

🔎 Vérification DataFrame 3
   ✅ 'Dispositifs_d_urgence Nb_personnes_prises_charge' OK | individuel = 8145.0 | final = 8145.0

🔎 Vérification DataFrame 4
   ❌ 'Dispositifs_d_urgence Nb_operations' KO | individuel = 74.0 | final = 67.0
   ❌ 'Dispositifs_d_urgence Nb_jours_operations' KO | individuel = 55.06111111111111 | final = 52.40833333333333
   ❌ 'Dispositifs_d_urgence Ope_secours' KO | individuel = 27.0 | final = 25.0
   ❌ 'Dispositifs_d_urgence Ope_soutien_pop' KO | individuel = 70.0 | final = 65.0
   ❌ 'Dispositifs_d_urgence Nb_personnes_prises_charge' KO | individuel = 7772.0 | final = 8145.0

🔎 Vérification DataFrame 5

🔎 Vérification DataFrame 6
   ✅ 'Secours Nb_agrements_DPS_2026' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 7
   ✅ 'AEO Structure_activite_mobile' OK | individuel = 169.0 | final = 169.0
   ✅ 'AEO Nb_PA_dispos_mobiles' OK | individuel = 17208.0 | final = 17208.0

🔎 Vérification DataFrame 8
   ✅ 'OCR Nb_deployees' OK | individuel = 100.0 | final = 100.0

🔎 Vérification DataFrame 9
   ✅ 'Dispositifs_d_urgence PST' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 10
   ✅ 'Dispositifs_d_urgence Nb_lots_CAI' OK | individuel = 228.0 | final = 228.0
   ✅ 'Dispositifs_d_urgence Nb_lots_CHU' OK | individuel = 182.0 | final = 182.0
   ✅ 'Dispositifs_d_urgence Nb_lots_CMCC' OK | individuel = 245.0 | final = 245.0
   ✅ 'Dispositifs_d_urgence Nb_conventions_prefecture' OK | individuel = 0.0 | final = 0.0
   ✅ 'Dispositifs_d_urgence Nb_conventions_operateurs_publics' OK | individuel = 247.0 | final = 247.0
   ✅ 'Dispositifs_d_urgence Nb_conventions_operateurs_prives' OK | individuel = 191.0 | final = 191.0
   ✅ 'Dispositifs_d_urgence Nb_conventions_operateurs' OK | individuel = 438.0 | final = 438.0

🔎 Vérification DataFrame 11
   ✅ 'Textile Nb_boutiques' OK | individuel = 756.0 | final = 756.0
   ✅ 'Textile Nb_vestiaires' OK | individuel = 139.0 | final = 139.0

🔎 Vérification DataFrame 12
   ✅ 'Structure Nb_Adherents' OK | individuel = 47403.0 | final = 47403.0

🔎 Vérification DataFrame 13
   ✅ 'AEO Nb_personnes_domiciliees_crf' OK | individuel = 30833.0 | final = 30833.0

🔎 Vérification DataFrame 14
   ✅ 'Maraude Nb_maraudes_SIGMA' OK | individuel = 7639.0 | final = 7639.0
   ✅ 'Maraude Nb_personnes_rencontrees' OK | individuel = 26001.0 | final = 26001.0
   ✅ 'Maraude Nb_contacts' OK | individuel = 130884.0 | final = 130884.0

🔎 Vérification DataFrame 15
   ✅ 'AEO Nb_AAD' OK | individuel = 1267.0 | final = 1267.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCAU_2026' OK | individuel = 11391.0 | final = 11391.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCEO_2026' OK | individuel = 1728.0 | final = 1728.0
   ✅ 'Dispositifs_d_urgence Nb_formes_PSP_2026' OK | individuel = 4928.0 | final = 4928.0
   ✅ 'Dispositifs_d_urgence Nb_formes_IRR_2026' OK | individuel = 22567.0 | final = 22567.0
   ✅ 'Dispositifs_d_urgence Nb_formes_GQS_2026' OK | individuel = 34143.0 | final = 34143.0
   ✅ 'Structure Nb_formes_CRB_2026' OK | individuel = 19885.0 | final = 19885.0
   ✅ 'Maraude Nb_SOLIDAR' OK | individuel = 7289.0 | final = 7289.0
   ✅ 'Maraude Nb_SOLIDAR2020' OK | individuel = 5485.0 | final = 5485.0
   ✅ 'AEO Nb_FAAD' OK | individuel = 49.0 | final = 49.0
   ✅ 'Structure Nb_formateurs_CRB_2026' OK | individuel = 809.0 | final = 809.0
   ✅ 'Structure Nb_formes_TCAS_2026' OK | individuel = 10889.0 | final = 10889.0
   ✅ 'Formation_grand_public Nb_sessions_PSC_2026' OK | individuel = 3257.0 | final = 3257.0
   ✅ 'Formation_grand_public Nb_sessions_GQS_2026' OK | individuel = 407.0 | final = 407.0
   ✅ 'Formation_grand_public Nb_sessions_IPS_2026' OK | individuel = 4110.0 | final = 4110.0
   ✅ 'Formation_grand_public Nb_sessions_IPSEN_2026' OK | individuel = 378.0 | final = 378.0
   ✅ 'Secours Nb_sessions_PSE' OK | individuel = 693.0 | final = 693.0
   ✅ 'Secours Nb_sessions_CI' OK | individuel = 163.0 | final = 163.0
   ✅ 'Secours Nb_sessions_FPSE' OK | individuel = 3.0 | final = 3.0
   ✅ 'Secours Nb_PSE1' OK | individuel = 368.0 | final = 368.0
   ✅ 'Secours Nb_PSE2' OK | individuel = 6116.0 | final = 6116.0
   ✅ 'Secours Nb_CI' OK | individuel = 1286.0 | final = 1286.0
   ✅ 'Secours Nb_IS' OK | individuel = 7770.0 | final = 7770.0
   ✅ 'Formation_grand_public Nb_FPSC' OK | individuel = 1149.0 | final = 1149.0
   ✅ 'Formation_grand_public Nb_AGQS' OK | individuel = 144.0 | final = 144.0
   ✅ 'Formation_grand_public Nb_FIPSEN' OK | individuel = 11.0 | final = 11.0
   ✅ 'Secours Taux_recy27_PSE1' OK | individuel = 52.758117146011884 | final = 52.758117146011884
   ✅ 'Secours Taux_recy27_PSE2' OK | individuel = 76.48392662202134 | final = 76.48392662202134
   ✅ 'Secours Taux_recy27_CI' OK | individuel = 13.43031407780032 | final = 13.43031407780032
   ✅ 'Secours Taux_ren26_PSE1' OK | individuel = 34.50107393581079 | final = 34.50107393581079
   ✅ 'Secours Taux_ren26_PSE2' OK | individuel = 35.121191394150216 | final = 35.121191394150216
   ✅ 'Secours Taux_ren26_CI' OK | individuel = 16.428818365268466 | final = 16.428818365268466
   ✅ 'Maraude Nb_benevoles_actifs_formes' OK | individuel = 562.0 | final = 562.0
   ✅ 'Secours Taux_IS_actifs' OK | individuel = 59.705170288995006 | final = 59.705170288995006
   ✅ 'Structure Nb_nvx_formes_CRB_2026' OK | individuel = 530.0 | final = 530.0
   ✅ 'Formation_grand_public Nb_formes_PSC_2026' OK | individuel = 26555.0 | final = 26555.0
   ✅ 'Formation_grand_public Nb_formes_GQS_2026' OK | individuel = 3134.0 | final = 3134.0
   ✅ 'Formation_grand_public Nb_formes_IPS_2026' OK | individuel = 33019.0 | final = 33019.0
   ✅ 'Formation_grand_public Nb_formes_IPSEN_2026' OK | individuel = 3218.0 | final = 3218.0

🔎 Vérification DataFrame 16
   ✅ 'Financier Prod_2025' OK | individuel = 92669355.0 | final = 92669355.0
   ✅ 'Financier ResNet_2025' OK | individuel = 2779906.0 | final = 2779906.0
   ✅ 'Financier ResCorrProd_2025' OK | individuel = 3.1278783101257397 | final = 3.1278783101257397
   ✅ 'Financier Prod_2023' OK | individuel = 90179785.55999999 | final = 90179785.55999999
   ✅ 'Financier ResNet_2023' OK | individuel = 5808912.420020002 | final = 5808912.420020002
   ✅ 'Financier ResCorrProd_2023' OK | individuel = 4.858713290389013 | final = 4.858713290389013
   ✅ 'Financier Prod_2024' OK | individuel = 91392120.05999999 | final = 91392120.05999999
   ✅ 'Financier ResNet_2024' OK | individuel = 4605741.17 | final = 4605741.17
   ✅ 'Financier ResCorrProd_2024' OK | individuel = 6.124145527106909 | final = 6.124145527106909
   ✅ 'Financier caf_2025' OK | individuel = 11919220.0 | final = 11919220.0
   ✅ 'Financier TresoBrute_2025' OK | individuel = 146027646.0 | final = 146027646.0
   ✅ 'Financier Mois_AvanceTreso_2025' OK | individuel = 2182.7724484242813 | final = 2182.7724484242813
   ✅ 'Textile Produit_2025' OK | individuel = 19523898.0 | final = 19523898.0
   ✅ 'Secours Produits_DPS_2025' OK | individuel = 9739183.0 | final = 9739183.0

🔎 Vérification DataFrame 17
   ✅ 'Formation_grand_public Produits_2025' OK | individuel = 88457195.10999998 | final = 88457195.10999998

🔎 Vérification DataFrame 18
   ✅ 'Maraude Nb_maraudes_PEGASS' OK | individuel = 7681.0 | final = 7681.0
   ❌ 'Dispositifs_d_urgence Nb_operations' KO | individuel = 1325.0 | final = 67.0
   ✅ 'Dispositifs_d_urgence Nb_exercices' OK | individuel = 60.0 | final = 60.0
   ✅ 'AEO Structure_activite_fixe' OK | individuel = 100.0 | final = 100.0
   ✅ 'AEO Structure_domiciliation_fixe' OK | individuel = 37.0 | final = 37.0
   ✅ 'AEO Structure_ecrivain_public_fixe' OK | individuel = 36.0 | final = 36.0
   ✅ 'Maraude Nb_benevoles_actifs' OK | individuel = 5182.0 | final = 5182.0
   ✅ 'AEO Nb_benevoles_actifs' OK | individuel = 661.0 | final = 661.0

🔎 Vérification DataFrame 19
   ✅ 'PAT Taux_nvx_formes_CRB' OK | individuel = 83.22 | final = 83.22
   ✅ 'PAT conv_pref' OK | individuel = 0.0 | final = 0.0
   ✅ 'PAT conv_prive' OK | individuel = 147.0 | final = 147.0
   ✅ 'PAT conv_public' OK | individuel = 231.0 | final = 231.0
   ✅ 'PAT astreinte' OK | individuel = 0.0 | final = 0.0
   ✅ 'PAT CAI_CHU' OK | individuel = 0.0 | final = 0.0
   ✅ 'PAT CAI' OK | individuel = 216.0 | final = 216.0
   ✅ 'PAT CHU' OK | individuel = 223.5 | final = 223.5
   ✅ 'PAT coup_coeur' OK | individuel = 229.0 | final = 229.0
   ✅ 'PAT Dispos_urgence_nb_exercices' OK | individuel = 325.0 | final = 325.0
   ✅ 'PAT Dispos_urgence_PST' OK | individuel = 0.0 | final = 0.0
   ✅ 'PAT %_TCAU_PSP' OK | individuel = 0.0 | final = 0.0
   ✅ 'PAT Dispos_urgence_tauxformation_TCAU' OK | individuel = 46.14 | final = 46.14000000000001
   ✅ 'PAT Dispos_urgence_tauxformation_PSP' OK | individuel = 34.58 | final = 34.580000000000005
   ✅ 'PAT Dispos_urgence_tauxformation_GQS' OK | individuel = 57.1 | final = 57.099999999999994
   ✅ 'PAT FGP_Nb_formes_PSC' OK | individuel = 116652.0 | final = 116652.0
   ✅ 'PAT FGP_Nb_FPSC' OK | individuel = 1708.0 | final = 1708.0
   ✅ 'PAT FGP_Nb_AGQS' OK | individuel = 1100.0 | final = 1100.0
   ✅ 'PAT FGP_Nb_sessions_PSC' OK | individuel = 10732.0 | final = 10732.0
   ✅ 'PAT FGP_Nb_sessions_GQS' OK | individuel = 3302.0 | final = 3302.0
   ✅ 'PAT FGP_Nb_sessions_IPS' OK | individuel = 3843.0 | final = 3843.0
   ✅ 'PAT FGP_Nb_sessions_IPSEN' OK | individuel = 2718.0 | final = 2718.0
   ✅ 'PAT OCR_Nb_OCR' OK | individuel = 369.0 | final = 369.0
   ✅ 'PAT Maraudes_Nb_maraudes' OK | individuel = 31439.0 | final = 31439.0
   ✅ 'PAT Maraudes_Formes_SOLIDAR2020' OK | individuel = 4779.0 | final = 4779.0
   ✅ 'PAT DPS_Nb_IS' OK | individuel = 11817.0 | final = 11817.0
   ✅ 'PAT DPS_Nb_DPS' OK | individuel = 25777.0 | final = 25777.0
   ✅ 'PAT DPS_CA' OK | individuel = 6496152.0 | final = 6496152.0
   ✅ 'PAT AEO_Nb_aeo_fixe' OK | individuel = 587.0 | final = 587.0
   ✅ 'PAT AEO_Nb_aeo_mobile' OK | individuel = 16.0 | final = 16.0
   ✅ 'PAT conv_total' OK | individuel = 378.0 | final = 378.0

In [ ]:
all_data, all_data_DT = vision_conso(all_data, all_data_DT, year = TARGET_YEAR)

In [ ]:
all_data = ajouter_colonnes_taux(all_data, 'Structure Nb_Benevoles',year = TARGET_YEAR)
all_data_DT = ajouter_colonnes_taux(all_data_DT, 'Structure Nb_Benevoles', year = TARGET_YEAR)

In [ ]:
all_data = ajouter_colonne_somme(all_data, 'AEO Nb_personnes_domiciliees_crf', 'AEO Nb_PA_dispos_mobiles')
all_data_DT = ajouter_colonne_somme(all_data_DT, 'AEO Nb_personnes_domiciliees_crf', 'AEO Nb_PA_dispos_mobiles')

In [ ]:
all_data

,n_structure,n_structure-ratt,type_structure,nom_structure,n_dept,adresse_physique_cp,adresse_physique_commune,adresse_complete,date_demarrage_activite_ben_struct,date_arret_activite_struct,...,Textile Structures_menant_activite,AEO Structures_menant_activite,Formation_grand_public Structures_menant_activite,Dispositifs_d_urgence Taux_formation_TCAU_2026,Dispositifs_d_urgence Taux_formation_TCEO_2026,Dispositifs_d_urgence Taux_formation_PSP_2026,Dispositifs_d_urgence Taux_formation_IRR_2026,Dispositifs_d_urgence Taux_formation_GQS_2026,Structure Taux_formation_CRB_2026,AEO Nb_PA_AEO_AAD
0,2615,2615,ANTENNE LOCALE - AL,AL DE DELLE,90,90100,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",2010-02-08 00:00:00,NaT,...,Action non menée,Activité AEO non menée,Action non menée,0.000000,0.000000,0.000000,0.444444,0.444444,0.000000,<NA>
1,2669,2669,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43,43220,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",2011-01-01 00:00:00,NaT,...,Action non menée,Activité AEO non menée,Action non menée,0.000000,0.000000,0.000000,0.000000,0.500000,0.500000,<NA>
2,2670,2670,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43,43600,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",2011-01-01 00:00:00,NaT,...,Action non menée,Activité AEO non menée,Action non menée,0.000000,0.000000,0.000000,0.666667,1.000000,0.666667,<NA>
3,2671,2671,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43,43300,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",2011-01-01 00:00:00,NaT,...,Action non menée,Activité AEO non menée,Action non menée,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,<NA>
4,2672,2672,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43,43000,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",2011-01-01 00:00:00,NaT,...,Action non menée,Activité AEO non menée,Action non menée,0.000000,0.000000,0.000000,0.172414,0.172414,0.344828,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851,993,993,UNITE LOCALE - UL,UL DE HAUTE PICARDIE,80,80320,CHAULNES,"36 Avenue Roger Salengro, 80320 CHAULNES",1919-12-10 00:00:00,NaT,...,Action menée,Activité AEO non menée,Action non menée,0.000000,0.000000,0.000000,0.095238,0.095238,0.000000,<NA>
852,995,995,UNITE LOCALE - UL,UL DE DOULLENNAIS,80,80600,DOULLENS,"1 Avenue du Général de Gaulle, 80600 DOULLENS",1916-12-10 00:00:00,NaT,...,Action menée,Activité AEO non menée,Action non menée,0.191781,0.000000,0.000000,0.109589,0.191781,0.136986,<NA>
853,996,996,UNITE LOCALE - UL,UL DU PAYS HAMOIS,80,80400,HAM,"25 Boulevard du Général de Gaulle, 80400 HAM",1894-12-10 00:00:00,NaT,...,Action menée,Activité AEO non menée,Action non menée,0.363636,0.000000,0.227273,0.681818,0.727273,0.227273,<NA>
854,998,998,UNITE LOCALE - UL,UL DU VAL D'AVRE,80,80500,MONTDIDIER,"6 Rue AMAND DE VIENNE, 80500 MONTDIDIER",1914-12-10 00:00:00,NaT,...,Action menée,Activité AEO non menée,Action non menée,0.194444,0.018519,0.000000,0.212963,0.250000,0.435185,<NA>
855,999,999,UNITE LOCALE - UL,UL DU PAYS NESLOIS,80,80190,NESLE,"2 bis Avenue Clémenceau, 80190 NESLE",1917-12-10 00:00:00,NaT,...,Action menée,Activité AEO non menée,Action non menée,0.000000,0.000000,0.000000,0.153846,0.153846,0.307692,<NA>

In [ ]:
all_data_DT

,n_structure,n_structure-ratt,type_structure,nom_structure,n_dept,adresse_physique_cp,adresse_physique_commune,adresse_complete,date_demarrage_activite_ben_struct,date_arret_activite_struct,...,Textile Structures_menant_activite,AEO Structures_menant_activite,Formation_grand_public Structures_menant_activite,Dispositifs_d_urgence Taux_formation_TCAU_2026,Dispositifs_d_urgence Taux_formation_TCEO_2026,Dispositifs_d_urgence Taux_formation_PSP_2026,Dispositifs_d_urgence Taux_formation_IRR_2026,Dispositifs_d_urgence Taux_formation_GQS_2026,Structure Taux_formation_CRB_2026,AEO Nb_PA_AEO_AAD
0,10,10,DELEGATION TERRITORIALE - DT,DT DES ALPES MARITIMES,6,6700,ST LAURENT DU VAR,"658 Boulevard JEAN OSSOLA, 06700 ST LAURENT DU...",1986-12-10 00:00:00,NaT,...,9,0,7,0.067422,0.011933,0.023866,0.255370,0.343079,0.116348,<NA>
1,100,100,DELEGATION TERRITORIALE - DT,DT DU VAL D'OISE,95,95460,EZANVILLE,"1 bis Rue Henri Dunant, 95460 EZANVILLE",1986-12-10 00:00:00,NaT,...,9,2,12,0.095238,0.014069,0.084416,0.484848,0.588745,0.228355,1067.0
2,102,102,DELEGATION TERRITORIALE - DT,DT DE LA GUADELOUPE,971,97139,LES ABYMES,"Rue des écoles, 97139 LES ABYMES",1986-12-10 00:00:00,NaT,...,0,0,1,0.087780,0.049914,0.055077,0.282272,0.438898,0.309811,<NA>
3,103,103,DELEGATION TERRITORIALE - DT,DT DE LA MARTINIQUE,972,97200,FORT DE FRANCE,"195 Avenue Leona Gabriel, 97200 FORT DE FRANCE",1986-12-10 00:00:00,NaT,...,0,1,1,0.148676,0.036660,0.057026,0.248473,0.319756,0.234216,<NA>
4,104,104,DELEGATION TERRITORIALE - DT,DT DE NOUVELLE CALEDONIE,988,98800,NOUMEA,"26 Rue DU DOCTEUR GEORGES COLLARD, 98800 NOUMEA",1956-12-10 00:00:00,NaT,...,1,1,1,0.144737,0.039474,0.136842,0.292105,0.428947,0.281579,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,94,94,DELEGATION TERRITORIALE - DT,DT DE L'YONNE,89,89300,JOIGNY,"Rue JEAN FRANÇOIS DE LA PÉROUSE, 89300 JOIGNY",1986-12-10 00:00:00,NaT,...,5,3,1,0.077307,0.004988,0.022444,0.246883,0.326683,0.234414,<NA>
104,95,95,DELEGATION TERRITORIALE - DT,DT DU TERRITOIRE DE BELFORT,90,90000,BELFORT,"15 Avenue du Général Sarrail, 90000 BELFORT",1986-12-10 00:00:00,NaT,...,1,0,1,0.057143,0.000000,0.038095,0.409524,0.542857,0.057143,<NA>
105,96,96,DELEGATION TERRITORIALE - DT,DT DE L'ESSONNE,91,91080,EVRY COURCOURONNES,"12 Rue Jean Mermoz, 91080 EVRY COURCOURONNES",1986-12-10 00:00:00,NaT,...,10,4,13,0.294165,0.021583,0.063949,0.288569,0.505196,0.330136,<NA>
106,97,97,DELEGATION TERRITORIALE - DT,DT DES HAUTS DE SEINE,92,92100,BOULOGNE BILLANCOURT,"14 Rue DE L'EST, 92100 BOULOGNE BILLANCOURT",1986-12-10 00:00:00,NaT,...,13,12,27,0.245466,0.058948,0.097340,0.517836,0.651149,0.327690,4385.0
107,99,99,DELEGATION TERRITORIALE - DT,DT DU VAL DE MARNE,94,94450,LIMEIL BREVANNES,"2 Rue ALBERT GARRY, 94450 LIMEIL BREVANNES",1986-12-10 00:00:00,NaT,...,12,2,17,0.250875,0.022170,0.038506,0.467911,0.638856,0.394399,<NA>

## Ajouter une colonne seulement

Repartir des données existantes

In [ ]:
# all_data_DT = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg/').worksheet('DT'))
# all_data_UL = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg/').worksheet('UL'))

Remplacement colonnes

In [ ]:
# df_add_DT = df_DT.copy() # Ici ajouter les dataframes à ajouter 
# df_add_UL = df_UL.copy()
# df_list = {'DT' : [df_add_DT], 'UL' : [df_add_UL]}




# # Remplacement des données
# for dt_add in df_list['DT']:
#     all_data_DT = ajouter_au_all_data(all_data_DT, dt_add, nom_bloc="", cle="n_structure")

# for ul_add in df_list['UL']:
#     all_data_UL = ajouter_au_all_data(all_data_UL, ul_add, nom_bloc="", cle="n_structure")

# Enregistrement des données

In [ ]:
# Entregistrement du DataFrame
# save_dataframe_to_sheet("1pmEUcLvVOK3t7TWmXL6cN0uTWJ9kPgIwd2x3hy14Alk", gspread_client, all_data, sheet_name = 'UL')
# save_dataframe_to_sheet("1pmEUcLvVOK3t7TWmXL6cN0uTWJ9kPgIwd2x3hy14Alk", gspread_client, all_data_DT, sheet_name = 'DT')

# save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", client, df_rattachement_court)