In [1]:
# !git config --global user.email "clement.dilasser@croix-rouge.fr"
# !git clone https://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@github.com/clementsouk-aloun-dot/Code-PAT.git

In [2]:
# !gcloud auth application-default login

In [3]:
# !pip install PyPDF2
# !pip install reportlab
# !pip install PyMuPDF tools
# !pip install xlsxwriter

# Imports

In [4]:
# 🔹 Compatibilité Google Colab pour code local
try:
    from google.colab import drive, files
    from google.colab import auth
except ModuleNotFoundError:
    # Crée un faux module google.colab pour que le code ne plante pas
    import types
    drive = types.SimpleNamespace(mount=lambda path: print(f"[Mock] drive.mount({path})"))
    files = types.SimpleNamespace(upload=lambda: print("[Mock] files.upload()"))
    auth = types.SimpleNamespace(authenticate_user=lambda: print("[Mock] auth.authenticate_user()"))

In [5]:
import traceback
import sys
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import seaborn as sns
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import re
import shutil
import zipfile
from google.auth import default
from google.cloud import bigquery
import unicodedata
import torch
from sentence_transformers import SentenceTransformer, util
import gc
from functools import reduce

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Imports des fichiers .py

In [6]:
from utils import *

sys.path.append(os.path.abspath("./data")) 

from adherent import *
from alim import *
from domifa import *
from financier import *
from gaia import *
from impact import *
from manuelles import *
from maraude import *
from maraude_manuel import *
from base_contact import*
from mobilite import *
from nomination import *
from pegass import *
from dps import *
from main_merge import *

sys.path.append(os.path.abspath("./checks")) 

from helpers import *

# AUTHENTIFICATION

In [7]:
json_key_bq_url = r'service_account\s_acc.json'

with open(json_key_bq_url, 'r') as f:
    json_key_bq = json.load(f)

SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly','https://www.googleapis.com/auth/bigquery']

credentials_bq = service_account.Credentials.from_service_account_info(json_key_bq, scopes=SCOPES)

In [8]:
PROJECT_ID = "crf-pat"
client = bigquery.Client(project=PROJECT_ID, credentials = credentials_bq)

In [9]:
# Etape 0 : Préparation de l'environnement

CREDENTIALS_JSON_url = r'service_account\old.json'

with open(CREDENTIALS_JSON_url, 'r') as f:
    CREDENTIALS_JSON = json.load(f)
SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly']


# Authentification
credentials = service_account.Credentials.from_service_account_info(CREDENTIALS_JSON, scopes=SCOPES)

# Initialisation des services
slides_service = build('slides', 'v1', credentials=credentials)
drive_service = build('drive', 'v3', credentials=credentials)
gspread_client  = gspread.authorize(credentials)

# Variables globales

In [10]:
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

In [11]:
mapping_df

,Source,nom_table,nom_variable,rename,Description,Type de valeurs,Présent extract DSI ?,Commentaires
0,Annuaire structure,AS_Actions_par_structure,N_structure,n_structure,Identifiant de la structure,INT,Optionnel,NaN
1,Annuaire structure,AS_Actions_par_structure,Type_de_lien,action_statut,Action menée/ Non menée,VARCHAR,Optionnel,NaN
2,Annuaire structure,AS_Actions_par_structure,Groupe_action,groupe_action_ben,Regroupement / famille d’actions,VARCHAR,Optionnel,NaN
3,Annuaire structure,AS_Actions_par_structure,Action,lib_action_ben,Libellé de l’action précise,VARCHAR,Optionnel,NaN
4,Annuaire structure,AS_Actions_par_structure,Date_demarrage_action_dans_la_structure,date_demarrage_action_structure,Date à laquelle l’action a effectivement démar...,DATE,Optionnel,NaN
...,...,...,...,...,...,...,...,...
242,GAIA ?,crf_pat_2025_rattachement_action,action_menee_date_fin,NaN,NaN,DATE,Présent & bon format,NaN
244,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_nivol_fk,NaN,NaN,STR,Présent & bon format,NaN
245,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_structure_id_fk,NaN,NaN,INT,Présent & bon format,NaN
246,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_date_debut,NaN,NaN,DATE,Présent & bon format,NaN
247,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_date_fin,NaN,NaN,DATE,Présent & bon format,NaN

# CHARGEMENT DE TOUTES LES DONNEES PAR TABLE

## 0. Ref_structure

In [12]:
df_ref_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw/').worksheet('Feuille 1'))

In [13]:
df_ref_structure = renommer_par_nom_table(df_ref_structure, "AS_Informations_structures", mapping_df)
df_ref_structure['n_structure'] = df_ref_structure['n_structure'].astype(int)
df_ref_structure = df_ref_structure[df_ref_structure["type_structure"].isin(["UNITE LOCALE - UL", "DELEGATION TERRITORIALE - DT", 'IMPLANTATION LOCALE HORS AL - IL', 'ANTENNE LOCALE - AL','INSTANCES NATIONALES - IN'])]
df_ref_structure.head()

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,Structure_de_rattachement,Structure_de_rattachement.1,DT_de_rattachement,lon,lat
0,5,DELEGATION TERRITORIALE - DT,DT DE L'AIN,1000.0,01053,BOURG EN BRESSE,"3 Rue HENRI DUNANT, 01000 BOURG EN BRESSE",1,1986-12-10 00:00:00,NaT,4457 - DR AUVERGNE RHONE ALPES,DT 5,5 - DT DE L'AIN,5.228792,46.212687
1,109,UNITE LOCALE - UL,UL DU BASSIN BURGIEN,1000.0,01053,BOURG EN BRESSE,"1 Avenue DES BELGES, 01000 BOURG EN BRESSE",1,1870-12-10 00:00:00,NaT,5 - DT DE L'AIN,UL 109,5 - DT DE L'AIN,5.231911,46.207112
2,135,UNITE LOCALE - UL,UL DES PAYS DE LA VEYLE,1540.0,01457,VONNAS,"Rue ANNE MARIE CROLET, 01540 VONNAS",1,1986-12-10 00:00:00,NaT,5 - DT DE L'AIN,UL 135,5 - DT DE L'AIN,4.988173,46.215632
3,3733,UNITE LOCALE - UL,UL DU VAL DE SAONE,1190.0,01305,PONT DE VAUX,"19 Avenue ADRIEN THIERRY, 01190 PONT DE VAUX",1,2008-06-02 00:00:00,NaT,5 - DT DE L'AIN,UL 3733,5 - DT DE L'AIN,4.940884,46.430076
4,3873,UNITE LOCALE - UL,UL DE PORTE DE LA DOMBES,1600.0,01427,TREVOUX,"94 Allée ANTOINE FINAZ, 01600 TREVOUX",1,2011-02-03 00:00:00,NaT,5 - DT DE L'AIN,UL 3873,5 - DT DE L'AIN,4.788434,45.937566

In [14]:
df_ref_structure_DT = df_ref_structure[df_ref_structure['nom_structure'].str.contains('DT')].astype(str)
df_ref_structure_DT['n_structure'] = df_ref_structure['n_structure'].astype(int)

### 0.1 rattachement_court

In [15]:
rattachement_court = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU/edit?usp=sharing').worksheet('Feuille 1'))

## 1. GAIA

In [ ]:
# Define target date and year once for all functions
TARGET_DATE = "2025-12-31"
TARGET_YEAR = 2025

In [ ]:
df_gaia_rattachement_benevole = clean_gaia(client, df_ref_structure)

df_nivols_gaia = import_table_GAIA_date_fixe(client, target_date=TARGET_DATE)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 2. PEGASS

In [17]:
df_ref_activite_benevole, df_pegass_activite, df_pegass_activite_seance, df_pegass_activite_seance_inscription,ref_structure1,df_rattachement_court,df_ref_action_groupe_action = import_tables_PEGASS(client)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 3. NOMINATION

In [18]:
df_ref_nomination, df_nomination = clean_nomination(client, df_ref_structure)

## 4. IMPACT

In [ ]:
df_ref_impact, df_impact = clean_impact(client, df_ref_structure)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 5. Données financières

In [20]:
financier_2023_2024 = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c')
financier_2025 = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1esF1OgTGD_HtkJVZq0ZDsqXs-7rzeRK2NMp0fMabMpM/')

Financier DPS & FGP & Textile

In [21]:
financier_DPS = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1PcNXO-Fv8BGzGv-GKzFxBoEIfYl8TWAsAU2wpezH7_Y/').worksheet('Données'), evaluate_formulas=True)
financier_textile = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1k6FKahQJj0JIvc3qGimqRCt7Y9Ow1vrCRwp1Li_hmUA/').worksheet('Données'), evaluate_formulas=True)

In [22]:
financier_FGP = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13J2zfbmLTILtGYtE_sM-ME8B0pNEwBeGJ1Gg5vKLeOc/').worksheet('DT_Prod'))

## 6. Mobilité

In [23]:
mobilite = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1dvxT58WR-FqdT-4r-A9ca4vaA9FG7IXHJJaTbnjio8A/')

In [24]:
df_mobilite = filtres_mobilite(mobilite,mapping_df, df_ref_structure)

## 7. Données manuelles

### 7.1 OCR

In [25]:
df_OCR = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ccRoyPycFDwvQvacvmHjfE87LtnlzUgtoRbITkC0pVQ/').worksheet('Feuille 1'), evaluate_formulas=True)

### 7.2 PST

In [26]:
df_PST = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1yifNna4Hsn5RihkRg50g9h1yKjuRjfolrjsWonEHnrQ').worksheet('Données'), evaluate_formulas=True)

### 7.3 Déclenchements

In [27]:
df_declenchement = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1y9jehT5fStcEWCF0pxAP7BdiI62VY3JM_hQzFftbcZA').worksheet('Feuille 1'), evaluate_formulas=True)

### 7.4 Redcall

In [28]:
df_redcall = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1EQzq0K8RY2Liyq-jtggX0bTlnOk9cwUTmf4t6c5_CiI').worksheet('structure-stats_2025-01-01_2025-12-31_min-1 (1)'), evaluate_formulas=True)

### 7.5 CHAI CHU CMCC

In [29]:
df_CAICHUCMCC = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/12nZY2leRCMn71NGAEUUtA0Pes598gOfeufDStxSCcnY').worksheet('Toutes données'), evaluate_formulas=True)

### 7.6 Conventions

In [30]:
df_conventions = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1u6E6SUydE7zB1bbcjPzjDt9m5YtGszl0MATPbDQeOhg').worksheet('Feuille 1'), evaluate_formulas=True)

### 7.7 Textile

In [31]:
df_raw_Textile_c = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1QYuKZo5lVI0HN4BWtk0v7bVFY2a2p4c72a0gU0ltWac/').worksheet('Liste des PAV'), evaluate_formulas=True)

#df_raw_ProdResTextile_c = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1l7KMjiav3usmLVJIbE2uENfNQCeQuxVeU1h13Cep3qk/",sheet_name="Compil Détail",header_row=7)

### 7.8 DOMIFA

In [32]:
df_domiciliation, df_rattachement_court = clean_domifa(client,df_ref_structure)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\utils.py:162: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ref['nom_structure'] = df_ref['nom_structure'].fillna('').astype(str)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1072.07it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

### 7.9 Alim

In [33]:
df_alim = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1bk_ktsT9hBPJS5EY70teq80NzOs_cm3JfrRkX4AYTF4/edit?gid=0#gid=0")

✅ Chargement des données réalisées
    Sheet : Liste U2A a jour - 21/01/2026
    Feuille 1 : Feuille 1 (628 lignes et 10 colonnes)

### 7.10 DPS

In [34]:
df_dps_source = df_conventions.copy()

### 7.11 Adherent

In [35]:
df_adherent = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1hsk3Xp2IrwnUs59sgWjhT9E9vEsw4TN2WT3nKejlBOE/edit?usp=drive_link")

✅ Chargement des données réalisées
    Sheet : exportAdherents (1) (1)
    Feuille 1 : exportAdherents (1) (1).csv (48300 lignes et 25 colonnes)

### 7.12 Préparation

In [36]:
# DPS a pour source le fichier conventions
df_dps = clean_dps(df_dps_source)

df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions, df_raw_Textile, df_duo_clean = clean_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement, df_redcall, df_CAICHUCMCC, df_conventions, df_raw_Textile_c, df_ref_structure)
df_alim = clean_alim(df_alim)
df_adherent = clean_adherent(df_adherent)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\dps.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Departement"] = df["Departement"].str.replace(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\manuelles.py:79: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['Grand Total', 'Exercice']] = df[['Grand Total', 'Exercice']].fillna(0)
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\manuelles.py:147: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Département"] = df["Département"].str.replace(

Point d'apport possible :  ['Boutique - La Boutique' 'Conteneur' 'Vestiaire' 'Boutique  - Mobile'
 'Autres' 'Boutique - Bébé' 'Boutique - Chez Henry' 'Ressourcerie CRi'
 'Boutique - Recylcerie / Meuble' 'Déchetterie' 'conteneur']
Unique values in 'Année de l'adhésion du contact': [2025]
Data type of 'Année de l'adhésion du contact': int64
Taille du DataFrame après suppression des doublons : (47424, 4)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\manuelles.py:262: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Departement"] = df["Departement"].str.replace(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\adherent.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_adherent["Année de l'adhésion du contact"] = pd.to_numeric(df_adherent["Année de l'adhésion du contact"], errors='coerce')

## 8. Maraudes

In [37]:
# 1) import
df_maraude, df_rattachement_court = import_maraude(client)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

In [38]:
#~rattachement successif
ref_structure_m , c , rattachement_successif, df_maraude = apply_rattachement_successif(df_ref_structure, df_maraude)

In [39]:
# 3) ✅ Filtre : on CHANGE df_maraude ici
df_maraude = filter_maraude_on_ref_structure(
    df_maraude,
    ref_structure_m,
    col_maraude="maraude_structure_id_fk",
    col_ref="n_structure",
    verbose=True
)

📌 Filtre structures ref: 114,538/116,527 lignes conservées (supprimées: 1,989).

In [40]:
# 3) clean/prep
df_nb_personnes_rencontrees_sigma, df_Nb_maraudes_SIGMA = clean_maraudes(df_maraude)

Données manuelles

In [41]:
#Import données maraude manuelles
df_Maraude_donnees_manuelles, df_rattachement_court_m = Import_Maraude_manuel(client,df_ref_structure)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2004.65it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

## 9. Base Contact

In [ ]:
df_formation_session_resultat, df_formation_count_session_2025, df_formation_session_resultat_fpg = clean_base_contact(client, df_ref_structure, target_date=TARGET_DATE)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

# FUSION DES TABLES

## 1. Fusion NOMINATION

In [ ]:
df_NOMINATION = fusion_nomination(df_nomination, df_ref_nomination, target_year=TARGET_YEAR)

## 2. Fusion IMPACT

In [ ]:
df_IMPACT = fusion_impact(df_impact, df_ref_impact, target_year=TARGET_YEAR)

Nombre de lignes après filtre 2025 : 388817

## 3. Fusion DOMIFA

In [45]:
df_domiciliation = pd.merge(df_domiciliation, df_rattachement_court, on='n_structure', how="left") #a conserver dans le code principal

# Calcul des indicateurs

## PEGASS

In [46]:
pegass_output = calcul_PEGASS_indicateurs(df_ref_structure,
    ref_structure1,
    df_ref_action_groupe_action,
    df_ref_activite_benevole,
    df_pegass_activite,
    df_pegass_activite_seance,
    df_pegass_activite_seance_inscription,
    df_rattachement_court,
    df_nivols_gaia
)

In [47]:
df_pegass_ben_activite_synthetique = pegass_output["df_pegass_ben_activite_synthetique"]
Indics_pegass_DT = pegass_output["Indics_pegass_DT"]
Indics_pegass_DT = add_nb_benevoles_DT_distincts(
    Indics_pegass_DT,
    df_pegass_ben_activite_synthetique,
    df_rattachement_court
)

## GAIA

In [ ]:
nb_benevoles = indicateurs_gaia(df_gaia_rattachement_benevole, target_date=TARGET_DATE)
nb_nvx_benevoles = indicateurs_gaia_nvx(df_gaia_rattachement_benevole, target_date=TARGET_DATE)
nb_benevoles_DT = indicateurs_gaia_DT(nb_benevoles,rattachement_court)
nb_nvx_benevoles_DT = indicateurs_gaia_nvx_DT(nb_nvx_benevoles, rattachement_court)

Nombre de structures agrégées : 836
Nombre total de bénévoles uniques : 82268
Nombre de structures agrégées : 757
Nombre total de nouveaux bénévoles uniques : 16896
Nombre de structures agrégées : 108
Nombre total de bénévoles uniques DT : 80764
Nombre de structures agrégées : 106
Nombre total de nouveaux bénévoles uniques DT : 16653

## NOMINATION

- RTAEO & RLAEO
- RTOCR & RLOCR

In [49]:
referents_AEO = indicateurs_nomination_AEO(df_NOMINATION,df_nivols_gaia, annee=2025)
referents_OCR = indicateurs_nomination_OCR(df_NOMINATION,df_nivols_gaia, annee=2025)
referents_AEO_DT = indicateurs_nominationAEO_DT(referents_AEO, rattachement_court)
referents_OCR_DT = indicateurs_nominationOCR_DT(referents_OCR, rattachement_court)

Nombre de structures agrégées : 23
Nombre total de responsables AEO : 36
Nombre de structures agrégées : 20
Nombre total de responsables OCR : 20
Nombre de structures agrégées : 15
Nombre total de responsables AEO DT : 36
Nombre de structures agrégées : 15
Nombre total de responsables OCR DT : 20

## IMPACT

- Nombre d'agréments territoriaux (Dispos d'urgence)
- Nombre de personnes prises en charge (Dispos d'urgence)

In [50]:
IMPACT_ppc = indicateurs_impact_ppc(df_IMPACT)
IMPACT_agrementAB = indicateurs_impact_agrementAB(df_IMPACT)
IMPACT_agrementDPS = indicateurs_impact_agrementDPS(df_IMPACT)
IMPACT_ppc_DT = indicateurs_IMPACTppc_DT(IMPACT_ppc, rattachement_court)
IMPACT_agrementAB_DT = indicateurs_IMPACTagrementAB_DT(IMPACT_agrementAB, rattachement_court)
IMPACT_agrementDPS_DT = indicateurs_IMPACTagrementDPS_DT(IMPACT_agrementDPS, rattachement_court)

Nombre de lignes après filtre urgences : 1206
Nombre de structures agrégées : 111
Somme totale Dispositifs d'urgence - Nb personnes prises en charge : 15709
Nombre de structures agrégées : 77
Somme totale agréments AB : 0
Nombre de structures agrégées : 49
Somme totale agréments DPS : 0
Nombre de structures agrégées : 61
Somme totale personnes prises en charge DT : 15709
Nombre de structures agrégées : 59
Somme totale agréments AB DT : 0
Nombre de structures agrégées : 38
Somme totale agréments DPS DT: 0

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\impact.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\impact.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\impact.py:151: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (

## Financier

In [51]:
df_financier, df_financier_DT,financier = import_clean_donnees_financieres_bigquery(financier_2025,financier_2023_2024,financier_textile,financier_DPS,df_ref_structure, mapping_df)

In [52]:
# Vérifications données financières
#verifications_financiers(df_financier, df_financier_DT, df_ref_structure, financier, financier_2025)

In [53]:
df_financier_FGP_DT = indicateur_financier_FGP_2024(financier_FGP, df_ref_structure)
#df_inancier_FGP_DT = financier_FGP_DT(df_financier_FGP, rattachement_court)

## Mobilité


Indicateurs qui nécessitent seulement les données mobilité :

- Nb de structures menant une activité AEO/AAD mobile
- Nombre de personnes accompagnées par des dispositifs AEO/AAD mobiles
<br>
Indicateurs qui nécessitent une fusion avec données AEO/AAD :

- Nombre de bénévoles impliqués dans les activités AEO ou AAD
- Nombre de bénévoles impliqués dans les activités AEO ou AAD

In [54]:
df_mobilite_DT = indicateurs_mobilite(df_mobilite, df_ref_structure, 'DT_de_rattachement')
df_mobilite_DT_UL = indicateurs_mobilite(df_mobilite, df_ref_structure, 'n_structure')

In [55]:
verifier_colonne_structure(df_mobilite_DT, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [56]:
verifier_colonne_structure(df_mobilite_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## Données manuelles

In [57]:
df_OCR_Nb_deployees, df_Dispositifs_d_urgence_PST, df_declenchement3, df_redcall2, df_CAICHUCMCC_VF, df_conventions2, df_raw_Textile, df_DUO = indicateurs_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions, df_raw_Textile, df_duo_clean, df_ref_structure)

Nb_OCR_DT,RedCall_DT = OCR_RedCall_DT(df_OCR_Nb_deployees, df_redcall2, rattachement_court)
df_Textile_DT = Textile_DT(df_raw_Textile, rattachement_court)

# ALIM
df_alim_U2A_sans_doublons, df_alim_epicerie_sociale, df_alim_accueil_alimentaire, df_alim_crsr = indicateurs_alim(df_alim, df_ref_structure)
df_alim_U2A_DT, df_alim_epicerie_sociale_DT, df_alim_accueil_alimentaire_DT, df_alim_crsr_DT = indicateurs_alim_DT(df_alim_U2A_sans_doublons, df_alim_epicerie_sociale, df_alim_accueil_alimentaire, df_alim_crsr, rattachement_court)

# ADHERENT
df_adherent = indicateurs_adherent(df_adherent, df_ref_structure)
df_adherent_DT = indicateurs_adherent_DT(df_adherent, rattachement_court)

# DOMIFA
df_personnes_domiciliees_struct, df_personnes_domiciliees_DT = indicateurs_domifa(df_domiciliation)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1442.53it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1488.14it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1560.20it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1555.85it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1675.15it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1568.25it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2057.05it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [58]:
verifier_colonne_structure(df_OCR_Nb_deployees, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Dispositifs_d_urgence_PST, "n_structure", df_ref_structure)
verifier_colonne_structure(df_declenchement3, "n_structure", df_ref_structure)
verifier_colonne_structure(df_redcall2, "n_structure", df_ref_structure)
verifier_colonne_structure(df_CAICHUCMCC_VF, "n_structure", df_ref_structure)
verifier_colonne_structure(df_conventions2, "n_structure", df_ref_structure)
verifier_colonne_structure(df_DUO, "n_structure", df_ref_structure)


# TEXTILE
verif_textile(df_raw_Textile_c, df_raw_Textile, df_Textile_DT, df_ref_structure, rattachement_court)

# DOMIFA

verifs_domifa(client, df_personnes_domiciliees_struct, df_personnes_domiciliees_DT, df_ref_structure, df_rattachement_court)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.
✅ df_Textile_DT est bien calculé (suomme de l indicateur == au nombre de lignes des données)
✅ df_Textile_DT est bien calculé (suomme de l indicateur == au nombre de lignes des données)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.
#1 Vérification qu on a bien la même somme de personnes domiciliées entre le fichier de base et le fichier df_personnes_domiciliees_struct
OK ✅ : sommes égales (30833) entre table struct[AEO Nb_personnes_domiciliees_crf] et table source[Nombre total de domiciliations]
#2 Vérification qu on a bien la même somme de personnes domiciliées entre le fichier structure et le fichier df_personnes_domiciliees_DT
OK ✅ : sommes égales (30833) entre table struct[AEO Nb_personnes_domiciliees_crf] et table DT[AEO Nb_personnes_domiciliees_crf]
#3 on vérifie que l ensemble des N° structure du nb personnes domicilées correspnd au ref structure

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.
#4 on vérifie que l ensemble des N° DTdu nb personnes domicilées correspnd au ref structure

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.
#5 On verifie que le nb de structure du df_personnes_domiciliees_struct est bien égal au nombre de ligne du df source
 ✅ n ligne = 30

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## Maraudes

In [59]:
(
    df_Nb_maraudes_SIGMA_struct,
    df_Nb_maraudes_SIGMA_DT,
    df_nb_contacts_SIGMA_struct,
    df_nb_contacts_SIGMA_DT,
    df_personnes_diff_base,                 # <- nouveau (base par bénéficiaire)
    df_nb_personnes_rencontrees_SIGMA_struct,
    df_nb_personnes_rencontrees_SIGMA_DT
) = indicateurs_maraude(
    df_nb_personnes_rencontrees_sigma,
    df_Nb_maraudes_SIGMA,
    df_rattachement_court
)

In [60]:
verifier_colonne_structure(df_Nb_maraudes_SIGMA_struct, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Nb_maraudes_SIGMA_DT, "DT_de_rattachement", df_ref_structure)
verifier_colonne_structure(df_nb_contacts_SIGMA_struct, "n_structure", df_ref_structure)
verifier_colonne_structure( df_nb_contacts_SIGMA_DT, "DT_de_rattachement", df_ref_structure)
verifier_colonne_structure(df_nb_personnes_rencontrees_SIGMA_struct, "n_structure", df_ref_structure)
verifier_colonne_structure(df_nb_personnes_rencontrees_SIGMA_DT, "DT_de_rattachement", df_ref_structure)

df_maraude_verif= prep_nb_personnes_rencontrees_sigma(df_maraude, filtre_annee_fn=None)

df_maraude_verif= add_nb_personnes(df_maraude_verif,
                     out_col="nb personnes",
                     cols=None,
                     col_typologie="maraude_rencontre_typologie")

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [61]:
run_verif_maraude(
    df_Nb_maraudes_SIGMA_struct=df_Nb_maraudes_SIGMA_struct,
    df_Nb_maraudes_SIGMA_DT=df_Nb_maraudes_SIGMA_DT,
    df_nb_contacts_SIGMA_struct=df_nb_contacts_SIGMA_struct,
    df_nb_contacts_SIGMA_DT=df_nb_contacts_SIGMA_DT,
    df_nb_personnes_rencontrees_SIGMA_struct=df_nb_personnes_rencontrees_SIGMA_struct,
    df_nb_personnes_rencontrees_SIGMA_DT=df_nb_personnes_rencontrees_SIGMA_DT,
    df_Nb_maraudes_SIGMA=df_Nb_maraudes_SIGMA,
    df_maraude_verif=df_maraude_verif,
    df_personnes_diff_base=df_personnes_diff_base,
)

====================
VERIF MARAUDE
====================

✅ #1 Nb maraudes (Struct vs DT) - OK : somme(df_left['Maraude Nb_maraudes_SIGMA']) = somme(df_right['Maraude Nb_maraudes_SIGMA']) (total=7910)
✅ #2 Nb contacts (Struct vs DT) - OK : somme(df_left['Maraude Nb_contacts']) = somme(df_right['Maraude Nb_contacts']) (total=127385)
✅ #3 Nb personnes rencontrées (Struct vs DT) - OK : somme(df_left['Maraude Nb_personnes_rencontrees']) = somme(df_right['Maraude Nb_personnes_rencontrees']) (total=102063)
✅ #4 OK : somme maraudes structure (7910) = len(df_Nb_maraudes_SIGMA) (7910)
✅ #5 OK : personnes différentes rencontrées — somme df_base = 102063 = somme df_struct = 102063
✅ #6 OK Somme contact  OK : somme 'Maraude Nb contacts struct' df struct = somme Nb contacts df maraude verif = 127385

Données manuelles maraude

In [62]:
#Calcul données maraude manuelles
df_Maraude_donnees_manuelles_DT_2, df_Maraude_donnees_manuelles_structure_2 = calcul_indic_maraude_manuelles(df_ref_structure, df_Maraude_donnees_manuelles, df_rattachement_court_m)

#Verif données maraude manuelles
check_maraude_sums( df_Maraude_donnees_manuelles, df_Maraude_donnees_manuelles_DT_2)
check_maraude_sums( df_Maraude_donnees_manuelles, df_Maraude_donnees_manuelles_structure_2)

✅ OK — sommes identiques (diff = 0)
✅ OK — sommes identiques (diff = 0)

Maraude Nb_maraudes_SIGMA           0
Maraude Nb_personnes_rencontrees    0
Maraude Nb_contacts                 0
dtype: Int64

## Base contact

In [63]:
# Indicateurs
indicateurs_base_contact, indicateurs_base_contact_DT = indicateurs_base_contact(client, df_formation_session_resultat, df_formation_count_session_2025, df_formation_session_resultat_fpg, df_ref_structure)
indicateurs_base_contact_DT = correction_indic_BC_DT(df_ref_structure, indicateurs_base_contact, indicateurs_base_contact_DT)

===== Vérification des codes =====

Indicateur : AEO Nb_AAD
  Codes attendus : {'AAD'}
  Codes trouvés  : {'AAD'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_TCAU_2025
  Codes attendus : {'TCAU', 'ETCAU'}
  Codes trouvés  : {'TCAU', 'ETCAU'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_TCEO_2025
  Codes attendus : {'TCEO', 'ESE'}
  Codes trouvés  : {'TCEO', 'ESE'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_PSP_2025
  Codes attendus : {'PSP'}
  Codes trouvés  : {'PSP'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_IRR_2025
  Codes attendus : {'IRR', 'IRRA', 'IRRJ'}
  Codes trouvés  : {'IRR', 'IRRA', 'IRRJ'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_GQS_2025
  Codes attendus : {'RECPSE2', 'PSC IRR', 'RATPSE2', 'PSE AGSU', 'APTE PSE1', 'FCPSE1', 'PSE1', 'FIPS2', 'GQS AC', 'FCPSE', 'PSE2', 'FCPSC', 'EPSC', 'FCPSE2', 'FIPS', 'PSC1 IRR', 'PSC1', 'PSC', 'GQS', 'PSC1 AC', 'PSC AC', 'RATPSE1', 'EPSC1', 'PSE', 'RECPSC1', 'RECPSE1'}
  Codes trouvés  : {'RECPSE2', 'PSC IRR', 'RATPSE2', 'APTE PSE1', 'FCPSE1', 'PSE1', 'FIPS2', 'FCPSE', 'PSE2', 'FCPSC', 'EPSC', 'FCPSE2', 'FIPS', 'PSC1 IRR', 'PSC1', 'PSC', 'GQS', 'PSC1 AC', 'PSC AC', 'RATPSE1', 'EPSC1', 'PSE', 'RECPSC1', 'RECPSE1'}
  Codes manquants: {'PSE AGSU', 'GQS AC'}

Indicateur : Structure Nb_formes_CRB_2025
  Codes attendus : {'VI', 'ECRB', 'CRB'}
  Codes trouvés  : {'VI', 'ECRB', 'CRB'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:130: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
AEO Nb_AAD : 1287
Dispositifs_d_urgence Nb_formes_TCAU_2025 : 11846
Dispositifs_d_urgence Nb_formes_TCEO_2025 : 1791
Dispositifs_d_urgence Nb_formes_PSP_2025 : 5037
Dispositifs_d_urgence Nb_formes_IRR_2025 : 23834
Dispositifs_d_urgence Nb_formes_GQS_2025 : 35592
Structure Nb_formes_CRB_2025 : 20551

===== Vérification des codes =====

Indicateur : AEO Nb_AAD
  Codes attendus : {'AAD'}
  Codes trouvés  : {'AAD'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_TCAU_2025
  Codes attendus : {'TCAU', 'ETCAU'}
  Codes trouvés  : {'TCAU', 'ETCAU'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_TCEO_2025
  Codes attendus : {'TCEO', 'ESE'}
  Codes trouvés  : {'TCEO', 'ESE'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_PSP_2025
  Codes attendus : {'PSP'}
  Codes trouvés  : {'PSP'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_IRR_2025
  Codes attendus : {'IRR', 'IRRA', 'IRRJ'}
  Codes trouvés  : {'IRR', 'IRRA', 'IRRJ'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Nb_formes_GQS_2025
  Codes attendus : {'RECPSE2', 'PSC IRR', 'RATPSE2', 'PSE AGSU', 'APTE PSE1', 'FCPSE1', 'PSE1', 'FIPS2', 'GQS AC', 'FCPSE', 'PSE2', 'FCPSC', 'EPSC', 'FCPSE2', 'FIPS', 'PSC1 IRR', 'PSC1', 'PSC', 'GQS', 'PSC1 AC', 'PSC AC', 'RATPSE1', 'EPSC1', 'PSE', 'RECPSC1', 'RECPSE1'}
  Codes trouvés  : {'RECPSE2', 'PSC IRR', 'RATPSE2', 'APTE PSE1', 'FCPSE1', 'PSE1', 'FIPS2', 'FCPSE', 'PSE2', 'FCPSC', 'EPSC', 'FCPSE2', 'FIPS', 'PSC1 IRR', 'PSC1', 'PSC', 'GQS', 'PSC1 AC', 'PSC AC', 'RATPSE1', 'EPSC1', 'PSE', 'RECPSC1', 'RECPSE1'}
  Codes manquants: {'PSE AGSU', 'GQS AC'}

Indicateur : Structure Nb_formes_CRB_2025
  Codes attendus : {'VI', 'ECRB', 'CRB'}
  Codes trouvés  : {'VI', 'ECRB', 'CRB'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:130: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
AEO Nb_AAD : 1287
Dispositifs_d_urgence Nb_formes_TCAU_2025 : 11846
Dispositifs_d_urgence Nb_formes_TCEO_2025 : 1791
Dispositifs_d_urgence Nb_formes_PSP_2025 : 5037
Dispositifs_d_urgence Nb_formes_IRR_2025 : 23834
Dispositifs_d_urgence Nb_formes_GQS_2025 : 35592
Structure Nb_formes_CRB_2025 : 20551

===== Vérification des codes =====

Indicateur : Maraude Nb_SOLIDAR
  Codes attendus : {'SOLIDAR', 'SOLIDAR1', 'ESOLIDAR2026', 'SOLIDAR2020', 'SOLIDAR2', 'PASSOLIDAR2020'}
  Codes trouvés  : {'SOLIDAR', 'SOLIDAR1', 'ESOLIDAR2026', 'SOLIDAR2020', 'SOLIDAR2', 'PASSOLIDAR2020'}
  Codes manquants: set()

Indicateur : Maraude Nb_SOLIDAR2020
  Codes attendus : {'ESOLIDAR2026', 'SOLIDAR2020', 'PASSOLIDAR2020'}
  Codes trouvés  : {'ESOLIDAR2026', 'PASSOLIDAR2020', 'SOLIDAR2020'}
  Codes manquants: set()

Indicateur : AEO Nb_FAAD
  Codes attendus : {'FAAD', 'EPIAF FAAD'}
  Codes trouvés  : {'FAAD', 'EPIAF FAAD'}
  Codes manquants: set()

Indicateur : Structure Nb_formateurs_CRB_2025
  Codes attendus : {'ACRB', 'ACRB3', 'ACRB2', 'ACRB2024'}
  Codes trouvés  : {'ACRB', 'ACRB3', 'ACRB2', 'ACRB2024'}
  Codes manquants: set()

Indicateur : Structure Nb_formes_TCAS_2025
  Codes attendus : {'ETCAS', 'TCAS'}
  Codes trouvés  : {'ETCAS', 'TCAS'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Maraude Nb_SOLIDAR : 7668
Maraude Nb_SOLIDAR2020 : 5713
AEO Nb_FAAD : 52
Structure Nb_formateurs_CRB_2025 : 840
Structure Nb_formes_TCAS_2025 : 11311

===== Vérification des codes =====

Indicateur : Maraude Nb_SOLIDAR
  Codes attendus : {'SOLIDAR', 'SOLIDAR1', 'ESOLIDAR2026', 'SOLIDAR2020', 'SOLIDAR2', 'PASSOLIDAR2020'}
  Codes trouvés  : {'SOLIDAR', 'SOLIDAR1', 'ESOLIDAR2026', 'SOLIDAR2020', 'SOLIDAR2', 'PASSOLIDAR2020'}
  Codes manquants: set()

Indicateur : Maraude Nb_SOLIDAR2020
  Codes attendus : {'ESOLIDAR2026', 'SOLIDAR2020', 'PASSOLIDAR2020'}
  Codes trouvés  : {'ESOLIDAR2026', 'PASSOLIDAR2020', 'SOLIDAR2020'}
  Codes manquants: set()

Indicateur : AEO Nb_FAAD
  Codes attendus : {'FAAD', 'EPIAF FAAD'}
  Codes trouvés  : {'FAAD', 'EPIAF FAAD'}
  Codes manquants: set()

Indicateur : Structure Nb_formateurs_CRB_2025
  Codes attendus : {'ACRB', 'ACRB3', 'ACRB2', 'ACRB2024'}
  Codes trouvés  : {'ACRB', 'ACRB3', 'ACRB2', 'ACRB2024'}
  Codes manquants: set()

Indicateur : Structure Nb_formes_TCAS_2025
  Codes attendus : {'ETCAS', 'TCAS'}
  Codes trouvés  : {'ETCAS', 'TCAS'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Maraude Nb_SOLIDAR : 7668
Maraude Nb_SOLIDAR2020 : 5713
AEO Nb_FAAD : 52
Structure Nb_formateurs_CRB_2025 : 840
Structure Nb_formes_TCAS_2025 : 11311

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_formes_PSC_2025
  Codes attendus : {'EPSC', 'PSC AC', 'PSC IRR', 'PSC1 IRR', 'PSC1', 'PSC', 'EPSC1', 'RECPSC1', 'FCPSC', 'PSC1 AC'}
  Codes trouvés  : {'EPSC', 'PSC AC', 'PSC IRR', 'PSC1 IRR', 'PSC1', 'PSC', 'EPSC1', 'RECPSC1', 'FCPSC', 'PSC1 AC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_GQS_2025
  Codes attendus : {'FIPS', 'GQS', 'FIPS2', 'GQS AC'}
  Codes trouvés  : {'FIPS', 'GQS', 'FIPS2', 'GQS AC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_IPS_2025
  Codes attendus : {'IPSM', 'IPS', 'IPS SR', 'IPSJP', 'IPSP', 'IPSEF', 'IPS AC', 'IPSJ', 'IPSE'}
  Codes trouvés  : {'IPS', 'IPS SR', 'IPSJP', 'IPSP', 'IPSEF', 'IPS AC', 'IPSJ', 'IPSE'}
  Codes manquants: {'IPSM'}

Indicateur : Formation_grand_public Nb_formes_IPSEN_2025
  Codes attendus : {'IPSEN'}
  Codes trouvés  : {'IPSEN'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_PREVIC_2025
  Codes attendus : {'PREVIC'}
  Codes trouvés  : {'PREVIC'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:255: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Formation_grand_public Nb_formes_PSC_2025 : 65593
Formation_grand_public Nb_formes_GQS_2025 : 9382
Formation_grand_public Nb_formes_IPS_2025 : 82137
Formation_grand_public Nb_formes_IPSEN_2025 : 8642
Formation_grand_public Nb_formes_PREVIC_2025 : 1

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_formes_PSC_2025
  Codes attendus : {'EPSC', 'PSC AC', 'PSC IRR', 'PSC1 IRR', 'PSC1', 'PSC', 'EPSC1', 'RECPSC1', 'FCPSC', 'PSC1 AC'}
  Codes trouvés  : {'EPSC', 'PSC AC', 'PSC IRR', 'PSC1 IRR', 'PSC1', 'PSC', 'EPSC1', 'RECPSC1', 'FCPSC', 'PSC1 AC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_GQS_2025
  Codes attendus : {'FIPS', 'GQS', 'FIPS2', 'GQS AC'}
  Codes trouvés  : {'FIPS', 'GQS', 'FIPS2', 'GQS AC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_IPS_2025
  Codes attendus : {'IPSM', 'IPS', 'IPS SR', 'IPSJP', 'IPSP', 'IPSEF', 'IPS AC', 'IPSJ', 'IPSE'}
  Codes trouvés  : {'IPS', 'IPS SR', 'IPSJP', 'IPSP', 'IPSEF', 'IPS AC', 'IPSJ', 'IPSE'}
  Codes manquants: {'IPSM'}

Indicateur : Formation_grand_public Nb_formes_IPSEN_2025
  Codes attendus : {'IPSEN'}
  Codes trouvés  : {'IPSEN'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_formes_PREVIC_2025
  Codes attendus : {'PREVIC'}
  Codes trouvés  : {'PREVIC'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:255: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Formation_grand_public Nb_formes_PSC_2025 : 65401
Formation_grand_public Nb_formes_GQS_2025 : 9381
Formation_grand_public Nb_formes_IPS_2025 : 82116
Formation_grand_public Nb_formes_IPSEN_2025 : 8621
Formation_grand_public Nb_formes_PREVIC_2025 : 1

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_sessions_PSC_2025
  Codes attendus : {'EPSC', 'PSC AC', 'PSC IRR', 'PSC1 IRR', 'PSC1', 'PSC', 'EPSC1', 'RECPSC1', 'FCPSC', 'PSC1 AC'}
  Codes trouvés  : {'EPSC', 'PSC AC', 'PSC IRR', 'PSC1 IRR', 'PSC1', 'PSC', 'EPSC1', 'RECPSC1', 'FCPSC', 'PSC1 AC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_GQS_2025
  Codes attendus : {'FIPS', 'GQS', 'FIPS2', 'GQS AC'}
  Codes trouvés  : {'FIPS', 'GQS', 'FIPS2', 'GQS AC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_IPS_2025
  Codes attendus : {'IPSM', 'IPS', 'IPS SR', 'IPSJP', 'IPSP', 'IPSEF', 'IPS AC', 'IPSJ', 'IPSE'}
  Codes trouvés  : {'IPS', 'IPS SR', 'IPSJP', 'IPSP', 'IPSEF', 'IPS AC', 'IPSJ', 'IPSE'}
  Codes manquants: {'IPSM'}

Indicateur : Formation_grand_public Nb_sessions_IPSEN_2025
  Codes attendus : {'IPSEN'}
  Codes trouvés  : {'IPSEN'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_PREVIC_2025
  Codes attendus : {'PREVIC'}
  Codes trouvés  : {'PREVIC'}
  Codes manquants: set()

Indicateur : Secours Nb_sessions_PSE
  Codes attendus : {'FCPSE1', 'PSE1', 'RECPSE2', 'FCPSE2', 'RATPSE1', 'RATPSE2', 'FCPSE', 'PSE', 'PSE2', 'APTE PSE1', 'RECPSE1'}
  Codes trouvés  : {'FCPSE1', 'PSE1', 'RECPSE2', 'FCPSE2', 'RATPSE1', 'RATPSE2', 'FCPSE', 'PSE', 'PSE2', 'APTE PSE1', 'RECPSE1'}
  Codes manquants: set()

Indicateur : Secours Nb_sessions_CI
  Codes attendus : {'CIP2', 'RECCI', 'CI', 'CI P1 P2', 'RECPSECI', 'REC PSECI', 'FCCI'}
  Codes trouvés  : {'RECCI', 'CI', 'FCCI'}
  Codes manquants: {'CIP2', 'REC PSECI', 'CI P1 P2', 'RECPSECI'}

Indicateur : Secours Nb_sessions_FPSE
  Codes attendus : {'FPSE', 'FCFPSE', 'RATFCFPSE', 'RECFPS', 'PICF FPS', 'FPS', 'PICF FPSE'}
  Codes trouvés  : {'FPSE', 'FCFPSE', 'RECFPS', 'RATFCFPSE', 'PICF FPS', 'FPS', 'PICF FPSE'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:329: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Formation_grand_public Nb_sessions_PSC_2025 : 8076
Formation_grand_public Nb_sessions_GQS_2025 : 1268
Formation_grand_public Nb_sessions_IPS_2025 : 10330
Formation_grand_public Nb_sessions_IPSEN_2025 : 1017
Formation_grand_public Nb_sessions_PREVIC_2025 : 19
Secours Nb_sessions_PSE : 1599
Secours Nb_sessions_CI : 350
Secours Nb_sessions_FPSE : 133

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_sessions_PSC_2025
  Codes attendus : {'EPSC', 'PSC AC', 'PSC IRR', 'PSC1 IRR', 'PSC1', 'PSC', 'EPSC1', 'RECPSC1', 'FCPSC', 'PSC1 AC'}
  Codes trouvés  : {'EPSC', 'PSC AC', 'PSC IRR', 'PSC1 IRR', 'PSC1', 'PSC', 'EPSC1', 'RECPSC1', 'FCPSC', 'PSC1 AC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_GQS_2025
  Codes attendus : {'FIPS', 'GQS', 'FIPS2', 'GQS AC'}
  Codes trouvés  : {'FIPS', 'GQS', 'FIPS2', 'GQS AC'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_IPS_2025
  Codes attendus : {'IPSM', 'IPS', 'IPS SR', 'IPSJP', 'IPSP', 'IPSEF', 'IPS AC', 'IPSJ', 'IPSE'}
  Codes trouvés  : {'IPS', 'IPS SR', 'IPSJP', 'IPSP', 'IPSEF', 'IPS AC', 'IPSJ', 'IPSE'}
  Codes manquants: {'IPSM'}

Indicateur : Formation_grand_public Nb_sessions_IPSEN_2025
  Codes attendus : {'IPSEN'}
  Codes trouvés  : {'IPSEN'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_PREVIC_2025
  Codes attendus : {'PREVIC'}
  Codes trouvés  : {'PREVIC'}
  Codes manquants: set()

Indicateur : Secours Nb_sessions_PSE
  Codes attendus : {'FCPSE1', 'PSE1', 'RECPSE2', 'FCPSE2', 'RATPSE1', 'RATPSE2', 'FCPSE', 'PSE', 'PSE2', 'APTE PSE1', 'RECPSE1'}
  Codes trouvés  : {'FCPSE1', 'PSE1', 'RECPSE2', 'FCPSE2', 'RATPSE1', 'RATPSE2', 'FCPSE', 'PSE', 'PSE2', 'APTE PSE1', 'RECPSE1'}
  Codes manquants: set()

Indicateur : Secours Nb_sessions_CI
  Codes attendus : {'CIP2', 'RECCI', 'CI', 'CI P1 P2', 'RECPSECI', 'REC PSECI', 'FCCI'}
  Codes trouvés  : {'RECCI', 'CI', 'FCCI'}
  Codes manquants: {'CIP2', 'REC PSECI', 'CI P1 P2', 'RECPSECI'}

Indicateur : Secours Nb_sessions_FPSE
  Codes attendus : {'FPSE', 'FCFPSE', 'RATFCFPSE', 'RECFPS', 'PICF FPS', 'FPS', 'PICF FPSE'}
  Codes trouvés  : {'FPSE', 'FCFPSE', 'RECFPS', 'RATFCFPSE', 'PICF FPS', 'FPS', 'PICF FPSE'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:329: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Formation_grand_public Nb_sessions_PSC_2025 : 8076
Formation_grand_public Nb_sessions_GQS_2025 : 1268
Formation_grand_public Nb_sessions_IPS_2025 : 10330
Formation_grand_public Nb_sessions_IPSEN_2025 : 1017
Formation_grand_public Nb_sessions_PREVIC_2025 : 19
Secours Nb_sessions_PSE : 1599
Secours Nb_sessions_CI : 350
Secours Nb_sessions_FPSE : 133

===== Vérification des codes =====

Indicateur : Dispositifs_d_urgence Structures_menant_activite_TCAU
  Codes attendus : {'TCAU', 'ETCAU'}
  Codes trouvés  : {'TCAU', 'ETCAU'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Structures_menant_activite_PSP
  Codes attendus : {'PSP'}
  Codes trouvés  : {'PSP'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Structures_menant_activite_GQS
  Codes attendus : {'FIPS', 'GQS', 'FIPS2', 'GQS AC'}
  Codes trouvés  : {'FIPS', 'GQS', 'FIPS2', 'GQS AC'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:396: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Dispositifs_d_urgence Structures_menant_activite_TCAU : 72
Dispositifs_d_urgence Structures_menant_activite_PSP : 59
Dispositifs_d_urgence Structures_menant_activite_GQS : 486

===== Vérification des codes =====

Indicateur : Dispositifs_d_urgence Structures_menant_activite_TCAU
  Codes attendus : {'TCAU', 'ETCAU'}
  Codes trouvés  : {'TCAU', 'ETCAU'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Structures_menant_activite_PSP
  Codes attendus : {'PSP'}
  Codes trouvés  : {'PSP'}
  Codes manquants: set()

Indicateur : Dispositifs_d_urgence Structures_menant_activite_GQS
  Codes attendus : {'FIPS', 'GQS', 'FIPS2', 'GQS AC'}
  Codes trouvés  : {'FIPS', 'GQS', 'FIPS2', 'GQS AC'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:396: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Dispositifs_d_urgence Structures_menant_activite_TCAU : 72
Dispositifs_d_urgence Structures_menant_activite_PSP : 59
Dispositifs_d_urgence Structures_menant_activite_GQS : 486

===== Vérification des codes =====

Indicateur : Secours Nb_PSE1
  Codes attendus : {'FCPSE1', 'PSE1', 'RATPSE1', 'APTE PSE1', 'RECPSE1'}
  Codes trouvés  : {'FCPSE1', 'PSE1', 'RATPSE1', 'APTE PSE1', 'RECPSE1'}
  Codes manquants: set()

Indicateur : Secours Nb_PSE2
  Codes attendus : {'RECPSE2', 'FCPSE2', 'RATPSE2', 'PSE AGSU', 'FCPSE', 'PSE', 'PSE2'}
  Codes trouvés  : {'RECPSE2', 'FCPSE2', 'RATPSE2', 'FCPSE', 'PSE', 'PSE2'}
  Codes manquants: {'PSE AGSU'}

Indicateur : Secours Nb_CI
  Codes attendus : {'CIP2', 'RECCI', 'CI', 'CI P1 P2', 'RECPSECI', 'REC PSECI', 'FCCI'}
  Codes trouvés  : {'RECCI', 'CI', 'FCCI'}
  Codes manquants: {'CIP2', 'REC PSECI', 'CI P1 P2', 'RECPSECI'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:492: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: pd.Series({

===== Somme globale par indicateur =====
Secours Nb_PSE1 : 509
Secours Nb_PSE2 : 7300
Secours Nb_CI : 1746

===== Vérification des codes =====

Indicateur : Secours Nb_PSE1
  Codes attendus : {'FCPSE1', 'PSE1', 'RATPSE1', 'APTE PSE1', 'RECPSE1'}
  Codes trouvés  : {'FCPSE1', 'PSE1', 'RATPSE1', 'APTE PSE1', 'RECPSE1'}
  Codes manquants: set()

Indicateur : Secours Nb_PSE2
  Codes attendus : {'RECPSE2', 'FCPSE2', 'RATPSE2', 'PSE AGSU', 'FCPSE', 'PSE', 'PSE2'}
  Codes trouvés  : {'RECPSE2', 'FCPSE2', 'RATPSE2', 'FCPSE', 'PSE', 'PSE2'}
  Codes manquants: {'PSE AGSU'}

Indicateur : Secours Nb_CI
  Codes attendus : {'CIP2', 'RECCI', 'CI', 'CI P1 P2', 'RECPSECI', 'REC PSECI', 'FCCI'}
  Codes trouvés  : {'RECCI', 'CI', 'FCCI'}
  Codes manquants: {'CIP2', 'REC PSECI', 'CI P1 P2', 'RECPSECI'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:492: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: pd.Series({

===== Somme globale par indicateur =====
Secours Nb_PSE1 : 509
Secours Nb_PSE2 : 7300
Secours Nb_CI : 1746

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_FPSC
  Codes attendus : {'FCFPSC', 'PAE3', 'FPSC', 'RECFPSC', 'RATFCFPSC', 'PICF FPSC'}
  Codes trouvés  : {'FCFPSC', 'FPSC', 'RECFPSC', 'RATFCFPSC', 'PICF FPSC'}
  Codes manquants: {'PAE3'}

Indicateur : Formation_grand_public Nb_AGQS
  Codes attendus : {'AGQS'}
  Codes trouvés  : {'AGQS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_FIPSEN
  Codes attendus : {'RECFIPSEN', 'FIPSEN'}
  Codes trouvés  : {'FIPSEN'}
  Codes manquants: {'RECFIPSEN'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:560: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Formation_grand_public Nb_FPSC : 1071
Formation_grand_public Nb_AGQS : 134
Formation_grand_public Nb_FIPSEN : 19

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_FPSC
  Codes attendus : {'FCFPSC', 'PAE3', 'FPSC', 'RECFPSC', 'RATFCFPSC', 'PICF FPSC'}
  Codes trouvés  : {'FCFPSC', 'FPSC', 'RECFPSC', 'RATFCFPSC', 'PICF FPSC'}
  Codes manquants: {'PAE3'}

Indicateur : Formation_grand_public Nb_AGQS
  Codes attendus : {'AGQS'}
  Codes trouvés  : {'AGQS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_FIPSEN
  Codes attendus : {'RECFIPSEN', 'FIPSEN'}
  Codes trouvés  : {'FIPSEN'}
  Codes manquants: {'RECFIPSEN'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:560: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Formation_grand_public Nb_FPSC : 1071
Formation_grand_public Nb_AGQS : 134
Formation_grand_public Nb_FIPSEN : 19

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:610: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:610: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:610: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(

nb_recy_PSE1 : 330.0
nb_recy_PSE2 : 5603.0
nb_recy_CI : 1139.0

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:610: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:610: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:610: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(

nb_recy_PSE1 : 330.0
nb_recy_PSE2 : 5603.0
nb_recy_CI : 1139.0

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:664: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:664: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:664: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(

nb_ren_PSE1 : 184.0
nb_ren_PSE2 : 1728.0
nb_ren_CI : 189.0

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:664: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:664: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:664: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  taux = df_res.groupby(col_groupby).apply(

nb_ren_PSE1 : 184.0
nb_ren_PSE2 : 1728.0
nb_ren_CI : 189.0

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

===== Vérification des codes =====

Indicateur : Maraude Nb_benevoles_actifs_formes
  Codes attendus : {'SOLIDAR', 'SOLIDAR1', 'ESOLIDAR2026', 'SOLIDAR2020', 'SOLIDAR2', 'PASSOLIDAR2020'}
  Codes trouvés  : {'SOLIDAR', 'SOLIDAR1', 'ESOLIDAR2026', 'SOLIDAR2020', 'SOLIDAR2', 'PASSOLIDAR2020'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:970: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Maraude Nb_benevoles_actifs_formes : 1992

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

===== Vérification des codes =====

Indicateur : Maraude Nb_benevoles_actifs_formes
  Codes attendus : {'SOLIDAR', 'SOLIDAR1', 'ESOLIDAR2026', 'SOLIDAR2020', 'SOLIDAR2', 'PASSOLIDAR2020'}
  Codes trouvés  : {'SOLIDAR', 'SOLIDAR1', 'ESOLIDAR2026', 'SOLIDAR2020', 'SOLIDAR2', 'PASSOLIDAR2020'}
  Codes manquants: set()

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:970: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Maraude Nb_benevoles_actifs_formes : 1599

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

===== Vérification des codes =====

Indicateur : Nb_IS
  Codes attendus : {'RECPSE2', 'RECCI', 'RATPSE2', 'PSE AGSU', 'FCCI', 'APTE PSE1', 'FCPSE1', 'PSE1', 'CIP2', 'CI P1 P2', 'FCPSE', 'RECPSECI', 'PSE2', 'FCPSE2', 'CI', 'RATPSE1', 'PSE', 'REC PSECI', 'RECPSE1'}
  Codes trouvés  : {'RECPSE2', 'PSE1', 'FCPSE1', 'FCPSE2', 'RATPSE1', 'RECCI', 'CI', 'RATPSE2', 'RECPSECI', 'FCPSE', 'PSE', 'FCCI', 'PSE2', 'APTE PSE1', 'RECPSE1'}
  Codes manquants: {'REC PSECI', 'CIP2', 'PSE AGSU', 'CI P1 P2'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:894: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Nb_IS : 10533

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

===== Vérification des codes =====

Indicateur : Nb_IS
  Codes attendus : {'RECPSE2', 'RECCI', 'RATPSE2', 'PSE AGSU', 'FCCI', 'APTE PSE1', 'FCPSE1', 'PSE1', 'CIP2', 'CI P1 P2', 'FCPSE', 'RECPSECI', 'PSE2', 'FCPSE2', 'CI', 'RATPSE1', 'PSE', 'REC PSECI', 'RECPSE1'}
  Codes trouvés  : {'RECPSE2', 'PSE1', 'FCPSE1', 'FCPSE2', 'RATPSE1', 'RECCI', 'CI', 'RATPSE2', 'RECPSECI', 'FCPSE', 'PSE', 'FCCI', 'PSE2', 'APTE PSE1', 'RECPSE1'}
  Codes manquants: {'REC PSECI', 'CIP2', 'PSE AGSU', 'CI P1 P2'}

===== Somme globale par indicateur =====
Nb_IS : 10533

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:894: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

===== Vérification des codes =====

Indicateur : Structure Nb_nvx_formes_CRB_2025
  Codes attendus : {'VI', 'ECRB', 'CRB'}
  Codes trouvés  : {'ECRB', 'CRB'}
  Codes manquants: {'VI'}

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:804: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

===== Somme globale par indicateur =====
Structure Nb_nvx_formes_CRB_2025 : 1472

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

===== Vérification des codes =====

Indicateur : Structure Nb_nvx_formes_CRB_2025
  Codes attendus : {'VI', 'ECRB', 'CRB'}
  Codes trouvés  : {'ECRB', 'CRB'}
  Codes manquants: {'VI'}

===== Somme globale par indicateur =====
Structure Nb_nvx_formes_CRB_2025 : 1472

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\base_contact.py:804: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_res.groupby(col_groupby).apply(

## DPS

In [64]:
df_indicateurs_dps = indicateurs_dps(df_dps, df_ref_structure)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 898.98it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

===== Somme globale par indicateur DPS =====
Secours Nb_PAPS_2025 : 12970.0
Secours Nb_DPS_PE_2025 : 28004.5
Secours Nb_DPS_ME_2025 : 9268.0
Secours Nb_DPS_GE_2025 : 4258.0
Secours Nb_DPS_2025 : 54500.5

In [65]:
verifications_dps(df_dps_source, df_indicateurs_dps)

✅ OK Secours Nb_PAPS_2025 : Nb de vacations de 4h effectuées PAPS = Secours Nb_PAPS_2025
✅ OK Secours Nb_DPS_PE_2025 : Nb de vacations de 4h effectuées DPS PE = Secours Nb_DPS_PE_2025
✅ OK Secours Nb_DPS_ME_2025 : Nb de vacations de 4h effectuées DPS ME = Secours Nb_DPS_ME_2025
✅ OK Secours Nb_DPS_GE_2025 : Nb de vacations de 4h effectuées DPS GE = Secours Nb_DPS_GE_2025
✅ OK Secours Nb_PAPS_2025 : source = Secours Nb_PAPS_2025

# Création du DataFrame final

La liste de tous les dataframes à fusionner sur df_ref_structure

In [66]:
# On ne filtre pas les implantations locales avant à cause du rattachement successif
df_ref_structure = df_ref_structure[df_ref_structure["type_structure"].isin(["UNITE LOCALE - UL", "DELEGATION TERRITORIALE - DT", 'ANTENNE LOCALE - AL','INSTANCES NATIONALES - IN'])]

In [67]:
liste_df_a_fusionner_toutes_structures = [nb_benevoles,nb_nvx_benevoles,referents_AEO,referents_OCR,IMPACT_ppc,df_DUO,IMPACT_agrementAB, IMPACT_agrementDPS,
                                          df_mobilite_DT_UL,df_OCR_Nb_deployees, df_redcall2,
                                          df_raw_Textile, df_alim_U2A_sans_doublons, df_alim_epicerie_sociale,
                                          df_alim_accueil_alimentaire, df_alim_crsr, df_adherent, df_personnes_domiciliees_struct,df_Maraude_donnees_manuelles_structure_2, indicateurs_base_contact,
                                          df_financier,
                                          pegass_output['Indics_pegass_struct'], df_indicateurs_dps]

liste_df_a_fusionner_DT = [nb_benevoles_DT,nb_nvx_benevoles_DT,referents_AEO_DT,referents_OCR_DT,IMPACT_ppc_DT,df_DUO,
                           IMPACT_agrementAB_DT, IMPACT_agrementDPS_DT,df_mobilite_DT,Nb_OCR_DT,RedCall_DT,df_Dispositifs_d_urgence_PST, df_declenchement3,
                           df_CAICHUCMCC_VF, df_conventions2,
                           df_Textile_DT, df_alim_U2A_DT, df_alim_epicerie_sociale_DT, df_alim_accueil_alimentaire_DT, df_alim_crsr_DT, df_adherent_DT,
                           df_personnes_domiciliees_DT, df_Maraude_donnees_manuelles_DT_2, indicateurs_base_contact_DT,
                           df_financier_DT,df_financier_FGP_DT,Indics_pegass_DT, df_indicateurs_dps]

In [68]:
all_data, all_data_DT, liste_df_a_fusionner_toutes_structures_processed, liste_df_a_fusionner_DT_processed = traitement_all_data(liste_df_a_fusionner_toutes_structures, liste_df_a_fusionner_DT, df_ref_structure,df_ref_structure_DT)

TRAITEMENT DES INDICATEURS POUR TOUTES LES STRUCTURES

🧹 DataFrame 5 : suppression des colonnes ['Departement', 'Opération type A', 'Opération type B', 'Opération type A et B', "Points d'Alerte et de Premiers Secours RIS", 'Dispositifs Prévisionnel de Secours de Petite Envergure RIS', 'Dispositifs Prévisionnel de Secours de Moyenne Envergure RIS', 'Dispositifs Prévisionnel de Secours de Grande Envergure RIS', 'nom_structure']
🧹 DataFrame 17 : suppression des colonnes ['DT_de_rattachement']
🧹 DataFrame 20 : suppression des colonnes ['libelle_structure_x', 'libelle_structure_y', 'Région', 'n_dept', 'N° Smartview', 'Nom structure']
🧹 DataFrame 22 : suppression des colonnes ['Departement', 'nom_structure']
✅ DataFrame 0 : aucun doublon dans 'n_structure'
✅ DataFrame 1 : aucun doublon dans 'n_structure'
✅ DataFrame 2 : aucun doublon dans 'n_structure'
✅ DataFrame 3 : aucun doublon dans 'n_structure'
✅ DataFrame 4 : aucun doublon dans 'n_structure'
✅ DataFrame 5 : aucun doublon dans 'n_structure'
✅ DataFrame 6 : aucun doublon dans 'n_structure'
✅ DataFrame 7 : aucun doublon dans 'n_structure'
✅ DataFrame 8 : aucun doublon dans 'n_structure'
✅ DataFrame 9 : aucun doublon dans 'n_structure'
✅ DataFrame 10 : aucun doublon dans 'n_structure'
✅ DataFrame 11 : aucun doublon dans 'n_structure'
✅ DataFrame 12 : aucun doublon dans 'n_structure'
✅ DataFrame 13 : aucun doublon dans 'n_structure'
✅ DataFrame 14 : aucun doublon dans 'n_structure'
✅ DataFrame 15 : aucun doublon dans 'n_structure'
✅ DataFrame 16 : aucun doublon dans 'n_structure'
✅ DataFrame 17 : aucun doublon dans 'n_structure'
✅ DataFrame 18 : aucun doublon dans 'n_structure'
✅ DataFrame 19 : aucun doublon dans 'n_structure'
✅ DataFrame 20 : aucun doublon dans 'n_structure'
✅ DataFrame 21 : aucun doublon dans 'n_structure'
✅ DataFrame 22 : aucun doublon dans 'n_structure'
TRAITEMENT DES INDICATEURS POUR LES DTs

🧹 DataFrame 5 : suppression des colonnes ['Departement', 'Opération type A', 'Opération type B', 'Opération type A et B', "Points d'Alerte et de Premiers Secours RIS", 'Dispositifs Prévisionnel de Secours de Petite Envergure RIS', 'Dispositifs Prévisionnel de Secours de Moyenne Envergure RIS', 'Dispositifs Prévisionnel de Secours de Grande Envergure RIS', 'nom_structure']
🧹 DataFrame 11 : suppression des colonnes ['Territoire', 'PST constitué', 'Nom structure DT', 'N° Département', 'nom_structure']
🧹 DataFrame 12 : suppression des colonnes ['Département', 'Etablissements', 'Exercice', 'Fonctionnement', 'Opérations', 'Grand Total', 'Unnamed: 6', 'DT Annuaire Opé', 'Exercice_convention', 'n_dept', 'DT', 'nom_structure']
🧹 DataFrame 13 : suppression des colonnes ['Dépt', 'Région', 'Département', 'nom_structure']
🧹 DataFrame 14 : suppression des colonnes ['Departement', 'nom_structure']
🧹 DataFrame 24 : suppression des colonnes ['n_dept_x', 'libelle_structure_x', 'n_dept_y', 'libelle_structure_y', 'n_dept']
🧹 DataFrame 25 : suppression des colonnes ['n_dept']
🧹 DataFrame 26 : suppression des colonnes ['nb_activite_AEO']
🧹 DataFrame 27 : suppression des colonnes ['Departement', 'nom_structure']
✅ DataFrame 0 : aucun doublon dans 'n_structure'
✅ DataFrame 1 : aucun doublon dans 'n_structure'
✅ DataFrame 2 : aucun doublon dans 'n_structure'
✅ DataFrame 3 : aucun doublon dans 'n_structure'
✅ DataFrame 4 : aucun doublon dans 'n_structure'
✅ DataFrame 5 : aucun doublon dans 'n_structure'
✅ DataFrame 6 : aucun doublon dans 'n_structure'
✅ DataFrame 7 : aucun doublon dans 'n_structure'
✅ DataFrame 8 : aucun doublon dans 'n_structure'
✅ DataFrame 9 : aucun doublon dans 'n_structure'
✅ DataFrame 10 : aucun doublon dans 'n_structure'
✅ DataFrame 11 : aucun doublon dans 'n_structure'
✅ DataFrame 12 : aucun doublon dans 'n_structure'
✅ DataFrame 13 : aucun doublon dans 'n_structure'
✅ DataFrame 14 : aucun doublon dans 'n_structure'
✅ DataFrame 15 : aucun doublon dans 'n_structure'
✅ DataFrame 16 : aucun doublon dans 'n_structure'
✅ DataFrame 17 : aucun doublon dans 'n_structure'
✅ DataFrame 18 : aucun doublon dans 'n_structure'
✅ DataFrame 19 : aucun doublon dans 'n_structure'
✅ DataFrame 20 : aucun doublon dans 'n_structure'
✅ DataFrame 21 : aucun doublon dans 'n_structure'
✅ DataFrame 22 : aucun doublon dans 'n_structure'
✅ DataFrame 23 : aucun doublon dans 'n_structure'
✅ DataFrame 24 : aucun doublon dans 'n_structure'
✅ DataFrame 25 : aucun doublon dans 'n_structure'
✅ DataFrame 26 : aucun doublon dans 'n_structure'
✅ DataFrame 27 : aucun doublon dans 'n_structure'

In [69]:
report = check_sums_against_final(
    df_final=all_data,
    list_of_dfs=liste_df_a_fusionner_toutes_structures,
    key_col="n_structure",
    atol=1e-6
)

🔎 Vérification DataFrame 0
   ✅ 'Structure Nb_Benevoles' OK | individuel = 81883.0 | final = 81883.0

🔎 Vérification DataFrame 1
   ✅ 'Structure Nb_nvx_Benevoles_2025' OK | individuel = 16784.0 | final = 16784.0

🔎 Vérification DataFrame 2
   ✅ 'AEO Nb_responsables' OK | individuel = 36.0 | final = 36.0

🔎 Vérification DataFrame 3
   ✅ 'OCR Nb_referents' OK | individuel = 20.0 | final = 20.0

🔎 Vérification DataFrame 4
   ✅ 'Dispositifs_d_urgence Nb_personnes_prises_charge' OK | individuel = 15709.0 | final = 15709.0

🔎 Vérification DataFrame 5
   ✅ 'Dispositifs_d_urgence Nb_operations2' OK | individuel = 209.0 | final = 209.0
   ✅ 'Dispositifs_d_urgence Nb_personnes_prises_charge2' OK | individuel = 14540.0 | final = 14540.0
   ✅ 'Dispositifs_d_urgence Nb_exercices2' OK | individuel = 159.0 | final = 159.0
   ✅ 'Dispositifs_d_urgence Nb_agrements2' OK | individuel = 282.0 | final = 282.0
   ✅ 'Secours Nb_agrements_DPS_2025_2' OK | individuel = 15257.0 | final = 15257.0

🔎 Vérification DataFrame 6
   ✅ 'Dispositifs_d_urgence Nb_agrements' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 7
   ✅ 'Secours Nb_agrements_DPS_2025' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 8
   ✅ 'AEO Structure_activite_mobile' OK | individuel = 169.0 | final = 169.0
   ✅ 'AEO Nb_PA_dispos_mobiles' OK | individuel = 17208.0 | final = 17208.0

🔎 Vérification DataFrame 9
   ✅ 'OCR Nb_deployees' OK | individuel = 58.0 | final = 58.0

🔎 Vérification DataFrame 10
   ✅ 'Dispositifs_d_urgence Utilisation_RedCall' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 11
   ✅ 'Textile Nb_dispositifs' OK | individuel = 895.0 | final = 895.0

🔎 Vérification DataFrame 12
   ✅ 'Aide_alimentaire Nb_U2A' OK | individuel = 627.0 | final = 627.0

🔎 Vérification DataFrame 13
   ✅ 'Aide_alimentaire Nb_epiceries_sociales' OK | individuel = 77.0 | final = 77.0

🔎 Vérification DataFrame 14
   ✅ 'Aide_alimentaire Nb_Centre_distribution_alimentaire' OK | individuel = 510.0 | final = 510.0

🔎 Vérification DataFrame 15
   ✅ 'Aide_alimentaire Nb_crsr' OK | individuel = 40.0 | final = 40.0

🔎 Vérification DataFrame 16
   ✅ 'Structure Nb_Adherents' OK | individuel = 47403.0 | final = 47403.0

🔎 Vérification DataFrame 17
   ✅ 'AEO Nb_personnes_domiciliees_crf' OK | individuel = 30833.0 | final = 30833.0

🔎 Vérification DataFrame 18
   ✅ 'Maraude Nb_maraudes_SIGMA' OK | individuel = 7645.0 | final = 7645.0
   ✅ 'Maraude Nb_personnes_rencontrees' OK | individuel = 26013.0 | final = 26013.0
   ✅ 'Maraude Nb_contacts' OK | individuel = 130910.0 | final = 130910.0

🔎 Vérification DataFrame 19
   ✅ 'AEO Nb_AAD' OK | individuel = 1273.0 | final = 1273.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCAU_2025' OK | individuel = 11792.0 | final = 11792.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCEO_2025' OK | individuel = 1788.0 | final = 1788.0
   ✅ 'Dispositifs_d_urgence Nb_formes_PSP_2025' OK | individuel = 5015.0 | final = 5015.0
   ✅ 'Dispositifs_d_urgence Nb_formes_IRR_2025' OK | individuel = 23706.0 | final = 23706.0
   ✅ 'Dispositifs_d_urgence Nb_formes_GQS_2025' OK | individuel = 35395.0 | final = 35395.0
   ✅ 'Structure Nb_formes_CRB_2025' OK | individuel = 20341.0 | final = 20341.0
   ✅ 'Maraude Nb_SOLIDAR' OK | individuel = 7631.0 | final = 7631.0
   ✅ 'Maraude Nb_SOLIDAR2020' OK | individuel = 5691.0 | final = 5691.0
   ✅ 'AEO Nb_FAAD' OK | individuel = 52.0 | final = 52.0
   ✅ 'Structure Nb_formateurs_CRB_2025' OK | individuel = 836.0 | final = 836.0
   ✅ 'Structure Nb_formes_TCAS_2025' OK | individuel = 11215.0 | final = 11215.0
   ✅ 'Formation_grand_public Nb_formes_PSC_2025' OK | individuel = 65593.0 | final = 65593.0
   ✅ 'Formation_grand_public Nb_formes_GQS_2025' OK | individuel = 9382.0 | final = 9382.0
   ✅ 'Formation_grand_public Nb_formes_IPS_2025' OK | individuel = 82137.0 | final = 82137.0
   ✅ 'Formation_grand_public Nb_formes_IPSEN_2025' OK | individuel = 8642.0 | final = 8642.0
   ✅ 'Formation_grand_public Nb_formes_PREVIC_2025' OK | individuel = 1.0 | final = 1.0
   ✅ 'Formation_grand_public Nb_sessions_PSC_2025' OK | individuel = 8076.0 | final = 8076.0
   ✅ 'Formation_grand_public Nb_sessions_GQS_2025' OK | individuel = 1268.0 | final = 1268.0
   ✅ 'Formation_grand_public Nb_sessions_IPS_2025' OK | individuel = 10330.0 | final = 10330.0
   ✅ 'Formation_grand_public Nb_sessions_IPSEN_2025' OK | individuel = 1017.0 | final = 1017.0
   ✅ 'Formation_grand_public Nb_sessions_PREVIC_2025' OK | individuel = 19.0 | final = 19.0
   ✅ 'Secours Nb_sessions_PSE' OK | individuel = 1599.0 | final = 1599.0
   ✅ 'Secours Nb_sessions_CI' OK | individuel = 350.0 | final = 350.0
   ✅ 'Secours Nb_sessions_FPSE' OK | individuel = 133.0 | final = 133.0
   ✅ 'Secours Nb_PSE1' OK | individuel = 508.0 | final = 508.0
   ✅ 'Secours Nb_PSE2' OK | individuel = 7294.0 | final = 7294.0
   ✅ 'Secours Nb_CI' OK | individuel = 1744.0 | final = 1744.0
   ✅ 'Formation_grand_public Nb_FPSC' OK | individuel = 1070.0 | final = 1070.0
   ✅ 'Formation_grand_public Nb_AGQS' OK | individuel = 134.0 | final = 134.0
   ✅ 'Formation_grand_public Nb_FIPSEN' OK | individuel = 19.0 | final = 19.0
   ✅ 'Secours Taux_recy26_PSE1' OK | individuel = 161.50912698412696 | final = 161.50912698412696
   ✅ 'Secours Taux_recy26_PSE2' OK | individuel = 399.277108772317 | final = 399.277108772317
   ✅ 'Secours Taux_recy26_CI' OK | individuel = 261.2899714965117 | final = 261.2899714965117
   ✅ 'Secours Taux_ren25_PSE1' OK | individuel = 73.90753968253966 | final = 73.90753968253966
   ✅ 'Secours Taux_ren25_PSE2' OK | individuel = 120.14997184873506 | final = 120.14997184873506
   ✅ 'Secours Taux_ren25_CI' OK | individuel = 40.87012998611296 | final = 40.87012998611296
   ✅ 'Maraude Nb_benevoles_actifs_formes' OK | individuel = 1983.0 | final = 1983.0
   ✅ 'Secours Taux_IS_actifs' OK | individuel = 433.50328487167724 | final = 433.50328487167724
   ✅ 'Structure Nb_nvx_formes_CRB_2025' OK | individuel = 1467.0 | final = 1467.0

🔎 Vérification DataFrame 20
   ✅ 'Financier Prod_2025' OK | individuel = 92639427.0 | final = 92639427.0
   ✅ 'Financier ResNet_2025' OK | individuel = 2762606.0 | final = 2762606.0
   ✅ 'Financier ResCorrProd_2025' OK | individuel = -445.78586716415316 | final = -445.78586716415316
   ✅ 'Financier Prod_2023' OK | individuel = 87333139.03 | final = 87333139.03
   ✅ 'Financier ResNet_2023' OK | individuel = 5450503.380000001 | final = 5450503.380000001
   ✅ 'Financier ResCorrProd_2023' OK | individuel = -35.448654671618556 | final = -35.448654671618556
   ✅ 'Financier Prod_2024' OK | individuel = 88893716.98 | final = 88893716.98
   ✅ 'Financier ResNet_2024' OK | individuel = 4610056.17 | final = 4610056.17
   ✅ 'Financier ResCorrProd_2024' OK | individuel = -38.49364332951876 | final = -38.49364332951876
   ✅ 'Financier caf_2025' OK | individuel = 11889289.0 | final = 11889289.0
   ✅ 'Financier TresoBrute_2025' OK | individuel = 145829119.0 | final = 145829119.0
   ✅ 'Financier Mois_AvanceTreso_2025' OK | individuel = 18626.97244842428 | final = 18626.97244842428
   ✅ 'Textile Produit_2025' OK | individuel = 19502431.0 | final = 19502431.0
   ✅ 'Secours Produits_DPS_2025' OK | individuel = 9739183.0 | final = 9739183.0

🔎 Vérification DataFrame 21
   ✅ 'nb_Maraude_Pegass' OK | individuel = 19179.0 | final = 19179.0
   ✅ 'Dispositifs_d_urgence Nb_operations' OK | individuel = 2460.0 | final = 2460.0
   ✅ 'Dispositifs_d_urgence Nb_exercices' OK | individuel = 269.0 | final = 269.0
   ✅ 'AEO Structure_activite_fixe' OK | individuel = 0.0 | final = 0.0
   ✅ 'Maraude Nb_benevoles_actifs' OK | individuel = 7672.0 | final = 7672.0
   ✅ 'AEO Nb_benevoles_actifs' OK | individuel = 987.0 | final = 987.0
   ✅ 'IS Nb_benevoles_actifs' OK | individuel = 20461.0 | final = 20461.0
   ✅ 'Activités AAD facultatives' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 22
   ✅ 'Secours Nb_PAPS_2025' OK | individuel = 12970.0 | final = 12970.0
   ✅ 'Secours Nb_DPS_PE_2025' OK | individuel = 28004.5 | final = 28004.5
   ✅ 'Secours Nb_DPS_ME_2025' OK | individuel = 9268.0 | final = 9268.0
   ✅ 'Secours Nb_DPS_GE_2025' OK | individuel = 4258.0 | final = 4258.0
   ✅ 'Secours Nb_DPS_2025' OK | individuel = 54500.5 | final = 54500.5

In [70]:
report = check_sums_against_final(
  df_final=all_data_DT,
  list_of_dfs=liste_df_a_fusionner_DT,
  key_col="n_structure",
  atol=1e-6
  )

🔎 Vérification DataFrame 0
   ✅ 'Structure Nb_Benevoles' OK | individuel = 80764.0 | final = 80764.0

🔎 Vérification DataFrame 1
   ✅ 'Structure Nb_nvx_Benevoles_2025' OK | individuel = 16653.0 | final = 16653.0

🔎 Vérification DataFrame 2
   ✅ 'AEO Nb_responsables' OK | individuel = 36.0 | final = 36.0

🔎 Vérification DataFrame 3
   ✅ 'OCR Nb_referents' OK | individuel = 20.0 | final = 20.0

🔎 Vérification DataFrame 4
   ✅ 'Dispositifs_d_urgence Nb_personnes_prises_charge' OK | individuel = 15709.0 | final = 15709.0

🔎 Vérification DataFrame 5
   ✅ 'Dispositifs_d_urgence Nb_operations2' OK | individuel = 209.0 | final = 209.0
   ✅ 'Dispositifs_d_urgence Nb_personnes_prises_charge2' OK | individuel = 14540.0 | final = 14540.0
   ✅ 'Dispositifs_d_urgence Nb_exercices2' OK | individuel = 159.0 | final = 159.0
   ✅ 'Dispositifs_d_urgence Nb_agrements2' OK | individuel = 282.0 | final = 282.0
   ✅ 'Secours Nb_agrements_DPS_2025_2' OK | individuel = 15257.0 | final = 15257.0

🔎 Vérification DataFrame 6
   ✅ 'Dispositifs_d_urgence Nb_agrements' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 7
   ✅ 'Secours Nb_agrements_DPS_2025' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 8
   ✅ 'AEO Structure_activite_mobile' OK | individuel = 169.0 | final = 169.0
   ✅ 'AEO Nb_PA_dispos_mobiles' OK | individuel = 17208.0 | final = 17208.0

🔎 Vérification DataFrame 9
   ✅ 'OCR Nb_deployees' OK | individuel = 58.0 | final = 58.0

🔎 Vérification DataFrame 10
   ✅ 'Dispositifs_d_urgence Utilisation_RedCall' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 11
   ✅ 'Dispositifs_d_urgence PST' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 12
   ✅ 'Dispositifs_d_urgence Nb_declenchements' OK | individuel = 495.0 | final = 495.0

🔎 Vérification DataFrame 13
   ✅ 'Dispositifs_d_urgence Nb_lots_CAI' OK | individuel = 239.0 | final = 239.0
   ✅ 'Dispositifs_d_urgence Nb_lots_CHU' OK | individuel = 174.0 | final = 174.0
   ✅ 'Dispositifs_d_urgence Nb_lots_CMCC' OK | individuel = 281.0 | final = 281.0

🔎 Vérification DataFrame 14
   ✅ 'Dispositifs_d_urgence Nb_conventions_prefecture' OK | individuel = 0.0 | final = 0.0
   ✅ 'Dispositifs_d_urgence Nb_conventions_operateurs' OK | individuel = 361.0 | final = 361.0

🔎 Vérification DataFrame 15
   ✅ 'Textile Nb_dispositifs' OK | individuel = 895.0 | final = 895.0

🔎 Vérification DataFrame 16
   ✅ 'Aide_alimentaire Nb_U2A' OK | individuel = 627.0 | final = 627.0

🔎 Vérification DataFrame 17
   ✅ 'Aide_alimentaire Nb_epiceries_sociales' OK | individuel = 77.0 | final = 77.0

🔎 Vérification DataFrame 18
   ✅ 'Aide_alimentaire Nb_Centre_distribution_alimentaire' OK | individuel = 510.0 | final = 510.0

🔎 Vérification DataFrame 19
   ✅ 'Aide_alimentaire Nb_crsr' OK | individuel = 40.0 | final = 40.0

🔎 Vérification DataFrame 20
   ✅ 'Structure Nb_Adherents' OK | individuel = 47403.0 | final = 47403.0

🔎 Vérification DataFrame 21
   ✅ 'AEO Nb_personnes_domiciliees_crf' OK | individuel = 30833.0 | final = 30833.0

🔎 Vérification DataFrame 22
   ✅ 'Maraude Nb_maraudes_SIGMA' OK | individuel = 7645.0 | final = 7645.0
   ✅ 'Maraude Nb_personnes_rencontrees' OK | individuel = 26013.0 | final = 26013.0
   ✅ 'Maraude Nb_contacts' OK | individuel = 130910.0 | final = 130910.0

🔎 Vérification DataFrame 23
   ✅ 'AEO Nb_AAD' OK | individuel = 1283.0 | final = 1283.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCAU_2025' OK | individuel = 11805.0 | final = 11805.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCEO_2025' OK | individuel = 1771.0 | final = 1771.0
   ✅ 'Dispositifs_d_urgence Nb_formes_PSP_2025' OK | individuel = 5030.0 | final = 5030.0
   ✅ 'Dispositifs_d_urgence Nb_formes_IRR_2025' OK | individuel = 23662.0 | final = 23662.0
   ✅ 'Dispositifs_d_urgence Nb_formes_GQS_2025' OK | individuel = 35279.0 | final = 35279.0
   ✅ 'Structure Nb_formes_CRB_2025' OK | individuel = 20464.0 | final = 20464.0
   ✅ 'Maraude Nb_SOLIDAR' OK | individuel = 7649.0 | final = 7649.0
   ✅ 'Maraude Nb_SOLIDAR2020' OK | individuel = 5706.0 | final = 5706.0
   ✅ 'AEO Nb_FAAD' OK | individuel = 51.0 | final = 51.0
   ✅ 'Structure Nb_formateurs_CRB_2025' OK | individuel = 832.0 | final = 832.0
   ✅ 'Structure Nb_formes_TCAS_2025' OK | individuel = 11268.0 | final = 11268.0
   ✅ 'Formation_grand_public Nb_formes_PREVIC_2025' OK | individuel = 1.0 | final = 1.0
   ✅ 'Formation_grand_public Nb_sessions_PSC_2025' OK | individuel = 7998.0 | final = 7998.0
   ✅ 'Formation_grand_public Nb_sessions_GQS_2025' OK | individuel = 1240.0 | final = 1240.0
   ✅ 'Formation_grand_public Nb_sessions_IPS_2025' OK | individuel = 10252.0 | final = 10252.0
   ✅ 'Formation_grand_public Nb_sessions_IPSEN_2025' OK | individuel = 1016.0 | final = 1016.0
   ✅ 'Formation_grand_public Nb_sessions_PREVIC_2025' OK | individuel = 13.0 | final = 13.0
   ✅ 'Secours Nb_sessions_PSE' OK | individuel = 1488.0 | final = 1488.0
   ✅ 'Secours Nb_sessions_CI' OK | individuel = 319.0 | final = 319.0
   ✅ 'Secours Nb_sessions_FPSE' OK | individuel = 92.0 | final = 92.0
   ✅ 'Secours Nb_PSE1' OK | individuel = 509.0 | final = 509.0
   ✅ 'Secours Nb_PSE2' OK | individuel = 7300.0 | final = 7300.0
   ✅ 'Secours Nb_CI' OK | individuel = 1745.0 | final = 1745.0
   ✅ 'Formation_grand_public Nb_FPSC' OK | individuel = 1069.0 | final = 1069.0
   ✅ 'Formation_grand_public Nb_AGQS' OK | individuel = 134.0 | final = 134.0
   ✅ 'Formation_grand_public Nb_FIPSEN' OK | individuel = 19.0 | final = 19.0
   ✅ 'Secours Taux_recy26_PSE1' OK | individuel = 60.86024693544666 | final = 60.86024693544666
   ✅ 'Secours Taux_recy26_PSE2' OK | individuel = 76.4656971749614 | final = 76.4656971749614
   ✅ 'Secours Taux_recy26_CI' OK | individuel = 65.71521165882733 | final = 65.71521165882733
   ✅ 'Secours Taux_ren25_PSE1' OK | individuel = 26.825586397886674 | final = 26.825586397886674
   ✅ 'Secours Taux_ren25_PSE2' OK | individuel = 25.65339731000367 | final = 25.65339731000367
   ✅ 'Secours Taux_ren25_CI' OK | individuel = 14.419339029748327 | final = 14.419339029748327
   ✅ 'Maraude Nb_benevoles_actifs_formes' OK | individuel = 1539.0 | final = 1539.0
   ✅ 'Secours Taux_IS_actifs' OK | individuel = 77.93759329810777 | final = 77.93759329810777
   ✅ 'Structure Nb_nvx_formes_CRB_2025' OK | individuel = 1472.0 | final = 1472.0
   ✅ 'Dispositifs_d_urgence Structures_menant_activite_TCAU' OK | individuel = 71.0 | final = 71.0
   ✅ 'Dispositifs_d_urgence Structures_menant_activite_PSP' OK | individuel = 58.0 | final = 58.0
   ✅ 'Dispositifs_d_urgence Structures_menant_activite_GQS' OK | individuel = 485.0 | final = 485.0
   ✅ 'Formation_grand_public Nb_formes_PSC_2025' OK | individuel = 65444.0 | final = 65444.0
   ✅ 'Formation_grand_public Nb_formes_GQS_2025' OK | individuel = 9353.0 | final = 9353.0
   ✅ 'Formation_grand_public Nb_formes_IPS_2025' OK | individuel = 81977.0 | final = 81977.0
   ✅ 'Formation_grand_public Nb_formes_IPSEN_2025' OK | individuel = 8642.0 | final = 8642.0

🔎 Vérification DataFrame 24
   ✅ 'Financier Prod_2025' OK | individuel = 92669355.0 | final = 92669355.0
   ✅ 'Financier ResNet_2025' OK | individuel = 2779906.0 | final = 2779906.0
   ✅ 'Financier ResCorrProd_2025' OK | individuel = 3.1278783101257392 | final = 3.1278783101257392
   ✅ 'Financier Prod_2023' OK | individuel = 90179785.56000002 | final = 90179785.56000002
   ✅ 'Financier ResNet_2023' OK | individuel = 5808912.420020001 | final = 5808912.420020001
   ✅ 'Financier ResCorrProd_2023' OK | individuel = 4.858713290389012 | final = 4.858713290389012
   ✅ 'Financier Prod_2024' OK | individuel = 91392120.06 | final = 91392120.06
   ✅ 'Financier ResNet_2024' OK | individuel = 4605741.17 | final = 4605741.17
   ✅ 'Financier ResCorrProd_2024' OK | individuel = 6.124145527106908 | final = 6.124145527106908
   ✅ 'Financier caf_2025' OK | individuel = 11919220.0 | final = 11919220.0
   ✅ 'Financier TresoBrute_2025' OK | individuel = 146027646.0 | final = 146027646.0
   ✅ 'Financier Mois_AvanceTreso_2025' OK | individuel = 2182.7724484242817 | final = 2182.7724484242817
   ✅ 'Textile Produit_2025' OK | individuel = 19523898.0 | final = 19523898.0
   ✅ 'Secours Produits_DPS_2025' OK | individuel = 9739183.0 | final = 9739183.0

🔎 Vérification DataFrame 25
   ✅ 'Formation_grand_public Produits_2025' OK | individuel = 88457195.11 | final = 88457195.11000001

🔎 Vérification DataFrame 26
   ✅ 'nb_Maraude_Pegass' OK | individuel = 19179.0 | final = 19179.0
   ✅ 'Dispositifs_d_urgence Nb_operations' OK | individuel = 2460.0 | final = 2460.0
   ✅ 'Dispositifs_d_urgence Nb_exercices' OK | individuel = 269.0 | final = 269.0
   ✅ 'AEO Structure_activite_fixe' OK | individuel = 126.0 | final = 126.0
   ✅ 'AEO Structure_domiciliation_fixe' OK | individuel = 38.0 | final = 38.0
   ✅ 'AEO Structure_ecrivain_public_fixe' OK | individuel = 46.0 | final = 46.0
   ✅ 'Maraude Nb_benevoles_actifs' OK | individuel = 7305.0 | final = 7305.0
   ✅ 'IS Nb_benevoles_actifs' OK | individuel = 12292.0 | final = 12292.0
   ✅ 'AEO Nb_benevoles_actifs' OK | individuel = 981.0 | final = 981.0

🔎 Vérification DataFrame 27
   ✅ 'Secours Nb_PAPS_2025' OK | individuel = 12970.0 | final = 12970.0
   ✅ 'Secours Nb_DPS_PE_2025' OK | individuel = 28004.5 | final = 28004.5
   ✅ 'Secours Nb_DPS_ME_2025' OK | individuel = 9268.0 | final = 9268.0
   ✅ 'Secours Nb_DPS_GE_2025' OK | individuel = 4258.0 | final = 4258.0
   ✅ 'Secours Nb_DPS_2025' OK | individuel = 54500.5 | final = 54500.5

In [71]:
all_data, all_data_DT = vision_conso(all_data, all_data_DT)

In [72]:
all_data = ajouter_colonnes_taux(all_data, 'Structure Nb_Benevoles')
all_data_DT = ajouter_colonnes_taux(all_data_DT, 'Structure Nb_Benevoles')

In [73]:
all_data = ajouter_colonne_somme(all_data, 'AEO Nb_personnes_domiciliees_crf', 'AEO Nb_PA_dispos_mobiles')
all_data_DT = ajouter_colonne_somme(all_data_DT, 'AEO Nb_personnes_domiciliees_crf', 'AEO Nb_PA_dispos_mobiles')

In [74]:
all_data

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,...,Maraudes Structures_menant_activite,AEO Structures_menant_activite,Formation_grand_public Structures_menant_activite,Dispositifs_d_urgence Taux_formation_TCAU_2025,Dispositifs_d_urgence Taux_formation_TCEO_2025,Dispositifs_d_urgence Taux_formation_PSP_2025,Dispositifs_d_urgence Taux_formation_IRR_2025,Dispositifs_d_urgence Taux_formation_GQS_2025,Structure Taux_formation_CRB,AEO Nb_PA_AEO_AAD
0,5,DELEGATION TERRITORIALE - DT,DT DE L'AIN,1000.0,01053,BOURG EN BRESSE,"3 Rue HENRI DUNANT, 01000 BOURG EN BRESSE",1,1986-12-10 00:00:00,NaT,...,Action menée,Activité AEO en dispositif mobile,Action menée,0.010363,0.000000,0.005181,0.108808,0.124352,0.046632,<NA>
1,109,UNITE LOCALE - UL,UL DU BASSIN BURGIEN,1000.0,01053,BOURG EN BRESSE,"1 Avenue DES BELGES, 01000 BOURG EN BRESSE",1,1870-12-10 00:00:00,NaT,...,Action non menée,Activité AEO en dispositif mobile,Action menée,0.178082,0.041096,0.054795,0.342466,0.424658,0.232877,<NA>
2,135,UNITE LOCALE - UL,UL DES PAYS DE LA VEYLE,1540.0,01457,VONNAS,"Rue ANNE MARIE CROLET, 01540 VONNAS",1,1986-12-10 00:00:00,NaT,...,Action non menée,Activité AEO non menée,Action menée,0.028986,0.000000,0.000000,0.202899,0.304348,0.173913,<NA>
3,3733,UNITE LOCALE - UL,UL DU VAL DE SAONE,1190.0,01305,PONT DE VAUX,"19 Avenue ADRIEN THIERRY, 01190 PONT DE VAUX",1,2008-06-02 00:00:00,NaT,...,Action non menée,Activité AEO non menée,Action menée,0.150943,0.000000,0.018868,0.264151,0.283019,0.603774,<NA>
4,3873,UNITE LOCALE - UL,UL DE PORTE DE LA DOMBES,1600.0,01427,TREVOUX,"94 Allée ANTOINE FINAZ, 01600 TREVOUX",1,2011-02-03 00:00:00,NaT,...,Action non menée,Activité AEO non menée,Action menée,0.037736,0.000000,0.037736,0.150943,0.150943,0.377358,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,3884,DELEGATION TERRITORIALE - DT,DT DE FUTUNA,98610.0,98611,ALO,"MALA'E, 98610 ALO",986,2011-06-08 00:00:00,NaT,...,Action non menée,Activité AEO non menée,Action non menée,0.000000,0.000000,0.000000,0.291667,0.416667,0.041667,<NA>
854,4303,DELEGATION TERRITORIALE - DT,DT DE WALLIS,98600.0,98613,UVEA,"MATA'UTU, 98600 UVEA",986,2014-11-07 00:00:00,NaT,...,Action non menée,Activité AEO non menée,Action non menée,0.043478,0.000000,0.000000,0.043478,0.217391,0.000000,<NA>
855,1285,DELEGATION TERRITORIALE - DT,DT DE TAHITI,98716.0,98736,PIRAE,"233 Rue Pater, 98716 PIRAE",987,1927-07-01 00:00:00,NaT,...,Action non menée,Activité AEO en dispositif mobile,Action non menée,0.000000,0.000000,0.000000,0.000000,0.000000,0.076923,<NA>
856,4730,ANTENNE LOCALE - AL,AL DE KONE,98859.0,98811,KONE,"278 Rue PAUL REUILLARD, 98859 KONE",988,2021-11-19 00:00:00,NaT,...,Action non menée,Activité AEO non menée,Action non menée,0.111111,0.018519,0.185185,0.296296,0.444444,0.203704,<NA>
857,104,DELEGATION TERRITORIALE - DT,DT DE NOUVELLE CALEDONIE,98800.0,98818,NOUMEA,"26 Rue DU DOCTEUR GEORGES COLLARD, 98800 NOUMEA",988,1956-12-10 00:00:00,NaT,...,Action non menée,Activité AEO non menée,Action menée,0.155280,0.046584,0.142857,0.295031,0.431677,0.307453,<NA>

In [75]:
all_data_DT

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,...,Maraudes Structures_menant_activite,AEO Structures_menant_activite,Formation_grand_public Structures_menant_activite,Dispositifs_d_urgence Taux_formation_TCAU_2025,Dispositifs_d_urgence Taux_formation_TCEO_2025,Dispositifs_d_urgence Taux_formation_PSP_2025,Dispositifs_d_urgence Taux_formation_IRR_2025,Dispositifs_d_urgence Taux_formation_GQS_2025,Structure Taux_formation_CRB,AEO Nb_PA_AEO_AAD
0,5,DELEGATION TERRITORIALE - DT,DT DE L'AIN,1000.0,01053,BOURG EN BRESSE,"3 Rue HENRI DUNANT, 01000 BOURG EN BRESSE",1,1986-12-10 00:00:00,NaT,...,2,3,11,0.089981,0.010204,0.026902,0.209647,0.279221,0.253247,<NA>
1,14,DELEGATION TERRITORIALE - DT,DT DE L'AUBE,10000.0,10387,TROYES,"18 Rue LOUIS MORIN, 10000 TROYES",10,1986-12-10 00:00:00,NaT,...,1,1,3,0.122616,0.021798,0.035422,0.313351,0.438692,0.215259,<NA>
2,15,DELEGATION TERRITORIALE - DT,DT DE L'AUDE,11000.0,11069,CARCASSONNE,"Zone artisanale ZAC DE CUCURLIS, 11000 CARCASS...",11,1986-12-10 00:00:00,NaT,...,2,2,3,0.123457,0.012346,0.148148,0.339506,0.456790,0.132716,<NA>
3,4395,DELEGATION TERRITORIALE - DT,DT DE L'AVEYRON,12510.0,12174,OLEMPS,"235 Route DE LA MOULINE, 12510 OLEMPS",12,2017-02-20 00:00:00,NaT,...,1,1,1,0.039024,0.002439,0.000000,0.163415,0.217073,0.036585,<NA>
4,17,DELEGATION TERRITORIALE - DT,DT DES BOUCHES DU RHONE,13004.0,13204,MARSEILLE,"42 Rue KRUGER, 13004 MARSEILLE",13,1986-12-10 00:00:00,NaT,...,6,8,11,0.205442,0.028785,0.112776,0.283517,0.478312,0.335962,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,3668,DELEGATION TERRITORIALE - DT,DT DE ST MARTIN,97150.0,97801,ST MARTIN,"2 Rue DU SOLEIL LEVANT, 97150 ST MARTIN",978,2007-09-26 00:00:00,NaT,...,0,0,1,0.150943,0.000000,0.264151,0.377358,0.452830,0.037736,<NA>
104,3884,DELEGATION TERRITORIALE - DT,DT DE FUTUNA,98610.0,98611,ALO,"MALA'E, 98610 ALO",986,2011-06-08 00:00:00,NaT,...,0,0,0,0.000000,0.000000,0.000000,0.291667,0.416667,0.041667,<NA>
105,4303,DELEGATION TERRITORIALE - DT,DT DE WALLIS,98600.0,98613,UVEA,"MATA'UTU, 98600 UVEA",986,2014-11-07 00:00:00,NaT,...,0,0,0,0.043478,0.000000,0.000000,0.043478,0.217391,0.000000,<NA>
106,1285,DELEGATION TERRITORIALE - DT,DT DE TAHITI,98716.0,98736,PIRAE,"233 Rue Pater, 98716 PIRAE",987,1927-07-01 00:00:00,NaT,...,0,1,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.076923,<NA>
107,104,DELEGATION TERRITORIALE - DT,DT DE NOUVELLE CALEDONIE,98800.0,98818,NOUMEA,"26 Rue DU DOCTEUR GEORGES COLLARD, 98800 NOUMEA",988,1956-12-10 00:00:00,NaT,...,0,0,1,0.148936,0.042553,0.148936,0.295213,0.433511,0.292553,<NA>

# Enregistrement des données

In [84]:
# Entregistrement du DataFrame
save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", gspread_client, all_data, sheet_name = 'UL')
save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", gspread_client, all_data_DT, sheet_name = 'DT')

# save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", client, df_rattachement_court)

📄 Feuille existante 'UL' sélectionnée.
🗑️ Les anciennes données ont été supprimées de la feuille 'UL'
💾 Données sauvegardées dans 'all_data_2025' → feuille 'UL'
    Nombre de lignes : 858
    Nombre de colonnes : 124
📄 Feuille existante 'DT' sélectionnée.
🗑️ Les anciennes données ont été supprimées de la feuille 'DT'
💾 Données sauvegardées dans 'all_data_2025' → feuille 'DT'
    Nombre de lignes : 108
    Nombre de colonnes : 134