In [1]:
# !git config --global user.email "clement.dilasser@croix-rouge.fr"
# !git clone https://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@github.com/clementsouk-aloun-dot/Code-PAT.git

In [2]:
# !gcloud auth application-default login

In [3]:
# !pip install PyPDF2
# !pip install reportlab
# !pip install PyMuPDF tools
# !pip install xlsxwriter

# Imports

In [4]:
# 🔹 Compatibilité Google Colab pour code local
try:
    from google.colab import drive, files
    from google.colab import auth
except ModuleNotFoundError:
    # Crée un faux module google.colab pour que le code ne plante pas
    import types
    drive = types.SimpleNamespace(mount=lambda path: print(f"[Mock] drive.mount({path})"))
    files = types.SimpleNamespace(upload=lambda: print("[Mock] files.upload()"))
    auth = types.SimpleNamespace(authenticate_user=lambda: print("[Mock] auth.authenticate_user()"))

In [5]:
import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
#import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import sys
import io
import re
import shutil
import zipfile

from google.auth import default
from google.cloud import bigquery

import unicodedata
import re
import torch
from sentence_transformers import SentenceTransformer, util
import gc
from functools import reduce

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Imports des fichiers .py

In [6]:
sys.path.append(os.path.abspath("./data")) 

from adherent import *
from alim import *
from domifa import *
from financier import *
from gaia import *
from impact import *
from manuelles import *
from maraude import *
from maraude_manuel import *
from base_contact import*
from mobilite import *
from nomination import *
from pegass import *
from dps import *

from utils import *

# AUTHENTIFICATION

In [7]:
json_key_bq = """
{
  "type": "service_account",
  "project_id": "crf-pat",
  "private_key_id": "74d4d8da82234ba180ecdf6dd77a8aa51c613591",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCxIjoJdp2q4Rs2\nfQbVYcFyH6hRY0n5/m9/MYIE6UsqynGllQqmYrFu9YSVJ50UBiddLR+/mEGHhjAT\nIVvOMsjFUikrwGtWm6u95ENiO5hM0LhOp8sh1mq1Oq/Su8gbFgnEmPC/y5mtaqsB\nR3wszpQmQ39PowEVkERQy1UUdtHKmvnT38cYtJj3jy79NicZZVPYYWW5noiMN1j1\ny/tnzrVuM56rpAAOU0oeqcGwV7GBzYdwfsBZVx7Zf7MjVwehs2TNFfPkYlUwM15M\nHhc2n+HNE7PVRjaOz8z9l3rKiN7jMmXL+MyqLlbSQnyHwpUldV4XnDKxYZVULdgz\nDlqeewtxAgMBAAECggEACp3ajKanXI6RavqjZjatuYFcPUSOMoWleSImgNTaxH3N\nwfbk5IQVzmi4wZfWOlUEFvmVZY5inxTT3NGrBvjUP79k6FJoHJDIAmGkCEc6IaCA\n63XzHtwTGTmjQCYxIC5592aTR2uUkmhKR5FZR/Y5uvFguA01C23SKmWFe+yDNnlp\n6BIWqOAgd4vFHfp9Z05tejVAaNPzvkOknqGvF/Lixpc54hSOPCpRIKJBPAvh61vJ\nvCPrfqmNJhl7nojp2+9UcYDBxoToqMB23p0U9s2xg1ZXRwsunQLHxckm08lmfjhQ\nkdLrqZ6wHhvh7kO7AalzTVQwfc4P4zjZ73D4z3gaYQKBgQDYugB0vC0dkpIxgSf4\n9qguKibtHXUMOtM0giz9z/0QvLCXwOWScXjdnZRuiQgCBIijGwAmWuUWnnsIYOUL\no6FUcADli6Rh1FSNmjIEeYwUIrB/9qancnpcqtN5BCR/tqMU0hjz1YPzNZvmIImm\nGWAIM6mvN4muetS3MzEzeK63vwKBgQDRO4CDLa8FD7ny8WSCe6Vfg0wHEsDpJJeS\nUMx/1TadTDuQ/7N1YvGKjWBIULBGOBMHRXwEtaThJkCDp48n/oOzgLgJLhL9aurU\n7Ro+SB0q7SJhZotgseFhKo8L4X0/6mvw5uCIPdUHiRlKJB29Kgh/rkcet/uBndy0\nAs1+timIzwKBgQCmv7XKG166+iLxY+ZVb7JGkrgQiDGej0QhimcDghu73PIiUJBR\n9GyCVtP1mAlJRCO9GvEqkZThql4PPD3+jo96YBLQiniXrL7BlHoXZ02X0Hjse+IN\nw87Rrb23xrAuc19WjbAVK5qybfTdQvuliLCSnu1XmuucC3XO3txkNd54EQKBgQC7\ndK/i1x8jTb+vZY5DSTwUorGO9MJZHyudLz7ImOHhc9c6RZ0m4oq9M4S7xW7ounxx\n21MNdSBPh9HtIkYj8udT/1LjBqCE4zGZqwQEIN/hAav3z8O30ia2w0Z9wnxQs1oZ\n7v/jkGI36iD6R/lM7UfH/QBDCVsP+bsunAQ4LkRwCQKBgB4yQQmNkjTJZ6ySUVY6\n2ZMS2R/LKf5n5Z1qcGFGo2zlu9EWyLwGQM6nbPSoe12EBgcE/oECcPxhwWPILT6S\naDOF1hJOHmnceY3/RVejlSTqIza392MBrs0PYuHLh4EiuC5X4P9phyRMVUpVhtpx\nCFrEu5J1iEnfi2uzS0zO/q/j\n-----END PRIVATE KEY-----\n",
  "client_email": "svc-pat@crf-pat.iam.gserviceaccount.com",
  "client_id": "104457263935915720424",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/svc-pat%40crf-pat.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""

SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly','https://www.googleapis.com/auth/bigquery']

credentials_bq = service_account.Credentials.from_service_account_info(json.loads(json_key_bq, strict=False), scopes=SCOPES)

In [8]:
PROJECT_ID = "crf-pat"
client = bigquery.Client(project=PROJECT_ID, credentials = credentials_bq)

In [9]:
# Etape 0 : Préparation de l'environnement

CREDENTIALS_JSON = """
{
  "type": "service_account",
  "project_id": "alexandrevalent",
  "private_key_id": "dba39c84ba4135ce5ede6479a186ad8cde499dee",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvGU4ZJFrBwCBb\nu8s4aPA5bQTOKDkPZEVdNyY//RneR6RC9JPrcbfVfIUaQU7A036sfdhDGFKJbw20\nTZ55fafcH9yCMiUO+Nzek0eogON4TXrXsh8UFtdw8BOuaVkFitU5yg8kFhTnEZtd\ntPfZHW3Aqhd/aDoTOBNgRuF/hVTKQ2ytbCbE77fL2/pz9kvpZ2Zrz3u1lmksSJls\nHIolNwX9R05YqmrkpZ/TMAULFk4bT0VRQng5pmN9AeB61eJLWhlLaEdeu79NWV4B\n7tZd6RzzTFors804aJkmXHM63VRtvGD0UlR0O7w1QlI3ymUxpy5hrjbz6n9bmpMI\nfebvydLnAgMBAAECggEADipn7RTJ2t7mP0WkHT4wIRU2zE7ovtwH2JC7oXWigB8f\npOMQjH24t6bJReR+sI7rspzDwDnZg5DedPXKml2WFPLm7gmMgfeUNtWHeJRk0rjB\n9W1NolxutY5WqUeQkig3M+Oq8epvano8LYqUepYs6OdZ207dU+y3dJSHbb+lqm9D\ntQZR2oBj7W1iZ8fJ+SQLSjU5BztS1CvWuayRd/tLd9Spp0NUn5uQFTKwel9Gazmz\n28IsPPm6SudplFhaGd4kCPvhcg0jGEKe61VYdgHoBzp+EXRWXUvQ+SbMafXtMvoB\nLoUH4X3creKzJQKXnjlDpAzRHMYhJTvHinHXaggdcQKBgQDcJszFOECfSovXFZNq\nMyQOWbesyDb2OQhJLFZCD2QraZm3jPaIPeMfFkmFAumcVal6EzpR5IE8g9jBuLo+\ng6j3NTo5jbGO9WEn4361yEotb+S8t3/DTHvWqXBK7HdUB/KHlyGtctm8yErdMZQB\nvzo03aTwwStNTeFG8GzT1Nd7JQKBgQDLnHIMbx9iAG3K21XCq0Dot2Q63hklJC26\nsJlrTkdXMOIlhpwJ6LTOJe2paHbR56IrKOHQCuLxQFhRd8Eidz1ahjO7D8fKr/TG\nS8/V32FrpONyxhKinLsccSb86S3vvpKCI265z5EEjk/1qnx3TOo6oqA/2DQLv0Q4\nYinmNSOeGwKBgHGjYY3n9IuE6lwy2e42ycTSkNoSWzSLyfgjd78PvNAf6WXy0IsR\nDvzL/1U2ZKn7GclWxYLiJce78xZEKXb9dSluA0kUF/RIO0dgydZBtfBwUq0LN1rz\nTvVGbx1tpEbu90UAQTUMFNK6vNIitliUghIp2usfex+jNMbuce6Cblw1AoGBAKDH\n1gtZiFeT7R7d2jfRkXzyrBQMI6D/k5izMULZ2l3QfROS2w68EmIi8yvuEL2qApXA\nP6hPoGtPGy6huQHlVK5yANF7IZI9JbWcUe8Z6MzetLiCDl8YEmzgMSBPZXXGb9yR\n7DKP5HzLf/qG+KggNWm913ry2A5ap506bsmZNpn3AoGBAM6vvI9tb+AcNfd4ewmY\nAWSb4GLliRTaBIGHYmotfyBEBWpXZq2/0JG32RRf3rYUJWWn/r7K+zrRUqeMwlD+\nz7GuSU+OaSDzYj7fwDyuxOwTJMLrh+AkKbUYBsMF7YH1qIRjBjKNdj1LOznASQMe\nu1E4sNa9RRRujbQw4AEP3Xjl\n-----END PRIVATE KEY-----\n",
  "client_email": "crf-slidemanager@alexandrevalent.iam.gserviceaccount.com",
  "client_id": "101959630014487618959",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/crf-slidemanager%40alexandrevalent.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly']


# Authentification
credentials = service_account.Credentials.from_service_account_info(json.loads(CREDENTIALS_JSON, strict=False), scopes=SCOPES)

# Initialisation des services
slides_service = build('slides', 'v1', credentials=credentials)
drive_service = build('drive', 'v3', credentials=credentials)
gspread_client  = gspread.authorize(credentials)

# Variables globales

In [10]:
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

In [11]:
mapping_df

,Source,nom_table,nom_variable,rename,Description,Type de valeurs,Présent extract DSI ?,Commentaires
0,Annuaire structure,AS_Actions_par_structure,N_structure,n_structure,Identifiant de la structure,INT,Optionnel,NaN
1,Annuaire structure,AS_Actions_par_structure,Type_de_lien,action_statut,Action menée/ Non menée,VARCHAR,Optionnel,NaN
2,Annuaire structure,AS_Actions_par_structure,Groupe_action,groupe_action_ben,Regroupement / famille d’actions,VARCHAR,Optionnel,NaN
3,Annuaire structure,AS_Actions_par_structure,Action,lib_action_ben,Libellé de l’action précise,VARCHAR,Optionnel,NaN
4,Annuaire structure,AS_Actions_par_structure,Date_demarrage_action_dans_la_structure,date_demarrage_action_structure,Date à laquelle l’action a effectivement démar...,DATE,Optionnel,NaN
...,...,...,...,...,...,...,...,...
242,GAIA ?,crf_pat_2025_rattachement_action,action_menee_date_fin,NaN,NaN,DATE,Présent & bon format,NaN
244,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_nivol_fk,NaN,NaN,STR,Présent & bon format,NaN
245,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_structure_id_fk,NaN,NaN,INT,Présent & bon format,NaN
246,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_date_debut,NaN,NaN,DATE,Présent & bon format,NaN
247,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_date_fin,NaN,NaN,DATE,Présent & bon format,NaN

# CHARGEMENT DE TOUTES LES DONNEES PAR TABLE

## 0. Ref_structure

In [12]:
df_ref_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw/').worksheet('Feuille 1'))

In [13]:
df_ref_structure = renommer_par_nom_table(df_ref_structure, "AS_Informations_structures", mapping_df)
df_ref_structure['n_structure'] = df_ref_structure['n_structure'].astype(int)
df_ref_structure = df_ref_structure[df_ref_structure["type_structure"].isin(["UNITE LOCALE - UL", "DELEGATION TERRITORIALE - DT", 'IMPLANTATION LOCALE HORS AL - IL', 'ANTENNE LOCALE - AL','INSTANCES NATIONALES - IN'])]
df_ref_structure.head()

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,Structure_de_rattachement,Structure_de_rattachement.1,DT_de_rattachement,lon,lat
0,5,DELEGATION TERRITORIALE - DT,DT DE L'AIN,1000.0,01053,BOURG EN BRESSE,"3 Rue HENRI DUNANT, 01000 BOURG EN BRESSE",1,1986-12-10 00:00:00,NaT,4457 - DR AUVERGNE RHONE ALPES,DT 5,5 - DT DE L'AIN,5.228792,46.212687
1,109,UNITE LOCALE - UL,UL DU BASSIN BURGIEN,1000.0,01053,BOURG EN BRESSE,"1 Avenue DES BELGES, 01000 BOURG EN BRESSE",1,1870-12-10 00:00:00,NaT,5 - DT DE L'AIN,UL 109,5 - DT DE L'AIN,5.231911,46.207112
2,135,UNITE LOCALE - UL,UL DES PAYS DE LA VEYLE,1540.0,01457,VONNAS,"Rue ANNE MARIE CROLET, 01540 VONNAS",1,1986-12-10 00:00:00,NaT,5 - DT DE L'AIN,UL 135,5 - DT DE L'AIN,4.988173,46.215632
3,3733,UNITE LOCALE - UL,UL DU VAL DE SAONE,1190.0,01305,PONT DE VAUX,"19 Avenue ADRIEN THIERRY, 01190 PONT DE VAUX",1,2008-06-02 00:00:00,NaT,5 - DT DE L'AIN,UL 3733,5 - DT DE L'AIN,4.940884,46.430076
4,3873,UNITE LOCALE - UL,UL DE PORTE DE LA DOMBES,1600.0,01427,TREVOUX,"94 Allée ANTOINE FINAZ, 01600 TREVOUX",1,2011-02-03 00:00:00,NaT,5 - DT DE L'AIN,UL 3873,5 - DT DE L'AIN,4.788434,45.937566

In [14]:
df_ref_structure_DT = df_ref_structure[df_ref_structure['nom_structure'].str.contains('DT')].astype(str)
df_ref_structure_DT['n_structure'] = df_ref_structure['n_structure'].astype(int)

### 0.1 rattachement_court

In [15]:
rattachement_court = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU/edit?usp=sharing').worksheet('Feuille 1'))

## 1. PEGASS

In [16]:
df_ref_activite_benevole, df_pegass_activite, df_pegass_activite_seance, df_pegass_activite_seance_inscription,ref_structure1,df_rattachement_court,df_ref_action_groupe_action = import_tables_PEGASS(client)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 2. GAIA

In [17]:
df_gaia_rattachement_benevole = clean_gaia(client, df_ref_structure)
df_nivols_gaia = import_table_GAIA_date_fixe(client)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 3. NOMINATION

In [18]:
df_ref_nomination, df_nomination = clean_nomination(client, df_ref_structure)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 4. IMPACT

In [19]:
df_ref_impact, df_impact = clean_impact(client,df_ref_structure)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 5. Données financières

In [20]:
financier_2023_2024 = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c')
financier_2025 = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1esF1OgTGD_HtkJVZq0ZDsqXs-7rzeRK2NMp0fMabMpM/')

Financier DPS & FGP

In [21]:
financier_DPS = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/145xeh1LkmYzTSW2zeAwHqmLyjmw_tobICHf-oXZmUFI/').worksheet('Base Smtw 03.03.25'))

In [22]:
financier_FGP = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13J2zfbmLTILtGYtE_sM-ME8B0pNEwBeGJ1Gg5vKLeOc/').worksheet('DT_Prod'))

## 6. Mobilité

In [23]:
mobilite = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1dvxT58WR-FqdT-4r-A9ca4vaA9FG7IXHJJaTbnjio8A/')

In [24]:
df_mobilite = filtres_mobilite(mobilite,mapping_df, df_ref_structure)

## 7. Données manuelles

### 7.1 OCR

In [25]:
df_OCR = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ccRoyPycFDwvQvacvmHjfE87LtnlzUgtoRbITkC0pVQ/').worksheet('Feuille 1'),evaluate_formulas=True)

In [26]:
df_OCR

,Info Completes,Reconduction,Année,Statut,Nom de la Région,Nom du Département,Numéro du Département,Structure CRf\n(Ville),Nom Commune de l'établissement,Académie
0,NaN,0.0,2026-2027,Projet,NaN,NaN,NaN,NaN,NaN,NaN
1,NON,0.0,2026-2027,Projet,Occitanie,Gard,30,Cèze-Auzonnet,NaN,NaN
2,NON,0.0,2025-2026,Idée,Occitanie,Gard,30,UL Nîmes,NaN,NaN
3,OUI,0.0,2025-2026,En cours,Occitanie,Lot,46,DT46,Vayrac,Toulouse
4,NON,0.0,2025-2026,Idée,Occitanie,Tarn-et-Garonne,82,DT82,Pech Blanc,NaN
...,...,...,...,...,...,...,...,...,...,...
557,OUI,1.0,2021-2022,Terminée,Normandie,Calvados,14,DT 14,Aunay sur Odon,Normandie
558,OUI,1.0,2020-2021,Terminée,Normandie,Calvados,14,DT 14,Aunay sur Odon,Normandie
559,NON,1.0,2020-2021,Terminée,Normandie,Calvados,14,NaN,NaN,Normandie
560,OUI,0.0,2019-2020,Terminée,Normandie,Calvados,14,DT 14,Aunay sur Odon,Normandie
561,OUI,0.0,2019-2020,Terminée,Normandie,Eure,27,DT 27,Gisors,Normandie

### 7.2 PST

In [27]:
df_PST = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1yifNna4Hsn5RihkRg50g9h1yKjuRjfolrjsWonEHnrQ').worksheet('Données'))

### 7.3 Déclenchements

In [28]:
df_declenchement = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1y9jehT5fStcEWCF0pxAP7BdiI62VY3JM_hQzFftbcZA').worksheet('Feuille 1'))

### 7.4 Redcall

In [29]:
df_redcall = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1EQzq0K8RY2Liyq-jtggX0bTlnOk9cwUTmf4t6c5_CiI').worksheet('structure-stats_2025-01-01_2025-12-31_min-1 (1)'))

### 7.5 CHAI CHU CMCC

In [30]:
df_CAICHUCMCC = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/12nZY2leRCMn71NGAEUUtA0Pes598gOfeufDStxSCcnY').worksheet('Toutes données'))

### 7.6 Conventions

In [31]:
df_conventions = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1u6E6SUydE7zB1bbcjPzjDt9m5YtGszl0MATPbDQeOhg').worksheet('Feuille 1'))

### 7.7 Textile

In [32]:
df_raw_Textile_c = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1QYuKZo5lVI0HN4BWtk0v7bVFY2a2p4c72a0gU0ltWac/').worksheet('Liste des PAV'))

df_raw_ProdResTextile_c = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1l7KMjiav3usmLVJIbE2uENfNQCeQuxVeU1h13Cep3qk/",sheet_name="Compil Détail",header_row=7)

✅ Chargement des données réalisées
    Sheet : Résultat Textile_2020-2024_V1_13 févr 2025
    Feuille  : Compil Détail (1338 lignes et 29 colonnes)

### 7.8 DOMIFA

In [33]:
df_domiciliation, df_rattachement_court = clean_domifa(client,df_ref_structure)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\utils.py:162: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ref['nom_structure'] = df_ref['nom_structure'].fillna('').astype(str)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 862.42it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

### 7.9 Alim

In [34]:
df_alim = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1bk_ktsT9hBPJS5EY70teq80NzOs_cm3JfrRkX4AYTF4/edit?gid=0#gid=0")

✅ Chargement des données réalisées
    Sheet : Liste U2A a jour - 21/01/2026
    Feuille 1 : Feuille 1 (628 lignes et 10 colonnes)

### 7.10 DPS

In [35]:
df_dps_source = df_conventions.copy()

### 7.11 Adherent

In [36]:
df_adherent = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1hsk3Xp2IrwnUs59sgWjhT9E9vEsw4TN2WT3nKejlBOE/edit?usp=drive_link")

✅ Chargement des données réalisées
    Sheet : exportAdherents (1) (1)
    Feuille 1 : exportAdherents (1) (1).csv (48300 lignes et 25 colonnes)

### 7.12 Préparation

In [37]:
# DPS a pour source le fichier conventions
df_dps = clean_dps(df_dps_source)

df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions, df_raw_Textile, df_duo_clean = clean_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement, df_redcall, df_CAICHUCMCC, df_conventions, df_raw_Textile_c, df_ref_structure)
df_alim = clean_alim(df_alim)
df_adherent = clean_adherent(df_adherent)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\dps.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Departement"] = df["Departement"].str.replace(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\manuelles.py:96: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['Grand Total', 'Exercice']] = df[['Grand Total', 'Exercice']].fillna(0)
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\manuelles.py:165: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Département"] = df["Département"].str.replace(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\manuelles.py:280: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Departement"] = df["Departement"].str.replace(

Point d'apport possible :  ['Boutique - La Boutique' 'Conteneur' 'Vestiaire' 'Boutique  - Mobile'
 'Autres' 'Boutique - Bébé' 'Boutique - Chez Henry' 'Ressourcerie CRi'
 'Boutique - Recylcerie / Meuble' 'Déchetterie' 'conteneur']

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\data\adherent.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_adherent["Année de l'adhésion du contact"] = pd.to_numeric(df_adherent["Année de l'adhésion du contact"], errors='coerce')

Unique values in 'Année de l'adhésion du contact': [2025]
Data type of 'Année de l'adhésion du contact': int64
Taille du DataFrame après suppression des doublons : (47424, 4)

## 8. Maraudes

In [38]:
# 1) import
df_maraude, df_rattachement_court = import_maraude(client)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

In [39]:
#~rattachement successif
ref_structure_m , c , rattachement_successif, df_maraude = apply_rattachement_successif(df_ref_structure, df_maraude)

In [40]:
# 3) ✅ Filtre : on CHANGE df_maraude ici
df_maraude = filter_maraude_on_ref_structure(
    df_maraude,
    ref_structure_m,
    col_maraude="maraude_structure_id_fk",
    col_ref="n_structure",
    verbose=True
)

📌 Filtre structures ref: 114,538/116,527 lignes conservées (supprimées: 1,989).

In [41]:
# 3) clean/prep
df_nb_personnes_rencontrees_sigma, df_Nb_maraudes_SIGMA = clean_maraudes(df_maraude)

Données manuelles

In [42]:
#Import données maraude manuelles
df_Maraude_donnees_manuelles, df_rattachement_court_m = Import_Maraude_manuel(client,df_ref_structure)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1289.63it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

## 9. Base Contact

In [43]:
df_formation_session_resultat, df_formation_count_session_2025, df_formation_session_resultat_fpg = clean_base_contact(client, df_ref_structure)

c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\dilasserc\Documents\vscode_test\Code-PAT\.venv\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

# FUSION DES TABLES

## 1. Fusion NOMINATION

In [44]:
df_NOMINATION = fusion_nomination(df_nomination, df_ref_nomination)

## 2. Fusion IMPACT

In [45]:
df_IMPACT = fusion_impact(df_impact, df_ref_impact)

Nombre de lignes après filtre 2025 : 388817

## 3. Fusion DOMIFA

In [46]:
df_domiciliation = pd.merge(df_domiciliation, df_rattachement_court, on='n_structure', how="left") #a conserver dans le code principal

# Calcul des indicateurs

## PEGASS

In [47]:
pegass_output = calcul_PEGASS_indicateurs(df_ref_structure,
    ref_structure1,
    df_ref_action_groupe_action,
    df_ref_activite_benevole,
    df_pegass_activite,
    df_pegass_activite_seance,
    df_pegass_activite_seance_inscription,
    df_rattachement_court,
    df_nivols_gaia
)

In [48]:
df_pegass_ben_activite_synthetique = pegass_output["df_pegass_ben_activite_synthetique"]
Indics_pegass_DT = pegass_output["Indics_pegass_DT"]
Indics_pegass_DT = add_nb_benevoles_DT_distincts(
    Indics_pegass_DT,
    df_pegass_ben_activite_synthetique,
    df_rattachement_court
)

## GAIA

In [49]:
nb_benevoles = indicateurs_gaia(df_gaia_rattachement_benevole)
nb_nvx_benevoles = indicateurs_gaia_nvx(df_gaia_rattachement_benevole)
nb_benevoles_DT = indicateurs_gaia_DT(nb_benevoles,rattachement_court)
nb_nvx_benevoles_DT = indicateurs_gaia_nvx_DT(nb_nvx_benevoles, rattachement_court)

Nombre de structures agrégées : 836
Nombre total de bénévoles uniques : 82268
Nombre de structures agrégées : 757
Nombre total de nouveaux bénévoles uniques : 16896
Nombre de structures agrégées : 108
Nombre total de bénévoles uniques DT : 80764
Nombre de structures agrégées : 106
Nombre total de nouveaux bénévoles uniques DT : 16653

## NOMINATION

- RTAEO & RLAEO
- RTOCR & RLOCR

In [ ]:
referents_AEO = indicateurs_nomination_AEO(df_NOMINATION, annee=2025,df_nivols_gaia)
referents_OCR = indicateurs_nomination_OCR(df_NOMINATION, annee=2025,df_nivols_gaia)
referents_AEO_DT = indicateurs_nominationAEO_DT(referents_AEO, rattachement_court)
referents_OCR_DT = indicateurs_nominationOCR_DT(referents_OCR, rattachement_court)

TypeError: indicateurs_nomination_AEO() missing 1 required positional argument: 'df_nivols_gaia'

## IMPACT

- Nombre d'agréments territoriaux (Dispos d'urgence)
- Nombre de personnes prises en charge (Dispos d'urgence)

In [ ]:
IMPACT_ppc = indicateurs_impact_ppc(df_IMPACT)
IMPACT_agrementAB = indicateurs_impact_agrementAB(df_IMPACT)
IMPACT_agrementDPS = indicateurs_impact_agrementDPS(df_IMPACT)
IMPACT_ppc_DT = indicateurs_IMPACTppc_DT(IMPACT_ppc, rattachement_court)
IMPACT_agrementAB_DT = indicateurs_IMPACTagrementAB_DT(IMPACT_agrementAB, rattachement_court)
IMPACT_agrementDPS_DT = indicateurs_IMPACTagrementDPS_DT(IMPACT_agrementDPS, rattachement_court)

## Financier

In [ ]:
df_financier, df_financier_DT,financier = import_clean_donnees_financieres_bigquery(financier_2025,financier_2023_2024,df_ref_structure, mapping_df)

In [ ]:
df_financier_DT

In [ ]:
df_financier

In [ ]:
# Vérifications données financières
#verifications_financiers(df_financier, df_financier_DT, df_ref_structure, financier, financier_2025)

In [ ]:
df_Secours_ProduitsDPS = indicateur_financier_DPS(financier_DPS, df_ref_structure)
df_financier_DPS_DT = financier_DPS_DT(df_Secours_ProduitsDPS, rattachement_court)
df_financier_FGP_DT = indicateur_financier_FGP(financier_FGP, df_ref_structure)
#df_inancier_FGP_DT = financier_FGP_DT(df_financier_FGP, rattachement_court)

## Mobilité


Indicateurs qui nécessitent seulement les données mobilité :

- Nb de structures menant une activité AEO/AAD mobile
- Nombre de personnes accompagnées par des dispositifs AEO/AAD mobiles
<br>
Indicateurs qui nécessitent une fusion avec données AEO/AAD :

- Nombre de bénévoles impliqués dans les activités AEO ou AAD
- Nombre de bénévoles impliqués dans les activités AEO ou AAD

In [ ]:
df_mobilite_DT = indicateurs_mobilite(df_mobilite, df_ref_structure, 'DT_de_rattachement')
df_mobilite_DT_UL = indicateurs_mobilite(df_mobilite, df_ref_structure, 'n_structure')

In [ ]:
verifier_colonne_structure(df_mobilite_DT, "n_structure", df_ref_structure)

In [ ]:
verifier_colonne_structure(df_mobilite_DT_UL, "n_structure", df_ref_structure)

## Données manuelles

In [ ]:
df_OCR_Nb_deployees, df_Dispositifs_d_urgence_PST, df_declenchement3, df_redcall2, df_CAICHUCMCC_VF, df_conventions2, df_raw_Textile, df_DUO = indicateurs_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions, df_raw_Textile, df_duo_clean, df_ref_structure)

Nb_OCR_DT,RedCall_DT = OCR_RedCall_DT(df_OCR_Nb_deployees, df_redcall2, rattachement_court)
df_Textile_DT = Textile_DT(df_raw_Textile, rattachement_court)

# ALIM
df_alim_U2A_sans_doublons, df_alim_epicerie_sociale, df_alim_accueil_alimentaire, df_alim_crsr = indicateurs_alim(df_alim, df_ref_structure)
df_alim_U2A_DT, df_alim_epicerie_sociale_DT, df_alim_accueil_alimentaire_DT, df_alim_crsr_DT = indicateurs_alim_DT(df_alim_U2A_sans_doublons, df_alim_epicerie_sociale, df_alim_accueil_alimentaire, df_alim_crsr, rattachement_court)

# ADHERENT
df_adherent = indicateurs_adherent(df_adherent, df_ref_structure)
df_adherent_DT = indicateurs_adherent_DT(df_adherent, rattachement_court)

# DOMIFA
df_personnes_domiciliees_struct, df_personnes_domiciliees_DT = indicateurs_domifa(df_domiciliation)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4726.26it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6889.29it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5976.28it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6997.19it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6208.60it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 8024.02it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7104.31it/s]
BertModel LOAD REPORT from: models/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

KeyError: "['DT_de_rattachement'] not in index"

In [ ]:
verifier_colonne_structure(df_OCR_Nb_deployees, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Dispositifs_d_urgence_PST, "n_structure", df_ref_structure)
verifier_colonne_structure(df_declenchement3, "n_structure", df_ref_structure)
verifier_colonne_structure(df_redcall2, "n_structure", df_ref_structure)
verifier_colonne_structure(df_CAICHUCMCC_VF, "n_structure", df_ref_structure)
verifier_colonne_structure(df_conventions2, "n_structure", df_ref_structure)
verifier_colonne_structure(df_DUO, "n_structure", df_ref_structure)


# TEXTILE
verif_textile(df_raw_Textile_c, df_raw_ProdResTextile_c, df_raw_Textile, df_Textile_DT,df_raw_ProdResTextile, df_Textile_financier_DT, df_ref_structure, rattachement_court)

# DOMIFA

verifs_domifa(client, df_personnes_domiciliees_struct, df_personnes_domiciliees_DT, df_ref_structure, df_rattachement_court)

## Maraudes

In [ ]:
(
    df_Nb_maraudes_SIGMA_struct,
    df_Nb_maraudes_SIGMA_DT,
    df_nb_contacts_SIGMA_struct,
    df_nb_contacts_SIGMA_DT,
    df_personnes_diff_base,                 # <- nouveau (base par bénéficiaire)
    df_nb_personnes_rencontrees_SIGMA_struct,
    df_nb_personnes_rencontrees_SIGMA_DT
) = indicateurs_maraude(
    df_nb_personnes_rencontrees_sigma,
    df_Nb_maraudes_SIGMA,
    df_rattachement_court
)

In [ ]:
verifier_colonne_structure(df_Nb_maraudes_SIGMA_struct, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Nb_maraudes_SIGMA_DT, "DT_de_rattachement", df_ref_structure)
verifier_colonne_structure(df_nb_contacts_SIGMA_struct, "n_structure", df_ref_structure)
verifier_colonne_structure(df_nb_contacts_SIGMA_DT, "DT_de_rattachement", df_ref_structure)
verifier_colonne_structure(df_nb_personnes_rencontrees_SIGMA_struct, "n_structure", df_ref_structure)
verifier_colonne_structure(df_nb_personnes_rencontrees_SIGMA_DT, "DT_de_rattachement", df_ref_structure)

df_maraude_verif= prep_nb_personnes_rencontrees_sigma(df_maraude, filtre_annee_fn=None)

df_maraude_verif= add_nb_personnes(df_maraude_verif,
                     out_col="nb personnes",
                     cols=None,
                     col_typologie="maraude_rencontre_typologie")

In [ ]:
run_verif_maraude(
    df_Nb_maraudes_SIGMA_struct=df_Nb_maraudes_SIGMA_struct,
    df_Nb_maraudes_SIGMA_DT=df_Nb_maraudes_SIGMA_DT,
    df_nb_contacts_SIGMA_struct=df_nb_contacts_SIGMA_struct,
    df_nb_contacts_SIGMA_DT=df_nb_contacts_SIGMA_DT,
    df_nb_personnes_rencontrees_SIGMA_struct=df_nb_personnes_rencontrees_SIGMA_struct,
    df_nb_personnes_rencontrees_SIGMA_DT=df_nb_personnes_rencontrees_SIGMA_DT,
    df_Nb_maraudes_SIGMA=df_Nb_maraudes_SIGMA,
    df_maraude_verif=df_maraude_verif,
    df_personnes_diff_base=df_personnes_diff_base,
)

Données manuelles maraude

In [ ]:
#Calcul données maraude manuelles
df_Maraude_donnees_manuelles_DT_2, df_Maraude_donnees_manuelles_structure_2 = calcul_indic_maraude_manuelles(df_ref_structure, df_Maraude_donnees_manuelles, df_rattachement_court_m)

#Verif données maraude manuelles
check_maraude_sums( df_Maraude_donnees_manuelles, df_Maraude_donnees_manuelles_DT_2)
check_maraude_sums( df_Maraude_donnees_manuelles, df_Maraude_donnees_manuelles_structure_2)

## Base contact

In [ ]:
# Indicateurs
indicateurs_base_contact, indicateurs_base_contact_DT = indicateurs_base_contact(client, df_formation_session_resultat, df_formation_count_session_2025, df_formation_session_resultat_fpg, df_ref_structure)
indicateurs_base_contact_DT = correction_indic_BC_DT(df_ref_structure, indicateurs_base_contact, indicateurs_base_contact_DT)

## DPS

In [ ]:
df_indicateurs_dps = indicateurs_dps(df_dps, df_ref_structure)

In [ ]:
verifications_dps(df_dps_source, df_indicateurs_dps)

# Création du DataFrame final

La liste de tous les dataframes à fusionner sur df_ref_structure

In [ ]:
# On ne filtre pas les implantations locales avant à cause du rattachement successif
df_ref_structure = df_ref_structure[df_ref_structure["type_structure"].isin(["UNITE LOCALE - UL", "DELEGATION TERRITORIALE - DT", 'ANTENNE LOCALE - AL','INSTANCES NATIONALES - IN'])]

In [ ]:
liste_df_a_fusionner_toutes_structures = [nb_benevoles,nb_nvx_benevoles,referents_AEO,referents_OCR,IMPACT_ppc,df_DUO,IMPACT_agrementAB, IMPACT_agrementDPS,
                                          df_mobilite_DT_UL,df_OCR_Nb_deployees, df_redcall2,
                                          df_raw_Textile, df_alim_U2A_sans_doublons, df_alim_epicerie_sociale,
                                          df_alim_accueil_alimentaire, df_alim_crsr, df_adherent, df_personnes_domiciliees_struct,df_Maraude_donnees_manuelles_structure_2, indicateurs_base_contact,
                                          df_financier,df_Secours_ProduitsDPS, df_raw_ProdResTextile,
                                          pegass_output['Indics_pegass_struct'], df_indicateurs_dps]

liste_df_a_fusionner_DT = [nb_benevoles_DT,nb_nvx_benevoles_DT,referents_AEO_DT,referents_OCR_DT,IMPACT_ppc_DT,df_DUO,
                           IMPACT_agrementAB_DT, IMPACT_agrementDPS_DT,df_mobilite_DT,Nb_OCR_DT,RedCall_DT,df_Dispositifs_d_urgence_PST, df_declenchement3,
                           df_CAICHUCMCC_VF, df_conventions2,
                           df_Textile_DT, df_alim_U2A_DT, df_alim_epicerie_sociale_DT, df_alim_accueil_alimentaire_DT, df_alim_crsr_DT, df_adherent_DT,
                           df_personnes_domiciliees_DT, df_Maraude_donnees_manuelles_DT_2, indicateurs_base_contact_DT,
                           df_financier_DT,df_financier_DPS_DT,df_financier_FGP_DT, df_Textile_financier_DT,Indics_pegass_DT, df_indicateurs_dps]

In [ ]:
all_data, all_data_DT, liste_df_a_fusionner_toutes_structures_processed, liste_df_a_fusionner_DT_processed = traitement_all_data(liste_df_a_fusionner_toutes_structures, liste_df_a_fusionner_DT, df_ref_structure,df_ref_structure_DT)

In [ ]:
report = check_sums_against_final(
    df_final=all_data,
    list_of_dfs=liste_df_a_fusionner_toutes_structures,
    key_col="n_structure",
    atol=1e-6
)

In [ ]:
report = check_sums_against_final(
  df_final=all_data_DT,
  list_of_dfs=liste_df_a_fusionner_DT,
  key_col="n_structure",
  atol=1e-6
  )

In [ ]:
all_data, all_data_DT = vision_conso(all_data, all_data_DT)

In [ ]:
all_data = ajouter_colonnes_taux(all_data, 'Structure Nb_Benevoles')
all_data_DT = ajouter_colonnes_taux(all_data_DT, 'Structure Nb_Benevoles')

In [ ]:
all_data = ajouter_colonne_somme(all_data, 'AEO Nb_personnes_domiciliees_crf', 'AEO Nb_PA_dispos_mobiles')
all_data_DT = ajouter_colonne_somme(all_data_DT, 'AEO Nb_personnes_domiciliees_crf', 'AEO Nb_PA_dispos_mobiles')

In [ ]:
all_data

In [ ]:
all_data_DT

# Enregistrement des données

In [ ]:
# Entregistrement du DataFrame
#save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", gspread_client, all_data, sheet_name = 'UL')
#save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", gspread_client, all_data_DT, sheet_name = 'DT')

# save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", client, df_rattachement_court)