In [9]:
# !git config --global user.email "clement.dilasser@croix-rouge.fr"
# !git clone https://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@github.com/clementsouk-aloun-dot/Code-PAT.git

In [10]:
# !gcloud auth application-default login

In [11]:
# !pip install PyPDF2
# !pip install reportlab
# !pip install PyMuPDF tools
# !pip install xlsxwriter

# Imports

In [12]:
# 🔹 Compatibilité Google Colab pour code local
try:
    from google.colab import drive, files
    from google.colab import auth
except ModuleNotFoundError:
    # Crée un faux module google.colab pour que le code ne plante pas
    import types
    drive = types.SimpleNamespace(mount=lambda path: print(f"[Mock] drive.mount({path})"))
    files = types.SimpleNamespace(upload=lambda: print("[Mock] files.upload()"))
    auth = types.SimpleNamespace(authenticate_user=lambda: print("[Mock] auth.authenticate_user()"))

In [13]:
import traceback
import sys
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
#from fitz import PyMuPDF
from PIL import Image as PILImage
import numpy as np
import seaborn as sns
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import re
import shutil
import zipfile
from google.auth import default
from google.cloud import bigquery
import unicodedata
import torch
from sentence_transformers import SentenceTransformer, util
import gc
from functools import reduce

Imports des fichiers .py

In [14]:
from utils import *

sys.path.append(os.path.abspath("./data")) 


from base_contact_formations_initiales import *
from Base_contact_retravail import *
from Base_contact_session_et_gd_public import * 

from adherent import *
from alim import *
from domifa import *
from financier import *
from gaia import *
from impact import *
from manuelles import *
from maraude import *
#from base_contact.base_contact import *
#from base_contact.pofo import *
from mobilite import *
from nomination import *
from pegass import *
from dps import *
from main_merge import *
from indicateurs_ambition_pat import *
from Indicateurs_composites import *


sys.path.append(os.path.abspath("./checks")) 

from helpers import *

In [15]:
import importlib
import Indicateurs_composites 

importlib.reload(Indicateurs_composites)

from Indicateurs_composites   import *

# AUTHENTIFICATION

In [16]:
json_key_bq_url = r'service_account\s_acc.json'

with open(json_key_bq_url, 'r') as f:
    json_key_bq = json.load(f)

SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly','https://www.googleapis.com/auth/bigquery']

credentials_bq = service_account.Credentials.from_service_account_info(json_key_bq, scopes=SCOPES)

In [17]:
PROJECT_ID = "crf-pat"
client = bigquery.Client(project=PROJECT_ID, credentials = credentials_bq)

In [18]:
# Etape 0 : Préparation de l'environnement

CREDENTIALS_JSON_url = r'service_account\old.json'

with open(CREDENTIALS_JSON_url, 'r') as f:
    CREDENTIALS_JSON = json.load(f)
SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly']


# Authentification
credentials = service_account.Credentials.from_service_account_info(CREDENTIALS_JSON, scopes=SCOPES)

# Initialisation des services
slides_service = build('slides', 'v1', credentials=credentials)
drive_service = build('drive', 'v3', credentials=credentials)
gspread_client  = gspread.authorize(credentials)

# Variables globales

In [19]:
# Define target date and year once for all functions
TARGET_DATE = "2026-05-31"
TARGET_YEAR = pd.Timestamp(TARGET_DATE).year

# Uniquement utile pour base contact pour le moment
half_year = True

mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

In [20]:
mapping_df

,Source,nom_table,nom_variable,rename,Description,Type de valeurs,Présent extract DSI ?,Commentaires
0,Annuaire structure,AS_Actions_par_structure,N_structure,n_structure,Identifiant de la structure,INT,Optionnel,NaN
1,Annuaire structure,AS_Actions_par_structure,Type_de_lien,action_statut,Action menée/ Non menée,VARCHAR,Optionnel,NaN
2,Annuaire structure,AS_Actions_par_structure,Groupe_action,groupe_action_ben,Regroupement / famille d’actions,VARCHAR,Optionnel,NaN
3,Annuaire structure,AS_Actions_par_structure,Action,lib_action_ben,Libellé de l’action précise,VARCHAR,Optionnel,NaN
4,Annuaire structure,AS_Actions_par_structure,Date_demarrage_action_dans_la_structure,date_demarrage_action_structure,Date à laquelle l’action a effectivement démar...,DATE,Optionnel,NaN
...,...,...,...,...,...,...,...,...
242,GAIA ?,crf_pat_2025_rattachement_action,action_menee_date_fin,NaN,NaN,DATE,Présent & bon format,NaN
244,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_nivol_fk,NaN,NaN,STR,Présent & bon format,NaN
245,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_structure_id_fk,NaN,NaN,INT,Présent & bon format,NaN
246,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_date_debut,NaN,NaN,DATE,Présent & bon format,NaN
247,GAIA ?,crf_pat_2025_rattachement_benevole,rattachement_benevole_date_fin,NaN,NaN,DATE,Présent & bon format,NaN

# CHARGEMENT DE TOUTES LES DONNEES PAR TABLE

## 0. Ref_structure

In [21]:
df_ref_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1PUdny0DiyOjSSYLte2o9r1Xyh02O9INFlzLJVHl92ic/').worksheet('Ref_structure RP 2026'))

In [22]:
df_ref_structure = renommer_par_nom_table(df_ref_structure, "AS_Informations_structures", mapping_df)
df_ref_structure['n_structure'] = df_ref_structure['n_structure'].astype(int)
df_ref_structure = df_ref_structure[df_ref_structure["type_structure"].isin(["UNITE LOCALE - UL", "DELEGATION TERRITORIALE - DT", 'IMPLANTATION LOCALE HORS AL - IL', 'ANTENNE LOCALE - AL','INSTANCES NATIONALES - IN'])]
df_ref_structure.head()

df_ref_structure_PST = df_ref_structure.copy()

In [23]:
df_ref_structure_DT = df_ref_structure[df_ref_structure['nom_structure'].str.contains('DT')].astype(str)
df_ref_structure_DT['n_structure'] = df_ref_structure['n_structure'].astype(int)

### 0.1 rattachement_court

In [24]:
rattachement_court = df_ref_structure[['n_structure', 'DT_de_rattachement']].copy().drop_duplicates()

## 1. GAIA

In [25]:
df_gaia_rattachement_benevole = clean_gaia(client, df_ref_structure, target_date=TARGET_DATE)

df_nivols_gaia = import_table_GAIA_date_fixe(client,df_ref_structure, target_date=TARGET_DATE)

c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 2. PEGASS

In [26]:
df_ref_activite_benevole, df_pegass_activite, df_pegass_activite_seance, df_pegass_activite_seance_inscription,df_rattachement_court,df_ref_action_groupe_action = import_tables_PEGASS(client,target_date = TARGET_DATE)

c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 3. NOMINATION

In [27]:
df_ref_nomination, df_nomination = clean_nomination(client, df_ref_structure, target_date=TARGET_DATE)

c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 4. IMPACT

In [28]:
df_ref_impact, df_impact = clean_impact(client,df_ref_structure, target_date=TARGET_DATE)

c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 5. Données financières

In [29]:
financier = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1weTpAFxzPOcv9acHYY3UbB8byWiZ82jQ7K4qK-gb2Hw')

Financier DPS & FGP & Textile

In [30]:
financier_DPS = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1PcNXO-Fv8BGzGv-GKzFxBoEIfYl8TWAsAU2wpezH7_Y/').worksheet('Données'), evaluate_formulas=True)
financier_textile = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1d90QgH6d7K5mkdnmJJjNQ6XsoB6HgDv9DUkCQRNsiT4/edit?gid=1977169536#gid=1977169536",sheet_name="Compil Détail",header_row=7)

✅ Chargement des données réalisées
    Sheet : Résultat Textile_2020-2025 VDEF (23.03.26)
    Feuille  : Compil Détail (1338 lignes et 29 colonnes)

In [31]:
financier_FGP = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13J2zfbmLTILtGYtE_sM-ME8B0pNEwBeGJ1Gg5vKLeOc/').worksheet('DT_Prod'))

## 6. Mobilité

In [32]:
mobilite = gspread_client.open_by_url(
    "https://docs.google.com/spreadsheets/d/1dvxT58WR-FqdT-4r-A9ca4vaA9FG7IXHJJaTbnjio8A/"
)

In [33]:
df_mobilite = filtres_mobilite(mobilite,mapping_df, df_ref_structure)

## 7. Données manuelles

### 7.1 OCR

In [34]:
df_OCR = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ccRoyPycFDwvQvacvmHjfE87LtnlzUgtoRbITkC0pVQ/').worksheet('Feuille 1'), evaluate_formulas=True)

### 7.2 PST

In [35]:
df_PST = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1yifNna4Hsn5RihkRg50g9h1yKjuRjfolrjsWonEHnrQ').worksheet('Données'), evaluate_formulas=True)

### 7.3 Déclenchements

In [36]:
df_declenchement = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1CpFNU_-SXxosoZ1KGo_KQ5424ODNU1OasvY7f-urf84').worksheet('Feuille 1'), evaluate_formulas=True)

### 7.4 Redcall

In [37]:
# df_redcall = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1EQzq0K8RY2Liyq-jtggX0bTlnOk9cwUTmf4t6c5_CiI').worksheet('structure-stats_2025-01-01_2025-12-31_min-1 (1)'), evaluate_formulas=True)

### 7.5 CHAI CHU CMCC

In [38]:
df_CAICHUCMCC_conventions = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1H5PFGbCc5wtfELPyKU97GxOx6ib0hqFEY8cm3h6wR80').worksheet('Feuille 1'), evaluate_formulas=True)

### 7.6 Conventions

In [39]:
df_CRope = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1DCzcs3emUsc1b8WDH5y3F2sezxFptktYUzXQRLQEZGc').worksheet('Feuille 1'), evaluate_formulas=True)

### 7.7 Textile

In [40]:
df_raw_Textile = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/140m37rwHWu1zCyYuXPBwTY7WV-LUtB3yCT6j7EqcLXU/').worksheet('Feuille 1'),evaluate_formulas=True)

df_tracabilite_textile = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1EwL2bcqaw2Or7F7fTWK5q2naOZGxAN4tvheLAaddb1s').worksheet('Feuille 1'), evaluate_formulas=True)

#df_raw_ProdResTextile_c = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1l7KMjiav3usmLVJIbE2uENfNQCeQuxVeU1h13Cep3qk/",sheet_name="Compil Détail",header_row=7)

### 7.8 DOMIFA

In [41]:
df_domiciliation, df_rattachement_court = clean_domifa(client,df_ref_structure)

c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\utils.py:162: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ref['nom_structure'] = df_ref['nom_structure'].fillna('').astype(str)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3405.38it/s]

### 7.9 Alim

In [42]:
# df_alim = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1bk_ktsT9hBPJS5EY70teq80NzOs_cm3JfrRkX4AYTF4/edit?gid=0#gid=0") # Rapports v2 (2025)

df_U2A_statut= get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1tJRRI5kkcVKQ-n_A2-jqk9sPMSsFKjhcGrvx94gX1gk/edit?gid=1582718806#gid=1582718806').worksheet('10_liste_statuts_data'))
df_U2A_actions= get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1bq_SEJeks8NTaw2uFlk6J0wLFT3epRbCFz597HxUGj0/edit?gid=440288067#gid=440288067').worksheet('1. Détail des U2A _data (1)'))

df_contact = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/12NDLNS4KY5bpYQqcPJLc1CcVqiTo-R1BBMKj_SPL2gU/edit?gid=1480139434#gid=1480139434').worksheet('Table'))

### 7.10 DPS

In [43]:
df_dps_source = df_CAICHUCMCC_conventions.copy()

### 7.11 Adherent

In [44]:
df_adherent = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1tD0b7lLHx3smwPNjbj5GJfeJoPOGO8m2dME1fvOcyUI/")

✅ Chargement des données réalisées
    Sheet : exportAdherents (2)
    Feuille 1 : exportAdherents (2) (56878 lignes et 25 colonnes)

### 7.12 Minutis

In [45]:
df_minutis = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1HUHjZ7YhuPB3GTAyuBo7SlIEXyfYpJp9jv6-Mf5e0gU').worksheet('Feuille 1'), evaluate_formulas=True)

### 7.12 Préparation

In [46]:
# DPS a pour source le fichier conventions
# df_dps = clean_dps(df_dps_source)

df_OCR_clean, df_PST_clean, df_declenchement_clean, df_exercices_clean, df_CAIconv_clean, df_raw_Textile_clean, df_CRope_clean = clean_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement, df_CAICHUCMCC_conventions, df_raw_Textile, df_CRope, df_ref_structure)
#df_alim = clean_alim(df_alim)
df_adherent = clean_adherent(df_adherent)

c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\manuelles.py:96: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtre[["n_dept", "DT"]] = df_filtre["Département concerné"].str.split(" - ", expand=True)
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\manuelles.py:96: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtre[["n_dept", "DT"]] = df_filtre["Département concerné"].str.split(" - ", expand=True)
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\manuelles.py:97: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtre["DT"] = "DT " + df_filtre["DT"]
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\manuelles.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtre[["n_dept", "DT"]] = df_filtre["Département concerné"].str.split(" - ", expand=True)
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\manuelles.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtre[["n_dept", "DT"]] = df_filtre["Département concerné"].str.split(" - ", expand=True)
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\manuelles.py:120: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtre["DT"] = "DT " + df_filtre["DT"]
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\adherent.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_adherent["Année de l'adhésion du contact"] = pd.to_numeric(df_adherent["Année de l'adhésion du contact"], errors='coerce')

Unique values in 'Année de l'adhésion du contact': [nan]
Data type of 'Année de l'adhésion du contact': float64
Taille du DataFrame après suppression des doublons : (55627, 4)

## 8. Maraudes

In [47]:
# 1) import
df_maraude, df_maraude_beneficiaire, df_maraude_filtre, df_maraude_filtre_contacts = import_maraude(
    client,
    target_date=TARGET_DATE
)

# 2) Contacts : utiliser la table SANS filtre beneficiaire_id
df_nb_personnes_rencontrees_sigma = prep_nb_personnes_rencontrees_sigma(
    df_maraude_filtre_contacts
)

# 3) Maraudes : je laisse comme avant pour éviter de modifier un autre indicateur
df_Nb_maraudes_SIGMA_prep = prep_nb_maraudes_sigma(
    df_maraude_filtre
)


# 4) Bénéficiaires différents : on conserve le filtre beneficiaire_id
df_final = maraude_retraitement(
    df_maraude_beneficiaire,
    df_maraude,
    df_maraude_filtre
)

c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

Données manuelles

In [48]:
#Import données maraude manuelles
#df_Maraude_donnees_manuelles = Import_Maraude_manuel(client,df_ref_structure)

## 9. Base Contact

1. calcul des personnes formées sans recyclage

In [49]:
# df_formation_session_resultat, df_formation_count_session_year, df_formation_session_resultat_fpg = clean_base_contact(client, df_ref_structure, target_date=TARGET_DATE)
# df_formation_session_resultat_IS = clean_pofo(client, df_ref_structure, target_date = TARGET_DATE, half_year=True)


# 1. Import de la Base Contact
df_formation_session_resultat_formation_initiale = importer_base_contact(
    client=client,
    target_date=TARGET_DATE,
)

# 2. Import et filtrage des rattachements bénévoles
df_rattachement_benevole_formation_initiale = importer_rattachement_benevole(
    client=client,
    df_ref_structure=df_ref_structure,
    target_date=TARGET_DATE,
)

# 3. Calcul des deux tables finales
(
    df_final_formation_initiale,
    df_final_formation_initiale_DT, df_nivol_solidar, df_nivol_CRB,
) = calculer_formations_initiales(
    df_formation_session_resultat_formation_initiale=(
        df_formation_session_resultat_formation_initiale
    ),
    df_rattachement_benevole=df_rattachement_benevole_formation_initiale,
    df_ref_structure=df_ref_structure,
    target_date=TARGET_DATE,
)

display(df_final_formation_initiale)
display(df_final_formation_initiale_DT)

c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,n_structure,AEO Nb_AAD,AEO Nb_FAAD,Maraude Nb_SOLIDAR,Aide_alimentaire nb_SAH,Aide_alimentaire nb_ASAH,Structure Nb_formes_CRB_2026,Structure Nb_formateurs_CRB_2026,Structure Nb_formes_TCAS_2026,Dispositifs_d_urgence Nb_formes_TCAU_2026,Dispositifs_d_urgence Nb_formes_TCEO_2026,Dispositifs_d_urgence Nb_formes_PSP_2026,Dispositifs_d_urgence Nb_formes_IRR_2026,Textile Animateurs_textile,Dispositifs_d_urgence Nb_formes_GQS_2026,Maraude Nb_SOLIDAR2020
0,1,3.0,1.0,18.0,16.0,4.0,89.0,8.0,45.0,43.0,21.0,6.0,179.0,NaN,205.0,7.0
1,5,NaN,NaN,41.0,NaN,NaN,8.0,1.0,1.0,1.0,NaN,NaN,21.0,NaN,18.0,38.0
2,6,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
4,10,NaN,NaN,1.0,NaN,NaN,4.0,NaN,NaN,NaN,1.0,NaN,2.0,NaN,7.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791,4934,NaN,NaN,NaN,NaN,NaN,26.0,NaN,14.0,5.0,2.0,5.0,26.0,NaN,24.0,NaN
792,4935,NaN,NaN,NaN,5.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,6.0,NaN,6.0,NaN
793,4936,NaN,NaN,NaN,1.0,NaN,21.0,1.0,5.0,10.0,NaN,3.0,22.0,NaN,17.0,NaN
794,4956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN
795,4995,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0,NaN

,DT_de_rattachement,AEO Nb_AAD,AEO Nb_FAAD,Maraude Nb_SOLIDAR,Aide_alimentaire nb_SAH,Aide_alimentaire nb_ASAH,Structure Nb_formes_CRB_2026,Structure Nb_formateurs_CRB_2026,Structure Nb_formes_TCAS_2026,Dispositifs_d_urgence Nb_formes_TCAU_2026,Dispositifs_d_urgence Nb_formes_TCEO_2026,Dispositifs_d_urgence Nb_formes_PSP_2026,Dispositifs_d_urgence Nb_formes_IRR_2026,Textile Animateurs_textile,Dispositifs_d_urgence Nb_formes_GQS_2026,Maraude Nb_SOLIDAR2020
0,10 - DT DES ALPES MARITIMES,0.0,0.0,17.0,4.0,2.0,191.0,7.0,71.0,111.0,20.0,40.0,431.0,0.0,365.0,4.0
1,100 - DT DU VAL D'OISE,0.0,0.0,87.0,52.0,3.0,211.0,7.0,85.0,88.0,13.0,77.0,448.0,0.0,452.0,65.0
2,102 - DT DE LA GUADELOUPE,0.0,0.0,37.0,0.0,0.0,180.0,12.0,12.0,51.0,29.0,32.0,164.0,0.0,162.0,15.0
3,103 - DT DE LA MARTINIQUE,0.0,0.0,1.0,0.0,0.0,115.0,7.0,62.0,73.0,18.0,28.0,121.0,3.0,133.0,0.0
4,104 - DT DE NOUVELLE CALEDONIE,0.0,0.0,1.0,19.0,0.0,107.0,6.0,42.0,55.0,15.0,51.0,113.0,0.0,125.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,94 - DT DE L'YONNE,3.0,2.0,43.0,40.0,1.0,94.0,3.0,46.0,31.0,2.0,9.0,99.0,0.0,108.0,14.0
104,95 - DT DU TERRITOIRE DE BELFORT,1.0,1.0,8.0,24.0,1.0,6.0,1.0,9.0,6.0,0.0,4.0,43.0,0.0,43.0,8.0
105,96 - DT DE L'ESSONNE,18.0,0.0,234.0,24.0,1.0,410.0,8.0,285.0,366.0,27.0,79.0,365.0,2.0,551.0,211.0
106,97 - DT DES HAUTS DE SEINE,118.0,3.0,846.0,57.0,1.0,1093.0,19.0,688.0,818.0,193.0,322.0,1721.0,1.0,1679.0,656.0
107,99 - DT DU VAL DE MARNE,48.0,2.0,334.0,17.0,4.0,674.0,27.0,417.0,428.0,38.0,65.0,802.0,0.0,883.0,222.0

2. calcul des indicateurs de formation avec date de recyclage + création des variables qui seront nécessaires aux calculs des taux

In [50]:
(
    df_formation_session_resultat,
    df_ref_structure,
    rattachement_court
) = clean_base_contact(
    client=client,
    gspread_client= gspread_client,
    mapping_df=mapping_df
)

# Rattachements actifs au 31 mai 2026
df_rattachement_benevole_2026 = import_rattachement_benevole(
    target_date="2026-05-31",
    df_ref_structure=df_ref_structure,
    client=client
)


# Rattachements actifs au 31 décembre 2025
df_rattachement_benevole_2025 = import_rattachement_benevole(
    target_date="2025-12-31",
    df_ref_structure=df_ref_structure,
    client=client
)

c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

In [51]:
#Calcul pour 2026 : 
df_formations_par_DT, df_formations_par_structure, df_formations_par_nivol, df_NIVOLS_IS =  calcul_base_contact( df_formation_session_resultat, df_ref_structure,df_rattachement_benevole_2026, annee = 2026,  date_limite_recyclage="31-05-2026", date_limite_obtention_debut="01-01-2025", date_limite_obtention_fin= "31-05-2026")

#On rename "Secours Nb_IS_2026" par "Secours Nb_IS"
df_formations_par_DT = df_formations_par_DT.rename(
    columns={"Secours Nb_IS_2026": "Secours Nb_IS"}
)

df_formations_par_structure = df_formations_par_structure.rename(
    columns={"Secours Nb_IS_2026": "Secours Nb_IS"}
)

#Numerateur pour taux de recyclage 2026 
df_formations_par_DT_rec_2026_numerateur, df_formations_par_structure_rec_2026_numerateur, _ ,_ =  calcul_base_contact( df_formation_session_resultat, df_ref_structure,df_rattachement_benevole_2026, annee = "recy2026",  date_limite_recyclage="31-12-2027", date_limite_obtention_debut="01-01-2026", date_limite_obtention_fin= "31-05-2026")

# Dénominateur pour taux de renouvellement et taux de recyclage Calcul pour 2025
df_formations_par_DT_ren_2026_denominateur, df_formations_par_structure_ren_2026_denominateur, _, _ =  calcul_base_contact( df_formation_session_resultat, df_ref_structure,df_rattachement_benevole_2025 , annee = 2025,  date_limite_recyclage=None, date_limite_obtention_debut="01-01-2024", date_limite_obtention_fin="31-12-2025")

#Numerateur Calcul pour taux de renouvellement 2026
df_formations_par_DT_ren_2026_numerateur, df_formations_par_structure_ren_2026_numerateur, _, _ =  calcul_base_contact( df_formation_session_resultat, df_ref_structure,df_rattachement_benevole_2026, annee = "renou_2026",  date_limite_recyclage=None, date_limite_obtention_debut="01-01-2026", date_limite_obtention_fin=None)

In [96]:
df_formations_par_DT

,DT_de_rattachement,Formation_grand_public Nb_FPSC_2026,Secours Nb_PSE1_2026,Secours Nb_FI_PSE1_2026,Secours Nb_FC_PSE1_2026,Secours Nb_PSE2_2026,Secours Nb_FI_PSE2_2026,Secours Nb_FC_PSE2_2026,Secours Nb_CI_2026,Secours Nb_FI_CI_2026,Secours Nb_FPSE_2026,Secours Nb_FI_FPSE_2026,Secours Nb_FC_FPSE_2026,Secours Nb_FC_CI_2026,calcul_FPS,Secours Nb_IS
0,10 - DT DES ALPES MARITIMES,38,7,2,5,93,29,64,32,2,17,14,3,30,17,132
1,100 - DT DU VAL D'OISE,64,4,2,2,146,21,125,44,4,21,13,8,40,21,194
2,102 - DT DE LA GUADELOUPE,6,0,0,0,29,11,18,4,0,1,0,1,4,1,33
3,103 - DT DE LA MARTINIQUE,9,3,0,3,29,4,25,4,0,1,0,1,4,1,36
4,104 - DT DE NOUVELLE CALEDONIE,10,0,0,0,13,12,1,5,2,2,0,2,3,2,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,94 - DT DE L'YONNE,6,2,0,2,23,7,16,7,1,2,1,1,6,2,32
101,95 - DT DU TERRITOIRE DE BELFORT,3,0,0,0,14,0,14,3,0,2,1,1,3,2,17
102,96 - DT DE L'ESSONNE,63,17,3,14,180,31,149,41,3,19,13,6,38,19,238
103,97 - DT DES HAUTS DE SEINE,166,8,2,6,573,80,493,146,11,59,54,5,135,59,727
104,99 - DT DU VAL DE MARNE,113,12,6,6,307,47,260,70,1,43,30,13,69,43,389

3. Calcul nb formés Grand public

In [52]:

(
    indicateurs_fgp_structure_2026,
    indicateurs_fgp_DT_2026,
) = calcul_indicateurs_formation_grand_public(
    client=client,
    df_ref_structure=df_ref_structure,
    target_date="2026-05-31",
)

c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\Base_contact_session_et_gd_public.py:328: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\Base_contact_session_et_gd_public.py:328: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

4. Calcul Base contact "nombre de sessions"

In [53]:
nb_sessions, nb_sessions_DT = (
    calcul_indicateurs_sessions(
        client,
        df_ref_structure,
        target_date="2026-05-31"
    )
)

c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_sessions_PSC_2026
  Codes attendus : {'RECPSC1', 'PSC1 AC', 'PSC', 'PSC IRR', 'EPSC', 'PSC1', 'FCPSC', 'PSC AC', 'EPSC1', 'PSC1 IRR'}
  Codes trouvés  : {'PSC', 'RECPSC1', 'PSC IRR', 'EPSC', 'PSC1', 'FCPSC', 'PSC AC', 'EPSC1', 'PSC1 IRR'}
  Codes manquants: {'PSC1 AC'}

Indicateur : Formation_grand_public Nb_sessions_GQS_2026
  Codes attendus : {'FIPS2', 'FIPS', 'GQS AC', 'GQS'}
  Codes trouvés  : {'FIPS2', 'FIPS', 'GQS AC', 'GQS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_IPS_2026
  Codes attendus : {'IPSJ', 'IPSP', 'IPS AC', 'IPS', 'IPSEF', 'IPSJP', 'IPS SR', 'IPSM', 'IPSE'}
  Codes trouvés  : {'IPS AC', 'IPSJ', 'IPSP', 'IPS', 'IPSEF', 'IPSJP', 'IPSE'}
  Codes manquants: {'IPS SR', 'IPSM'}

Indicateur : Formation_grand_public Nb_sessions_IPSEN_2026
  Codes attendus : {'IPSEN'}
  Codes trouvés  : {'IPSEN'}
  Codes manquants: set()

Indicateur : Secours Nb_sessions_PSE
  Codes attendus : {'RATPSE1', 'FCPSE1', 'RECPSE2', 'PSE2', 'FCPSE2', 'PSE', 'PSE1', 'RECPSE1', 'PSE AGSU', 'FCPSE', 'RATPSE2', 'APTE PSE1'}
  Codes trouvés  : {'RATPSE1', 'FCPSE1', 'RECPSE2', 'PSE2', 'FCPSE2', 'PSE', 'PSE1', 'RECPSE1', 'FCPSE', 'RATPSE2', 'APTE PSE1'}
  Codes manquants: {'PSE AGSU'}

Indicateur : Secours Nb_sessions_CI
  Codes attendus : {'RECPSECI', 'CI', 'REC PSECI', 'CI P1 P2', 'CIP2', 'FCCI', 'RECCI'}
  Codes trouvés  : {'FCCI', 'CI', 'RECCI'}
  Codes manquants: {'RECPSECI', 'REC PSECI', 'CI P1 P2', 'CIP2'}

Indicateur : Secours Nb_sessions_FPSE
  Codes attendus : {'FCFPSE', 'PICF FPS', 'FPSE', 'FPSE AFGU', 'FPS', 'RECFPS', 'RATFCFPSE', 'PICF FPSE'}
  Codes trouvés  : {'FCFPSE', 'PICF FPS', 'FPSE', 'FPS', 'RATFCFPSE', 'PICF FPSE'}
  Codes manquants: {'RECFPS', 'FPSE AFGU'}

c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\Base_contact_session_et_gd_public.py:791: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

===== Somme globale par indicateur =====
Formation_grand_public Nb_sessions_PSC_2026 : 3926
Formation_grand_public Nb_sessions_GQS_2026 : 516
Formation_grand_public Nb_sessions_IPS_2026 : 1309
Formation_grand_public Nb_sessions_IPSEN_2026 : 453
Secours Nb_sessions_PSE : 808
Secours Nb_sessions_CI : 185
Secours Nb_sessions_FPSE : 11

===== Vérification des codes =====

Indicateur : Formation_grand_public Nb_sessions_PSC_2026
  Codes attendus : {'RECPSC1', 'PSC1 AC', 'PSC', 'PSC IRR', 'EPSC', 'PSC1', 'FCPSC', 'PSC AC', 'EPSC1', 'PSC1 IRR'}
  Codes trouvés  : {'PSC', 'RECPSC1', 'PSC IRR', 'EPSC', 'PSC1', 'FCPSC', 'PSC AC', 'EPSC1', 'PSC1 IRR'}
  Codes manquants: {'PSC1 AC'}

Indicateur : Formation_grand_public Nb_sessions_GQS_2026
  Codes attendus : {'FIPS2', 'FIPS', 'GQS AC', 'GQS'}
  Codes trouvés  : {'FIPS2', 'FIPS', 'GQS AC', 'GQS'}
  Codes manquants: set()

Indicateur : Formation_grand_public Nb_sessions_IPS_2026
  Codes attendus : {'IPSJ', 'IPSP', 'IPS AC', 'IPS', 'IPSEF', 'IPSJP', 'IPS SR', 'IPSM', 'IPSE'}
  Codes trouvés  : {'IPS AC', 'IPSJ', 'IPSP', 'IPS', 'IPSEF', 'IPSJP', 'IPSE'}
  Codes manquants: {'IPS SR', 'IPSM'}

Indicateur : Formation_grand_public Nb_sessions_IPSEN_2026
  Codes attendus : {'IPSEN'}
  Codes trouvés  : {'IPSEN'}
  Codes manquants: set()

Indicateur : Secours Nb_sessions_PSE
  Codes attendus : {'RATPSE1', 'FCPSE1', 'RECPSE2', 'PSE2', 'FCPSE2', 'PSE', 'PSE1', 'RECPSE1', 'PSE AGSU', 'FCPSE', 'RATPSE2', 'APTE PSE1'}
  Codes trouvés  : {'RATPSE1', 'FCPSE1', 'RECPSE2', 'PSE2', 'FCPSE2', 'PSE', 'PSE1', 'RECPSE1', 'FCPSE', 'RATPSE2', 'APTE PSE1'}
  Codes manquants: {'PSE AGSU'}

Indicateur : Secours Nb_sessions_CI
  Codes attendus : {'RECPSECI', 'CI', 'REC PSECI', 'CI P1 P2', 'CIP2', 'FCCI', 'RECCI'}
  Codes trouvés  : {'FCCI', 'CI', 'RECCI'}
  Codes manquants: {'RECPSECI', 'REC PSECI', 'CI P1 P2', 'CIP2'}

Indicateur : Secours Nb_sessions_FPSE
  Codes attendus : {'FCFPSE', 'PICF FPS', 'FPSE', 'FPSE AFGU', 'FPS', 'RECFPS', 'RATFCFPSE', 'PICF FPSE'}
  Codes trouvés  : {'FCFPSE', 'PICF FPS', 'FPSE', 'FPS', 'RATFCFPSE', 'PICF FPSE'}
  Codes manquants: {'RECFPS', 'FPSE AFGU'}

===== Somme globale par indicateur =====
Formation_grand_public Nb_sessions_PSC_2026 : 3926
Formation_grand_public Nb_sessions_GQS_2026 : 516
Formation_grand_public Nb_sessions_IPS_2026 : 1309
Formation_grand_public Nb_sessions_IPSEN_2026 : 453
Secours Nb_sessions_PSE : 808
Secours Nb_sessions_CI : 185
Secours Nb_sessions_FPSE : 11

c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\Base_contact_session_et_gd_public.py:791: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

## 10. DPS

In [54]:
df_dps_dimensionnement, df_dps_manifestation, df_dps_ref_type_dispositif, df_dps_ref_type_statut_demande = import_clean_dps(client, df_ref_structure,target_date = TARGET_DATE)

c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## 11. Ambition

In [55]:
df_indic_ambition = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1tdM09TkAGaJQEQx1ddGDUjU7h79gtFU0_7ViNMyknYM/edit?gid=736259206#gid=736259206').worksheet('Consolidation PATV2'),evaluate_formulas=True)

# FUSION DES TABLES

## 1. Fusion NOMINATION

In [56]:
df_NOMINATION = fusion_nomination(df_nomination, df_ref_nomination)

## 2. Fusion IMPACT

In [57]:
df_IMPACT = fusion_impact(df_impact, df_ref_impact)

Nombre de lignes après filtre 2025 : 176882

## 3. Fusion DOMIFA

In [58]:
df_domiciliation = pd.merge(df_domiciliation, df_rattachement_court, on='n_structure', how="left") #a conserver dans le code principal

# Calcul des indicateurs

## PEGASS

In [59]:
pegass_output = calcul_PEGASS_indicateurs(df_ref_structure,
    df_ref_action_groupe_action,
    df_ref_activite_benevole,
    df_pegass_activite,
    df_pegass_activite_seance,
    df_pegass_activite_seance_inscription,
    df_rattachement_court,
    df_nivols_gaia
)

In [60]:
pegass_output = calcul_PEGASS_indicateurs(df_ref_structure,
    df_ref_action_groupe_action,
    df_ref_activite_benevole,
    df_pegass_activite,
    df_pegass_activite_seance,
    df_pegass_activite_seance_inscription,
    df_rattachement_court,
    df_nivols_gaia
)

#Nécessaires calculs indicateurs PEGASS
Indics_pegass = pegass_output["Indics_pegass"]
Indics_pegass_struct = pegass_output["Indics_pegass_struct"]

#Les 2 dfs utiles : Indics_pegass_struct et Indics_pegass_DT
Indics_pegass_DT, Indics_pegass_struct = calcul_PEGASS_DT_indicateurs(Indics_pegass_struct, df_ref_structure)


#Nécessaires calculs indicateurs composites
df_pegass_ben_activite = pegass_output["df_pegass_ben_activite"]
df_pegass_ben_activite_synthetique = pegass_output['df_pegass_ben_activite_synthetique']

## GAIA

In [61]:
df_indicateurs_gaia, df_indicateurs_gaia_DT, df_NIVOLS_Nouveaux_benevoles_gaia = calcul_indicateurs_gaia(df_gaia_rattachement_benevole,rattachement_court,target_date=TARGET_DATE)

Nombre de structures agrégées : 824
Nombre total de bénévoles uniques : 81299
Nombre de structures agrégées : 686
Nombre total de nouveaux bénévoles uniques : 7509
Nombre de structures agrégées : 108
Nombre total de bénévoles uniques DT : 80137
Nombre de structures agrégées : 106
Nombre total de nouveaux bénévoles uniques DT : 7454

# Calcul des variables pour les indicateurs composites

In [62]:
#Calcul du nombre d'IS actif

df_indicateurs_IS_DT, df_indicateurs_IS_Structure = calcul_indicateurs_IS(
    df_pegass_ben_activite,
    df_NIVOLS_IS,
    df_ref_structure,
)

# calcul du nb de maraudeurs actifs 

(
    df_maraude_benevole_actif_DT,
    df_maraude_benevole_actif_structure,
) = calcul_indicateurs_maraude(
    df_pegass_ben_activite_synthetique,
    df_nivol_solidar,
    df_ref_structure,
)

# Calcul du nombre de nouveaux bénévoles qui ont été formés CRB

df_nouveaux_CRB_DT, df_nouveaux_CRB_structure = calcul_indicateurs_CRB(
    df_NIVOLS_Nouveaux_benevoles_gaia,
    df_nivol_CRB,
    df_ref_structure,
    target_date = "2026-05-31",
)

In [102]:
df_NIVOLS_IS

       n_structure  Secours Nb_IS               NIVOL_ID_FK
2           4284.0              1  eNozMAABC0NTQ3NXAA8bAmw=
3            602.0              1  eNozMAABC0NzI2MXAA8dAmo=
4             20.0              1  eNozMAABC0NzI3MPAA8pAnI=
7            892.0              1  eNozMAABC0sjEwNHAA8uAmk=
9            886.0              1  eNozMAABC0tjc7NwAA9dAok=
...            ...            ...                       ...
11811       4872.0              1      eNozMIAASyNDJwAO6gJf
11813       4397.0              1      eNozMIAAUwvLIAAPDAJ5
11816       2457.0              1      eNozMIAAcwszVwAPAQJr
11818        524.0              1      eNozMIABM3cADs8CXg==
11819        524.0              1      eNozMIABUzcADswCXA==

[10648 rows x 3 columns]

In [99]:
df_indicateurs_IS_Structure["Secours Nb_IS_actifs"].sum()

np.float64(3972.0)

## NOMINATION

- RTAEO & RLAEO
- RTOCR & RLOCR

In [63]:
referents_AEO = indicateurs_nomination_AEO(df_NOMINATION,df_nivols_gaia)
referents_OCR = indicateurs_nomination_OCR(df_NOMINATION,df_nivols_gaia)
referents_AEO_DT = indicateurs_nominationAEO_DT(referents_AEO, rattachement_court)
referents_OCR_DT = indicateurs_nominationOCR_DT(referents_OCR, rattachement_court)

Nombre de structures agrégées : 45
Nombre total de responsables AEO : 55
Nombre de structures agrégées : 22
Nombre total de responsables OCR : 22
Nombre de structures agrégées : 22
Nombre total de responsables AEO DT : 55
Nombre de structures agrégées : 18
Nombre total de responsables OCR DT : 22

## IMPACT

- Nombre d'agréments territoriaux (Dispos d'urgence)
- Nombre de personnes prises en charge (Dispos d'urgence)

In [64]:
IMPACT_ppc = indicateurs_impact_ppc(df_IMPACT)
IMPACT_agrementAB = indicateurs_impact_agrementAB(df_IMPACT)
IMPACT_agrementDPS = indicateurs_impact_agrementDPS(df_IMPACT, year = TARGET_YEAR)
IMPACT_ppc_DT = indicateurs_IMPACTppc_DT(IMPACT_ppc, rattachement_court)
IMPACT_agrementAB_DT = indicateurs_IMPACTagrementAB_DT(IMPACT_agrementAB, rattachement_court)
IMPACT_agrementDPS_DT = indicateurs_IMPACTagrementDPS_DT(IMPACT_agrementDPS, rattachement_court, year = TARGET_YEAR)

Nombre de lignes après filtre urgences : 698
Nombre de structures agrégées : 95
Somme totale Dispositifs d'urgence - Nb personnes prises en charge : 9467
Nombre de structures agrégées : 54
Somme totale agréments AB : 0
Nombre de structures agrégées : 19
Somme totale agréments DPS : 0
Nombre de structures agrégées : 54
Somme totale personnes prises en charge DT : 9467
Nombre de structures agrégées : 46
Somme totale agréments AB DT : 0
Nombre de structures agrégées : 17
Somme totale agréments DPS DT: 0

c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\impact.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\impact.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\impact.py:151: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (

## Financier

In [65]:
df_financier, df_financier_DT,financier = import_clean_donnees_financieres_bigquery(financier,financier_textile,financier_DPS,df_ref_structure)

In [66]:
# Vérifications données financières
#verifications_financiers(df_financier, df_financier_DT, df_ref_structure, financier, financier_2025)

In [67]:
df_financier_FGP_DT = indicateur_financier_FGP_2024(financier_FGP, df_ref_structure)
#df_inancier_FGP_DT = financier_FGP_DT(df_financier_FGP, rattachement_court)

## Mobilité


Indicateurs qui nécessitent seulement les données mobilité :

- Nb de structures menant une activité AEO/AAD mobile
- Nombre de personnes accompagnées par des dispositifs AEO/AAD mobiles
<br>
Indicateurs qui nécessitent une fusion avec données AEO/AAD :

- Nombre de bénévoles impliqués dans les activités AEO ou AAD

In [68]:
mobilite_DT, mobilite_struct = indicateurs_mobilite(df_mobilite, df_ref_structure)


#df_mobilite_DT = indicateurs_mobilite(df_mobilite, df_ref_structure, 'DT_de_rattachement')
#df_mobilite_DT_UL = indicateurs_mobilite(df_mobilite, df_ref_structure, 'n_structure')

In [69]:
#verifier_colonne_structure(mobilite_DT, "n_structure", df_ref_structure)

In [70]:
verifier_colonne_structure(mobilite_struct, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## Données manuelles

In [71]:
df_OCR_Nb_deployees, df_Dispositifs_d_urgence_PST, df_declenchement_VF, df_exercices_VF, df_CAICHUCMCC_conventionsVF, df_raw_TextileVF, df_CRopeVF, df_tracabilite_textileVF, df_minutisVF = indicateurs_OCR_PST_DEC_RED_CAI_CONV(df_OCR_clean, df_PST_clean, df_declenchement_clean, df_exercices_clean, df_CAIconv_clean, df_raw_Textile_clean, df_CRope_clean,df_tracabilite_textile,df_minutis, df_ref_structure, df_ref_structure_PST)

Nb_OCR_DT = indicateurs_OCR_DT(df_OCR_Nb_deployees, rattachement_court)
df_Textile_DT = Textile_DT(df_raw_TextileVF, rattachement_court)
df_tracabilite_textile_DT = tracabilite_textile_DT(df_tracabilite_textileVF)
df_CRopeVF_DT = crope_DT(df_CRopeVF, rattachement_court)

# ALIM
df_U2A_final, df_U2A_Structure, df_struct_DT, df_U2A_DT = calcul_u2a(
    df_ref_structure,
    df_U2A_statut,
    df_U2A_actions,
    df_contact
)

# ADHERENT
df_adherent, df_adherent_DT = indicateurs_adherent(df_adherent, df_ref_structure)

# df_adherent = indicateurs_adherent(df_adherent, df_ref_structure)
# df_adherent_DT = indicateurs_adherent_DT(df_adherent, rattachement_court)

# DOMIFA
df_personnes_domiciliees_struct, df_personnes_domiciliees_DT = indicateurs_domifa(df_domiciliation)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5191.53it/s]
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\utils.py:162: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ref['nom_structure'] = df_ref['nom_structure'].fillna('').astype(str)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4674.86it/s]
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\utils.py:162: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ref['nom_structure'] = df_ref['nom_structure'].fillna('').astype(str)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6946.67it/s]
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5819.93it/s]
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\alim.py:147: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_U2A_statut["Date de dernière distribution"] = pd.to_datetime(
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\alim.py:233: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_contact["Nb. AD uniques"] = pd.to_numeric(
c:\Users\Soukalounc\Documents\Git Repository\Code-PAT dernière version\GitHub\Code-PAT\data\alim.py:380: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_struct_DT["Aide_alimentaire Nb_struct"] = 1

In [72]:
verifier_colonne_structure(df_OCR_Nb_deployees, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Dispositifs_d_urgence_PST, "n_structure", df_ref_structure)
# verifier_colonne_structure(df_declenchement3, "n_structure", df_ref_structure)
# verifier_colonne_structure(df_redcall2, "n_structure", df_ref_structure)
verifier_colonne_structure(df_CAICHUCMCC_conventionsVF, "n_structure", df_ref_structure)
verifier_colonne_structure(df_CRopeVF, "n_structure", df_ref_structure)


# TEXTILE
verif_textile(df_raw_Textile_clean, df_raw_TextileVF, df_Textile_DT, df_ref_structure, rattachement_court)

# DOMIFA

verifs_domifa(client, df_personnes_domiciliees_struct, df_personnes_domiciliees_DT, df_ref_structure, df_rattachement_court)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.
❌ df_Textile_DT n'est pas bien calculé (suomme de l indicateur != au nombre de lignes des données), différence : -128
❌ df_Textile_DT n'est pas bien calculé (suomme de l indicateur != au nombre de lignes des données), différence : -128
❌ df_Textile_DT n'est pas bien calculé (suomme de l indicateur != au nombre de lignes des données), différence : -747
❌ df_Textile_DT n'est pas bien calculé (suomme de l indicateur != au nombre de lignes des données), différence : -747

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.
#1 Vérification qu on a bien la même somme de personnes domiciliées entre le fichier de base et le fichier df_personnes_domiciliees_struct
OK ✅ : sommes égales (30833) entre table struct[AEO Nb_personnes_domiciliees_crf] et table source[Nombre total de domiciliations]
#2 Vérification qu on a bien la même somme de personnes domiciliées entre le fichier structure et le fichier df_personnes_domiciliees_DT
OK ✅ : sommes égales (30833) entre table struct[AEO Nb_personnes_domiciliees_crf] et table DT[AEO Nb_personnes_domiciliees_crf]
#3 on vérifie que l ensemble des N° structure du nb personnes domicilées correspnd au ref structure

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.
#4 on vérifie que l ensemble des N° DTdu nb personnes domicilées correspnd au ref structure
#5 On verifie que le nb de structure du df_personnes_domiciliees_struct est bien égal au nombre de ligne du df source
 ✅ n ligne = 30

c:\Users\Soukalounc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

## Maraudes

In [73]:
# 3) Calcul
df_SIGMA_DT, df_SIGMA_struct = maraude_calcul_final(df_final, df_Nb_maraudes_SIGMA_prep, df_nb_personnes_rencontrees_sigma, df_ref_structure)

Données manuelles maraude

In [74]:
#Calcul données maraude manuelles
#df_Maraude_donnees_manuelles_DT_2, df_Maraude_donnees_manuelles_structure_2 = calcul_indic_maraude_manuelles(df_ref_structure, df_Maraude_donnees_manuelles, rattachement_court)

#Verif données maraude manuelles
#check_maraude_sums(df_Maraude_donnees_manuelles, df_Maraude_donnees_manuelles_DT_2)
#check_maraude_sums(df_Maraude_donnees_manuelles, df_Maraude_donnees_manuelles_structure_2)

## Base contact

In [75]:
# Indicateurs : méthode précedente de calcul
# indicateurs_base_contact, indicateurs_base_contact_DT = indicateurs_base_contact(client, df_formation_session_resultat, df_formation_count_session_year, df_formation_session_resultat_fpg, df_ref_structure, target_date=TARGET_DATE)
# indicateurs_base_contact_DT = correction_indic_BC_DT(df_ref_structure, indicateurs_base_contact, indicateurs_base_contact_DT, year = TARGET_YEAR)
# indicateurs_pofo, indicateurs_pofo_DT = indicateurs_pofo(client, df_formation_session_resultat_IS, df_ref_structure, target_date= TARGET_DATE)
# indicateurs_pofo_DT = correction_indic_pofo_DT(df_ref_structure, indicateurs_pofo, indicateurs_pofo_DT, year = TARGET_YEAR)

## DPS

In [76]:
df_dps, df_dps_DT = indicateurs_dps(df_dps_dimensionnement, df_dps_manifestation, df_dps_ref_type_dispositif, df_dps_ref_type_statut_demande, df_ref_structure, target_date = TARGET_DATE)
#df_indicateurs_dps = indicateurs_dps(df_dps, df_ref_structure)

In [77]:
#verifications_dps(df_dps_source, df_indicateurs_dps)

## AMBITION

In [78]:
df_indic_ambition_pat = charger_indicateurs_ambition_pat(df_indic_ambition, df_ref_structure)

# Création du DataFrame final

La liste de tous les dataframes à fusionner sur df_ref_structure

In [79]:
# Index 30
indicateurs_fgp_DT_2026 = indicateurs_fgp_DT_2026[
    indicateurs_fgp_DT_2026["DT_de_rattachement"].notna()
    & indicateurs_fgp_DT_2026["DT_de_rattachement"].astype(str).str.strip().ne("")
].copy()

# Index 31
nb_sessions_DT = nb_sessions_DT[
    nb_sessions_DT["DT_de_rattachement"].notna()
    & nb_sessions_DT["DT_de_rattachement"].astype(str).str.strip().ne("")
].copy()

In [80]:
# On ne filtre pas les implantations locales avant à cause du rattachement successif
df_ref_structure = df_ref_structure[df_ref_structure["type_structure"].isin(["UNITE LOCALE - UL", "DELEGATION TERRITORIALE - DT", 'ANTENNE LOCALE - AL','INSTANCES NATIONALES - IN'])]

In [81]:
liste_df_a_fusionner_toutes_structures = [df_indicateurs_gaia,referents_AEO,referents_OCR,df_CRopeVF,
                                          mobilite_struct,df_OCR_Nb_deployees,
                                          df_raw_TextileVF, df_tracabilite_textileVF, df_U2A_Structure,
                                          df_adherent, df_personnes_domiciliees_struct,df_SIGMA_struct,  
                                          df_indicateurs_IS_Structure, 
                                          df_maraude_benevole_actif_structure, df_nouveaux_CRB_structure,
                                          df_financier,
                                          Indics_pegass_struct, df_dps, df_final_formation_initiale, df_formations_par_structure,  
                                          df_formations_par_structure_rec_2026_numerateur, df_formations_par_structure_ren_2026_denominateur, 
                                          df_formations_par_structure_ren_2026_numerateur, indicateurs_fgp_structure_2026, nb_sessions
]

liste_df_a_fusionner_DT = [df_indicateurs_gaia_DT,referents_AEO_DT,referents_OCR_DT,df_CRopeVF_DT,
                           mobilite_DT,Nb_OCR_DT,df_Dispositifs_d_urgence_PST,
                           df_declenchement_VF, df_exercices_VF, df_CAICHUCMCC_conventionsVF,
                           df_Textile_DT, df_tracabilite_textile_DT,df_minutisVF, df_U2A_DT, df_adherent_DT,
                           df_personnes_domiciliees_DT, df_SIGMA_DT, 
                           df_financier_DT,df_financier_FGP_DT,Indics_pegass_DT,df_indic_ambition_pat,df_dps_DT, df_indicateurs_IS_DT, df_nouveaux_CRB_DT, df_maraude_benevole_actif_DT,
                           df_final_formation_initiale_DT, df_formations_par_DT, df_formations_par_DT_rec_2026_numerateur, df_formations_par_DT_ren_2026_denominateur, 
                           df_formations_par_DT_ren_2026_numerateur, indicateurs_fgp_DT_2026, nb_sessions_DT
]

In [82]:
all_data, all_data_DT, liste_df_a_fusionner_toutes_structures_processed, liste_df_a_fusionner_DT_processed = traitement_all_data(liste_df_a_fusionner_toutes_structures, liste_df_a_fusionner_DT, df_ref_structure,df_ref_structure_DT,year = TARGET_YEAR)

TRAITEMENT DES INDICATEURS POUR TOUTES LES STRUCTURES

🧹 DataFrame 7 : suppression des colonnes ['DT_de_rattachement']
🧹 DataFrame 10 : suppression des colonnes ['DT_de_rattachement']
🧹 DataFrame 15 : suppression des colonnes ['Région', 'n_dept', 'N° Smartview', 'Nom structure']
🧹 DataFrame 16 : suppression des colonnes ['IS Nb_benevoles_actifs']
🧹 DataFrame 19 : suppression des colonnes ['calcul_FPS']
🧹 DataFrame 20 : suppression des colonnes ['calcul_FPS', 'Secours Nb_IS_recy2026']
🧹 DataFrame 21 : suppression des colonnes ['calcul_FPS', 'Secours Nb_IS_2025']
🧹 DataFrame 22 : suppression des colonnes ['calcul_FPS', 'Secours Nb_IS_renou_2026']
✅ DataFrame 0 : aucun doublon dans 'n_structure'
✅ DataFrame 1 : aucun doublon dans 'n_structure'
✅ DataFrame 2 : aucun doublon dans 'n_structure'
✅ DataFrame 3 : aucun doublon dans 'n_structure'
✅ DataFrame 4 : aucun doublon dans 'n_structure'
✅ DataFrame 5 : aucun doublon dans 'n_structure'
✅ DataFrame 6 : aucun doublon dans 'n_structure'
✅ DataFrame 7 : aucun doublon dans 'n_structure'
✅ DataFrame 8 : aucun doublon dans 'n_structure'
✅ DataFrame 9 : aucun doublon dans 'n_structure'
✅ DataFrame 10 : aucun doublon dans 'n_structure'
✅ DataFrame 11 : aucun doublon dans 'n_structure'
✅ DataFrame 12 : aucun doublon dans 'n_structure'
✅ DataFrame 13 : aucun doublon dans 'n_structure'
✅ DataFrame 14 : aucun doublon dans 'n_structure'
✅ DataFrame 15 : aucun doublon dans 'n_structure'
✅ DataFrame 16 : aucun doublon dans 'n_structure'
✅ DataFrame 17 : aucun doublon dans 'n_structure'
✅ DataFrame 18 : aucun doublon dans 'n_structure'
✅ DataFrame 19 : aucun doublon dans 'n_structure'
✅ DataFrame 20 : aucun doublon dans 'n_structure'
✅ DataFrame 21 : aucun doublon dans 'n_structure'
✅ DataFrame 22 : aucun doublon dans 'n_structure'
✅ DataFrame 23 : aucun doublon dans 'n_structure'
✅ DataFrame 24 : aucun doublon dans 'n_structure'
TRAITEMENT DES INDICATEURS POUR LES DTs

🧹 DataFrame 6 : suppression des colonnes ['Territoire', 'PST constitué', 'Nom structure DT', 'N° Département', 'nom_structure']
🧹 DataFrame 9 : suppression des colonnes ['Departement', 'nom_structure']
🧹 DataFrame 12 : suppression des colonnes ['code_territoire', 'codes_structures_dt', 'libelles_structures_dt', 'types_structures_dt', 'territoire', 'type_territoire', 'annee', 'operations_reellement_gerees', 'mois_actifs_source']
🧹 DataFrame 18 : suppression des colonnes ['n_dept']
🧹 DataFrame 19 : suppression des colonnes ['IS Nb_benevoles_actifs']
🧹 DataFrame 20 : suppression des colonnes ['n_dept', 'DT', '% Completion PAT', 'PAT FGP_Nb_sessions_PREVIC']
🧹 DataFrame 26 : suppression des colonnes ['calcul_FPS']
🧹 DataFrame 27 : suppression des colonnes ['calcul_FPS', 'Secours Nb_IS_recy2026']
🧹 DataFrame 28 : suppression des colonnes ['calcul_FPS', 'Secours Nb_IS_2025']
🧹 DataFrame 29 : suppression des colonnes ['calcul_FPS', 'Secours Nb_IS_renou_2026']
✅ DataFrame 0 : aucun doublon dans 'n_structure'
✅ DataFrame 1 : aucun doublon dans 'n_structure'
✅ DataFrame 2 : aucun doublon dans 'n_structure'
✅ DataFrame 3 : aucun doublon dans 'n_structure'
✅ DataFrame 4 : aucun doublon dans 'n_structure'
✅ DataFrame 5 : aucun doublon dans 'n_structure'
✅ DataFrame 6 : aucun doublon dans 'n_structure'
✅ DataFrame 7 : aucun doublon dans 'n_structure'
✅ DataFrame 8 : aucun doublon dans 'n_structure'
✅ DataFrame 9 : aucun doublon dans 'n_structure'
✅ DataFrame 10 : aucun doublon dans 'n_structure'
✅ DataFrame 11 : aucun doublon dans 'n_structure'
✅ DataFrame 12 : aucun doublon dans 'n_structure'
✅ DataFrame 13 : aucun doublon dans 'n_structure'
✅ DataFrame 14 : aucun doublon dans 'n_structure'
✅ DataFrame 15 : aucun doublon dans 'n_structure'
✅ DataFrame 16 : aucun doublon dans 'n_structure'
✅ DataFrame 17 : aucun doublon dans 'n_structure'
✅ DataFrame 18 : aucun doublon dans 'n_structure'
✅ DataFrame 19 : aucun doublon dans 'n_structure'
✅ DataFrame 20 : aucun doublon dans 'n_structure'
✅ DataFrame 21 : aucun doublon dans 'n_structure'
✅ DataFrame 22 : aucun doublon dans 'n_structure'
✅ DataFrame 23 : aucun doublon dans 'n_structure'
✅ DataFrame 24 : aucun doublon dans 'n_structure'
✅ DataFrame 25 : aucun doublon dans 'n_structure'
✅ DataFrame 26 : aucun doublon dans 'n_structure'
✅ DataFrame 27 : aucun doublon dans 'n_structure'
✅ DataFrame 28 : aucun doublon dans 'n_structure'
✅ DataFrame 29 : aucun doublon dans 'n_structure'
✅ DataFrame 30 : aucun doublon dans 'n_structure'
✅ DataFrame 31 : aucun doublon dans 'n_structure'

In [83]:
for df in liste_df_a_fusionner_toutes_structures_processed + liste_df_a_fusionner_DT_processed:
    verifier_colonne_structure(df, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [84]:
report = check_sums_against_final(
    df_final=all_data,
    list_of_dfs=liste_df_a_fusionner_toutes_structures,
    key_col="n_structure",
    atol=1e-6
)

🔎 Vérification DataFrame 0
   ✅ 'Structure Nb_Benevoles' OK | individuel = 81299.0 | final = 81299.0
   ✅ 'Structure Nb_nvx_Benevoles_2026' OK | individuel = 7509.0 | final = 7509.0
   ✅ 'Structure Taux_nvx_Benevoles' OK | individuel = 7594.4014339897485 | final = 7594.401433989749

🔎 Vérification DataFrame 1
   ✅ 'AEO Nb_responsables' OK | individuel = 55.0 | final = 55.0

🔎 Vérification DataFrame 2
   ✅ 'OCR Nb_referents' OK | individuel = 22.0 | final = 22.0

🔎 Vérification DataFrame 3
   ✅ 'Dispositifs_d_urgence Nb_operations' OK | individuel = 90.0 | final = 90.0
   ✅ 'Dispositifs_d_urgence Nb_jours_operations' OK | individuel = 71.20972222222221 | final = 71.20972222222223
   ✅ 'Dispositifs_d_urgence Ope_secours' OK | individuel = 21.0 | final = 21.0
   ✅ 'Dispositifs_d_urgence Ope_soutien_pop' OK | individuel = 66.0 | final = 66.0
   ✅ 'Dispositifs_d_urgence Nb_personnes_prises_charge' OK | individuel = 8744.0 | final = 8744.0

🔎 Vérification DataFrame 4
   ✅ 'AEO Structure_activite_mobile' OK | individuel = 97.0 | final = 97.0
   ✅ 'AEO Nb_PA_dispos_mobiles' OK | individuel = 0.0 | final = 0.0
   ✅ 'AEO Nb_activites_mobiles' OK | individuel = 117.0 | final = 117.0

🔎 Vérification DataFrame 5
   ✅ 'OCR Nb_deployees' OK | individuel = 102.0 | final = 102.0

🔎 Vérification DataFrame 6
   ✅ 'Textile Nb_boutiques' OK | individuel = 747.0 | final = 747.0
   ✅ 'Textile Nb_vestiaires' OK | individuel = 128.0 | final = 128.0

🔎 Vérification DataFrame 7
   ✅ 'Textile tracabilite_flux' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 8
   ✅ 'Aide_alimentaire Nb_U2A' OK | individuel = 553.0 | final = 553.0
   ✅ 'Aide_alimentaire Nb_Centre_distribution_alimentaire' OK | individuel = 480.0 | final = 480.0
   ✅ 'Aide_alimentaire Nb_epiceries_sociales' OK | individuel = 71.0 | final = 71.0
   ✅ 'Aide_alimentaire Nb_crsr' OK | individuel = 18.0 | final = 18.0
   ✅ 'Aide_alimentaire nb_distributions' OK | individuel = 424537.0 | final = 424537.0
   ✅ 'Aide_alimentaire nb_tonnes' OK | individuel = 6615253.0 | final = 6615253.0
   ✅ 'Aide_alimentaire nb_PA' OK | individuel = 179264.0 | final = 179264.0

🔎 Vérification DataFrame 9
   ✅ 'Structure Nb_Adherents' OK | individuel = 55627.0 | final = 55627.0

🔎 Vérification DataFrame 10
   ✅ 'AEO Nb_personnes_domiciliees_crf' OK | individuel = 30833.0 | final = 30833.0

🔎 Vérification DataFrame 11
   ✅ 'Maraude Nb_personnes_diff_rencontrees' OK | individuel = 14351.0 | final = 14351.0
   ✅ 'Maraude Nb_contacts' OK | individuel = 60309.0 | final = 60309.0
   ✅ 'Maraude Nb_maraudes_SIGMA' OK | individuel = 3568.0 | final = 3568.0

🔎 Vérification DataFrame 12
   ✅ 'Secours Nb_IS_apte_inactif' OK | individuel = 4451.0 | final = 4451.0
   ✅ 'Secours Nb_IS_actifs' OK | individuel = 3972.0 | final = 3972.0
   ✅ 'Secours Nb_renfort_IS_OUT' OK | individuel = 3436.0 | final = 3436.0
   ✅ 'Secours Nb_renfort_IS_IN' OK | individuel = 5581.0 | final = 5581.0

🔎 Vérification DataFrame 13
   ✅ 'Maraude Nb_benevoles_actifs_formes' OK | individuel = 2929.0 | final = 2929.0

🔎 Vérification DataFrame 14
   ✅ 'Structure Nb_nvx_formes_CRB_2026' OK | individuel = 808.0 | final = 808.0

🔎 Vérification DataFrame 15
   ✅ 'Financier Prod_2025' OK | individuel = 92522349.0 | final = 92522349.0
   ✅ 'Financier ResNet_2025' OK | individuel = 2933238.0 | final = 2933238.0
   ✅ 'Financier ResCorrProd_2025' OK | individuel = -439.7708672849474 | final = -439.7708672849474
   ✅ 'Financier caf_2025' OK | individuel = 11943298.0 | final = 11943298.0
   ✅ 'Financier TresoBrute_2025' OK | individuel = 145661681.0 | final = 145661681.0
   ✅ 'Financier Mois_AvanceTreso_2025' OK | individuel = 18602.972448424283 | final = 18602.972448424283
   ✅ 'Secours Produits_DPS_2025' OK | individuel = 9739183.0 | final = 9739183.0
   ✅ 'Textile Produit_2025' OK | individuel = 21302847.0 | final = 21302847.0
   ✅ 'Textile Vente_solidaire' OK | individuel = 214041.0 | final = 214041.0

🔎 Vérification DataFrame 16
   ✅ 'Maraude Nb_maraudes_PEGASS' OK | individuel = 9051.0 | final = 9051.0
   ✅ 'AEO Structure_domiciliation_fixe' OK | individuel = 38.0 | final = 38.0
   ✅ 'AEO Structure_ecrivain_public_fixe' OK | individuel = 38.0 | final = 38.0
   ✅ 'Maraude Nb_benevoles_actifs' OK | individuel = 5664.0 | final = 5664.0
   ✅ 'AEO Nb_benevoles_actifs' OK | individuel = 732.0 | final = 732.0
   ✅ 'AEO Nb_activites_fixes' OK | individuel = 115.0 | final = 115.0

🔎 Vérification DataFrame 17
   ✅ 'Secours Nb_PAPS_2026' OK | individuel = 1203.0 | final = 1203.0
   ✅ 'Secours Nb_DPS_PE_2026' OK | individuel = 1456.0 | final = 1456.0
   ✅ 'Secours Nb_DPS_ME_2026' OK | individuel = 70.0 | final = 70.0
   ✅ 'Secours Nb_DPS_GE_2026' OK | individuel = 2.0 | final = 2.0
   ✅ 'Secours Nb_DPS_2026' OK | individuel = 3912.0 | final = 3912.0
   ✅ 'Secours Nb_PAPS_ps_2026' OK | individuel = 724.5 | final = 724.5
   ✅ 'Secours Nb_DPS_PE_ps_2026' OK | individuel = 1307.5 | final = 1307.5
   ✅ 'Secours Nb_DPS_ME_ps_2026' OK | individuel = 157.5 | final = 157.5
   ✅ 'Secours Nb_DPS_GE_ps_2026' OK | individuel = 0.0 | final = 0.0
   ✅ 'Secours Nb_DPS_ps_2026' OK | individuel = 2817.0 | final = 2817.0

🔎 Vérification DataFrame 18
   ✅ 'AEO Nb_AAD' OK | individuel = 1277.0 | final = 1277.0
   ✅ 'AEO Nb_FAAD' OK | individuel = 50.0 | final = 50.0
   ✅ 'Maraude Nb_SOLIDAR' OK | individuel = 7380.0 | final = 7380.0
   ✅ 'Aide_alimentaire nb_SAH' OK | individuel = 2369.0 | final = 2369.0
   ✅ 'Aide_alimentaire nb_ASAH' OK | individuel = 94.0 | final = 94.0
   ✅ 'Structure Nb_formes_CRB_2026' OK | individuel = 20350.0 | final = 20350.0
   ✅ 'Structure Nb_formateurs_CRB_2026' OK | individuel = 725.0 | final = 725.0
   ✅ 'Structure Nb_formes_TCAS_2026' OK | individuel = 11080.0 | final = 11080.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCAU_2026' OK | individuel = 11566.0 | final = 11566.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCEO_2026' OK | individuel = 1755.0 | final = 1755.0
   ✅ 'Dispositifs_d_urgence Nb_formes_PSP_2026' OK | individuel = 4981.0 | final = 4981.0
   ✅ 'Dispositifs_d_urgence Nb_formes_IRR_2026' OK | individuel = 22884.0 | final = 22884.0
   ✅ 'Textile Animateurs_textile' OK | individuel = 56.0 | final = 56.0
   ✅ 'Dispositifs_d_urgence Nb_formes_GQS_2026' OK | individuel = 27907.0 | final = 27907.0
   ✅ 'Maraude Nb_SOLIDAR2020' OK | individuel = 5570.0 | final = 5570.0

🔎 Vérification DataFrame 19
   ✅ 'Formation_grand_public Nb_FPSC_2026' OK | individuel = 2679.0 | final = 2679.0
   ✅ 'Secours Nb_PSE1_2026' OK | individuel = 525.0 | final = 525.0
   ✅ 'Secours Nb_FI_PSE1_2026' OK | individuel = 187.0 | final = 187.0
   ✅ 'Secours Nb_FC_PSE1_2026' OK | individuel = 338.0 | final = 338.0
   ✅ 'Secours Nb_PSE2_2026' OK | individuel = 7780.0 | final = 7780.0
   ✅ 'Secours Nb_FI_PSE2_2026' OK | individuel = 1605.0 | final = 1605.0
   ✅ 'Secours Nb_FC_PSE2_2026' OK | individuel = 6175.0 | final = 6175.0
   ✅ 'Secours Nb_CI_2026' OK | individuel = 1868.0 | final = 1868.0
   ✅ 'Secours Nb_FI_CI_2026' OK | individuel = 169.0 | final = 169.0
   ✅ 'Secours Nb_FPSE_2026' OK | individuel = 1038.0 | final = 1038.0
   ✅ 'Secours Nb_FI_FPSE_2026' OK | individuel = 707.0 | final = 707.0
   ✅ 'Secours Nb_FC_FPSE_2026' OK | individuel = 331.0 | final = 331.0
   ✅ 'Secours Nb_FC_CI_2026' OK | individuel = 1699.0 | final = 1699.0
   ✅ 'Secours Nb_IS' OK | individuel = 10173.0 | final = 10173.0

🔎 Vérification DataFrame 20
   ✅ 'Formation_grand_public Nb_FPSC_recy2026' OK | individuel = 357.0 | final = 357.0
   ✅ 'Secours Nb_PSE1_recy2026' OK | individuel = 276.0 | final = 276.0
   ✅ 'Secours Nb_FI_PSE1_recy2026' OK | individuel = 76.0 | final = 76.0
   ✅ 'Secours Nb_FC_PSE1_recy2026' OK | individuel = 200.0 | final = 200.0
   ✅ 'Secours Nb_PSE2_recy2026' OK | individuel = 5069.0 | final = 5069.0
   ✅ 'Secours Nb_FI_PSE2_recy2026' OK | individuel = 930.0 | final = 930.0
   ✅ 'Secours Nb_FC_PSE2_recy2026' OK | individuel = 4139.0 | final = 4139.0
   ✅ 'Secours Nb_CI_recy2026' OK | individuel = 965.0 | final = 965.0
   ✅ 'Secours Nb_FI_CI_recy2026' OK | individuel = 96.0 | final = 96.0
   ✅ 'Secours Nb_FPSE_recy2026' OK | individuel = 76.0 | final = 76.0
   ✅ 'Secours Nb_FI_FPSE_recy2026' OK | individuel = 75.0 | final = 75.0
   ✅ 'Secours Nb_FC_FPSE_recy2026' OK | individuel = 1.0 | final = 1.0
   ✅ 'Secours Nb_FC_CI_recy2026' OK | individuel = 869.0 | final = 869.0

🔎 Vérification DataFrame 21
   ✅ 'Formation_grand_public Nb_FPSC_2025' OK | individuel = 2699.0 | final = 2699.0
   ✅ 'Secours Nb_PSE1_2025' OK | individuel = 653.0 | final = 653.0
   ✅ 'Secours Nb_FI_PSE1_2025' OK | individuel = 284.0 | final = 284.0
   ✅ 'Secours Nb_FC_PSE1_2025' OK | individuel = 369.0 | final = 369.0
   ✅ 'Secours Nb_PSE2_2025' OK | individuel = 7749.0 | final = 7749.0
   ✅ 'Secours Nb_FI_PSE2_2025' OK | individuel = 2254.0 | final = 2254.0
   ✅ 'Secours Nb_FC_PSE2_2025' OK | individuel = 5486.0 | final = 5486.0
   ✅ 'Secours Nb_CI_2025' OK | individuel = 1794.0 | final = 1794.0
   ✅ 'Secours Nb_FI_CI_2025' OK | individuel = 203.0 | final = 203.0
   ✅ 'Secours Nb_FPSE_2025' OK | individuel = 1102.0 | final = 1102.0
   ✅ 'Secours Nb_FI_FPSE_2025' OK | individuel = 303.0 | final = 303.0
   ✅ 'Secours Nb_FC_FPSE_2025' OK | individuel = 799.0 | final = 799.0
   ✅ 'Secours Nb_FC_CI_2025' OK | individuel = 1591.0 | final = 1591.0

🔎 Vérification DataFrame 22
   ✅ 'Formation_grand_public Nb_FPSC_renou_2026' OK | individuel = 289.0 | final = 289.0
   ✅ 'Secours Nb_PSE1_renou_2026' OK | individuel = 273.0 | final = 273.0
   ✅ 'Secours Nb_FI_PSE1_renou_2026' OK | individuel = 77.0 | final = 77.0
   ✅ 'Secours Nb_FC_PSE1_renou_2026' OK | individuel = 196.0 | final = 196.0
   ✅ 'Secours Nb_PSE2_renou_2026' OK | individuel = 5068.0 | final = 5068.0
   ✅ 'Secours Nb_FI_PSE2_renou_2026' OK | individuel = 932.0 | final = 932.0
   ✅ 'Secours Nb_FC_PSE2_renou_2026' OK | individuel = 4136.0 | final = 4136.0
   ✅ 'Secours Nb_CI_renou_2026' OK | individuel = 960.0 | final = 960.0
   ✅ 'Secours Nb_FI_CI_renou_2026' OK | individuel = 96.0 | final = 96.0
   ✅ 'Secours Nb_FPSE_renou_2026' OK | individuel = 72.0 | final = 72.0
   ✅ 'Secours Nb_FI_FPSE_renou_2026' OK | individuel = 72.0 | final = 72.0
   ✅ 'Secours Nb_FC_FPSE_renou_2026' OK | individuel = 0.0 | final = 0.0
   ✅ 'Secours Nb_FC_CI_renou_2026' OK | individuel = 864.0 | final = 864.0

🔎 Vérification DataFrame 23
   ✅ 'Formation_grand_public Nb_formes_PSC_2026' OK | individuel = 31633.0 | final = 31633.0
   ✅ 'Formation_grand_public Nb_formes_GQS_2026' OK | individuel = 3913.0 | final = 3913.0
   ✅ 'Formation_grand_public Nb_formes_IPS_2026' OK | individuel = 11681.0 | final = 11681.0
   ✅ 'Formation_grand_public Nb_formes_IPSEN_2026' OK | individuel = 3850.0 | final = 3850.0

🔎 Vérification DataFrame 24
   ✅ 'Formation_grand_public Nb_sessions_PSC_2026' OK | individuel = 3926.0 | final = 3926.0
   ✅ 'Formation_grand_public Nb_sessions_GQS_2026' OK | individuel = 516.0 | final = 516.0
   ✅ 'Formation_grand_public Nb_sessions_IPS_2026' OK | individuel = 1309.0 | final = 1309.0
   ✅ 'Formation_grand_public Nb_sessions_IPSEN_2026' OK | individuel = 453.0 | final = 453.0
   ✅ 'Secours Nb_sessions_PSE' OK | individuel = 808.0 | final = 808.0
   ✅ 'Secours Nb_sessions_CI' OK | individuel = 185.0 | final = 185.0
   ✅ 'Secours Nb_sessions_FPSE' OK | individuel = 11.0 | final = 11.0

In [85]:
report = check_sums_against_final(
  df_final=all_data_DT,
  list_of_dfs=liste_df_a_fusionner_DT,
  key_col="n_structure",
  atol=1e-6
  )

🔎 Vérification DataFrame 0
   ✅ 'Structure Nb_Benevoles' OK | individuel = 80137.0 | final = 80137.0
   ✅ 'Structure Nb_nvx_Benevoles_2026' OK | individuel = 7454.0 | final = 7454.0
   ✅ 'Structure Taux_nvx_Benevoles' OK | individuel = 9.868553109826875 | final = 9.868553109826873

🔎 Vérification DataFrame 1
   ✅ 'AEO Nb_responsables' OK | individuel = 55.0 | final = 55.0

🔎 Vérification DataFrame 2
   ✅ 'OCR Nb_referents' OK | individuel = 22.0 | final = 22.0

🔎 Vérification DataFrame 3
   ✅ 'Dispositifs_d_urgence Nb_operations' OK | individuel = 90.0 | final = 90.0
   ✅ 'Dispositifs_d_urgence Nb_jours_operations' OK | individuel = 71.20972222222221 | final = 71.20972222222223
   ✅ 'Dispositifs_d_urgence Ope_secours' OK | individuel = 21.0 | final = 21.0
   ✅ 'Dispositifs_d_urgence Ope_soutien_pop' OK | individuel = 66.0 | final = 66.0
   ✅ 'Dispositifs_d_urgence Nb_personnes_prises_charge' OK | individuel = 8744.0 | final = 8744.0

🔎 Vérification DataFrame 4
   ✅ 'AEO Structure_activite_mobile' OK | individuel = 97.0 | final = 97.0
   ✅ 'AEO Nb_PA_dispos_mobiles' OK | individuel = 0.0 | final = 0.0
   ✅ 'AEO Nb_activites_mobiles' OK | individuel = 117.0 | final = 117.0

🔎 Vérification DataFrame 5
   ✅ 'OCR Nb_deployees' OK | individuel = 102.0 | final = 102.0

🔎 Vérification DataFrame 6
   ✅ 'Dispositifs_d_urgence PST' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 7
   ✅ 'Dispositifs_d_urgence Nb_declenchements' OK | individuel = 466.0 | final = 466.0

🔎 Vérification DataFrame 8
   ✅ 'Dispositifs_d_urgence Nb_exercices' OK | individuel = 56.0 | final = 56.0

🔎 Vérification DataFrame 9
   ✅ 'Dispositifs_d_urgence Nb_lots_CAI' OK | individuel = 228.0 | final = 228.0
   ✅ 'Dispositifs_d_urgence Nb_lots_CHU' OK | individuel = 182.0 | final = 182.0
   ✅ 'Dispositifs_d_urgence Nb_lots_CMCC' OK | individuel = 245.0 | final = 245.0
   ✅ 'Dispositifs_d_urgence Nb_conventions_prefecture' OK | individuel = 0.0 | final = 0.0
   ✅ 'Dispositifs_d_urgence Nb_conventions_operateurs_publics' OK | individuel = 360.0 | final = 360.0
   ✅ 'Dispositifs_d_urgence Nb_conventions_operateurs_prives' OK | individuel = 78.0 | final = 78.0
   ✅ 'Dispositifs_d_urgence Nb_conventions_operateurs' OK | individuel = 438.0 | final = 438.0

🔎 Vérification DataFrame 10
   ✅ 'Textile Nb_boutiques' OK | individuel = 747.0 | final = 747.0
   ✅ 'Textile Nb_vestiaires' OK | individuel = 128.0 | final = 128.0

🔎 Vérification DataFrame 11
   ✅ 'Textile tracabilite_flux' OK | individuel = 124.0 | final = 124.0

🔎 Vérification DataFrame 12
   ✅ 'Dispositifs_d_urgence Minutis_Nb_interventions' OK | individuel = 428.0 | final = 428.0
   ✅ 'Dispositifs_d_urgence Minutis_Nb_victimes' OK | individuel = 7718.0 | final = 7718.0
   ✅ 'Dispositifs_d_urgence Utilisation_Minutis' OK | individuel = 0.0 | final = 0.0

🔎 Vérification DataFrame 13
   ✅ 'Aide_alimentaire Nb_U2A' OK | individuel = 553.0 | final = 553.0
   ✅ 'Aide_alimentaire Nb_Centre_distribution_alimentaire' OK | individuel = 480.0 | final = 480.0
   ✅ 'Aide_alimentaire Nb_epiceries_sociales' OK | individuel = 71.0 | final = 71.0
   ✅ 'Aide_alimentaire Nb_crsr' OK | individuel = 18.0 | final = 18.0
   ✅ 'Aide_alimentaire nb_distributions' OK | individuel = 424537.0 | final = 424537.0
   ✅ 'Aide_alimentaire nb_tonnes' OK | individuel = 6615253.0 | final = 6615253.0
   ✅ 'Aide_alimentaire nb_PA' OK | individuel = 179264.0 | final = 179264.0
   ✅ 'Aide_alimentaire Nb_struct' OK | individuel = 339.0 | final = 339.0

🔎 Vérification DataFrame 14
   ✅ 'Structure Nb_Adherents' OK | individuel = 55626.0 | final = 55626.0

🔎 Vérification DataFrame 15
   ✅ 'AEO Nb_personnes_domiciliees_crf' OK | individuel = 30833.0 | final = 30833.0

🔎 Vérification DataFrame 16
   ✅ 'Maraude Nb_personnes_diff_rencontrees' OK | individuel = 14351.0 | final = 14351.0
   ✅ 'Maraude Nb_contacts' OK | individuel = 60309.0 | final = 60309.0
   ✅ 'Maraude Nb_maraudes_SIGMA' OK | individuel = 3568.0 | final = 3568.0

🔎 Vérification DataFrame 17
   ✅ 'Financier Prod_2025' OK | individuel = 92669355.0 | final = 92669355.0
   ✅ 'Financier ResNet_2025' OK | individuel = 2779906.0 | final = 2779906.0
   ✅ 'Financier ResCorrProd_2025' OK | individuel = 3.1278783101257392 | final = 3.1278783101257392
   ✅ 'Financier Prod_2023' OK | individuel = 89134261.0 | final = 89134261.0
   ✅ 'Financier Prod_2024' OK | individuel = 90607796.0 | final = 90607796.0
   ✅ 'Financier ResNet_2023' OK | individuel = 5820630.0 | final = 5820630.0
   ✅ 'Financier ResNet_2024' OK | individuel = 4609490.0 | final = 4609490.0
   ✅ 'Financier ResCorrProd_2024' OK | individuel = 5.308333610715164 | final = 5.308333610715164
   ✅ 'Financier ResCorrProd_2023' OK | individuel = 4.947771066668042 | final = 4.947771066668042
   ✅ 'Financier caf_2025' OK | individuel = 11920304.0 | final = 11920304.0
   ✅ 'Financier TresoBrute_2025' OK | individuel = 146686075.0 | final = 146686075.0
   ✅ 'Financier Mois_AvanceTreso_2025' OK | individuel = 2178.4724484242815 | final = 2178.4724484242815
   ✅ 'Secours Produits_DPS_2025' OK | individuel = 9739183.0 | final = 9739183.0
   ✅ 'Textile Produit_2025' OK | individuel = 21522457.0 | final = 21522457.0
   ✅ 'Textile Vente_solidaire' OK | individuel = 8851.0 | final = 8851.0

🔎 Vérification DataFrame 18
   ✅ 'Formation_grand_public Produits_2025' OK | individuel = 88457195.11 | final = 88457195.11000001

🔎 Vérification DataFrame 19
   ✅ 'Maraude Nb_maraudes_PEGASS' OK | individuel = 9050.0 | final = 9050.0
   ✅ 'AEO Structure_domiciliation_fixe' OK | individuel = 38.0 | final = 38.0
   ✅ 'AEO Structure_ecrivain_public_fixe' OK | individuel = 38.0 | final = 38.0
   ✅ 'Maraude Nb_benevoles_actifs' OK | individuel = 5664.0 | final = 5664.0
   ✅ 'AEO Nb_benevoles_actifs' OK | individuel = 732.0 | final = 732.0
   ✅ 'AEO Nb_activites_fixes' OK | individuel = 115.0 | final = 115.0
   ✅ 'AEO Structure_activite_fixe' OK | individuel = 114.0 | final = 114.0

🔎 Vérification DataFrame 20
   ✅ 'PAT Taux_nvx_formes_CRB' OK | individuel = 83.22 | final = 83.22
   ✅ 'PAT conv_pref' OK | individuel = 0.0 | final = 0.0
   ✅ 'PAT conv_prive' OK | individuel = 147.0 | final = 147.0
   ✅ 'PAT conv_public' OK | individuel = 231.0 | final = 231.0
   ✅ 'PAT astreinte' OK | individuel = 0.0 | final = 0.0
   ✅ 'PAT CAI_CHU' OK | individuel = 0.0 | final = 0.0
   ✅ 'PAT CAI' OK | individuel = 216.0 | final = 216.0
   ✅ 'PAT CHU' OK | individuel = 223.5 | final = 223.5
   ✅ 'PAT coup_coeur' OK | individuel = 229.0 | final = 229.0
   ✅ 'PAT Dispos_urgence_nb_exercices' OK | individuel = 325.0 | final = 325.0
   ✅ 'PAT Dispos_urgence_PST' OK | individuel = 0.0 | final = 0.0
   ✅ 'PAT %_TCAU_PSP' OK | individuel = 0.0 | final = 0.0
   ✅ 'PAT Dispos_urgence_tauxformation_TCAU' OK | individuel = 46.14 | final = 46.14
   ✅ 'PAT Dispos_urgence_tauxformation_PSP' OK | individuel = 34.58 | final = 34.58
   ✅ 'PAT Dispos_urgence_tauxformation_GQS' OK | individuel = 57.1 | final = 57.1
   ✅ 'PAT FGP_Nb_formes_PSC' OK | individuel = 116652.0 | final = 116652.0
   ✅ 'PAT FGP_Nb_FPSC' OK | individuel = 1708.0 | final = 1708.0
   ✅ 'PAT FGP_Nb_AGQS' OK | individuel = 1100.0 | final = 1100.0
   ✅ 'PAT FGP_Nb_sessions_PSC' OK | individuel = 10732.0 | final = 10732.0
   ✅ 'PAT FGP_Nb_sessions_GQS' OK | individuel = 3302.0 | final = 3302.0
   ✅ 'PAT FGP_Nb_sessions_IPS' OK | individuel = 3843.0 | final = 3843.0
   ✅ 'PAT FGP_Nb_sessions_IPSEN' OK | individuel = 2718.0 | final = 2718.0
   ✅ 'PAT OCR_Nb_OCR' OK | individuel = 367.0 | final = 367.0
   ✅ 'PAT Maraudes_Nb_maraudes' OK | individuel = 31439.0 | final = 31439.0
   ✅ 'PAT Maraudes_Formes_SOLIDAR2020' OK | individuel = 4779.0 | final = 4779.0
   ✅ 'PAT DPS_Nb_IS' OK | individuel = 11817.0 | final = 11817.0
   ✅ 'PAT DPS_Nb_DPS' OK | individuel = 25777.0 | final = 25777.0
   ✅ 'PAT DPS_CA' OK | individuel = 6496152.0 | final = 6496152.0
   ✅ 'PAT AEO_Nb_aeo_fixe' OK | individuel = 587.0 | final = 587.0
   ✅ 'PAT AEO_Nb_aeo_mobile' OK | individuel = 16.0 | final = 16.0
   ✅ 'PAT conv_total' OK | individuel = 378.0 | final = 378.0
   ✅ 'PAT AEO_Structure_menant_activite' OK | individuel = 588.0 | final = 588.0

🔎 Vérification DataFrame 21
   ✅ 'Secours Nb_PAPS_2026' OK | individuel = 1203.0 | final = 1203.0
   ✅ 'Secours Nb_DPS_PE_2026' OK | individuel = 1456.0 | final = 1456.0
   ✅ 'Secours Nb_DPS_ME_2026' OK | individuel = 70.0 | final = 70.0
   ✅ 'Secours Nb_DPS_GE_2026' OK | individuel = 2.0 | final = 2.0
   ✅ 'Secours Nb_DPS_2026' OK | individuel = 3912.0 | final = 3912.0
   ✅ 'Secours Nb_PAPS_ps_2026' OK | individuel = 724.5 | final = 724.5
   ✅ 'Secours Nb_DPS_PE_ps_2026' OK | individuel = 1307.5 | final = 1307.5
   ✅ 'Secours Nb_DPS_ME_ps_2026' OK | individuel = 157.5 | final = 157.5
   ✅ 'Secours Nb_DPS_GE_ps_2026' OK | individuel = 0.0 | final = 0.0
   ✅ 'Secours Nb_DPS_ps_2026' OK | individuel = 2817.0 | final = 2817.0

🔎 Vérification DataFrame 22
   ✅ 'Secours Nb_IS_apte_inactif' OK | individuel = 4449.0 | final = 4449.0
   ✅ 'Secours Nb_IS_actifs' OK | individuel = 3972.0 | final = 3972.0
   ✅ 'Secours Nb_renfort_IS_OUT' OK | individuel = 3436.0 | final = 3436.0
   ✅ 'Secours Nb_renfort_IS_IN' OK | individuel = 5581.0 | final = 5581.0

🔎 Vérification DataFrame 23
   ✅ 'Structure Nb_nvx_formes_CRB_2026' OK | individuel = 806.0 | final = 806.0

🔎 Vérification DataFrame 24
   ✅ 'Maraude Nb_benevoles_actifs_formes' OK | individuel = 2929.0 | final = 2929.0

🔎 Vérification DataFrame 25
   ✅ 'AEO Nb_AAD' OK | individuel = 1274.0 | final = 1274.0
   ✅ 'AEO Nb_FAAD' OK | individuel = 49.0 | final = 49.0
   ✅ 'Maraude Nb_SOLIDAR' OK | individuel = 7362.0 | final = 7362.0
   ✅ 'Aide_alimentaire nb_SAH' OK | individuel = 2353.0 | final = 2353.0
   ✅ 'Aide_alimentaire nb_ASAH' OK | individuel = 90.0 | final = 90.0
   ✅ 'Structure Nb_formes_CRB_2026' OK | individuel = 20261.0 | final = 20261.0
   ✅ 'Structure Nb_formateurs_CRB_2026' OK | individuel = 717.0 | final = 717.0
   ✅ 'Structure Nb_formes_TCAS_2026' OK | individuel = 11035.0 | final = 11035.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCAU_2026' OK | individuel = 11523.0 | final = 11523.0
   ✅ 'Dispositifs_d_urgence Nb_formes_TCEO_2026' OK | individuel = 1734.0 | final = 1734.0
   ✅ 'Dispositifs_d_urgence Nb_formes_PSP_2026' OK | individuel = 4975.0 | final = 4975.0
   ✅ 'Dispositifs_d_urgence Nb_formes_IRR_2026' OK | individuel = 22705.0 | final = 22705.0
   ✅ 'Textile Animateurs_textile' OK | individuel = 56.0 | final = 56.0
   ✅ 'Dispositifs_d_urgence Nb_formes_GQS_2026' OK | individuel = 27702.0 | final = 27702.0
   ✅ 'Maraude Nb_SOLIDAR2020' OK | individuel = 5563.0 | final = 5563.0

🔎 Vérification DataFrame 26
   ✅ 'Formation_grand_public Nb_FPSC_2026' OK | individuel = 2666.0 | final = 2666.0
   ✅ 'Secours Nb_PSE1_2026' OK | individuel = 525.0 | final = 525.0
   ✅ 'Secours Nb_FI_PSE1_2026' OK | individuel = 187.0 | final = 187.0
   ✅ 'Secours Nb_FC_PSE1_2026' OK | individuel = 338.0 | final = 338.0
   ✅ 'Secours Nb_PSE2_2026' OK | individuel = 7779.0 | final = 7779.0
   ✅ 'Secours Nb_FI_PSE2_2026' OK | individuel = 1605.0 | final = 1605.0
   ✅ 'Secours Nb_FC_PSE2_2026' OK | individuel = 6174.0 | final = 6174.0
   ✅ 'Secours Nb_CI_2026' OK | individuel = 1867.0 | final = 1867.0
   ✅ 'Secours Nb_FI_CI_2026' OK | individuel = 169.0 | final = 169.0
   ✅ 'Secours Nb_FPSE_2026' OK | individuel = 1034.0 | final = 1034.0
   ✅ 'Secours Nb_FI_FPSE_2026' OK | individuel = 704.0 | final = 704.0
   ✅ 'Secours Nb_FC_FPSE_2026' OK | individuel = 330.0 | final = 330.0
   ✅ 'Secours Nb_FC_CI_2026' OK | individuel = 1698.0 | final = 1698.0
   ✅ 'Secours Nb_IS' OK | individuel = 10171.0 | final = 10171.0

🔎 Vérification DataFrame 27
   ✅ 'Formation_grand_public Nb_FPSC_recy2026' OK | individuel = 349.0 | final = 349.0
   ✅ 'Secours Nb_PSE1_recy2026' OK | individuel = 276.0 | final = 276.0
   ✅ 'Secours Nb_FI_PSE1_recy2026' OK | individuel = 76.0 | final = 76.0
   ✅ 'Secours Nb_FC_PSE1_recy2026' OK | individuel = 200.0 | final = 200.0
   ✅ 'Secours Nb_PSE2_recy2026' OK | individuel = 5068.0 | final = 5068.0
   ✅ 'Secours Nb_FI_PSE2_recy2026' OK | individuel = 930.0 | final = 930.0
   ✅ 'Secours Nb_FC_PSE2_recy2026' OK | individuel = 4138.0 | final = 4138.0
   ✅ 'Secours Nb_CI_recy2026' OK | individuel = 965.0 | final = 965.0
   ✅ 'Secours Nb_FI_CI_recy2026' OK | individuel = 96.0 | final = 96.0
   ✅ 'Secours Nb_FPSE_recy2026' OK | individuel = 76.0 | final = 76.0
   ✅ 'Secours Nb_FI_FPSE_recy2026' OK | individuel = 75.0 | final = 75.0
   ✅ 'Secours Nb_FC_FPSE_recy2026' OK | individuel = 1.0 | final = 1.0
   ✅ 'Secours Nb_FC_CI_recy2026' OK | individuel = 869.0 | final = 869.0

🔎 Vérification DataFrame 28
   ✅ 'Formation_grand_public Nb_FPSC_2025' OK | individuel = 2694.0 | final = 2694.0
   ✅ 'Secours Nb_PSE1_2025' OK | individuel = 651.0 | final = 651.0
   ✅ 'Secours Nb_FI_PSE1_2025' OK | individuel = 282.0 | final = 282.0
   ✅ 'Secours Nb_FC_PSE1_2025' OK | individuel = 369.0 | final = 369.0
   ✅ 'Secours Nb_PSE2_2025' OK | individuel = 7708.0 | final = 7708.0
   ✅ 'Secours Nb_FI_PSE2_2025' OK | individuel = 2214.0 | final = 2214.0
   ✅ 'Secours Nb_FC_PSE2_2025' OK | individuel = 5485.0 | final = 5485.0
   ✅ 'Secours Nb_CI_2025' OK | individuel = 1793.0 | final = 1793.0
   ✅ 'Secours Nb_FI_CI_2025' OK | individuel = 203.0 | final = 203.0
   ✅ 'Secours Nb_FPSE_2025' OK | individuel = 1101.0 | final = 1101.0
   ✅ 'Secours Nb_FI_FPSE_2025' OK | individuel = 303.0 | final = 303.0
   ✅ 'Secours Nb_FC_FPSE_2025' OK | individuel = 798.0 | final = 798.0
   ✅ 'Secours Nb_FC_CI_2025' OK | individuel = 1590.0 | final = 1590.0

🔎 Vérification DataFrame 29
   ✅ 'Formation_grand_public Nb_FPSC_renou_2026' OK | individuel = 287.0 | final = 287.0
   ✅ 'Secours Nb_PSE1_renou_2026' OK | individuel = 273.0 | final = 273.0
   ✅ 'Secours Nb_FI_PSE1_renou_2026' OK | individuel = 77.0 | final = 77.0
   ✅ 'Secours Nb_FC_PSE1_renou_2026' OK | individuel = 196.0 | final = 196.0
   ✅ 'Secours Nb_PSE2_renou_2026' OK | individuel = 5067.0 | final = 5067.0
   ✅ 'Secours Nb_FI_PSE2_renou_2026' OK | individuel = 932.0 | final = 932.0
   ✅ 'Secours Nb_FC_PSE2_renou_2026' OK | individuel = 4135.0 | final = 4135.0
   ✅ 'Secours Nb_CI_renou_2026' OK | individuel = 960.0 | final = 960.0
   ✅ 'Secours Nb_FI_CI_renou_2026' OK | individuel = 96.0 | final = 96.0
   ✅ 'Secours Nb_FPSE_renou_2026' OK | individuel = 72.0 | final = 72.0
   ✅ 'Secours Nb_FI_FPSE_renou_2026' OK | individuel = 72.0 | final = 72.0
   ✅ 'Secours Nb_FC_FPSE_renou_2026' OK | individuel = 0.0 | final = 0.0
   ✅ 'Secours Nb_FC_CI_renou_2026' OK | individuel = 864.0 | final = 864.0

🔎 Vérification DataFrame 30
   ✅ 'Formation_grand_public Nb_formes_PSC_2026' OK | individuel = 31474.0 | final = 31474.0
   ✅ 'Formation_grand_public Nb_formes_GQS_2026' OK | individuel = 3903.0 | final = 3903.0
   ✅ 'Formation_grand_public Nb_formes_IPS_2026' OK | individuel = 11681.0 | final = 11681.0
   ✅ 'Formation_grand_public Nb_formes_IPSEN_2026' OK | individuel = 3844.0 | final = 3844.0

🔎 Vérification DataFrame 31
   ✅ 'Formation_grand_public Nb_sessions_PSC_2026' OK | individuel = 3892.0 | final = 3892.0
   ✅ 'Formation_grand_public Nb_sessions_GQS_2026' OK | individuel = 505.0 | final = 505.0
   ✅ 'Formation_grand_public Nb_sessions_IPS_2026' OK | individuel = 1309.0 | final = 1309.0
   ✅ 'Formation_grand_public Nb_sessions_IPSEN_2026' OK | individuel = 453.0 | final = 453.0
   ✅ 'Secours Nb_sessions_PSE' OK | individuel = 766.0 | final = 766.0
   ✅ 'Secours Nb_sessions_CI' OK | individuel = 174.0 | final = 174.0
   ✅ 'Secours Nb_sessions_FPSE' OK | individuel = 5.0 | final = 5.0

In [86]:
all_data, all_data_DT = vision_conso(all_data, all_data_DT, year = TARGET_YEAR)

In [87]:
all_data = ajouter_colonnes_taux(all_data, year = TARGET_YEAR)
all_data_DT = ajouter_colonnes_taux(all_data_DT, year = TARGET_YEAR)

In [88]:
all_data

,n_structure,n_structure-ratt,type_structure,nom_structure,n_dept,adresse_physique_cp,adresse_physique_commune,adresse_complete,date_demarrage_activite_ben_struct,date_arret_activite_struct,...,Structure Taux_nvx_formes_CRB_2026,Secours Taux_IS_actifs,Secours Taux_recy27_PSE1,Secours Taux_recy27_PSE2,Secours Taux_recy27_CI,Secours Taux_recy27_FPSE,Secours Taux_ren26_PSE1,Secours Taux_ren26_PSE2,Secours Taux_ren26_CI,Secours Taux_ren26_FPSE
0,2615,2615,ANTENNE LOCALE - AL,AL DE DELLE,90,90100,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",2010-02-08 00:00:00,NaT,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2669,2669,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43,43220,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",2011-01-01 00:00:00,NaT,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2670,2670,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43,43600,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",2011-01-01 00:00:00,NaT,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2671,2671,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43,43300,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",2011-01-01 00:00:00,NaT,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2672,2672,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43,43000,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",2011-01-01 00:00:00,NaT,...,0.2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851,993,993,UNITE LOCALE - UL,UL DE HAUTE PICARDIE,80,80320,CHAULNES,"36 Avenue Roger Salengro, 80320 CHAULNES",1919-12-10 00:00:00,NaT,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
852,995,995,UNITE LOCALE - UL,UL DE DOULLENNAIS,80,80600,DOULLENS,"1 Avenue du Général de Gaulle, 80600 DOULLENS",1916-12-10 00:00:00,NaT,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
853,996,996,UNITE LOCALE - UL,UL DU PAYS HAMOIS,80,80400,HAM,"25 Boulevard du Général de Gaulle, 80400 HAM",1894-12-10 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
854,998,998,UNITE LOCALE - UL,UL DU VAL D'AVRE,80,80500,MONTDIDIER,"6 Rue AMAND DE VIENNE, 80500 MONTDIDIER",1914-12-10 00:00:00,NaT,...,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
855,999,999,UNITE LOCALE - UL,UL DU PAYS NESLOIS,80,80190,NESLE,"2 bis Avenue Clémenceau, 80190 NESLE",1917-12-10 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [89]:
all_data_DT

,n_structure,n_structure-ratt,type_structure,nom_structure,n_dept,adresse_physique_cp,adresse_physique_commune,adresse_complete,date_demarrage_activite_ben_struct,date_arret_activite_struct,...,Structure Taux_nvx_formes_CRB_2026,Secours Taux_IS_actifs,Secours Taux_recy27_PSE1,Secours Taux_recy27_PSE2,Secours Taux_recy27_CI,Secours Taux_recy27_FPSE,Secours Taux_ren26_PSE1,Secours Taux_ren26_PSE2,Secours Taux_ren26_CI,Secours Taux_ren26_FPSE
0,5,5,DELEGATION TERRITORIALE - DT,DT DE L'AIN,1,1000,BOURG EN BRESSE,"3 Rue HENRI DUNANT, 01000 BOURG EN BRESSE",1986-12-10 00:00:00,NaT,...,0.048077,0.166667,0.000000,0.714286,0.142857,0.0,0.000000,0.000000,0.000000,0.000000
1,14,14,DELEGATION TERRITORIALE - DT,DT DE L'AUBE,10,10000,TROYES,"18 Rue LOUIS MORIN, 10000 TROYES",1986-12-10 00:00:00,NaT,...,0.000000,0.714286,0.416667,0.611111,0.000000,0.0,0.166667,0.166667,0.000000,0.000000
2,15,15,DELEGATION TERRITORIALE - DT,DT DE L'AUDE,11,11300,LIMOUX,"49 Rue DU PALAIS, 11300 LIMOUX",1986-12-10 00:00:00,NaT,...,0.038462,0.052632,NaN,0.529412,0.333333,0.0,NaN,0.205882,0.000000,0.000000
3,4395,4395,DELEGATION TERRITORIALE - DT,DT DE L'AVEYRON,12,12510,OLEMPS,"235 Route DE LA MOULINE, 12510 OLEMPS",2017-02-20 00:00:00,NaT,...,0.000000,0.666667,0.000000,0.714286,0.000000,0.0,0.000000,0.000000,2.000000,0.000000
4,17,17,DELEGATION TERRITORIALE - DT,DT DES BOUCHES DU RHONE,13,13004,MARSEILLE,"42 Rue KRUGER, 13004 MARSEILLE",1986-12-10 00:00:00,NaT,...,0.234875,0.476071,0.393939,0.568807,0.736842,0.0,0.090909,0.116208,0.105263,0.108108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,3668,3668,DELEGATION TERRITORIALE - DT,DT DE ST MARTIN,978,97150,ST MARTIN,"2 Rue DU SOLEIL LEVANT, 97150 ST MARTIN",2007-09-26 00:00:00,NaT,...,0.000000,NaN,0.000000,0.000000,NaN,NaN,0.000000,0.000000,NaN,NaN
104,3884,3884,DELEGATION TERRITORIALE - DT,DT DE FUTUNA,986,98610,ALO,"MALA'E, 98610 ALO",2011-06-08 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,4303,4303,DELEGATION TERRITORIALE - DT,DT DE WALLIS,986,98600,UVEA,"MATA'UTU, 98600 UVEA",2014-11-07 00:00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,1285,1285,DELEGATION TERRITORIALE - DT,DT DE TAHITI,987,98716,PIRAE,"233 Rue Pater, 98716 PIRAE",1927-07-01 00:00:00,NaT,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,104,104,DELEGATION TERRITORIALE - DT,DT DE NOUVELLE CALEDONIE,988,98800,NOUMEA,"26 Rue DU DOCTEUR GEORGES COLLARD, 98800 NOUMEA",1956-12-10 00:00:00,NaT,...,0.121951,0.000000,0.000000,0.142857,0.000000,0.0,0.000000,0.714286,0.000000,0.000000

## Ajouter une colonne seulement

Repartir des données existantes

In [90]:
# all_data_DT = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1pmEUcLvVOK3t7TWmXL6cN0uTWJ9kPgIwd2x3hy14Alk/').worksheet('DT'))
# all_data = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1pmEUcLvVOK3t7TWmXL6cN0uTWJ9kPgIwd2x3hy14Alk/').worksheet('UL'))

Remplacement colonnes

In [91]:

# df_add_DT = mobilite_DT.copy() # Ici ajouter les dataframes à ajouter 
# df_add_UL = df_U2A_final.copy()
# df_list = {'DT' : [mobilite_DT], 'UL' : [mobilite_struct]}




# # Remplacement des données
# for dt_add in df_list['DT']:
#     all_data_DT = ajouter_au_all_data(all_data_DT, dt_add, nom_bloc="", cle="n_structure")

# for ul_add in df_list['UL']:
#     all_data = ajouter_au_all_data(all_data, ul_add, nom_bloc="", cle="n_structure")

In [ ]:
#Les colonnes à renommer car pas tout à fait les mêmes
colonnes_a_renommer = {
    "Secours Nb_PSE1_2026": "Secours Nb_PSE1",
    "Secours Nb_PSE2_2026": "Secours Nb_PSE2",
    "Secours Nb_CI_2026": "Secours Nb_CI",
    "Secours Nb_FPSE_2026": "Secours Nb_FPSE",
    "Formation_grand_public Nb_FPSC_2026": "Formation_grand_public Nb_FPSC",
}

all_data_DT = all_data_DT.rename(
    columns=colonnes_a_renommer
)

all_data = all_data.rename(
    columns=colonnes_a_renommer
)

# Enregistrement des données

In [98]:
# # Entregistrement du DataFrame
save_dataframe_to_sheet("1pmEUcLvVOK3t7TWmXL6cN0uTWJ9kPgIwd2x3hy14Alk", gspread_client, all_data, sheet_name = 'UL')
save_dataframe_to_sheet("1pmEUcLvVOK3t7TWmXL6cN0uTWJ9kPgIwd2x3hy14Alk", gspread_client, all_data_DT, sheet_name = 'DT')

# # save_dataframe_to_sheet("1maXN8FgvkzZEjivAfj5uRdCSnWOa_OQdekEXVAVGrgg", client, df_rattachement_court)

📄 Feuille existante 'UL' sélectionnée.
🗑️ Les anciennes données ont été supprimées de la feuille 'UL'
💾 Données sauvegardées dans 'all_data_2026' → feuille 'UL'
    Nombre de lignes : 856
    Nombre de colonnes : 181
📄 Feuille existante 'DT' sélectionnée.
🗑️ Les anciennes données ont été supprimées de la feuille 'DT'
💾 Données sauvegardées dans 'all_data_2026' → feuille 'DT'
    Nombre de lignes : 108
    Nombre de colonnes : 233